### ISSUE TITLE
UI: "Offset x" and "Offset y" are placed wrong

### ISSUE THREAD

**Issue by abrudz** [Dyalog/ride#1003]
### Describe the issue you are having
In the Options>Windows the "Offset x" and "Offset y" settings are only available if "Single Floating Window" is checked. It should therefore be placed indented below "Single Floating Window"

4.5.3807

**Comment by e9gille** [comment]
Actually, offsets are only relevant if it is NOT checked. They are only used to offset multiple floating windows.
