### ISSUE TITLE
Add huge "GO" button to the connect screen, which starts the "best" APL right away

### ISSUE THREAD

**Issue by abrudz** [Dyalog/ride#1014]
Mockup:
![image](https://github.com/Dyalog/ride/assets/10961427/3095ea86-989c-4796-8d93-4ecd02ad15fa)

* The button can include a small text that describes what will happen when the button is clicked.
* Disable the button and change the small text to "No local interpreter found" if applicable.
* The button should autofocus so one can simply hit <kbd>Enter</kbd> to go.

4.5.3807

**Comment by e9gille** [comment]
Replaced by #1056
