### ISSUE TITLE
Export item(s) as syntax coloured HTML

### ISSUE THREAD

**Issue by abrudz** [Dyalog/ride#1027]
As a replacement for WinIDE's out-dated Print functionality, add the ability to export item(s) as HTML, including the chosen syntax colouring scheme.

4.5.3807

**Comment by e9gille** [comment]
There's no built in feature in Monaco editor to do this (that I have found). We would need to refactor the tokenizer so it can be used both via the Monaco editor and directly, allowing us to generate a marked up version for export.

**Comment by abrudz** [comment]
Too hard, use 200⌶ and 201⌶ to do this in APL code.
