### ISSUE TITLE
Cannot enter APL characters with escape (`) key in Search window

### ISSUE THREAD

**Issue by bpbecker** [Dyalog/ride#103]
# RIDE Issue Report

### Describe the issue you are having
Using version 4.0.2669, when in the editor, I cannot enter APL characters in the search input field using the escape (`) key.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Started the interpreter (Linux 15.0.28753 Unicode 64bit) 

### How do you reproduce the issue?
Start RIDE and an interpreter.
)ed something
Click the magnifying glass (search input field appears)
Try to enter APL characters in search input field using the escape (`) key

**Comment by e9gille** [comment]
I've looked into this and the problem is that both the search feature and the autocomplete using prefix feature are add-ons to the main edit window. I can't think of a way to incorporate one in the other. I'll try to find a sensible solution, but suggestions are welcome.
