### ISSUE TITLE
Shared icons ODE/RIDE?

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/ride#104]
Is it possible to use the same Icon Resources in RIDE and ODE? Of course RIDE is not ODE and is entitled to its own look - but OTOH I did not feel "at home" in the tracer because it used different icons for the same functions...

**Comment by abrudz** [comment]
IDE uses an icon set which Microsoft has only allowed usage of for applications made with Visual Studio. RIDE's icons are homemade. IDE uses many more icons than RIDE, so the current homemade set is insufficient. As part of our visual overhaul discussions, it will be taken up whether to make (or outsource) an entire icon pack for IDE and RIDE to share.

**Comment by johndaintree** [comment]
Sharing Icons is IMHO a "bad" idea. Cosmetically I think it will lead to some things looks odd, and It'll potentially slow development  of both platforms.

 

/JD

**Comment by mkromberg** [comment]
I suggest we close this issue: Having identical look and feel as ODE is not a goal for the RIDE project. As we design the future look and feel of RIDE, we want to avoid being different unless there are good reasons for it, but I don't think that high level goal warrants an open issue.

**Comment by jayfoad** [comment]
Agreed.
