### ISSUE TITLE
Like the IDE, RIDE should ask for confirmation before overwriting a workspace saved with an earlier version of Dyalog

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/ride#1045]
Like the IDE, RIDE should ask for confirmation before overwriting a workspace saved with an earlier version of Dyalog

The msgbox in the IDE asks: If you overwrite this workspace, you will not be able to )LOAD is with an older version of Dyalog APL.  Do you wish to continue ? 

See also mantis 20784: "RIDE should pop up a msgbox if you attempt to )save a workspace over one created with an earlier version of Dyalog" as there may be a need for changes to the interpreter to allow this. 

FWIW, the tty interface will now insist on the use of -force in lieu of asking a question

**Comment by bear8642** [comment]
Decision made to follow to follow the TTY interface for `)SAVE` staying at the 6-space prompt

As and when GUI menu option to save workspace, display message box confirmation.

**Comment by e9gille** [comment]
OK, nothing to do in RIDE for now.
