### ISSUE TITLE
Missing distinction of session gutter 

### ISSUE THREAD

**Issue by abrudz** [Dyalog/ride#1049]
### Describe the issue you are having
Being that the gutter uses characters as indicators, it must be distinguishable from the main part of the session, either by the drawing of a thin line (compare to the line that distinguishes the scroll bar) or by making its background slightly differently from the session background (e.g. by making it the GUI chrome colour, i.e. #edeff5 for light schemes and #1c1e28 for dark schemes).

`RIDE` ![image](https://github.com/Dyalog/ride/assets/10961427/527da063-e6b1-486b-b422-4998a1cc6e98) 
`WIDE` ![image](https://github.com/Dyalog/ride/assets/10961427/8437ebc3-7eae-4468-b7e4-a3da8c89feb3)

4.5.3842

**Comment by e9gille** [comment]
Ah, the border is actually in place, I overlooked that it disappeared when I reduced the excessive width of the margin.
