### ISSUE TITLE
Docked editor tab tooltips should show filename (if any)

### ISSUE THREAD

**Issue by abrudz** [Dyalog/ride#1051]
### Describe the issue you are having
Floating editor window titlebars contain filename info, but it isn't available in non-floating window mode. 

Ideally, the tooltip would be of the language-bar type, so one can select the filename and/or it would be possibel to right-click on the tab and select "Copy path", like Notepad++ and VSCode have it.

4.5.3842

**Comment by e9gille** [comment]
Fixed in #1059
