### ISSUE TITLE
Tracer does not open with dyalog runtime in RIDE 4.  Does work in RIDE 3.

### ISSUE THREAD

**Issue by dyavc** [Dyalog/ride#107]
# RIDE Issue Report

### Describe the issue you are having
 Ride 4 does not open the tracer if I Action/Trace or press ctrl+enter in the session window

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Already running dyalog runtime

### How do you reproduce the issue?
 Create a workspace whose ⎕LX function Run has the following:   

Run;a
 {}3502⌶0
 {}3502⌶'SERVE::4512'
 {}3502⌶1
 'f'⎕WC'form'
⎕DQ'.'

⎕←'done'

### Paste the contents of Help → About (Shift+F1)
 IDE:
  Version: 4.0.2657
  Platform: Win32
  Date: 2017-02-20 14:18:24 +0000
  Git commit: 2b01969378d9c1b15f42d09bf60c95273a31eb2b
  Preferences:{
    "favs":"[{\"type\":\"listen\",\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"listen4502\"},{\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"connect4512\",\"ride_port\":\"4512\",\"type\":\"connect\",\"port\":\"4512\",\"host\":\"127.0.0.1\"}]",
    "kbdLocale":"en_US"
  }

Interpreter:
  Version: 15.0.29007
  Platform: Windows-64
  Edition: Unicode/64
  Date: Jan 16 2017 at 18:17:56

**Comment by dyavc** [comment]
Tracer does not open on a runtime dyalog.

Create a workspace whose ⎕lx function Run does the following:
 Run;a
 {}3502⌶0
 {}3502⌶'SERVE::4512'
 {}3502⌶1
 'f'⎕WC'form'
⎕DQ'.'

⎕←'done'


Either use this workspace with dyalogrt.exe or export a standalone runtime .exe.


IDE:
  Version: 4.0.2657
  Platform: Win32
  Date: 2017-02-20 14:18:24 +0000
  Git commit: 2b01969378d9c1b15f42d09bf60c95273a31eb2b
  Preferences:{
    "favs":"[{\"type\":\"listen\",\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"listen4502\"},{\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"connect4512\",\"ride_port\":\"4512\",\"type\":\"connect\",\"port\":\"4512\",\"host\":\"127.0.0.1\"}]",
    "kbdLocale":"en_US"
  }

Interpreter:
  Version: 15.0.29007
  Platform: Windows-64
  Edition: Unicode/64
  Date: Jan 16 2017 at 18:17:56

**Comment by dyavc** [comment]
Ctrl+ F12 ride protocol log of Ride 4 not working:

ctrl-F12 ride protocol log:
3326 send SupportedProtocols=2
3326 send UsingProtocol=2
3326 send ["Identify",{"identity":1}]
3326 send ["Connect",{"remoteId":2}]
3326 send ["GetWindowLayout",{}]
3520 recv SupportedProtocols=2
3521 recv UsingProtocol=2
3521 recv ["Identify",{"Port":0,"IPAddress":"","Vendor":"Dyalog Limited","Language":"APL","version":"15.0.29007","Machine":"VINCE-PC","arch":"Unicode/64","Project":"e:\\cust\\k1321\\v1321b.dws","Process":"dyalogrt.exe","User":"Vince","pid":31668,"token":"{AED1BE34-FE84-496F-9FAD-BE4F47FFCCD7}","date":"Created: Jan 16 2017 at 18:17:56","platform":"Windows-64"}]
3523 send ["SetPW",{"pw":74}]
3526 recv ["UpdateDisplayName",{"displayName":"e:\\cust\\k1321\\v1321b.dws"}]
3527 recv ["AppendSessionOutput",{"result":[""]}]
3527 recv ["SetPromptType",{"type":0}]
18827 send ["StrongInterrupt",{}]
18852 recv ["HadError",{"error":1003,"dmx":0}]
18886 recv ["AppendSessionOutput",{"result":"INTERRUPT\n"}]
18896 recv ["AppendSessionOutput",{"result":"Run[5] ⎕DQ'.'\n"}]
18899 recv ["AppendSessionOutput",{"result":"      ∧\n"}]
18904 recv ["FocusThread",{"tid":0}]
18941 send ["UnknownCommand",{"name":"FocusThread"}]
18954 recv ["SetPromptType",{"type":1}]
20886 send ["Execute",{"trace":0,"text":"      \n"}]
20925 recv ["EchoInput",{"input":"      \n"}]
20949 recv ["SetPromptType",{"type":0}]
20959 recv ["FocusThread",{"tid":0}]
20962 recv ["SetPromptType",{"type":1}]
20983 send ["UnknownCommand",{"name":"FocusThread"}]
21534 send ["Execute",{"trace":0,"text":"      \n"}]
21563 recv ["EchoInput",{"input":"      \n"}]
21585 recv ["SetPromptType",{"type":0}]
21593 recv ["FocusThread",{"tid":0}]
21599 recv ["SetPromptType",{"type":1}]
21616 send ["UnknownCommand",{"name":"FocusThread"}]
24344 send ["Execute",{"trace":0,"text":"      \n"}]
24377 recv ["EchoInput",{"input":"      \n"}]
24409 recv ["SetPromptType",{"type":0}]
24415 recv ["FocusThread",{"tid":0}]
24421 recv ["SetPromptType",{"type":1}]
24436 send ["UnknownCommand",{"name":"FocusThread"}]
30147 send ["GetAutocomplete",{"line":"      )off","pos":10,"token":0}]
30181 recv ["ReplyGetAutocomplete",{"options":[],"skip":4,"token":0}]

**Comment by dyavc** [comment]
RIDE 3 working, protocol log:

1 2017-03-02T11:18:06.592Z
946 browser connected
1033 from browser:["*getProxyInfo"]
2514 to browser:["*proxyInfo",{"interpreters":[{"exe":"C:\\Dyalog101\\dyalog.exe","ver":[10,1],"bits":32,"edition":"classic"},{"exe":"C:\\Dyalog\\Dyalog APL 11.0\\\\dyalog.exe","ver":[11,0],"bits":32,"edition":"classic"},{"exe":"C:\\Program Files (x86)\\Dyalog\\Dyalog APL 12.0 Classic\\\\dyalog.exe","ver":[12,0],"bits":32,"edition":"classic"},{"exe":"C:\\Program Files (x86)\\Dyalog\\Dyalog APL 12.0 Unicode\\\\dyalog.exe","ver":[12,0],"bits":32,"edition":"unicode"},{"exe":"C:\\dyalog\\12.1.Classic\\\\dyalog.exe","ver":[12,1],"bits":32,"edition":"classic"},{"exe":"C:\\Dyalog\\12.1.Unicode\\\\dyalog.exe","ver":[12,1],"bits":32,"edition":"unicode"},{"exe":"C:\\Dyalog\\13.0.Classic\\\\dyalog.exe","ver":[13,0],"bits":32,"edition":"classic"},{"exe":"C:\\Dyalog\\13.0.Unicode\\\\dyalog.exe","ver":[13,0],"bits":32,"edition":"unicode"},{"exe":"C:\\Program Files (x86)\\Dyalog\\Dyalog APL 13.1 Classic\\\\dyalog.exe","ver":[13,1],"bits":32,"edition":"classic"},{"exe":"C:\\Program Files (x86)\\Dyalog\\Dyalog APL ...
5140 from browser:["*connect",{"host":"127.0.0.1","port":4512}]
5145 to browser:["*connected",{"host":"127.0.0.1","port":4512}]
5416 send SupportedProtocols=2
5420 send UsingProtocol=2
5420 send ["Identify",{"identity":1}]
5420 send ["Connect",{"remoteId":2}]
5420 send ["GetWindowLayout",{}]
5422 recv SupportedProtocols=2
5446 recv UsingProtocol=2
5523 recv ["Identify",{"Port":0,"IPAddress":"","Vendor":"Dyalog Limited","Language":"APL","version":"15.0.29007","Machine":"VINCE-PC","arch":"Unicode/64","Project":"e:\\cust\\k1321\\v1321b.dws","Process":"dyalogrt.exe","User":"Vince","pid":6240,"token":"{B5C19F8D-1D23-4EEF-91CC-7899C716B6E5}","date":"Created: Jan 16 2017 at 18:17:56","platform":"Windows-64"}]
5532 send ["SetPW",{"pw":110}]
5558 recv ["UpdateDisplayName",{"displayName":"e:\\cust\\k1321\\v1321b.dws"}]
5605 recv ["AppendSessionOutput",{"result":[""]}]
5627 recv ["SetPromptType",{"type":0}]
14379 send ["StrongInterrupt",{}]
14400 recv ["HadError",{"error":1003,"dmx":0}]
14405 recv ["AppendSessionOutput",{"result":"INTERRUPT\n"}]
14409 recv ["AppendSessionOutput",{"result":"Run[5] ⎕DQ'.'\n"}]
14417 recv ["AppendSessionOutput",{"result":"      ∧\n"}]
14421 recv ["FocusThread",{"tid":0}]
14425 recv ["SetPromptType",{"type":1}]
14436 send ["UnknownCommand",{"name":"FocusThread"}]
16769 send ["Execute",{"trace":1,"text":"      \n"}]
16789 recv ["OpenWindow",{"currentRow":5,"debugger":1,"entityType":1,"name":"Run","offset":0,"readOnly":0,"size":0,"stop":[],"text":[" Run;a"," {}3502⌶0"," {}3502⌶'SERVE::4512'"," {}3502⌶1"," 'f'⎕WC'form'"," ⎕DQ'.'",""," ⎕←'done'"],"tid":0,"tname":"Tid:0","token":1}]
16847 recv ["SetHighlightLine",{"win":1,"line":5}]
20558 send ["CloseWindow",{"win":1}]
20593 recv ["CloseWindow",{"win":1}]
20673 recv ["FocusThread",{"tid":0}]
20790 send ["UnknownCommand",{"name":"FocusThread"}]
25718 send ["GetAutocomplete",{"line":"      )","pos":7,"token":0}]
25740 recv ["ReplyGetAutocomplete",{"options":[")CLEAR",")CMD",")CONTINUE",")COPY",")CS",")DROP",")ED",")ERASE",")EVENTS",")FNS",")LIB",")LOAD",")METHODS",")NS",")OBS",")OBJECTS",")OFF",")OPS",")PCOPY",")PROPS",")RESET",")SAVE",")SH",")SI",")SINL",")HOLDS",")TID",")VARS",")WSID",")XLOAD",")CLASSES",")SIC"],"skip":1,"token":0}]
26130 send ["GetAutocomplete",{"line":"      )o","pos":8,"token":0}]
26188 recv ["ReplyGetAutocomplete",{"options":[")obs",")objects",")off",")ops"],"skip":2,"token":0}]
26367 send ["GetAutocomplete",{"line":"      )of","pos":9,"token":0}]
26426 recv ["ReplyGetAutocomplete",{"options":[")off"],"skip":3,"token":0}]
26604 send ["GetAutocomplete",{"line":"      )off","pos":10,"token":0}]
26656 recv ["ReplyGetAutocomplete",{"options":[],"skip":4,"token":0}]
27734 send ["Execute",{"trace":0,"text":"      )off\n"}]
27748 recv ["EchoInput",{"input":"      )off\n"}]
27767 recv ["SetPromptType",{"type":0}]
27771 interpreter diconnected
27771 to browser:["*disconnected",null]

**Comment by jayfoad** [comment]
Fixed by 4ff05735198d2ff5a74e0399bd7aff71611103eb
