### ISSUE TITLE
Help menu item can go to the wrong RIDE documentation

### ISSUE THREAD

**Issue by abrudz** [Dyalog/ride#1081]
### Describe the issue you are having
Help > Documentation Centre > RIDE User Guide shows me help for RIDE 3.0, even though I'm using RIDE 4.5.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Start an interpreter

### How do you reproduce the issue?
Help > Documentation Centre > RIDE User Guide

### Paste the contents of Help → About (Shift+F1)
```
  Version: 4.5.3886
  Electron: 25.3.2
  Chrome: 114.0.5735.248
  Node: 18.15.0
  Platform: Win32
  Date: 2023-08-10 09:25:56 +0200
  Git commit: af15c1b2f07d6e4677218605321dee070463e423

Interpreter:
  Version: 15.0.12345
  Platform: Windows-64
  Edition: Unicode/64
  Date: Jul 25 2023 at 20:29:15
```

**Comment by e9gille** [comment]
Just to be clear, this is currently handled outside of this repo, so nothing I can do about it.

**Comment by abrudz** [comment]
@e9gille Correct. We're deciding what to do about it today, and will update this issue with actionable items.
