### ISSUE TITLE
Make edit msgbox error message more user friendly, e.g. by removing it altogether

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/ride#109]
z←(⎕Wa-100000)⍴2
z ED

Msgbox appears with "An error (1) occurred processing Edit"

How about "Error: WS FULL generated by the Editor" (approved by docs mgr)

IDE:
  Version: 4.0.2679
  Platform: MacIntel
  Date: 2017-03-01 19:10:37 +0000
  Git commit: c359f660447dce9b29195939a3a6a052af6cedac
  Preferences:{

  }

Interpreter:
  Version: 16.0.29355
  Platform: Mac-64
  Edition: Unicode/64
  Date: Mar  2 2017 at 02:32:24

**Comment by e9gille** [comment]
@johndaintree This currently reports the undocumented **InternalError** with an object:
{
  "error": 1,
  "dmx": 0
  "message": "Edit"
}

Do you want to include more detail for us to show or add something to the protocol to request/map from error number to description?

**Comment by johndaintree** [comment]
I can include the ⎕EM of the error number (in this case 1 == WS FULL) if that would help you. Pretty much all I have to give is ⎕EN (and ⎕EM), ⎕DMX.Message and the protocol message that lead to the error.

 

/JD

**Comment by e9gille** [comment]
@johndaintree That should be plenty.
@dyaandys Are you happy with that? I don't think RIDE should have a dictionary of error messages for these errors, what JD is offering is probably enough.

**Comment by dyaandys** [comment]
OK .. @FionaDyalog and I will have a chat with JD: we're more than happy with the "WS FULL", but we really would like something better than "processing Edit" .. but we don't know what the full list of "message" is ..

**Comment by abrudz** [comment]
WinIDE doesn't pop up a message, it just prints `WS FULL` in the session (19.0: in error colour). RIDE could do the same.

Btw, `⎕ED'z'` gives a normal `WS FULL ERROR` on `⎕ED` and `)ed z` gives `WS FULL ERROR`. There's no reason Shift+Enter or double-clicking should be any different.

**Comment by e9gille** [comment]
RIDE can't add text to the session log itself as it would cause the logs to get out of sync. I see that the message now includes the property `error_text` that has a more descriptive message, so will use that instead for now. If you want the message written to session the interpreter should be changed to send an `AppendSessionOutput` rather than `InternalError`
