### ISSUE TITLE
Having got an error from the Editor, the next line entered in the session generates a SYNTAX ERROR

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/ride#110]
z←(⎕wa-10000)⍴2
      z ED
Close the resulting message box
In session
      1
SYNTAX ERROR
      1
       ∧

I think there might be a syserror lurking around here too ..

IDE:
  Version: 4.0.2679
  Platform: MacIntel
  Date: 2017-03-01 19:10:37 +0000
  Git commit: c359f660447dce9b29195939a3a6a052af6cedac
  Preferences:{

  }

Interpreter:
  Version: 16.0.29355
  Platform: Mac-64
  Edition: Unicode/64
  Date: Mar  2 2017 at 02:32:24

**Comment by jayfoad** [comment]
This is a bug in the interpreter, not in RIDE.

**Comment by johndaintree** [comment]
I can fix this with PROTECTEDSTART2 and PROTECTEDEND2. This pushes/pops keeps and saves/restores the SIstack.

**Comment by dyaandys** [comment]
Now Mantis 014313: RIDE related: Having got an error from the Editor, the next line entered in the session generates a SYNTAX ERROR

**Comment by jayfoad** [comment]
Fixed in the interpreter in 16.0.29369.
