### ISSUE TITLE
Regressions in version v4.5.3915 when compared to v4.5.3770

### ISSUE THREAD

**Issue by kspalaiologos** [Dyalog/ride#1100]
The following things seem to be broken in the newer build but work fine in the older build:
- Preferences screen does not open in the new version
- Connecting to a local instance of an interpreter which refuses connection freezes RIDE in a blue screen.

**Comment by e9gille** [comment]
Could be related to changes in the preferences, perhaps some of the changes are not backwards compatible. Can you manage to bring up the `About` window? If so, please copy/paste the content in here and I can take a look.

**Comment by e9gille** [comment]
Re-open if it is still an issue with in the latest pre-release
