### ISSUE TITLE
The Help window shows the text for the chosen name/symbol, but also shows the previous one, even if it had been closed

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/ride#111]
Hit F1 on ⎕PW .. you will get two tabs on for the ⎕PW documentation ..

open a tab and navigate to bbc.co.uk for example
close all tabs
Hit F1 on ⎕rtf .. now you're likely to get tabs for ⎕rtf, ⎕PW and bbc.co.uk

http://help.dyalog.com/15.0/Content/Language/System%20Functions/pp.htm

IDE:
  Version: 4.0.2679
  Platform: MacIntel
  Date: 2017-03-01 19:10:37 +0000
  Git commit: c359f660447dce9b29195939a3a6a052af6cedac
  Preferences:{

  }

Interpreter:
  Version: 16.0.29355
  Platform: Mac-64
  Edition: Unicode/64
  Date: Mar  2 2017 at 02:32:24

**Comment by jayfoad** [comment]
Can't reproduce in RIDE 4.1 on the Mac.
