### ISSUE TITLE
Adress os-locale 6.0.0 breaking change

### ISSUE THREAD

**Issue by TomaSajt** [Dyalog/ride#1112]
### Describe the issue you are having

The `os-locale` dependency has been updated in a [recent commit](https://github.com/Dyalog/ride/commit/012e31c1839c347b8d41d29eb27f0902baac7d63) from `5.0.0` to `6.0.2`.

However there was a breaking change between major versions, which was that `os-locale` became a pure ESM package.

[Changelog of `os-locale` `6.0.0`](https://github.com/sindresorhus/os-locale/releases/tag/v6.0.0)
[The package owner's proposed solutions for using the package with Electron](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#how-can-i-import-esm-in-electron)

I did not notice this change, because of my saved preferences (in `prefs.js` the `kbdLocale` field), however, once I deleted my RIDE config directory, (or just the prefs file,) it couldn't start the interpreter, because of errors being thrown about not being able to `require(...)` ESM modules.

I think it is acceptable to revert the version of `os-locale` to `5.0.0`

**Comment by e9gille** [comment]
well spotted, will downgrade as suggested
