### ISSUE TITLE
Edit window unsaved data indicator not cleared on save

### ISSUE THREAD

**Issue by xpqz** [Dyalog/ride#1120]
### Describe the issue you are having

If you edit a function, the 'contains unsaved data' blob appears. However, if you then save the window by clicking on the floppy disk icon, it's not cleared -- expected to get the cross back.

<img width="371" alt="Screenshot 2023-09-01 at 09 59 50" src="https://github.com/Dyalog/ride/assets/2690852/fc59a7ca-192e-4640-af83-97f2caebfa9b">

### Did you connect to an already running interpreter or start the interpreter from RIDE?

Started interpreter.

### How do you reproduce the issue?

1. Type `)ed test`. 
2. Make a change to the function.
3. Click floppy disk icon

### Paste the contents of Help → About (Shift+F1)
```
IDE:
  Version: 4.5.3969
  Electron: 25.3.2
  Chrome: 114.0.5735.248
  Node: 18.15.0
  Platform: MacIntel
  Date: 2023-09-01 09:02:21 +0100
  Git commit: a8a0a2d35320f003a3d2f7c0e2a55f235576eca0
 
Interpreter:
  Version: 19.0.47336
  Platform: Mac-64
  Edition: Unicode/64
  Date: Jun 22 2023 at 00:48:15

```

**Comment by xpqz** [comment]
I'm re-opening this -- it now works for when clicking the floppy disk save icon, but it still does not work for the key binding FX.

**Comment by e9gille** [comment]
I can't replicate this. After assigning a keyboard shortcut for FX it does save and remove the marker, both in floating and docked windows.

**Comment by xpqz** [comment]
Ok, tried latest build; does the right thing.
