### ISSUE TITLE
Custom options pane behaves badly in narrow windows

### ISSUE THREAD

**Issue by abrudz** [Dyalog/ride#1121]
![image](https://github.com/Dyalog/ride/assets/10961427/08beacc8-dc40-4b11-bbfb-3914fb2cbb48)

- [ ] If possible, prevent window from getting too narrow
- [ ] Buttons at the bottom should never render outside the window
- [ ] If not enough space, fold labels and input fields so each label is above its input field
- [ ] If not enough space to show both panes, have the [custom options] button switch between them instead

4.5.3967

**Comment by e9gille** [comment]
fixed in #1134
