### ISSUE TITLE
Even further connection screen tweaks

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/ride#1125]
- [ ] Add headings to the two panes: "Available Configurations" and "Configuration Details" using a block with background colour matching the button areas
- [ ] Change background of left pane to #edeff5 in light mode, #08090c in dark mode
- [ ] Add #cn_favs > div border-bottom: 1px solid #dde0ec in light mode, #323446 in dark mode
- [ ] Make #cn_favs > div line-height 36xp

![image](https://github.com/Dyalog/ride/assets/10961427/2aa01523-b7e5-4c65-8842-1c2408a064c8)
![image](https://github.com/Dyalog/ride/assets/10961427/dfbaa191-cbeb-4f08-8829-041201fd45f7)

**Comment by abrudz** [comment]
The to-do list above is missing an entry for the left pane buttons:
- [ ] <kbd>N̲EW CONFIGURATION...</kbd> and <kbd>C̲USTOM OPTIONS ⟫</kbd> should be <kbd>N̲EW...</kbd> and <kbd>E̲DIT ⟫</kbd>
