### ISSUE TITLE
Improve editor colour token names and organisation

### ISSUE THREAD

**Issue by abrudz** [Dyalog/ride#1148]
Re-order, re-name (new ← old) and split the #col_grp select list into optgroups:

### User Interface
Autocomplete selection ← autocomplete sel
Cursor ← cursor
Matching bracket ← matching bracket
Search match ← search match
Selection ← selection
Modified session line ← modified line
Value tip ← value tip
Value tip target ← value tip target
RIDE disconnected ← disconnected

### Editor/Tracer
Active tracer← tracer
Pendent tracer ← pendent
Vector of character vectors ← charvecvec
Simple numeric array ← numarr
Simple character matrix ← charmat
Simple character vector ← charvec
Other character array ← chararr
Other array ← mixarr
Object representation ← quador
Line number ← line number
Line number active ← line number active

### Language Elements
Normal code ← normal
Assignment arrow ← assignment
Diamond ← diamond
Primitive function
Primitive operator monadic ← monadic operator
Primitive operator dyadic ← dyadic operator
Semicolon ← semicolon
Comment ← comment
Invalid syntax ← error
Invalid token ← invalid token
Optimised idiom ← idiom
Keyword ← keyword

### Values
Character literal ← string
Empty numeric vector ← zilde
Number ← number
Root or parent namespace ← namespace
Tradfn name in header ← tradfn
User defined global ← global name
User defined local ← name
Label ← label
System name ← quad name
System name local ← quad name local
System command ← system command
User command ← user command

### Enclosures
Curly brace ← curly braces
Round parenthesis ← parenthesis
Square bracket ← bracket
Dfn ← dfn
Dfn level 1 ← dfn level 1
Dfn level 2 ← dfn level 2
Dfn level 3 ← dfn level 3
Dfn level 4 ← dfn level 4
Dfn level 5 ← dfn level 5

```
4.5.4014
```

**Comment by e9gille** [comment]
Fixed in #1154 #1156
