### ISSUE TITLE
RIDE asks "Quit Dyalog APL. Are you sure?" even though it is not closing Dyalog (when you hit the Close button)

### ISSUE THREAD

**Issue by dyavc** [Dyalog/ride#115]
# RIDE Issue Report

### Describe the issue you are having
RIDE 4.0: when you hit the Close button, RIDE asks "Quit Dyalog APL. Are you sure?" even though it is not closing Dyalog

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Already running interpreter 

### How do you reproduce the issue?
Start Dyalog like this:
dyalog.exe  log_file=null  -ride -RIDE_INIT=SERVE::4502 &

Connect ride 4 to it.  

Close Ride 4 with the X button.

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.0.2710
  Platform: Win32
  Date: 2017-03-06 11:26:39 +0100
  Git commit: 4ff05735198d2ff5a74e0399bd7aff71611103eb
  Preferences:{
    "favs":"[{\"type\":\"listen\",\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"listen4502\"},{\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"connect4512\",\"ride_port\":\"4512\",\"type\":\"connect\",\"port\":\"4512\",\"host\":\"127.0.0.1\"}]",
    "kbdLocale":"en_US"
  }

Interpreter:
  Version: 15.0.29232
  Platform: Windows-64
  Edition: Unicode/64
  Date: Feb 19 2017 at 17:55:23

**Comment by mbaas2** [comment]
This might be a V15-Problem - I could repro with V15.0.28955, but not  with V16.0.29298...

**Comment by flouc001** [comment]
@mbaas2 it may not show in V15 because the protocol messages have been extended for V16 :)

**Comment by flouc001** [comment]
@dyavc RIDE will also terminate the underlying APL interpreter in most exit cases, I will update the message to be clearer.

**Comment by jayfoad** [comment]
@flouc001 that's not quite right.

The behaviour we want is:
- If you close RIDE after spawning an interpreter, it should (prompt you and then) shut down that interpreter. I think the original prompt text was good: it didn't mention RIDE explicitly, which is nice in the Mac case where the end user isn't really aware of RIDE as a separate application; it's just providing a UI for the interpreter.
- If you close RIDE after connecting to a running interpreter, it should disconnect but leave the interpreter running. In this case probably no prompt is necessary(?)

**Comment by flouc001** [comment]
@jayfoad I see, but this isn't the current behaviour. When we send the Disconnect protocol message regardless of whether the interpreter has been started by RIDE or was pre-existing it shuts down. Should we not be using the Disconnect message in the case of connecting to an existing interpreter? @johndaintree

**Comment by jayfoad** [comment]
My [suggestion](https://github.com/Dyalog/ride/issues/122#issuecomment-285089002) was that sending Disconnect to an interpreter should not cause it to shut down; that's what the Exit message is for.

**Comment by johndaintree** [comment]
The interpreter does an )OFF on both exit and disconnect. If you want them to mean different things, that's easy. If you want to use a single message with a parameter to indicate disconnect/exit then that's easy too. I agree that the two case should be distinct. (but I also think the user should have the option to just disconnect from spawned and exit from attached).

**Comment by flouc001** [comment]
@johndaintree I think we will want separate messages doing separate things. A "Disconnect" message should do just that and not )off afterwards. "Exit" on the other hand should shut down the interpreter.

**Comment by flouc001** [comment]
Fixed in interpreter 16.0.29830 and RIDE commit 5700c3d.
