### ISSUE TITLE
empty host field should always default to 127.0.0.1

### ISSUE THREAD

**Issue by dyavc** [Dyalog/ride#116]
# RIDE Issue Report

### Describe the issue you are having
I'm trying to connect to port 4512 on the localhost.  I'm starting ride 4 and empty host field should always default to 127.0.0.1

### Did you connect to an already running interpreter or start the interpreter from RIDE?
already running

### How do you reproduce the issue?
Start dyalog with 
dyalog.exe  log_file=null  -ride -RIDE_INIT=SERVE::4512

Start ride and try to connect to 4512 but without putting anything in host field
it does not work.

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.0.2710
  Platform: Win32
  Date: 2017-03-06 11:26:39 +0100
  Git commit: 4ff05735198d2ff5a74e0399bd7aff71611103eb
  Preferences:{
    "favs":"[{\"type\":\"listen\",\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"listen4502\"},{\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"connect4512\",\"ride_port\":\"4512\",\"type\":\"connect\",\"port\":\"4512\",\"host\":\"127.0.0.1\"}]",
    "kbdLocale":"en_US"
  }

Interpreter:
  Version: 15.0.29232
  Platform: Windows-64
  Edition: Unicode/64
  Date: Feb 19 2017 at 17:55:23

**Comment by jayfoad** [comment]
OK, but "127.0.0.1" is IPv4-specific. I suggest "localhost" instead.
