### ISSUE TITLE
ssh port should default to 22

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/ride#117]
# RIDE Issue Report

### Describe the issue you are having
When you select "Start an interpreter" and check the "start the interpreter over ssh" checkbox, the port number should default to 22 (the ssh port), instead of 4502 (the default RIDE port).

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Started APL from RIDE via ssh on a raspberry Pi.

### How do you reproduce the issue?
See description.

### Paste the contents of Help → About (Shift+F1)
git pull from March 6th (no version information in Help|About)

**Comment by jayfoad** [comment]
It does default to 22! Perhaps you have set it to something else and then saved the connection? What happens if you go to the "port" field and delete the number? You should see the placeholder (default) value of 22 in grey text.

**Comment by mkromberg** [comment]
It does now. The 4502 I saw may have been some kind of "alternative fact", I cannot reproduce it today.
