### ISSUE TITLE
Fetching list of interpreters starts the current config

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/ride#1179]
### Describe the issue you are having
Clicking the "Fetch list of interpreters" button launches the current configuration.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Configuration is set to start one.

### How do you reproduce the issue?
Select configuration "mac5" and click the button.  (Please email me if you want a copy of my connections.json)

### Paste the contents of Help → About (Shift+F1)
(BTW, these instructions should be updated, as that menu item currently is on a different spot)
```
IDE:
  Version: 4.5.4043
  Electron: 25.3.2
  Chrome: 114.0.5735.248
  Node: 18.15.0
  Platform: Win32
  Date: 2023-09-26 17:25:50 +0200
  Git commit: 5f3a6111e4c67f4c605b4cdbaff1088208d5972d
  Preferences:{
    "autoPW":"1",
    "connectOnQuit":"1",
    "kbdLocale":"de_DE",
    "persistentHistorySize":"1000",
    "pfkeys":"[\"\",\"\",\"\",\"\",\"+2⎕nq'.' 'GetEnvironment' '\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\"]",
    "prefixKey":"<",
    "selectedExe":"/opt/mdyalog/19.0/64/unicode/p9/mapl",
    "wse":"1"
  }

Interpreter:
  Version: unknown
  Platform: unknown
  Edition: unknown
  Date: unknown

```

**Comment by e9gille** [comment]
Please re-open if you can replicate.
