### ISSUE TITLE
When launching RIDE (also when using "Connect on quit"), my 6th config always has the focus

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/ride#1180]
### Describe the issue you are having
This seems a bit odd because it is not the default config and it also isn't the one I last used (which I would find "most natural")

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Launched RIDE.

### How do you reproduce the issue?
Launch RIDE, remember highlighted config (for me: nr. 6), launch a different interpreter, quit, search highlighted config - in my case: nr. 6 again!

### Paste the contents of Help → About (Shift+F1)
```
IDE:
  Version: 4.5.4043
  Electron: 25.3.2
  Chrome: 114.0.5735.248
  Node: 18.15.0
  Platform: Win32
  Date: 2023-09-26 17:25:50 +0200
  Git commit: 5f3a6111e4c67f4c605b4cdbaff1088208d5972d
  Preferences:{
    "autoPW":"1",
    "connectOnQuit":"1",
    "kbdLocale":"de_DE",
    "persistentHistorySize":"1000",
    "pfkeys":"[\"\",\"\",\"\",\"\",\"+2⎕nq'.' 'GetEnvironment' '\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\"]",
    "prefixKey":"<",
    "selectedExe":"/opt/mdyalog/19.0/64/unicode/p9/mapl",
    "wse":"1"
  }

Interpreter:
  Version: unknown
  Platform: unknown
  Edition: unknown
  Date: unknown
```

**Comment by abrudz** [comment]
Can't repro, please post gif.

**Comment by e9gille** [comment]
Please re-open if you can replicate.
