### ISSUE TITLE
Simplify connect screen

### ISSUE THREAD

**Issue by abrudz** [Dyalog/ride#1197]
### Describe the issue you are having
- [x] Whenever a config setting input field is changed, auto-save
- [x] Remove <kbd>SAVE</kbd> button
- [x] Remove <kbd>MAKE DEFAULT</kbd> button
- [x] Change "Auto-start default configuration when RIDE starts" into "Auto-start top-most configuration when RIDE starts"
- [x] Allow moving top-most config down, and any other config up to top
- [x] Make all configs have the same size and look
- [x] Move Play buttons to left of config titles
- [x] On right hand end of each config entry, add cog button which opens right pane
- [x] Remove right hand pane toggle button next to "Available Configurations"
- [x] CSS everything in left pane to "user-select:none"

4.5.4043

**Comment by e9gille** [comment]
Additional changes added in #1205
