### ISSUE TITLE
The current session is remote. To connect elsewhere or launch a local interpreter, please use "Connect..." instead.

### ISSUE THREAD

**Issue by JasonRivers** [Dyalog/ride#12]
When "launch an interpreter" on the local system followed by "New Session" I'm presented with a message: "The current session is remote. To connect elsewhere or launch a local interpreter, please use "Connect..." instead.", The current session is local and not remote.

--- 

IDE:
  Version: 4.0.2395
  Platform: Linux x86_64
  Date: 2016-10-27 10:19:12 +0100
  Git commit: e309bb5e21cbed5b0a4d2d0a3644d0b6d09f6462
  Preferences:{
    "favs":"[{\"type\":\"start\",\"ssh_auth_type\":\"pass\",\"exe\":\"/opt/mdyalog/16.0/64/unicode/mapl\"}]",
    "kbdLocale":"en_GB",
    "selectedExe":"/opt/mdyalog/16.0/64/unicode/mapl",
    "theme":"classic",
    "colourScheme":"Francisco Goya"
  }

Interpreter:
  Version: 16.0.28511
  Platform: Linux-64
  Edition: Unicode/64
  Date: Oct 26 2016 at 02:24:33

**Comment by jayfoad** [comment]
Seems fixed by that commit.
