### ISSUE TITLE
Preferences dialog is not tall enough for its content

### ISSUE THREAD

**Issue by abrudz** [Dyalog/ride#120]
On Linux
![image](https://cloud.githubusercontent.com/assets/10961427/23667357/75b2dc14-0355-11e7-9999-16fd242dcced.png)

**Comment by JasonRivers** [comment]
My feeling is that the problem is the preferences window is not a separate window, and is actually just a floating DIV, if this was a separate window it would make it easier as I could also move it out of the way while looking at my colouring options.
