### ISSUE TITLE
Style issues of connect screen cogs and play button

### ISSUE THREAD

**Issue by abrudz** [Dyalog/ride#1206]
- [ ] First config's play button is always visible, even when not selected/hovered
- [ ] All cogs are always visible, even when not selected/hovered
- [ ] Selected config's cog should be white, not grey
- [ ] Hovering over sleected config's cog makes it invisible

![image](https://github.com/Dyalog/ride/assets/10961427/236873be-bff1-4db3-aab0-8a2fa059fb2d)

![image](https://github.com/Dyalog/ride/assets/10961427/b3909fcf-00f9-43b2-9bb9-1a1f17e39561)

4.5.4087

**Comment by e9gille** [comment]
I can't replicate any of this, but what you describe suggests the build didn't run. How did you run this?

**Comment by abrudz** [comment]
Downloaded and installed the pre-release. However, I did install it on top of my existing 4.5 without uninstalling the old one — could that play tricks?

**Comment by abrudz** [comment]
Can't repro any more
