### ISSUE TITLE
Platform pre-requisites statements likely out of date

### ISSUE THREAD

**Issue by FionaDyalog** [Dyalog/ride#1223]
The [installation]( https://dyalog.github.io/ride/4.5/installation/) section makes version statements that look to be out of date. Windows 7 support was [dropped](https://www.electronjs.org/blog/windows-7-to-8-1-deprecation-notice) for Electron v23, for example.

**Comment by xpqz** [comment]
The information is present here: https://dyalog.github.io/ride/4.5/installation/

However, the versions are almost certainly out of date; we're at the mercy of the exact version of Electron.

**Comment by xpqz** [comment]
Deployed: https://dyalog.github.io/ride/4.5/installation/
