### ISSUE TITLE
Editing name-at-line-number fails to scroll the edit window

### ISSUE THREAD

**Issue by JohnScholes** [Dyalog/ride#124]
# RIDE Issue Report

### Describe the issue you are having
If you Shift+Enter or double click a name-with-line-number, the edit window opens with the character cursor on the appropriate line but with the text un-scrolled in the edit window. Typing any keystrokes (eg RC)  cause the edit window to scroll appropriately.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
No

### How do you reproduce the issue?
      )xload dfns
... saved ...
      notes find'antithesis'
 #.notes.declarative[80]  functional. The antithesis of denotative is 'impera···

Double-click (or Shift+Enter) on "declarative": the character cursor will be on line 80, which (with my edit window size) is scrolled off the bottom of the window.

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.0.2710
  Platform: MacIntel
  Date: 2017-03-06 11:26:39 +0100
  Git commit: 4ff05735198d2ff5a74e0399bd7aff71611103eb
  Preferences:{
    "lineNums":"0",
    "zoom":"5"
  }

Interpreter:
  Version: 16.0.29396
  Platform: Mac-64
  Edition: Unicode/64
  Date: Mar  6 2017 at 15:13:25

**Comment by jayfoad** [comment]
Similar to #102, we get into this bit of D.Ed.open:

    cm.setCursor(line,col);cm.scrollIntoView(null,cm.getScrollInfo().clientHeight/2)

... before things have been laid out properly. In this case, if I stop here in the debugger, clientHeight is -30!

**Comment by jayfoad** [comment]
Works for me in master (RIDE 4.1).
