### ISSUE TITLE
Quote-quad output doesn't like backspace chars

### ISSUE THREAD

**Issue by JohnScholes** [Dyalog/ride#125]
# RIDE Issue Report

### Describe the issue you are having
Backspace chars embedded in a vector assigned to ⍞ show up as red blobs.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
No 

### How do you reproduce the issue?
⍞←'hello',(5⍴⊃⎕tc),'world'   ⍝ should display as: world

Also:
      )load max
... saved ...
      max''  ⍝ start max's REPL - ignore horrid red blobs
    )  // quit max's REPL

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.0.2720
  Platform: MacIntel
  Date: 2017-03-07 17:34:10 +0100
  Git commit: 70ef64b21888efb7ea30f09c64baebf7d6583031
  Preferences:{
    "lineNums":"0",
    "zoom":"5"
  }

Interpreter:
  Version: 16.0.29412
  Platform: Mac-64
  Edition: Unicode/64
  Date: Mar  8 2017 at 02:33:17

**Comment by e9gille** [comment]
@JohnScholes I just had to look into this as I've never used backspace in this fashion. What I understand you'd expect the backspace character to be interpreted as moving the cursor a step to the left, but only if sent to ⍞? RIDE can't tell the difference between text written to the session or via assignment to ⍞.

@johndaintree Is it down to the interpreter or RIDE to treat backspace the way JS expects?

**Comment by JohnScholes** [comment]
This has low, if any, priority. I might be the only person on the planet still using ⍞ :-) I'll change my app.

Historical note: The way all input to APL was originally conceived was that the system presented a whole line, from col 0 to col ⎕pw-1, possibly including some text, and with the input cursor placed at some position. The user then *overtyped* that line in any order and returned the whole line to the system by pressing Enter (with the cursor anywhere in the line). The fashion now is to separate a read-only prompt, on the left, from user-input text on the right.

IMHO the APL input mechanism was superior to the new-fangled prompt-field vs input-field fad but, hey ho, that's progress :-(

Us old ⍞-users liked to play visual tricks. For example, by sending umpteen reshape of '|/-\', with intervening backspaces, to ⍞, one could animate a spinning stick. People used this to show the system hadn't died while something was happening.

My use in supplied workspace max.dws is to show the combinators loading at the start of a max session.  On a slow machine, you can see the single character primitive function and combinator codes !+-∘○↓IKSBC$¢&Y∇+-!↑↓∘⊂?⍬ briefly appear, one at a time, as they are loaded.

What you see in MacDyalog is:




No prob, I'll change max.dws and we can all go back to sleep.

John

**Comment by abrudz** [comment]
You're not the only one. I was also disappointed to see that the IDE's effect of overwriting is not universal.

**Comment by johndaintree** [comment]
This isn't a ⍞ issue. The display of that array in RIDE is the same:

 

 



 

We should address the question of how RIDE displays backspaces first (FWIW I don't have a problem with the above). Then we can consider if ⍞ should preprocess it's input (if that would help).

 

/JD

**Comment by e9gille** [comment]
@johndaintree Red dots is not the problem. In the ODE you can see how backspace is treated in 3 different ways depending on context:

![image](https://cloud.githubusercontent.com/assets/8232484/23873265/bc6cc490-0831-11e7-9b20-e5e7b8f22405.png)

**Comment by e9gille** [comment]
To be honest, I thought the same and started looking at it a couple of weeks ago, but then got distracted. I'll see what I can do now.
