### ISSUE TITLE
⎕PFKEY doesn't work on the Mac version

### ISSUE THREAD

**Issue by JohnScholes** [Dyalog/ride#126]
# RIDE Issue Report

### Describe the issue you are having
Being able to (easily) program function keys F1..F12 is an important productivity tool. APLX has it and it works when I'm using the Windows version from my Mac, so it must be possible.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
No

### How do you reproduce the issue?
      '2+3' ⎕pfkey 4  ⍝ now press F4

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.0.2720
  Platform: MacIntel
  Date: 2017-03-07 17:34:10 +0100
  Git commit: 70ef64b21888efb7ea30f09c64baebf7d6583031
  Preferences:{
    "lineNums":"0",
    "zoom":"5"
  }

Interpreter:
  Version: 16.0.29412
  Platform: Mac-64
  Edition: Unicode/64
  Date: Mar  8 2017 at 02:33:17

**Comment by jayfoad** [comment]
We're not planning to support ⎕PFKEY on the Mac, but you can achieve the same result by going to Preferences->Shortcuts and entering "2+3" in the box for PF4. You can also but keystroke codes in here like "2+3<ER>".
