### ISSUE TITLE
Attempting to regenerate kbd definitions fails

### ISSUE THREAD

**Issue by bear8642** [Dyalog/ride#1268]
Attempting to regenerate kbd definitions by running tools/kbds-gen.js generates empty layouts definition

**Comment by MaxCan-Code** [comment]
tools/kbds-gen.js gave me an empty result as well, so I added Behind by hand:
https://github.com/MaxCan-Code/ride/commit/96b10fb5ac1be472bcc053f819c31455c6696119

**Comment by bear8642** [comment]
Realised dfns pages have moved from http → https

**Comment by MaxCan-Code** [comment]
Worked for me. Thanks!
