### ISSUE TITLE
Scrollbar arrows scroll too much and don't autorepeat

### ISSUE THREAD

**Issue by jayfoad** [Dyalog/ride#127]
When you click the arrow at either end of a RIDE scrollbar (down the side of the session or an editor) it seems to scroll by a full page, instead of just a line. And if you hold the mouse button down then nothing happens until you release it; it would be nice if it auto-repeated, scrolling a line at a time until you release the button.

**Comment by jayfoad** [comment]
@ngn I'm tempted to fix this by removing RIDE's custom "simple" scrollbars, and going back to the default "native" style. They look roughly the same (on Windows and Linux at least) but work better. Do you think this would cause problems? Why did you implement custom scrollbars in the first place (54a4db210c5aa32a20d5d65f273907efa87c567f)?

**Comment by ngn** [comment]
two reasons:
* to allow for virtual whitespace at the bottom of the session so the Dyalog banner can appear on top (but then I ran into race conditions on initialisation - I couldn't resolve them until @flouc001 came along)
* to have sane scrollbars on mac - the default ones are (were?) too narrow and show up only when you start scrolling

the name "simple" is inherited from https://github.com/codemirror/CodeMirror/blob/master/addon/scroll/simplescrollbars.js which I used as a starting point

**Comment by jayfoad** [comment]
> to allow for virtual whitespace at the bottom of the session so the Dyalog banner can appear on top

Even if I go back to "native" scrollbars I can still scroll (with the mouse wheel) down into virtual whitespace, so that my cursor is at the top of the screen.

**Comment by JohnScholes** [comment]
> I can still scroll (with the mouse wheel) down into virtual whitespace, so that my cursor is at the top of the screen.
> 

When I remember, I do that to move the banner to the top of the screen before plugging in the projector for a demo.

**Comment by ngn** [comment]
> Even if I go back to "native" scrollbars I can still scroll (with the mouse wheel) down into virtual whitespace

As long as the initial banner placement is correct, I think scrapping my custom scrollbars would be the right thing to do.
I guess Mac users wouldn't mind Apple's native invisible scrollbars too much.

**Comment by flouc001** [comment]
Commit d2f240f nullified code we wrote to ensure the session placement was correct when doing things such as opening the workspace explorer.
