### ISSUE TITLE
The focus on the dropdown list of interpreters that can be started is on the last line .. more useful to have on the first

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/ride#129]
The dropdown list of interpreters which can be started from RIDE is in reverse order - the most recent at the top of the list.  This seems sensible.
However, the "Other ..." option is at the bottom of the list, and is where the focus is initally on the dropdown list.  Be better to have the focus at the top of the list .. possibly move "Other ..." to the top ?

IDE:
  Version: 4.0.2729
  Platform: Win32
  Date: 2017-03-12 00:25:35 +0100
  Git commit: 65c21df5ad993a18c6da2c5f2172e62826f5598e
  Preferences:{
    "favs":"[{\"type\":\"connect\",\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"debian7dev\",\"host\":\"debian7dev.dyalog.bramley\",\"port\":\"4502\"},{\"type\":\"connect\",\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"dfsaix\",\"host\":\"10.0.61.100\",\"port\":\"9003\"},{\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"mac0\",\"host\":\"mac0\"},{\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"local\",\"host\":\"127.0.0.1\",\"port\":\"9999\",\"type\":\"start\",\"exe\":\"C:\\\\Program Files\\\\Dyalog\\\\Dyalog APL-64 16.0 Unicode\\\\dyalog.exe\"},{\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"p7-61qa\",\"host\":\"p7-61qa\",\"port\":\"4503\"}]",
    "kbdLocale":"en_GB",
    "lineNums":"0",
    "selectedExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 16.0 Unicode\\dyalog.exe",
    "title":"{WSID} {PID}",
    "wse":"1",
    "zoom":"-2"
  }

Interpreter:
  Version: unknown
  Platform: unknown
  Edition: unknown
  Date: unknown

**Comment by jayfoad** [comment]
How about just changing the order in which the interpreters are listed:

Version 14.1
Version 15.0
Version 16.0
Other... <- default selection is here

Otherwise it all seems a bit upside-down to me.

**Comment by dyaandys** [comment]
The reason for having the list in reverse order was that originally the focus was on the first item of the list, rather than the last.  And I would argue that the user is more likely to want to attach RIDE to the highest versioned interpreter.

 

I appreciate that I am an unusual case, but my list of interpreters on Windows has 7 entries for interpreters that I can attach RIDE  to, and 30 that it can’t.   

 

How about suppressing the unusable ones ..

 

 

A

**Comment by jayfoad** [comment]
> The reason for having the list in reverse order was that originally the focus was on the first item of the list, rather than the last.  And I would argue that the user is more likely to want to attach RIDE to the highest versioned interpreter.

Right, and with my suggestion the focus would still be right next to the highest versioned interpreter.

> How about suppressing the unusable ones ..

That seems like a backward step. We'll get complaints that "I've got APL installed but RIDE can't find it".

**Comment by dyaandys** [comment]
Not hugely fussed about the order .. although I find it more natural to start at the top of a list and work my way down – it is after all a dropdown list rather than a dropup list !

 

But as long as “Other” is next to the highest versioned interpreter, that’s the important bit.

**Comment by mkromberg** [comment]
1) "I've got APL installed but RIDE can't find it" is much better than "RIDE won't work with APL"
2) I think I want the most recent APL at the top (like messages in my InBox), it is generally the one I want to work with. Even if you put the focus at the end of the list it seems NAF to me.

**Comment by JasonRivers** [comment]
It seems odd to me that the focus by default is on "Other" rather than the latest "installed" interpreter, I would expect the focus to be on 16.0 if I have that installed. To me, "Other" would be for advanced users, 90% of the time you're probably going to want the latest APL that is installed on the box.

**Comment by jayfoad** [comment]
> "I've got APL installed but RIDE can't find it" is much better than "RIDE won't work with APL"

The ones it won't work with are greyed out and not selectable, so that's not an issue.

How about:

Version 16.0 <- default selection is here
Version 15.0
Version 14.1
Other...

**Comment by dyaandys** [comment]
Sorry .. do you mean

 

Version 16.0 <- default selection is here
Version 15.0

Other…
Version 14.1, 64-bit, Classic (unsupported)



That is that other is between the list of supported and unsupported APLs ?  Or that “Other…” still comes at the bottom of the list ?

 

 

A

**Comment by mkromberg** [comment]
Looks good to me.

**Comment by jayfoad** [comment]
I meant what I said: "Other..." at the bottom of the list. Looks a bit odd to me to have it sandwiched in the middle.
