### ISSUE TITLE
RIDE on Windows doesn't remember maximised window state

### ISSUE THREAD

**Issue by jayfoad** [Dyalog/ride#131]
On Windows if I maximise the RIDE window, then quit and restart, it restores the window to a fairly large size, but not actually maximised (and not quite filling my screen).

**Comment by ngn** [comment]
This library claims to be able to save position and maximised state (but not devtools state)
https://github.com/Sethorax/electron-window-state-manager
If you want to use it or a similar library, my code in `main.js` that reads and writes `winstate.json` may become obsolete.
