### ISSUE TITLE
Having maximised WS Explorer, closing it and typing a non-existent name results in APL not responding to keyboard input

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/ride#132]
Open APL
Open the workspace explorer
Maximise it so that it occupies all of the RIDE window
Close it
type foo in the session and hit Enter

no output, and now can't type into the session.  Only option is to hit X to close RIDE/APL down.

I also think that there are some focus issues when WS Explorer is closed .. if you do that while the editor is open, and then you close the editor, the session doesn't get the focus 

IDE:
  Version: 4.0.2739
  Platform: MacIntel
  Date: 2017-03-14 14:50:48 +0000
  Git commit: 03d6ff7cad87b89582756c9d541f38c3adb76b89
  Preferences:{
    "kbdLocale":"en_GB_Mac",
    "zoom":"2"
  }

Interpreter:
  Version: 16.0.29487
  Platform: Mac-64
  Edition: Unicode/64
  Date: Mar 14 2017 at 15:40:09

**Comment by jayfoad** [comment]
I can also reproduce this by closing an editor when it's maximised. Shortly afterwards, Se.focus() calls m.toggleMaximise() where m is not a GoldenLayout component, or has been destroyed or something, so we get `goldenlayout.min.js:2 Uncaught TypeError: Cannot read property 'preventDefault' of undefined`

**Comment by flouc001** [comment]
I have requested the fix I put in for dd23245 is reflected in the official GoldenLayout repository.
