### ISSUE TITLE
Menu item to save without closing editor

### ISSUE THREAD

**Issue by abrudz** [Dyalog/ride#133]
In the IDE, I often keep my code open while experimenting. Then I save and go to the session to try out my changes. I don't want to lose my place, so I keep the editor open.

In the IDE this command is File>Save.

**Comment by jayfoad** [comment]
In RIDE you can assign a keystroke to FX. Does that do what you want?

**Comment by abrudz** [comment]
Yes.

**Comment by ngn** [comment]
The user can add `Save =FX` to Prefs > Menu.
There might be an argument for having it there by default.
