### ISSUE TITLE
Input line length limited to ~127 chars

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/ride#134]
# RIDE Issue Report

### Describe the issue you are having
Input line length limited to 127 chars (ish)

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Doesn't matter.

### How do you reproduce the issue?
Backspace to the left margin and enter:
⍴'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbcccccccccccccccdddddddbbbbbb'
123
Now try to insert one more character into the vector. Hear a bleep. Input is discarded.

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.0.2742
  Platform: Win32
  Date: 2017-03-15 13:20:34 +0000
  Git commit: c7a95f46c2740c1fa094637ab634549016811a89
  Preferences:{
    "favs":"[{\"type\":\"start\",\"ssh_auth_type\":\"pass\",\"exe\":\"C:\\\\Users\\\\mkrom.INSIGHT\\\\AppData\\\\Local\\\\Programs\\\\Dyalog\\\\Dyalog APL-64 15.0 Unicode\\\\dyalog.exe\",\"ssh_tnl_auth_type\":\"pass\",\"host\":\"10.0.60.99\",\"name\":\"Local v15.0 64 U\"},{\"type\":\"start\",\"ssh_auth_type\":\"pass\",\"exe\":\"C:\\\\Program Files\\\\Dyalog\\\\Dyalog APL-64 16.0 Unicode\\\\dyalog.exe\",\"name\":\"Local v16.0 64 U\",\"ssh_tnl_auth_type\":\"pass\"},{\"type\":\"connect\",\"ssh_auth_type\":\"pass\",\"exe\":\"C:\\\\Users\\\\mkrom.INSIGHT\\\\AppData\\\\Local\\\\Programs\\\\Dyalog\\\\Dyalog APL-64 15.0 Unicode\\\\dyalog.exe\",\"name\":\"4502 on DFS Test\",\"ssh\":1,\"ssh_tnl_auth_type\":\"pass\",\"host\":\"192.168.6.236\",\"port\":\"4502\",\"user\":\"brian\"},{\"type\":\"connect\",\"ssh_auth_type\":\"pass\",\"exe\":\"C:\\\\Users\\\\mkrom.INSIGHT\\\\AppData\\\\Local\\\\Programs\\\\Dyalog\\\\Dyalog APL-64 15.0 Unicode\\\\dyalog.exe\",\"name\":\"4503 on DFS Test\",\"ssh\":1,\"ssh_tnl_auth_type\":\"pass\",\"host\":\"192.168.17.154\",\"port\":\"4503\",\"user\":\"brian\"},{\"type\":\"connect\",\"ssh_auth_type\":\"pass\",\"exe\":\"C:\\\\Users\\\\mkrom.INSIGHT\\\\AppData\\\\Local\\\\Programs\\\\Dyalog\\\\Dyalog APL-64 15.0 Unicode\\\\dyalog.exe\",\"name\":\"9003 on DFS Test\",\"ssh\":1,\"ssh_tnl_auth_type\":\"pass\",\"host\":\"192.168.17.154\",\"port\":\"9001\",\"user\":\"brian\"},{\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"PiZero\",\"host\":\"t8pz\",\"port\":\"4502\"}]",
    "kbdLocale":"da_DK",
    "keys":"{\"MA\":[\"F9\"],\"PF2\":[],\"PF3\":[],\"PF4\":[],\"PF5\":[],\"PF6\":[],\"PF7\":[],\"PF8\":[],\"PF9\":[],\"PF10\":[],\"RD\":[\"F5\"],\"RP\":[\"Shift-Ctrl-F\"]}",
    "lbarOrder":"←→ +-×÷*⍟⌹○!? |⌈⌊⊥⊤⊣⊢ =≠≤<>≥≡≢ ∨∧⍲⍱ ↑↓⊆⊂⊃⌷⍋⍒ ⍳⍷∪∩∊~⍸ /\\⌿⍀ ,⍪⍴⌽⊖⍉ ¨⍨⍣.∘⍤ ⍞⎕⍠⌸⌶⍎⍕ ⋄⍝⍵⍺∇& ¯⍬ ",
    "menu":"# see below for syntax\n\nDyalog                          {mac}\n  About Dyalog             =ABT\n  -\n  Preferences              =PRF\n  -                            \n  &Quit                    =QIT\n&File                           {!browser}\n  New &Session             =NEW\n  &Connect...              =CNC\n  -                             {!mac}\n  &Quit                    =QIT {!mac}\n&Edit\n  Undo                     =UND {!browser}\n  Redo                     =RDO {!browser}\n  -                             {!browser}\n  Cut                      =CT  {!browser}\n  Copy                     =CP  {!browser}\n  Paste                    =PT  {!browser}\n  Select All               =SA  {mac}\n  -                             {!mac&&!browser}\n  Preferences              =PRF {!mac}\n&View\n  Show Language Bar        =LBR\n  Show Workspace Explorer  =WSE\n  Show Debug               =DBG\n  Line Wrapping in Session =WRP\n  -                             {!browser}\n  Increase Font Size       =ZMI {!browser}\n  Decrease Font Size       =ZMO {!browser}\n  Reset Font Size          =ZMR {!browser}\n&Window\n  Close All Windows        =CAW\n&Action\n  Edit                     =ED\n  Trace                    =TC\n  Weak Interrupt           =WI\n  Strong Interrupt         =SI\n&Threads\n  Resume All Threads       =MA\n&Help\n  Dyalog Help              =http://help.dyalog.com/\n  Documentation Centre     =http://dyalog.com/documentation.htm\n  -\n  Dyalog Website           =http://dyalog.com/\n  MyDyalog                 =https://my.dyalog.com/\n  -\n  Dyalog Forum             =http://www.dyalog.com/forum\n  -                             {!mac}\n  About                    =ABT {!mac}\n\n# Syntax:\n#   &x   access key, alt+x\n#   =CMD command code; some are special:\n#          LBR FLT WRP TOP WSE render as checkboxes\n#   =http://example.com/  open a URL\n#   {}   conditional display, a boolean expression\n#          operators: && || ! ( )\n#          variables: browser mac win\n#   -    separator (when alone)\n#   #    comment\n\n# The =PRF (\"Preferences\") menu item must be present.",
    "otherExe":"/opt/mdyalog/16.0/32/unicode/mapl",
    "prefixKey":"<",
    "selectedExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 16.0 Unicode\\dyalog.exe",
    "wse":"1"
  }

Interpreter:
  Version: 16.0.29503
  Platform: Windows-64
  Edition: Unicode/64
  Date: Mar 16 2017 at 12:19:44

**Comment by jayfoad** [comment]
This is an interpreter bug.

**Comment by johndaintree** [comment]
Yes, the interpreter has a little internal buffer, which gives this restriction. We can bump the size of the buffer and send RIDE a message if the limit is hit.

**Comment by jayfoad** [comment]
We should do _something_ about this for 4.1, even if it's just increasing the limit.

**Comment by e9gille** [comment]
@jayfoad @johndaintree any update on this? Will the limit be increased? Is the protocol extended with the suggested message?

**Comment by bpbecker** [comment]
I'm running into the same issue in
IDE:
  Version: 4.1.3363
  Platform: Win32
  Date: 2018-06-20 16:03:15 +0200
  Git commit: a3de78419b8cd9d07833e209b406e76b57d545ad
Interpreter:
  Version: 17.0.33663
  Platform: Windows-64
  Edition: Unicode/64
  Date: Jul 10 2018 at 20:06:50
