### ISSUE TITLE
Ride 4 crashes on start-up

### ISSUE THREAD

**Issue by DyalogRichard** [Dyalog/ride#135]
# RIDE Issue Report

### Describe the issue you are having
Ride 4 crashes on start-up. If started from e.g. the command-line, it outputs lots of messages of the form

[11667:0317/095913:ERROR:gles2_cmd_decoder.cc(2291)] [.RenderWorker-0x1074c2e9aa00]GL ERROR :GL_INVALID_ENUM : GLES2DecoderImpl::DoBindTexImage2DCHROMIUM: <- error from previous GL command
[11667:0317/095913:ERROR:gles2_cmd_decoder.cc(2295)] [.RenderWorker-0x1074c2e9aa00]GL ERROR :GL_INVALID_OPERATION : ScopedTextureBinder::ctor: was unhandled

Disabling 3D graphics support in my VM is a workaround. Jay said:

"It seems like a problem with the Chromium engine using the GPU to do its rendering, and maybe some bad interaction with your VM.

Other people have reported similar things in Chrome and Electron, e.g.: 
http://askubuntu.com/questions/836616/chromium-crashes-upon-starting-in-ubuntu-16-04"

### Did you connect to an already running interpreter or start the interpreter from RIDE?
N/A - unable to get that far.

### How do you reproduce the issue?
Just start RIDE 4

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.0.2745
  Platform: Linux x86_64
  Date: 2017-03-16 14:13:05 +0000
  Git commit: 9094f072e717270099c645a3ae3141588d5be061
  Preferences:{
    "dbg":"1",
    "wse":"1"
  }

Interpreter:
  Version: unknown
  Platform: unknown
  Edition: unknown
  Date: unknown

**Comment by jayfoad** [comment]
> Disabling 3D graphics support in my VM is a workaround.

Another workaround, if you're starting RIDE from the command line, is to add --disable-gpu.

It looks like it might have been "fixed" upstream in Chromium too: https://chromium.googlesource.com/chromium/src/+/9154331c218d5917c7f27b9dedcc4d1cf884c7b8%5E%21/
