### ISSUE TITLE
RIDE window can open off screen, leading user to assume it crashed

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/ride#139]
# RIDE Issue Report

### Describe the issue you are having
After using RIDE with a large monitor or multiple monitors, when returning to a smaller screen the RIDE window can open "off screen". It is easy to conclude that RIDE failed to start / crashed / hung. RIDE should check the desktop size on startup and make sure it positions itself within the available space.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
N/A

### How do you reproduce the issue?
Not exactly sure but it typically happens when I use my laptop on the road without my external monitor. Alt+space, M, cursor arrows can be used to bring the screen back into view.

### Paste the contents of Help → About (Shift+F1)
N/A

**Comment by jayfoad** [comment]
Some discussion about the same problem in Atom: https://github.com/atom/atom/issues/6939
