### ISSUE TITLE
Mac: Editor misplaced window and hang

### ISSUE THREAD

**Issue by JohnScholes** [Dyalog/ride#140]
# RIDE Issue Report

### Describe the issue you are having
On the Mac: edit a variable, then double-click or Shift+Enter a name in the edit window to open a window on a second variable. Esc to close. The remaining edit window now seems badly positioned, and typing a second Esc hangs the system.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
No

### How do you reproduce the issue?
M←↑¯40↑⊂'EditMe'
EditMe←40 80⍴⎕A
)ed M
Scroll to bottom of edit window
Double click EditMe
An edit window opens on the char matrix EditMe: so far, so good.
Type Esc - the M window becomes visible but is misplaced: top-left in the editor frame
Type Esc - the system hangs
System doesn't respond to: clicking the session's red dot; Cmd+w; or Cmd+q.
Use →Force Quit... to quit.

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.0.2751
  Platform: MacIntel
  Date: 2017-03-20 10:43:50 +0000
  Git commit: 3c98300d1b48086cdccf42f28b1fde08b1f5b837
  Preferences:{
    "lineNums":"0",
    "zoom":"6"
  }

Interpreter:
  Version: 16.0.29556
  Platform: Mac-64
  Edition: Unicode/64
  Date: Mar 23 2017 at 02:27:23

**Comment by jayfoad** [comment]
I can reproduce this on the Mac but not on Linux.

**Comment by flouc001** [comment]
CodeMirror is getting stuck in an infinite loop triggered initially by the updSize function of ed.js. Looking into this.
