### ISSUE TITLE
Quit (Shift+Esc) from editor back to tracer needs a repaint

### ISSUE THREAD

**Issue by JohnScholes** [Dyalog/ride#141]
# RIDE Issue Report

### Describe the issue you are having
Quitting (discarding changes) from the editor back to the tracer does not restore the pre-edit view of the function.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
No

### How do you reproduce the issue?
)copy dfns display
display ⍳2 2 [TC]   ⍝trace
[ER] [ED]    ⍝ next line and turn trace window into edit window
zzzzz     ⍝ add junk
[QT]      ⍝ Shift+Esc: the zzzz should disappear
[ER]      ⍝ the zzzz is clearly not really there

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.0.2751
  Platform: MacIntel
  Date: 2017-03-20 10:43:50 +0000
  Git commit: 3c98300d1b48086cdccf42f28b1fde08b1f5b837
  Preferences:{
    "lineNums":"0",
    "zoom":"5",
    "kbdLocale":"en_US_Mac",
    "pfkeys":"[\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\")reset<ER>)save<ER>\",\"\",\"\"]"
  }

Interpreter:
  Version: 16.0.29556
  Platform: Mac-64
  Edition: Unicode/64
  Date: Mar 23 2017 at 02:27:23

**Comment by jayfoad** [comment]
@johndaintree When I hit QT I see this in the protocol log:

78053 send ["CloseWindow",{"win":1}]
78055 recv ["WindowTypeChanged",{"win":1,"tracer":1}]
78068 recv ["SetHighlightLine",{"win":1,"line":0}]

Should the interpreter be sending an UpdateWindow to restore the original content? Or does RIDE have to remember it?

**Comment by johndaintree** [comment]
Yeah, I think an UpdateWindow is appropriate.

**Comment by jayfoad** [comment]
OK. I've raised this internally as an interpreter issue (Mantis 14469).

**Comment by flouc001** [comment]
@jayfoad should this issue be closed on Github now it's been raised in Mantis?

**Comment by jayfoad** [comment]
@flouc001 sure.
