### ISSUE TITLE
Diamond keystroke not available

### ISSUE THREAD

**Issue by bpbecker** [Dyalog/ride#145]
# RIDE Issue Report

### Describe the issue you are having
Pressing `` {sp} (esc key twice followed by space ) does not produce diamond, but left arrow (assignment) instead 

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Started an interpreter

### How do you reproduce the issue?
Start Ride
Start interpreter (I tried both v15 on the Pi and v16 on Windows)
Press `` space

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.0.2753
  Platform: Win32
  Date: 2017-03-27 16:01:25 +0100
  Git commit: 16ca4d6e93f170e982719c70a1a17e2dfd2648f6
  Preferences:{
    "favs":"[{\"ssh_auth_type\":\"pass\",\"type\":\"start\",\"exe\":\"C:\\\\Program Files\\\\Dyalog\\\\Dyalog APL-64 15.0 Unicode\\\\dyalog.exe\",\"ssh_tnl_auth_type\":\"pass\"},{\"ssh_auth_type\":\"pass\",\"name\":\"DFS AIX\",\"host\":\"dfsaix.dyalog.bramley\",\"ssh_tnl_auth_type\":\"pass\"},{\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"port\":\"9000\"}]",
    "kbdLocale":"en_US",
    "selectedExe":"/opt/mdyalog/15.0/32/unicode/mapl\n",
    "title":"{PROFILE}-{WSID}",
    "zoom":"10"
  }

Interpreter:
  Version: 16.0.29359
  Platform: Windows-64
  Edition: Unicode/64
  Date: Mar  2 2017 at 09:46:16

**Comment by jayfoad** [comment]
Triple backquote should give you a diamond. I see the language bar tooltip for ⋄ says `` so that needs fixing. Was there anything else that misled you that we ought to fix?
