### ISSUE TITLE
Increasing font-size should also affect language-bar

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/ride#146]
While demoing Dyalog @ Vassar Hackathon, user commented that "the glyphs are still not readable"...referring to the language-bar. (Old person, having problems with eyesight...)

**Comment by jayfoad** [comment]
See also #34.

**Comment by jayfoad** [comment]
I've asked around and there seems to be a lot of support for this, so I think we should just do it. If we get complaints then _maybe_ we'll need an option to disable it... but hopefully not.

**Comment by flouc001** [comment]
I've added support for this in the iss146 branch, please test and I will merge it in.

**Comment by jayfoad** [comment]
Looks good to me!
