### ISSUE TITLE
Mac / Ride weak interrupt doesn't work

### ISSUE THREAD

**Issue by JohnScholes** [Dyalog/ride#149]
# RIDE Issue Report

### Describe the issue you are having
Action -> Weak interrupt has no effect.
Strong interrupt is OK.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
No

### How do you reproduce the issue?
      ⍎⎕fx'loop' '→1'
... try weak interrupt.

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.0.2776
  Platform: MacIntel
  Date: 2017-04-07 16:23:55 +0100
  Git commit: a04d9d8d7a67b4bb2945e932d66d7401a8e5c696
  Preferences:{
    "kbdLocale":"en_US_Mac",
    "lineNums":"0",
    "pfkeys":"[\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\")reset<ER>)save<ER>\",\"\",\"\"]",
    "zoom":"5"
  }

Interpreter:
  Version: 16.0.29722
  Platform: Mac-64
  Edition: Unicode/64
  Date: Apr 10 2017 at 02:28:09

**Comment by jayfoad** [comment]
Can you please try with interpreter version 16.0.29732 or later?

**Comment by JohnScholes** [comment]
It's fixed now.Thanks.
