### ISSUE TITLE
Fast ctrl+tab switching between tracer, session, and scrolled edit windows results in a hang

### ISSUE THREAD

**Issue by dyavc** [Dyalog/ride#150]
# RIDE Issue Report

### Describe the issue you are having
Fast ctrl+tab switching between tracer, session, and scrolled edit windows results in a hang

### Did you connect to an already running interpreter or start the interpreter from RIDE?
started ride first with listen.  Then started dyalog on Windows.

### How do you reproduce the issue?
M←↑¯40↑⊂'EditMe'
EditMe←40 80⍴⎕A
)ed M
Scroll to bottom of edit window
Double click EditMe
Scroll to bottom of EditMe

)ed foo
make foo a function with about 4 lines which are just numbers 1 to 4.
escape to fix foo

trace into foo by typing foo into session part and ctrl+enter
now, ctrl+tab to switch between tracer, session, edit windows 

Will get a hang quite soon.  And one of the edit windows will appear to be a small square.

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.0.2776
  Platform: Win32
  Date: 2017-04-07 16:23:55 +0100
  Git commit: a04d9d8d7a67b4bb2945e932d66d7401a8e5c696
  Preferences:{
    "favs":"[{\"type\":\"listen\",\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"listen4502\"},{\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"connect4512\",\"ride_port\":\"4512\",\"type\":\"connect\",\"port\":\"4512\",\"host\":\"127.0.0.1\"}]",
    "kbdLocale":"en_US"
  }

Interpreter:
  Version: 15.0.29644
  Platform: Windows-64
  Edition: Unicode/64
  Date: Apr  3 2017 at 17:58:05

**Comment by jayfoad** [comment]
Probably the same as #140.

**Comment by flouc001** [comment]
Fixed in 93dafe2
