### ISSUE TITLE
Controversial colour scheme

### ISSUE THREAD

**Issue by DyalogRichard** [Dyalog/ride#152]
# RIDE Issue Report

### Describe the issue you are having
The orange text (Preferences screen etc) / orange background colours (Threads and SI stack panels) - which cannot be changed even by selecting a different colour scheme - is very unusual and bound to be disliked by at least some users. We should adopt something less controversial.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Attached to existing interpreter.

### How do you reproduce the issue?
Start RIDE.

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.0.2784
  Platform: Linux x86_64
  Date: 2017-04-21 13:05:05 +0100
  Git commit: 93dafe26bae19f90d12bd0e7eadd06e33046aa4f
  Preferences:{
    "dbg":"1",
    "wse":"1",
    "kbdLocale":"en_GB"
  }

Interpreter:
  Version: 16.0.29800
  Platform: Linux-64
  Edition: Unicode/64
  Date: Apr 24 2017 at 10:28:43
![image1](https://cloud.githubusercontent.com/assets/10868907/25332171/70120192-28dd-11e7-94b0-1340c274b6ee.png)

**Comment by abrudz** [comment]
![image](https://cloud.githubusercontent.com/assets/10961427/25333807/c317c984-28e3-11e7-9d2f-cec28291f291.png)

**Comment by flouc001** [comment]
Mike Mingard is currently working on a new colour palette for RIDE and we're looking to completely overhaul the styling very soon.

**Comment by jayfoad** [comment]
Styling work has been going on for a long time. I don't think it's helpful to have this bug open.

**Comment by DyalogRichard** [comment]
Please reconsider closing this. The problem is worse now than it was!

**Comment by fourier** [comment]
I agree the choice of colours is not really pleasant.
