### ISSUE TITLE
Tool tip values for ⍺ and ⍵ are wrong

### ISSUE THREAD

**Issue by DyalogRichard** [Dyalog/ride#155]
### Describe the issue you are having
If you hover over a name you get a tooltip showing its value. If you hover over primitive you get a tooltip showing an explanation of what it is. If you hover over ⍺ or ⍵ you get an explanation of what it is, not its value as you would expect. 

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Connect to already running

### How do you reproduce the issue?
See description

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.0.2787
  Platform: Linux x86_64
  Date: 2017-04-24 16:41:40 +0100
  Git commit: b4cdc0af241089f1181ca0e9c68ae0cb2f923291
  Preferences:{
    "dbg":"1",
    "kbdLocale":"en_GB",
    "wse":"1"
  }

Interpreter:
  Version: 16.0.29813
  Platform: Linux-64
  Edition: Unicode/64
  Date: Apr 25 2017 at 09:26:51

**Comment by ngn** [comment]
As a temp measure you can disable Preferences > Code > Show tips for glyphs.
Assuming the interpreter knows how to [`GetValueTip`](https://github.com/Dyalog/ride/blob/master/docs/protocol.md#GetValueTip) for this, a good place to fix it could be as a special case in the big boolean expression at [vt.js:20](https://github.com/Dyalog/ride/blob/6ef2bfba55b890bb54590eb2ef201f9ad0ba6dcb/src/vt.js#L20).

**Comment by flouc001** [comment]
I've altered the code in commit 504cab2 to send a [`GetValueTip`](https://github.com/Dyalog/ride/blob/master/docs/protocol.md#GetValueTip) request for this however I need the interpreter to comply. Is it possible for the interpreter to send values back for alpha and omega @johndaintree?

**Comment by DyalogRichard** [comment]
http://mantis.dyalog.com/view.php?id=14540

**Comment by jayfoad** [comment]
Fixed in interpreter 16.0.30740.
