### ISSUE TITLE
Incorrect editor indentation

### ISSUE THREAD

**Issue by JohnScholes** [Dyalog/ride#158]
### Describe the issue you are having
If preferences->code-> "Indent contents when an editor is opened" is checked, some lines are incorrectly indented.
Plus, the editor's usually excellent predictive indentation gets it wrong if the last line ended }{.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Start an interpreter

### How do you reproduce the issue?
Ensure  preferences->code-> "Indent contents when an editor is opened" is checked then open an edit window on this function:
<pre>
foo←{
    {
        1+⍵}{
        1+⍵}{
        1+⍵}⍵
}
</pre>
It is wrongly indented like this:
<pre>
foo←{
    {
        1+⍵}{
            1+⍵}{
                1+⍵}⍵
}
</pre>
For a larger example:
<pre>
      )xload min
... saved ...
      )ed combo
</pre>
### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.0.2801
  Platform: MacIntel
  Date: 2017-05-05 15:12:33 +0100
  Git commit: 1f2c48118cb3919c6b2fc48a93df4b84fbfbbf95
  Preferences:{
    "autocompletion":"0",
    "kbdLocale":"en_US_Mac",
    "lineNums":"0",
    "pfkeys":"[\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\")reset<ER>)save<ER>\",\"\",\"\"]",
    "squiggleTips":"0",
    "valueTips":"0",
    "zoom":"5"
  }

Interpreter:
  Version: 16.0.29853
  Platform: Mac-64
  Edition: Unicode/64
  Date: May  6 2017 at 01:17:57

**Comment by e9gille** [comment]
When the editor is opened it receives the formatted body of the function from the interpreter. I'm not sure what the value is of this feature in the first place. Is there a use case for keeping it in?

**Comment by JohnScholes** [comment]
"Indent contents when an editor is opened" is an alternative to the ODE editor's  Edit->Reformat command. So the use-case question boils down to: do people require a mechanism to reformat their code with leading indentation.

**Comment by e9gille** [comment]
Is this specifically to deal with scripts?
Normal functions get reformatted on fix anyway, or is that a setting in the interpreter?

**Comment by JohnScholes** [comment]
I don't know about scripts. Auto-reformatting of (normal) functions is a setting:
ODE:  "Options->Configure->Trace/Edit->AutoFormat Functions"
Ride:   "Preferences->Code->Indent contents when an editor is opened"
The problem is not that it happens but that Ride gets the indentation level wrong, as per the above examples and code such as http://dfns.dyalog.com/c_morse.htm

**Comment by e9gille** [comment]
Yes, I agree that RIDE gets it wrong and I can see why (now I just need to think of the solution).
So enabling autoformat in ODE causes functions to be formatted when you fix them from RIDE, irrespective of the settings in RIDE. I had autoformat enabled in ODE which is why I questioned the benefit of the RIDE setting.
