### ISSUE TITLE
Bug: scroll to the beginning of the history when the Workspace Explorer is opened

### ISSUE THREAD

**Issue by fourier** [Dyalog/ride#16]
```IDE:
  Version: 4.0.2559
  Platform: MacIntel
  Date: 2016-12-19 09:16:32 +0000
  Git commit: b07720323cca4239e3e761c5daecbc1aa9045bbf
```
Bug: When opening Workspace Explorer the IDE window is scrolled to the beginning of the history.
Expected result: the window should not scroll and stay on the same position.

**Comment by jayfoad** [comment]
I can reproduce this on Linux too. The session scrolls to the beginning, but oddly the session scrollbar thumb does not move to the top.

**Comment by fourier** [comment]
Still can reproduce this issue, or spin-off of it:
When both Workspace Explorer and Session window are visible, if I maximize Session window by clicking on its "maximize" button, the scroll moves to the top of window, see animated gif attached:

![ride4_scroll_issue](https://cloud.githubusercontent.com/assets/900250/22629100/42aa539c-ebe0-11e6-9bc8-5ba05fcbbabd.gif)

**Comment by johndaintree** [comment]
I'm seeing this (on Windows, don't know about others), when a trace windows is opened (in this instance because of a weak interrupt, and "show trace on error" is set). The session scrolls all the way to the top.
