### ISSUE TITLE
Dismissing "Cannot fix object without a name" dialog with an escape hangs Ride

### ISSUE THREAD

**Issue by JohnScholes** [Dyalog/ride#160]
### Describe the issue you are having
as above

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Start an interpreter

### How do you reproduce the issue?
<pre>
      )ed foo
Type ! following the foo in the edit window.
Type Esc : "Cannot fix object without a name"
Type Esc :  dialog disappears
Now all bets are off
...
Force Quit of Dyalog app.
</pre>

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.0.2801
  Platform: MacIntel
  Date: 2017-05-05 15:12:33 +0100
  Git commit: 1f2c48118cb3919c6b2fc48a93df4b84fbfbbf95
  Preferences:{
    "autocompletion":"0",
    "indentOnOpen":"0",
    "kbdLocale":"en_US_Mac",
    "lineNums":"0",
    "pfkeys":"[\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\")reset<ER>)save<ER>\",\"\",\"\"]",
    "squiggleTips":"0",
    "valueTips":"0",
    "zoom":"5"
  }

Interpreter:
  Version: 16.0.29853
  Platform: Mac-64
  Edition: Unicode/64
  Date: May  6 2017 at 01:17:57

**Comment by flouc001** [comment]
I have changed the mechanic of the dialog boxes created by the interpreter to not allow "Esc" or "X" closing. You must acknowledge the dialog using one of the buttons. This can still be done with the keyboard and it provides the interpreter with information it needs to continue.

**Comment by lstefano71** [comment]
I beg you... don't do this. Conventions, not matter how annoying for the developer, as long as they are recognised as universal conventions, must be respected. "Esc" to close a modal dialog box is even today (I may say: especially today, after 30+ years of history of UX) a must.

**Comment by e9gille** [comment]
Apart from Stefano's comment on the behavior of dialog boxes I can see that on the nix version RIDE receives an OptionsDialog event with the message above. This event is missing in the win version.
