### ISSUE TITLE
Start an Interpreter fails if you do not select other than the first entry in the dropdown list

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/ride#162]
Set Type to "Start an Interpreter"
Click on Go
Msgbox   "Interpreter" is required appears.

If you select any other entry in the dropdown, and then select the initial entry it works.

IDE:
  Version: 4.0.2803
  Platform: Win32
  Date: 2017-05-08 18:29:48 +0100
  Git commit: 1e70861c2d83f74e3b32a07face820f06ac3b9c3
  Preferences:{
    "favs":"[{\"type\":\"connect\",\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"debian7dev\",\"host\":\"debian7dev.dyalog.bramley\",\"port\":\"4502\"},{\"type\":\"connect\",\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"dfsaix\",\"host\":\"10.0.61.100\",\"port\":\"9003\"},{\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"mac0\",\"host\":\"mac0\"},{\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"local\",\"host\":\"127.0.0.1\",\"port\":\"9999\",\"type\":\"start\",\"exe\":\"C:\\\\Program Files\\\\Dyalog\\\\Dyalog APL-64 16.0 Unicode\\\\dyalog.exe\"},{\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"p7-61qa\",\"host\":\"p7-61qa\",\"port\":\"4503\"}]",
    "kbdLocale":"en_GB",
    "lineNums":"0",
    "selectedExe":"/opt/mdyalog/16.0/64/unicode/mapl",
    "title":"{WSID} {PID}",
    "wse":"1",
    "zoom":"-2"
  }

Interpreter:
  Version: unknown
  Platform: unknown
  Edition: unknown
  Date: unknown

**Comment by dyaandys** [comment]
Sorry .. still a problem in 
 Version: 4.0.2836
  Platform: Win32
  Date: 2017-06-27 14:11:02 +0100
  Git commit: 2b8dba4598c1ba136f80a3a09dbcd94ace4c7032

**Comment by flouc001** [comment]
@dyaandys please could you checkout the issue branch and test. Thank you.
