### ISSUE TITLE
macOS: Clicking on Connect has the same effect as clicking on New Session

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/ride#165]
Start Dyalog 16.0
Click on Connect .. get another session, rather than the connect dialog screen.
Is fine on Windows

IDE:
  Version: 4.0.2803
  Platform: MacIntel
  Date: 2017-05-08 18:29:48 +0100
  Git commit: 1e70861c2d83f74e3b32a07face820f06ac3b9c3
  Preferences:{
    "kbdLocale":"en_GB_Mac",
    "zoom":"4",
    "wse":"1"
  }

Interpreter:
  Version: 16.0.29865
  Platform: Mac-64
  Edition: Unicode/64
  Date: May 10 2017 at 02:35:38

**Comment by e9gille** [comment]
I can't replicate this. Is it still an issue?

**Comment by FionaDyalog** [comment]
Yes it is

IDE:
  Version: 4.1.2839
  Platform: MacIntel
  Date: 2017-06-27 13:44:54 +0100
  Git commit: a118d9fe9d28f87f3b80b778789253b8ad02bcc4
  Preferences:{
    "kbdLocale":"en_GB_Mac"
  }

Interpreter:
  Version: 16.0.30270
  Platform: Mac-64
  Edition: Unicode/64
  Date: Jun 28 2017 at 11:14:26
