### ISSUE TITLE
The session is ready but the Ride does not think so.

### ISSUE THREAD

**Issue by lstefano71** [Dyalog/ride#167]
### Describe the issue you are having
The Ride session does not realise that the cursor is blinking in the session.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
I connect to an already running interpreter (15.0, classic, 32 bits) in which I have executed the following lines of code:

              +3502⌶'SERVE::4551' ⍝ Update init string
         0

               +3502⌶1             ⍝ Start RIDE
          0

### How do you reproduce the issue?
I think the trick is to have a really huge session log. Mine comes from a "Session Log Size: 9999" and all of it is full, with some very long lines in its complex history. I've attached a zipped copy [session_log.zip](https://github.com/Dyalog/ride/files/1042072/session_log.zip). And I think it's also necessary to have a relatively slow connection between the ODE and Ride: a connection to localhost with the same session file opened causes different problems which I might describe in a separate issue.

Immediately after the connection, the session appears empty in the Ride and the cursor remains blinking at the top left corner. I cannot type anything.
If I type anything in the ODE session, then Ride wakes up. Or if I open the Workspace explorer in Ride, Ride also wakes up.  Which reminds me: to reproduce the issue, make sure the Workspace Explorer flag and the Debug Pane in Ride are both not active before connecting.

I must say, I miss the "debug mode" from Ride 2.0 where I could watch the messages going back and forth the Ride and the interpreter.

### Paste the contents of Help → About (Shift+F1)

IDE:
  Version: unknown
  Platform: Win32
  Date: unknown
  Git commit: unknown
  Preferences:{
    "kbdLocale":"it_IT"
  }

Interpreter:
  Version: 15.0.29488
  Platform: Windows
  Edition: Classic/32
  Date: Mar 14 2017 at 18:52:50

The Ride is compiled from the current master branch of the Github repo.

**Comment by jayfoad** [comment]
> I must say, I miss the "debug mode" from Ride 2.0 where I could watch the messages going back and forth the Ride and the interpreter.

Ctrl+F12 opens a protocol log window.

**Comment by lstefano71** [comment]
@jayfoad Thank you! I did not know that!
The log for a session which hangs in the way described above is as follows:
```
191077 send SupportedProtocols=2
191077 send UsingProtocol=2
191077 send ["Identify",{"identity":1}]
191077 send ["Connect",{"remoteId":2}]
191077 send ["GetWindowLayout",{}]
191182 recv SupportedProtocols=2
191182 recv UsingProtocol=2
191182 recv ["Identify",{"Port":0,"IPAddress":"","Vendor":"Dyalog Limited","Language":"APL","version":"15.0.29488","Machine":"CTXP102","arch":"Classic/32","Project":"<A> [Sviluppo Generali Svi CS].dws","Process":"dyalog.exe","User":"stf","pid":5676,"token":"{B371C96E-BFD4-4746-8540-E0E0265F44E9}","date":"Created: Mar 14 2017 at 18:52:50","platform":"Windows"}]
191183 send ["SetPW",{"pw":123}]
191183 recv ["UpdateDisplayName",{"displayName":"<A> [Sviluppo Generali Svi CS].dws"}]
192863 resized recv buffer to 2097152
192952 resized recv buffer to 4194304
```

**Comment by lstefano71** [comment]
With the sessions I tried, v4.1 seems to work just fine. I'll close the issue.
