### ISSUE TITLE
If the language bar wraps, the session is partially truncated

### ISSUE THREAD

**Issue by lstefano71** [Dyalog/ride#168]
### Describe the issue you are having
A picture is worth a thousand words.
![image](https://cloud.githubusercontent.com/assets/2143482/26595160/bc450d08-456a-11e7-8d3d-e85123fa39be.png)

### How do you reproduce the issue?
Look at how the "Serial No" is partly covered at the top of the session pane.

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: unknown
  Platform: Win32
  Date: unknown
  Git commit: unknown
  Preferences:{
    "kbdLocale":"it_IT"
  }

Ride compiled from a forked repo from the official github repo, master branch.

Interpreter:
  Version: 16.0.29865
  Platform: Windows
  Edition: Classic/32
  Date: May  9 2017 at 18:34:50

**Comment by e9gille** [comment]
Can you confirm if you experience this as you start the session or on resizing the window. I can only replicate this by resizing or toggling the language bar, but not when starting a fresh session.
The session is attached to the bottom, so any changes in size trigger it to scroll so the last line sticks to the bottom. We could improve this so it keeps the top line to the top as long as there is room for the remaining text.

**Comment by lstefano71** [comment]
I can confirm that the patch fixes the issue for me.
