### ISSUE TITLE
RIDE 4 tracer and editor do not have X button which does "Quit this function" (tracer) or "Save changes and return" (editor) as Windows ODE has

### ISSUE THREAD

**Issue by dyavc** [Dyalog/ride#170]
### Describe the issue you are having
RIDE 4 tracer and editor do not have X button which does "Quit this function" (tracer) or "Save changes and return" (editor) as Windows ODE has

### Did you connect to an already running interpreter or start the interpreter from RIDE?
N/A

### How do you reproduce the issue?
Just edit or trace something

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.0.2803
  Platform: Win32
  Date: 2017-05-08 18:29:48 +0100
  Git commit: 1e70861c2d83f74e3b32a07face820f06ac3b9c3
  Preferences:{
    "favs":"[{\"type\":\"listen\",\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"listen4502\"},{\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"connect4512\",\"ride_port\":\"4512\",\"type\":\"connect\",\"port\":\"4512\",\"host\":\"127.0.0.1\"}]",
    "kbdLocale":"en_US"
  }

Interpreter:
  Version: 15.0.29644
  Platform: Windows
  Edition: Classic/32
  Date: Apr  3 2017 at 17:55:00

**Comment by jayfoad** [comment]
I guess you mean that there isn't an X button on the toolbar (like the ODE has). But there is an X on the tab, which closes the editor/tracer with the behaviour you want, so I don't see the need for a toolbar button too. We are not striving to make the RIDE UI identical to the ODE just for the sake of it.
