### ISSUE TITLE
Debugger is not showing all the trace tabs when suspension occurs in some client/server combinations

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/ride#172]
]udebug on
]settings - 
macOS: see just one tab with SaltinSpice.  No sign of UCMD, nor of intermediate functions
Windows client to windows APL: same

IDE:
  Version: 4.0.2834
  Platform: Win32
  Date: 2017-06-20 13:42:27 +0100
  Git commit: 2d04452b43978e397de5f1131b0252560523ae3c
  Preferences:{
    "favs":"[{\"type\":\"connect\",\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"debian7dev\",\"host\":\"debian7dev.dyalog.bramley\",\"port\":\"4502\"},{\"type\":\"connect\",\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"dfsaix\",\"host\":\"10.0.61.100\",\"port\":\"9003\"},{\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"mac0\",\"host\":\"mac0\"},{\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"local\",\"host\":\"127.0.0.1\",\"port\":\"9999\",\"type\":\"start\",\"exe\":\"C:\\\\Program Files\\\\Dyalog\\\\Dyalog APL-64 16.0 Unicode\\\\dyalog.exe\"},{\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"p7-61qa\",\"host\":\"p7-61qa\",\"port\":\"4503\"}]",
    "kbdLocale":"en_GB",
    "lineNums":"0",
    "pfkeys":"[\"\",\"\",\"{⍺ ⍵} \",\"FOO <ED>\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\"]",
    "selectedExe":"/opt/mdyalog/17.0/64/unicode/mapl",
    "title":"{WSID} {PID}",
    "wse":"1",
    "zoom":"-2"
  }

Interpreter:
  Version: 16.0.30022
  Platform: Windows
  Edition: Unicode/32
  Date: Jun  2 2017 at 15:00:45

**Comment by jayfoad** [comment]
This is probably due to the setting of SINGLETRACE on the interpreter side.

**Comment by abrudz** [comment]
Simple repro:
```apl
⎕FX' foo' ' goo'
⎕FX' goo' ' ∘∘∘'
foo
```
![image](https://user-images.githubusercontent.com/10961427/182817364-2195af53-fe63-4724-88dd-00367347ddd0.png)

**Comment by abrudz** [comment]
OK, but how does one switch the content of the trace window to higher levels of the stack?

**Comment by e9gille** [comment]
In any case, I committed 828d915a2309bd09c4cd4e533ce85c603a976c1d to allow overriding the SINGLETRACE option from RIDE so you can start an interpreter with this turned off.
Switching stack level should be logged as a separate issue.
