### ISSUE TITLE
Currently suspended line is not always in debug window 

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/ride#173]
Windows RIDE, linux client

]udebug on
]settings -

Have four tabs (correct, unlike #172), and are in correct tab, but I'm at the top of the namespace, not on Run[1]

IDE:
  Version: 4.0.2834
  Platform: Win32
  Date: 2017-06-20 13:42:27 +0100
  Git commit: 2d04452b43978e397de5f1131b0252560523ae3c
  Preferences:{
    "favs":"[{\"type\":\"connect\",\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"debian7dev\",\"host\":\"debian7dev.dyalog.bramley\",\"port\":\"4502\"},{\"type\":\"connect\",\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"dfsaix\",\"host\":\"10.0.61.100\",\"port\":\"9003\"},{\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"mac0\",\"host\":\"mac0\"},{\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"local\",\"host\":\"127.0.0.1\",\"port\":\"9999\",\"type\":\"start\",\"exe\":\"C:\\\\Program Files\\\\Dyalog\\\\Dyalog APL-64 16.0 Unicode\\\\dyalog.exe\"},{\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"p7-61qa\",\"host\":\"p7-61qa\",\"port\":\"4503\"}]",
    "kbdLocale":"en_GB",
    "lineNums":"0",
    "pfkeys":"[\"\",\"\",\"{⍺ ⍵} \",\"FOO <ED>\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\"]",
    "selectedExe":"/opt/mdyalog/17.0/64/unicode/mapl",
    "title":"{WSID} {PID}",
    "wse":"1",
    "zoom":"-2"
  }

Interpreter:
  Version: 16.0.30198
  Platform: Linux-64
  Edition: Classic/64
  Date: Jun 22 2017 at 01:54:51

**Comment by flouc001** [comment]
Commit 230bcde should resolve this, please test.

**Comment by jayfoad** [comment]
Works for me in master 4.1.3150.
