### ISSUE TITLE
Editor: repeated page-down leaves last line at _top_ of window

### ISSUE THREAD

**Issue by JohnScholes** [Dyalog/ride#176]
### Describe the issue you are having
... it would be better if the editor left the last line at the _bottom_ so that the whole of the last page is still visible.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Start an interpreter

### How do you reproduce the issue?
<pre>
      )copy dfns display
... saved ...
      )ed disp
      ⍝ now type  repeated page-down keys (Cmd+down_cursor)
</pre>

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.0.2834
  Platform: MacIntel
  Date: 2017-06-20 13:42:27 +0100
  Git commit: 2d04452b43978e397de5f1131b0252560523ae3c
  Preferences:{
    "autocompletion":"0",
    "fold":"0",
    "indentOnOpen":"0",
    "kbdLocale":"en_US_Mac",
    "pfkeys":"[\"\",\"\",\"\",\"\",\"\",\"wsdiff''<ER>\",\"\",\"\",\"\",\"\",\")reset<ER>)save<ER>\",\"\",\"\"]",
    "squiggleTips":"0",
    "valueTips":"0",
    "zoom":"5",
    "lineNums":"0"
  }

Interpreter:
  Version: 16.0.30211
  Platform: Mac-64
  Edition: Unicode/64
  Date: Jun 23 2017 at 02:31:38

**Comment by e9gille** [comment]
Just tested and it appears this is working as requested in 4.1
