### ISSUE TITLE
Way too slow

### ISSUE THREAD

**Issue by lstefano71** [Dyalog/ride#178]
### Describe the issue you are having
In certain not so uncommon circumstances, Ride is so slow to be of very little practical use.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
I opened a local Dyalog 16 Beta 2 (but the same happens with Dyalog 15.1 as well). I executed manually

              +3502⌶'SERVE::4551' 
    0
              +3502⌶1             
    0

### How do you reproduce the issue?
Get from somebody (Chris Hogan or Morten) a copy of the DFS client: it's a workspace called DFC.dws. I am using one created with a very recent drop on the SVN repo that I got from Chris Hogan. Load it in, then open a Ride on the interpreter, primed as described, and try and trace (with Ctrl-Enter):

        ⎕new DFS.DFC 'test'

The invocation is meaningless and it'll probably crash down the line, but it opens the tracer inside a script with 4000 lines. Simply opening the tracer takes several seconds. Now try and trace the code line by line (by pressing Enter). On my PC (an I7 with 24 Gigs of RAM connected to a local instance of Dyalog APL) it takes several seconds to go from one line to the next regardless of the complexity of the code being executed: even an empty line still takes several seconds to be traced in this way.

I believe the 4000 lines aren't the largest of the scripts part of DFS.

A bit of context: the reason why we got into Ride was to support an installation at a customer site where they want to go to real Windows Services, with no GUI. The installation is going to be based on Ride. 

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.0.1
  Platform: Win32
  Date: 2017-05-18 16:05:22 +0100
  Git commit: ba4314bf77178d5b35926d14116d9275a92d532d
  Preferences:{
    "dbg":"1",
    "kbdLocale":"it_IT"
  }

Interpreter:
  Version: 16.0.29865
  Platform: Windows
  Edition: Classic/32
  Date: May  9 2017 at 18:34:50

**Comment by e9gille** [comment]
@JohnScholes reported a similar issue when tracing large scripts. I believe it is improved with commit db1624848ec9157b8fc5a73ea3370ebc26afe6af but more work is required to make it snappy. Could you try the latest build Stefano and see if it is any better.

**Comment by lstefano71** [comment]
Thank you, Gil. I tried the new commit. I think I can see an improvement, but unfortunately it's still beyond the usable threshold for most of the DFS. 
Another symptom of the problem can be seen by resizing the window of the Ride while tracing the 4000-lines script. From the moment you let the mouse go to the moment the Ride gives control back, several seconds go by. As I said, a symptom of a problem, not something (resizing several times a minute) I recommend doing during a working day. ;-)

**Comment by jayfoad** [comment]
Seems to be completely fixed for me now the monaco branch has been merged into master. Awesome work @e9gille! (I tested with interpreter 17.0.3290 and there is no noticeable delay when single-stepping through the DFC class script.)
