### ISSUE TITLE
The language bar is not showing the quad diamond glyph when running on the Pi

### ISSUE THREAD

**Issue by FionaDyalog** [Dyalog/ride#180]
The language bar is not showing the quad diamond glyph when running on the Pi.

The RIDE is the default for the Pi, so double-clicking the Dyalog icon opens the RIDE GUI.

To reproduce the issue double-click the Dyalog icon to open the RIDE GUI then look at the language bar!

Version 16.0 (GA release version) of Dyalog and 4.0 of RIDE.

**Comment by jayfoad** [comment]
I can't reproduce this with 4.0.2838. What version are you running?

**Comment by FionaDyalog** [comment]
I'll have to check on the Pi tomorrow.

**Comment by jayfoad** [comment]
This was with 4.0.2787.

**Comment by jayfoad** [comment]
Should be "fixed" now, by uploading a newer version of RIDE to our Pi package repository.

**Comment by FionaDyalog** [comment]
Thanks J  Hadn’t even occurred to me that my.dyalog.com would have an out-of-date version!
