### ISSUE TITLE
Search/Replace options should include regex as an option

### ISSUE THREAD

**Issue by FionaDyalog** [Dyalog/ride#181]
Currently the four Search/Replace options all say "(Use /re/ syntax for regexp search)" next to the search field. This is confusing to newbies and takes up valuable space. Even more confusing when the window wraps the text! I believe it would be better to have a toggle-button for whether the specified term is a regex and lose this text.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Connected but this is irrelevant

### How do you reproduce the issue?
Open an Edit window and perform any of the search options

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.0.2836
  Platform: Win32
  Date: 2017-06-27 14:11:02 +0100
  Git commit: 2b8dba4598c1ba136f80a3a09dbcd94ace4c7032
  Preferences:{
    "zoom":"-1",
    "kbdLocale":"en_US",
    "wse":"1"
  }

Interpreter:
  Version: 16.0.30131
  Platform: Windows-64
  Edition: Unicode/64
  Date: Jun 15 2017 at 20:16:16

**Comment by jayfoad** [comment]
Fixed in master (RIDE 4.1): Monaco's search box has a ".*" button to enable regular expression search.
