### ISSUE TITLE
Linux version has a grey box instead of a Dyalog icon

### ISSUE THREAD

**Issue by FionaDyalog** [Dyalog/ride#183]
### Describe the issue you are having
RIDE on Linux does not have the correct icon in the top left of the application. A grey box is there instead

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Irrelevant but already running

### How do you reproduce the issue?
Just look at the screen :-)

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.0.2836
  Platform: Win32
  Date: 2017-06-27 14:11:02 +0100
  Git commit: 2b8dba4598c1ba136f80a3a09dbcd94ace4c7032
  Preferences:{
    "kbdLocale":"en_US",
    "lineNums":"0",
    "selectedExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 15.0 Unicode\\dyalog.exe",
    "wse":"1",
    "zoom":"-1"
  }

**Comment by jayfoad** [comment]
Probably broken by e5d13be9da1245bab81d6d9c79507453ee39bc39

**Comment by jayfoad** [comment]
Reported on Ubuntu MATE.

**Comment by jayfoad** [comment]
Should be fixed in 4.0.2842. @DyalogRichard can you confirm?

**Comment by DyalogRichard** [comment]
@jayfoad: yes, it works correctly now - thanks!
