### ISSUE TITLE
Language bar: dragging and dropping glyphs only works once!

### ISSUE THREAD

**Issue by FionaDyalog** [Dyalog/ride#184]
### Describe the issue you are having
Language bar: dragging and dropping glyphs only works once!

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Connected

### How do you reproduce the issue?
Open RIDE, drag an drop a glyph in the language bar - success. Try to do it again - failure.

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.0.2836
  Platform: Win32
  Date: 2017-06-27 14:11:02 +0100
  Git commit: 2b8dba4598c1ba136f80a3a09dbcd94ace4c7032
  Preferences:{
    "kbdLocale":"en_US",
    "lineNums":"0",
    "selectedExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 15.0 Unicode\\dyalog.exe",
    "wse":"1",
    "zoom":"-1",
    "lbarOrder":"← +-×÷*⍟⌹○!? |⌈⌊⊥⊤⊣⊢ =≠≤<>≥≢ ∨∧⍲⍱ ≡↑↓⊂⊃⊆⌷⍋⍒ ⍳⍸∊⍷∪∩~ /\\⌿⍀ ,⍪⍴⌽⊖⍉ ¨⍨⍣.∘⍤@ ⍞⎕⍠⌸⌺⌶⍎⍕ ⋄⍝→⍵⍺∇& ¯⍬"
  }

Interpreter:
  Version: 16.0.30307
  Platform: Windows-64
  Edition: Unicode/64
  Date: Jul  5 2017 at 20:34:46

**Comment by jayfoad** [comment]
Broken by 67c3a3cb5fbe464737a73d28de2b17b68fb95493
