### ISSUE TITLE
Connect dialog box permits identical configuration names

### ISSUE THREAD

**Issue by FionaDyalog** [Dyalog/ride#185]
### Describe the issue you are having
In the RIDE-Connect dialog box, multiple configuration names can be created that are exactly the same. Is this intentional (and if so, why?)?

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Not at that stage yet!

### How do you reproduce the issue?
Open a RIDE session, clone the unnamed entry in the list of configurations (or create lots of new entries with the same name)

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.0.2836
  Platform: Win32
  Date: 2017-06-27 14:11:02 +0100
  Git commit: 2b8dba4598c1ba136f80a3a09dbcd94ace4c7032
  Preferences:{
    "kbdLocale":"en_US",
    "lbarOrder":"← +-×÷*⍟⌹○!? |⌈⌊⊥⊤⊣⊢ =≠≤<>≥≢ ∨∧⍲⍱ ≡↑↓⊂⊃⊆⌷⍋⍒ ⍳⍸∊⍷∪∩~ /\\⌿⍀ ,⍪⍴⌽⊖⍉ ¨⍨⍣.∘⍤@ ⍞⎕⍠⌸⌺⌶⍎⍕ ⋄⍝→⍵⍺∇& ¯⍬",
    "lineNums":"0",
    "selectedExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 15.0 Unicode\\dyalog.exe",
    "wse":"1",
    "zoom":"-1"
  }

Interpreter:
  Version: 16.0.30307
  Platform: Windows-64
  Edition: Unicode/64
  Date: Jul  5 2017 at 20:34:46

**Comment by jayfoad** [comment]
Dunno. Maybe it's just easier to allow it than to work out exactly how to disallow it. Does it cause any problems apart from user confusion? It may not be RIDE's job to prevent the user from confusing himself...
