### ISSUE TITLE
Edit->Undo does not undo Edit->Paste in the session

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/ride#189]
Start APL
      1+1 <Enter>

Using mouse, select 1+1
Copy this text, using menu
Move mouse to input line
Paste using menu
Undo using menu

[This was originally logged against macOS in Mantis issue 11504.  However, the protocol log suggests  that there is no traffic between RIDE and APL, so suggests this is a RIDE issue]

IDE:
  Version: 4.0.2836
  Platform: Win32
  Date: 2017-06-27 14:11:02 +0100
  Git commit: 2b8dba4598c1ba136f80a3a09dbcd94ace4c7032
  Preferences:{
    "favs":"[{\"type\":\"connect\",\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"debian7dev\",\"host\":\"debian7dev.dyalog.bramley\",\"port\":\"4502\"},{\"type\":\"connect\",\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"dfsaix\",\"host\":\"10.0.61.100\",\"port\":\"9003\"},{\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"mac0\",\"host\":\"mac0\"},{\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"local\",\"host\":\"127.0.0.1\",\"port\":\"9999\",\"type\":\"start\",\"exe\":\"C:\\\\Program Files\\\\Dyalog\\\\Dyalog APL-64 16.0 Unicode\\\\dyalog.exe\"},{\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"p7-61qa\",\"host\":\"p7-61qa\",\"port\":\"4503\"}]",
    "kbdLocale":"en_GB",
    "lbarOrder":"← +-×÷*⍟⌹○!? |⌈⌊⊥⊤⊣⊢ =≠≤<>≥≡≢ ∨∧⍲⍱ ↑↓⊂⊃⊆⌷⍋⍒ ⍳⍸∊⍷∪∩~ /\\⌿⍀ ,⍪⍴⌽⊖⍉ ¨⍨⍣.∘⍤@ ⍞⎕⍠⌸⌺⌶⍎⍕ ⋄⍝→⍵⍺∇& ¯⍬",
    "lineNums":"0",
    "pfkeys":"[\"\",\"\",\"{⍺ ⍵} \",\"FOO <ED>\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\"]",
    "selectedExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 16.0 Unicode\\dyalog.exe",
    "title":"{WSID} {PID}",
    "wse":"1",
    "zoom":"-2"
  }

Interpreter:
  Version: 16.0.30263
  Platform: Windows-64
  Edition: Unicode/64
  Date: Jun 27 2017 at 20:27:00

**Comment by jayfoad** [comment]
Looks like Ctrl+Z works, but the Undo menu item does not work. And the reason the menu item doesn't work seems to be because we give it the "undo" role, which means that instead of executing our own UND command, it goes through the standard web browser mechanisms for undo commands (see [here](https://developer.mozilla.org/en/docs/Web/API/Document/execCommand#Commands)).

**Comment by jayfoad** [comment]
Fixed by ee067a812156442a1345a894ff83b34623e213d0.
