### ISSUE TITLE
Bug: "Cannot find module 'ssh2'" on attempt to start remote interpreter over ssh

### ISSUE THREAD

**Issue by fourier** [Dyalog/ride#19]
Version of RIDE from Git on OSX. On attempt to connect to remote interpreter got the message "Cannot find module 'ssh2'".

**Comment by flouc001** [comment]
@fourier I'm looking into this now, it's down to the build script not including the libraries necessary for node to make and utilise an SSH connection.

**Comment by fourier** [comment]
Hi,

Now the error:
```
Cannot find module 'ssh2-streams'
``` 
start to appear. I still can't neither start nor to connect to interpreter over ssh.

**Comment by flouc001** [comment]
@fourier can you report the folder names you have under the `node_modules` directory please.

**Comment by fourier** [comment]
Here it is
```
async             codemirror        electron          express           jquery            ws
cheerio           compression       electron-packager golden-layout     ssh2
```

**Comment by flouc001** [comment]
@fourier Try building again with the latest changes :)

**Comment by fourier** [comment]
Thanks, works now. I can't seem to connect, but this is another story, for different issue.
