### ISSUE TITLE
Closing editor tabs with middle mouse button renders RIDE unresponsive

### ISSUE THREAD

**Issue by paul7** [Dyalog/ride#190]
### Describe the issue you are having
After I close a RIDE editor tab by clicking the middle mouse button on its title, I'm not able to reopen the same function in the editor.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Start an interpreter

### How do you reproduce the issue?
Open RIDE; start an interpreter.
Define some function, say foo.
Open an editor on it.
Close the editor by middle clicking its tab.
Try to reopen the editor in any way, clicking at 'foo', evaluating ')ed foo', or pressing Shift+Enter, no difference.
=> nothing happens. 
If I do ')ed foo', RIDE stops to accept any input afterwards as well. I can enter expressions, but I never get an answer back.

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.0.2836
  Platform: Linux x86_64
  Date: 2017-06-27 14:11:02 +0100
  Git commit: 2b8dba4598c1ba136f80a3a09dbcd94ace4c7032
  Preferences:{
    "colourScheme":"Paul7",
    "colourSchemes":"[{\"name\":\"Paul7\",\"styles\":\"asgn=fg:00f com=fg:088 dfn=fg:00f diam=fg:00f err=fg:f00 fn=fg:008 idm=fg:00f kw=fg:800 lnum=fg:008,bg:f,bgo:1 mod=bg:e,bgo:1 mtch=bg:ff8,bgo:0.5 norm=bg:#e7e7e7,bgo:1 ns=fg:8 num=fg:8 op1=fg:00f op2=fg:00f par=fg:00f quad=fg:808 sel=bg:48e,bgo:0.5 semi=fg:00f sqbr=fg:00f srch=bg:f80,bgo:0.5 str=fg:088 tc=bg:d,bgo:1 trad=fg:8 var=fg:8 zld=fg:008 scmd=fg:00f ucmd=fg:00f vtt=bg:ff0\"}]",
    "kbdLocale":"en_US",
    "keys":"{\"SI\":[\"Ctrl-Alt-Pause\"]}",
    "otherExe":"/opt/mdyalog/16.0/64/unicode/mapl",
    "selectedExe":"/opt/mdyalog/15.0/64/unicode/mapl",
    "zoom":"2"
  }

Interpreter:
  Version: 16.0.30320
  Platform: Linux-64
  Edition: Unicode/64
  Date: Jul  7 2017 at 02:48:48

**Comment by jayfoad** [comment]
I didn't know you could middle-click on a tab to close it! It looks like this must be going through a different code path from clicking on the X, but so far I have not been able to work out what the difference is.

**Comment by flouc001** [comment]
Tested in Linux and Windows. Please confirm @paul7
