### ISSUE TITLE
Language bar should have grey background

### ISSUE THREAD

**Issue by jayfoad** [Dyalog/ride#191]
In RIDE 3 the language bar had a grey background:

![image](https://user-images.githubusercontent.com/108316/28208697-e71c8d8c-6886-11e7-9103-0b358ed5a498.png)

In RIDE 4 it's gone:

![image](https://user-images.githubusercontent.com/108316/28208716-02ab0628-6887-11e7-98b5-2bb8264442f6.png)

There's not much point in grouping characters if there's no background.

**Comment by DyalogRichard** [comment]
I always thought the language bar looked “half finished” (without having realised this was the reason) and would very much like the grey background to come back

I did some screen captures for Fiona to include in the documentation, and these will probably need to be redone, so the sooner it happens the better.

**Comment by FionaDyalog** [comment]
Before retaking screenshots it would be very useful if #183 could also be resolved...
