### ISSUE TITLE
Preferences dialog box > Code tab : "Handle formatting through the interpreter" is not working

### ISSUE THREAD

**Issue by FionaDyalog** [Dyalog/ride#193]
### Describe the issue you are having
Preferences dialog box > Code tab : "Handle formatting through the interpreter" is not working. Whether the option is selected or not, the formatting options defined in the Code tab are taken in preference to those of the interpreter.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Connect to already running

### How do you reproduce the issue?
Set interpreter formatting options. Set RIDE formatting options. Toggle "Handle formatting through the interpreter" on/off and see that there are no differences.

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.0.2836
  Platform: Win32
  Date: 2017-06-27 14:11:02 +0100
  Git commit: 2b8dba4598c1ba136f80a3a09dbcd94ace4c7032
  Preferences:{
    "kbdLocale":"en_US",
    "lbarOrder":"← +-×÷*⍟⌹○!? |⌈⌊⊥⊤⊣⊢ =≠≤<>≥≢ ∨∧⍲⍱ ≡↑↓⊂⊃⊆⌷⍋⍒ ⍳⍸∊⍷∪∩~ /\\⌿⍀ ,⍪⍴⌽⊖⍉ ¨⍨⍣.∘⍤@ ⍞⎕⍠⌸⌺⌶⍎⍕ ⋄⍝→⍵⍺∇& ¯⍬",
    "zoom":"-1",
    "lineNums":"0",
    "indent":"9",
    "indentMethods":"9",
    "indentOnOpen":"0",
    "matchBrackets":"0",
    "autoCloseBrackets":"0",
    "autoCloseBlocks":"0",
    "autocompletion":"0",
    "ilf":"0"
  }

Interpreter:
  Version: 16.0.30307
  Platform: Windows-64
  Edition: Unicode/64
  Date: Jul  5 2017 at 20:34:46

**Comment by jayfoad** [comment]
Currently RIDE only heeds the "Handle formatting through the interpreter" option when you hit NumpadDivide (RD, Reformat). The problem is that when you open an editor on a function it always uses RIDE's settings to reformat the code, ignoring the "Handle formatting through the interpreter" option.
