### ISSUE TITLE
Esc to exit full screen?

### ISSUE THREAD

**Issue by jayfoad** [Dyalog/ride#199]
On the Mac, would it be possible to hit Esc to get out of full screen mode? Or would that clash with the normal IDE uses of the Esc key?

**Comment by JohnScholes** [comment]
I think Esc would close my edit window. The Mac convention seems to be that Ctrl+Cmd+f  _toggles_ full-screen mode.

**Comment by DyalogRichard** [comment]
RIDE on Linux maximises and minimises the window using F11, which is conventional. Chrome follows that convention, however some web applications running within Chrome have a separate maximise function - YouTube, for example, allows you to maximise the video (which is different from maximising the browser) from a button and then use Escape to exit again. I think this leads to confusion about what key undoes maximisation.

When Chrome maximises using F11, Escape does not revert and I don't think we should make Esc revert in RIDE either. However what we could perhaps do, which Chrome does, is pop up a text box for a few seconds when the window maximises, which says you you revert.

**Comment by jayfoad** [comment]
Let's do nothing then.

> However what we could perhaps do, which Chrome does, is pop up a text box for a few seconds when the window maximises, which says how you revert.

If that was a standard thing for Mac apps to do then I'd be happy for us to follow suit, but I don't think we should implement it from scratch ourselves.

**Comment by JasonRivers** [comment]
Please can you be careful with "maximise" and "full screen" the 2 are different, I don't know any application that shows a popup when you maximise a window, RIDE (like chrome) uses F11 to FULLSCREEN - not maximise - This is when Chrome shows a message on how to revert. Maximise is done by the maximise button.
