### ISSUE TITLE
Edit window: Search functionality - highlighting in scroll bar is not as expected

### ISSUE THREAD

**Issue by FionaDyalog** [Dyalog/ride#200]
### Describe the issue you are having
In the Edit window, search for a term. All occurrences of the specified string are highlighted in the Edit window. If the content of the Edit window is sufficiently long for there to be a vertical scroll bar, then the locations of occurrences of the specified string within the entire content are identified by yellow marks overlaid on the scroll bar. However, these marks are not in the correct places. For example, if there is an occurence of the search term in the last line of the Edit window, I would expect it to be at the bottom of the scroll bar but it all seems to be shunted up a bit.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Connect to already running

### How do you reproduce the issue?
see "Describe the issue you are having"

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.0.2849
  Platform: Win32
  Date: 2017-07-20 11:23:40 +0100
  Git commit: ff806cb588cd1c8ae908949e27211d64cbf565e9
  Preferences:{
    "indent":"6",
    "indentComments":"1",
    "indentMethods":"2",
    "kbdLocale":"en_US",
    "lbarOrder":"← +-×÷*⍟⍴⌹○~!? |⌈⌊⍉⊥⊤⊣⊢ =≠≤<>≥≢ ∨∧⍲⍱ ≡↑↓⊂⊃⊆⌷⍋⍒ ⍳⍸∊⍷∪∩ /\\⌿⍀ ,⍪⌽⊖ ¨⍨⍣.∘⍤@ ⍞⎕⍠⌸⌺⌶⍎⍕ ⋄⍝→⍵⍺∇& ¯⍬",
    "lineNums":"0",
    "zoom":"-1",
    "dbg":"1"
  }

Interpreter:
  Version: 16.0.30307
  Platform: Windows-64
  Edition: Unicode/64
  Date: Jul  5 2017 at 20:34:46

**Comment by jayfoad** [comment]
It all looks good to me in 4.1 (please reopen if you still think there's a problem).
