### ISSUE TITLE
Edit window: Replace functionality does not highlight terms

### ISSUE THREAD

**Issue by FionaDyalog** [Dyalog/ride#202]
### Describe the issue you are having
In the Edit window, searching for a term highlights all occurrences of that term. Replacing a term does not, but I was expecting it to.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Connect to already running

### How do you reproduce the issue?
In the Edit window, enter a term to replace and press enter. No highlighting of that term occurs in the Edit window (cf using Search rather than Replace).

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.0.2849
  Platform: Win32
  Date: 2017-07-20 11:23:40 +0100
  Git commit: ff806cb588cd1c8ae908949e27211d64cbf565e9
  Preferences:{
    "indent":"6",
    "indentComments":"1",
    "indentMethods":"2",
    "kbdLocale":"en_US",
    "lbarOrder":"← +-×÷*⍟⍴⌹○~!? |⌈⌊⍉⊥⊤⊣⊢ =≠≤<>≥≢ ∨∧⍲⍱ ≡↑↓⊂⊃⊆⌷⍋⍒ ⍳⍸∊⍷∪∩ /\\⌿⍀ ,⍪⌽⊖ ¨⍨⍣.∘⍤@ ⍞⎕⍠⌸⌺⌶⍎⍕ ⋄⍝→⍵⍺∇& ¯⍬",
    "lineNums":"0",
    "zoom":"-1",
    "dbg":"1"
  }

Interpreter:
  Version: 16.0.30307
  Platform: Windows-64
  Edition: Unicode/64
  Date: Jul  5 2017 at 20:34:46

**Comment by jayfoad** [comment]
It does now in master (RIDE 4.1).
