### ISSUE TITLE
Trying to save (and fix) an unfixable function causes the Edit window to become undocked

### ISSUE THREAD

**Issue by FionaDyalog** [Dyalog/ride#205]
### Describe the issue you are having
Trying to close (and fix) an unfixable function in the Edit window generates an error message (correctly). Closing that error message makes the Edit window undock and float around with the mouse looking for a new location as if I had selected the tab and started dragging it (I hadn't).

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Connect to already running

### How do you reproduce the issue?
In Session window:
)ed foo
In the Edit window:
∇ foo;A;B
A←1
B←'Hello World'
INIT
CALC
REPORT
∇
Click on the x in the Edit window tab to close and save it.
Get an error message (correctly)
Close the error message
Edit window becomes undocked and floats round with the cursor until manually redocked

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.0.2849
  Platform: Win32
  Date: 2017-07-20 11:23:40 +0100
  Git commit: ff806cb588cd1c8ae908949e27211d64cbf565e9
  Preferences:{
    "indent":"6",
    "indentComments":"1",
    "indentMethods":"2",
    "kbdLocale":"en_US",
    "lbarOrder":"← +-×÷*⍟⍴⌹○~!? |⌈⌊⍉⊥⊤⊣⊢ =≠≤<>≥≢ ∨∧⍲⍱ ≡↑↓⊂⊃⊆⌷⍋⍒ ⍳⍸∊⍷∪∩ /\\⌿⍀ ,⍪⌽⊖ ¨⍨⍣.∘⍤@ ⍞⎕⍠⌸⌺⌶⍎⍕ ⋄⍝→⍵⍺∇& ¯⍬",
    "lineNums":"0",
    "zoom":"-1"
  }

Interpreter:
  Version: 16.0.30307
  Platform: Windows-64
  Edition: Unicode/64
  Date: Jul  5 2017 at 20:34:46

**Comment by flouc001** [comment]
@FionaDyalog a fix for this issue can be found in the iss205 branch. As soon as testing can be performed the changes will be merged and the issue can be closed.

**Comment by flouc001** [comment]
Tested on Linux and Windows platforms. Merging into ride4 and master.
