### ISSUE TITLE
Stencil is missing from the backtick prefix keyboard input mechanism

### ISSUE THREAD

**Issue by DyalogRichard** [Dyalog/ride#206]
### Describe the issue you are having
`` keyboard input does not include tessellate

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Connect to running

### How do you reproduce the issue?
Type `` and try to find tessellate

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.0.2850
  Platform: Linux x86_64
  Date: 2017-07-24 10:39:12 +0100
  Git commit: c6fe399aeeae1e489a486dfa2126399200ef54bb
  Preferences:{
    "kbdLocale":"en_GB",
    "pfkeys":"[\"\",\"Hello\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\"]",
    "wse":"1",
    "zoom":"2"
  }

Interpreter:
  Version: 16.0.30305
  Platform: Linux-64
  Edition: Unicode/64
  Date: Jul  6 2017 at 11:22:35

**Comment by DyalogRichard** [comment]
stencil, quaddiamond and diamondquad would appear to be the minimum to be consistent with what's there already.

In development it's been referred to as tessellate, tile and moving window so it's at least worth considering these, I guess.

**Comment by jayfoad** [comment]
I added: diamondquad quaddiamond stencil tessellate tile
