### ISSUE TITLE
)ed ns.foo where ns is a scripted object results in the cursor being on ns[0] rather than on ns.foo[].  Same with the tracer.

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/ride#207]
⎕fix 1 100 1 1 1 1 /':namespace ns' ' ' '∇foo' '1' '∇' ':endnamespace'
      )ed  ns.foo
cursor on ns[0], no sign of foo.  Hit Enter to get to the right place.
Same happens with the tracer.  I'm pretty sure that this is a regression.

IDE:
  Version: 4.1.2878
  Platform: MacIntel
  Date: 2017-07-27 10:42:44 +0100
  Git commit: 45b8031419f89add06fab99aa289c050a19b24f7
  Preferences:{
    "kbdLocale":"en_GB_Mac",
    "keys":"{\"LOG\":[\"Shift-Cmd-L\"]}",
    "lbarOrder":"← +-×÷*⍟⌹○!? |⌈⌊⊥⊤⊣⊢ =≠≤<>≥≢ ∨∧⍝⍲⍱ ↑↓⍠⊂⊃⊆⌷⍋⍒ ⍳⍸∊⍷∪∩~ /\\⌿⍀ ,⍪⍴⌽⊖⍉ ¨⍨⍣.∘⍤@ ⍞⎕≡⌸⌺⌶⍎⍕ ⋄→⍵⍺∇& ¯⍬"
  }

Interpreter:
  Version: 16.0.30513
  Platform: Mac-64
  Edition: Unicode/64
  Date: Jul 28 2017 at 02:45:38

**Comment by jayfoad** [comment]
Duplicate of #173 ?

**Comment by dyaandys** [comment]
Quite possibly .. or something very similar.  I am also not certain that the focus is where it should be if the tracer is opened as the result of hitting a Stop bit.

**Comment by e9gille** [comment]
this was introduced by 57bd6cfbb8809da3433df211ebf2481e11c3c506

**Comment by jayfoad** [comment]
Gil, I've just noticed another oddity. If I type ")ed foo" then ed.open sets the cursor position to 0,3 (at the end of the line "foo"). Then it calls the RD command, which puts a leading space on that line (" foo") but preserves the cursor position, so what I end up with is the cursor between the two "o"s!

**Comment by e9gille** [comment]
I see, I can understand why the cursor doesn't move as we are essentially replacing the content on reformat but preserve the absolute position of the cursor. 
We could probably correct that for the case where we have just opened the editor. Not sure what happens when you reformat while editing though. Does the ODE move the cursor when reformatting?

**Comment by dyaandys** [comment]
It appears to.

**Comment by flouc001** [comment]
The space might be interesting. For now the cursor should move to the end of the line when a window first opens. The cursor will not move on subsequent reformats, I believe this is closer to the behavior we want to achieve. e5fb14d introduces this as a fix for #209

**Comment by jayfoad** [comment]
@dyaandys can you confirm you're happy with the behaviour now? (It looks good to me!)

**Comment by dyaandys** [comment]
Looks good to me in 4.0.2860
