### ISSUE TITLE
Feature request: implement d3 library support in RIDE with APL bindings

### ISSUE THREAD

**Issue by fourier** [Dyalog/ride#22]
Since RIDE uses JS for implementation, it would be a fantastic opportunity to utilize [D3](https://d3js.org/) library to create graphs from APL in RIDE.

**Comment by abrudz** [comment]
@fourier Maybe, but we already have `3500⌶`, which works great with SharpPlot (including the `]Chart` GUI wizard).

**Comment by fourier** [comment]
Interesting, thanks, I have to look at it.

**Comment by jayfoad** [comment]
This is out of scope for the RIDE project. Sorry.
