### ISSUE TITLE
A hint only appears if you hover over the left hand side of a one-character name

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/ride#225]
⎕fx'foo a' 'a ⍝'
      foo 11 {TC}

move the sprite slowly leftwards from right of the letter "a" on foo[1].  Only when you get about 1/2 way across the "a" does the hint appear.  It's almost as though the region that is considered to be where the "a" is is offset by about 1/2 character .. 

IDE:
  Version: 4.0.2860
  Platform: MacIntel
  Date: 2017-08-03 09:42:41 +0100
  Git commit: ea7171c622602555be0e6dfb106ed73f6261f7d7
  Preferences:{
    "kbdLocale":"en_GB_Mac",
    "keys":"{\"LOG\":[\"Shift-Cmd-L\"]}",
    "lbarOrder":"← +-×÷*⍟⌹○!? |⌈⌊⊥⊤⊣⊢ =≠≤<>≥≢ ∨∧⍝⍲⍱ ↑↓⍠⊂⊃⊆⌷⍋⍒ ⍳⍸∊⍷∪∩~ /\\⌿⍀ ,⍪⍴⌽⊖⍉ ¨⍨⍣.∘⍤@ ⍞⎕≡⌸⌺⌶⍎⍕ ⋄→⍵⍺∇& ¯⍬"
  }

Interpreter:
  Version: 16.0.30778
  Platform: Mac-64
  Edition: Unicode/64
  Date: Aug 16 2017 at 15:11:48

**Comment by jayfoad** [comment]
I reckon this is a bug in CodeMirror: https://github.com/codemirror/CodeMirror/issues/5010
