### ISSUE TITLE
more features for the demo system

### ISSUE THREAD

**Issue by jayfoad** [Dyalog/ride#228]
The RIDE demo system (DMR, DMN and DMP commands) could borrow some features from the old ]demo user command:
* display a line in the session without executing it
* execute a line without displaying it in the session
* execute lines as soon as the script is loaded, without you having to explicitly step through them
* build up a single line in the session bit by bit each time you press "next"
* don't ignore blank lines

**Comment by JohnScholes** [comment]
Perhaps controversially: place my script lines starting from column[0] in the session. 
Con: I would need to indent the lines in my script file.
Pro: it give me complete control. In particular I can use full-width comments or choose, say, a 4- or even 2-space indent if session width is limited because I want a large font for the old folk.

**Comment by JohnScholes** [comment]
Regarding the 4th bullet point above:
- build up a single line in the session bit by bit each time you press "next"
It is possible to achieve this at the moment by having near-identical lines and calling them up _without_ executing each but the final one. However, this is a hard trick to get right when presenting live.

**Comment by JohnScholes** [comment]
Ride seems to skip all-comment lines in my DM demo script. Is this intentional? 

⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝
⍝         set display state for ]boxing and ]defs        ⍝
⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝
]box ON -t=parens
avg ← +⌿ ÷ ≢

**Comment by e9gille** [comment]
> - execute a line without displaying it in the session
> - execute lines as soon as the script is loaded, without you having to explicitly step through them

We need to extend the protocol to allow RIDE to request execution of expressions for this to work.

**Comment by JohnScholes** [comment]
Closed: to be replaced with simpler alternative.
