### ISSUE TITLE
WIBNI it was possible to print functions/scripted objects from RIDE

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/ride#231]
The IDE can print the contents of the current edit/trace window.  WIBNI RIDE could do the same.

Rather than mimicing the functionality of the IDE, we should consider other possibilities too - print all functions or scripted object or all of a ws for example ..

**Comment by dyavc** [comment]
A customer asked today how to print from RIDE.

**Comment by abrudz** [comment]
WinIDE's Print functionality is out-dated, and e.g. doesn't even work with namespaces. See instead #1027
