### ISSUE TITLE
On Centos 7, ride does not start as it cannot open shared library libXss.so.1

### ISSUE THREAD

**Issue by dyavc** [Dyalog/ride#233]
### Describe the issue you are having
I have installed ride 4.0.2860 and am trying to start it.

$ ride
ride: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory

### Did you connect to an already running interpreter or start the interpreter from RIDE?
N/A

### How do you reproduce the issue?
try to start ride

### Paste the contents of Help → About (Shift+F1)
N/A

Centos 7:
$ cat /etc/*release
CentOS Linux release 7.3.1611 (Core) 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Comment by jayfoad** [comment]
As a workaround you can manually install the `libXScrnSaver` package.

**Comment by jayfoad** [comment]
Looks like this is tricky to fix in the rpm, because RHEL/Centos/Fedora calls the package `libXScrnSaver` but SUSE calls it `libXss1` :-(

**Comment by jayfoad** [comment]
@JasonDyalog reckons most people ship separate RPMs for Centos and openSUSE, but it would be a shame to have to start doing that just for one dependency...

**Comment by flouc001** [comment]
Would it be wrong to set up a symbolic link for the user? Or are there differences in the packages?

**Comment by JasonRivers** [comment]
No, the problem is that the package is named completely differently and we'd need to know what to install as a dependency. It won't be too hard to create 2 RPMs with different dependencies. I suggest for now we start with fixing the reported issue for Centos, and I'll look at adding an openSUSE RPM.
