### ISSUE TITLE
Editor should not show ⍝ button when editing a variable

### ISSUE THREAD

**Issue by abrudz** [Dyalog/ride#24]
The comment and un-comment buttons are only meaningful for functions, operators, classes, etc.

**Comment by e9gille** [comment]
@johndaintree editing a variable that is a namespace ref reports entityType 1 (defined function). Not sure what it should be, but 256 is reported for a scripted namespace.

Would it be ok to remove the comment buttons when editor is read-only? That would leave them in for character arrays. Maybe not appropriate, you tell me.

**Comment by johndaintree** [comment]
It certainly shouldn’t report “defined function” I’ll take a look at that. 

 

I think the comment buttons can be removed (or disabled, which may be better) if the editor is NOT “defined function” OR is read-only.

 

/JD

**Comment by flouc001** [comment]
Fixed in ccf087ca, I forgot the hash before the issue number in the commit message.
