### ISSUE TITLE
Dialog button text invisible on mouse hover

### ISSUE THREAD

**Issue by abrudz** [Dyalog/ride#240]
### Describe the issue you are having
Dialog button text invisible on mouse hover.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Start an interpreter

### How do you reproduce the issue?
Open a dialog box. Hover mouse over button.

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.unknown
  Platform: Win32
  Date: 2017-10-13 16:05:26 +0100
  Git commit: d7ac6a5f748f8aba063d0c95160486f4df8518b9
  Preferences:{
    "colourScheme":"Kazimir Malevich",
    "kbdLocale":"en_US",
    "lbarOrder":"← +-×÷*⍟⌹○!? |⌈⌊⊥⊤⊣⊢ =≠≤<>≥≡≢ ∨∧⍲⍱ ↑↓⊂⊃⊆⌷⍋⍒ ⍳⍸∊⍷∪∩~ /\\⌿⍀ ,⍪⍴⌽⊖⍉ ¨⍨⍣.∘⍤@ ⍞⎕⍠⌸⌺⌶⍎⍕ ⋄⍝→⍵⍺∇& ¯⍬",
    "otherExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 17.0 Unicode\\dyalog.exe",
    "selectedExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 17.0 Unicode\\dyalog.exe",
    "squiggleTips":"1",
    "title":"{WSID} {VER}",
    "zoom":"8"
  }

Interpreter:
  Version: unknown
  Platform: unknown
  Edition: unknown
  Date: unknown

![ride](https://user-images.githubusercontent.com/10961427/31600428-50ca3dfe-b24e-11e7-92b0-93e3e7aad3e2.png)

**Comment by flouc001** [comment]
Fixed in 1d10212 ( branch iss240 ). Please test.

**Comment by jayfoad** [comment]
Looks good to me. With your fix the button styling doesn't change in any way when I hover over it, right?

**Comment by flouc001** [comment]
@jayfoad that's correct, the hover effects will be addressed in future styling, it's justa  fix for now.
