### ISSUE TITLE
macOS: when starting an interpreter, the connect button cannot be fully seen if the window requires a scrollbar

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/ride#241]
Start RIDE
Select Connect

Unless the window is large enough that the Connect button is visible, when you scroll down to click on it, you can read the line "For example, MAXWS=1G", and you can just see the top of the Connect button .. but would be better to see the entire button !

IDE:
  Version: 4.1.2920
  Platform: MacIntel
  Date: 2017-10-16 10:54:09 +0200
  Git commit: e7b8222b26275f831bfbe6b3cfebaeeaadd38fd8
  Preferences:{

  }

Interpreter:
  Version: unknown
  Platform: unknown
  Edition: unknown
  Date: unknown

**Comment by jayfoad** [comment]
This problem has gone away now the Connect button is near the top of the page, above all the optional fields you can fill in.
