### ISSUE TITLE
No matter what the connection Type is, the action button's Caption is always "Connect:

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/ride#242]
Start Ride
Note that Type is Connect, and the button's caption is Connect.
Change Type to Start.  The button's caption is still Connect .. I think that would be better being Start.
Same is true of Listen.

IDE:
  Version: 4.1.2920
  Platform: MacIntel
  Date: 2017-10-16 10:54:09 +0200
  Git commit: e7b8222b26275f831bfbe6b3cfebaeeaadd38fd8
  Preferences:{

  }

Interpreter:
  Version: unknown
  Platform: unknown
  Edition: unknown
  Date: unknown

**Comment by flouc001** [comment]
Fixed in fc18e50 please test.

**Comment by jayfoad** [comment]
Looks good to me.
