### ISSUE TITLE
don't highlight idioms by default ?

### ISSUE THREAD

**Issue by JohnScholes** [Dyalog/ride#244]
### Describe the issue you are having
I wonder if the underlining of idioms in code should be an option. It's a bit distracting for non-specialists.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
N/A

### How do you reproduce the issue?
In the session, type   0=≡ ⍴⍴ ⊢/  99

### Paste the contents of Help → About (Shift+F1)

IDE:
  Version: 4.1.2919
  Platform: MacIntel
  Date: 2017-10-13 14:43:11 +0100
  Git commit: 6715bdfade037456d6269f2eac89be547890bca4
  Preferences:{
    "autocompletion":"0",
    "blinkCursor":"0",
    "colourScheme":"Albrecht Dürer",
    "fold":"0",
    "ilf":"0",
    "indentOnOpen":"0",
    "kbdLocale":"en_US_Mac",
    "lineNums":"0",
    "pfkeys":"[\"\",\"\",\"\",\"\",\"\",\"wsdiff''<ER>\",\"\",\"\",\"\",\"\",\")reset<ER>)save<ER>\",\"\",\"\"]",
    "sqp":"0",
    "valueTips":"0",
    "zoom":"6"
  }

Interpreter:
  Version: 17.0.31152
  Platform: Mac-64
  Edition: Unicode/64
  Date: Oct 16 2017 at 04:08:04

**Comment by jayfoad** [comment]
Underlining of idioms is part of syntax highlighting, which you can configure by going to Preferences→Colours. I see you've chosen the predefined Dürer colour scheme. Of the colour schemes we supply:
- Default does nothing with idioms
- Goya makes idioms bold
- Dürer underlines idioms
- Malevich does nothing with idioms

So the options are:
- John tweaks his selected scheme to his liking
- John chooses a different scheme (may I recommend Malevich, sir?)
- We change all predefined schemes so they don't identify idioms by default

For comparison, the Windows GUI IDE doesn't highlight idioms in any way by default. And even if you choose to highlight them, it only kicks in in edit windows, not in the session (but I suspect that's a bug).

**Comment by jayfoad** [comment]
I'd be happy with:

> We change all predefined schemes so they don't identify idioms by default

Anyone agree/disagree?
