### ISSUE TITLE
The space allocated for "Threads" and "SI Stack" does not scale with text

### ISSUE THREAD

**Issue by abrudz** [Dyalog/ride#249]
### Describe the issue you are having
If the font size is made very large, the allocated area is too low, and the titles will overlap the content below them.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Start an interpreter

### How do you reproduce the issue?
View>Show Debug
Increase font size
![image](https://user-images.githubusercontent.com/10961427/31658284-83e2ae9e-b328-11e7-87f8-fbdc5e5f26d1.png) ![image](https://user-images.githubusercontent.com/10961427/31658292-87728e3a-b328-11e7-8670-4e53077736fb.png)

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: unknown
  Platform: Win32
  Date: unknown
  Git commit: unknown
  Preferences:{
    "kbdLocale":"en_US",
    "lbarOrder":"← +-×÷*⍟⌹○!? |⌈⌊⊥⊤⊣⊢ =≠≤<>≥≡≢ ∨∧⍲⍱ ↑↓⊂⊃⊆⌷⍋⍒ ⍳⍸∊⍷∪∩~ /\\⌿⍀ ,⍪⍴⌽⊖⍉ ¨⍨⍣.∘⍤@ ⍞⎕⍠⌸⌺⌶⍎⍕ ⋄⍝→⍵⍺∇& ¯⍬",
    "otherExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 17.0 Unicode\\dyalog.exe",
    "selectedExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 17.0 Unicode\\dyalog.exe",
    "squiggleTips":"1",
    "title":"{WSID} {VER}",
    "zoom":"10",
    "wse":"1",
    "dbg":"1"
  }

Interpreter:
  Version: 17.0.31153
  Platform: Windows-64
  Edition: Unicode/64
  Date: Oct 16 2017 at 10:27:50

**Comment by e9gille** [comment]
this is now working as requested
