### ISSUE TITLE
Keyboard shortcut to refresh Workspace Explorer

### ISSUE THREAD

**Issue by abrudz** [Dyalog/ride#251]
### Describe the issue you are having
Being that the Workspace Explorer does not reflect changes to the workspaces, it would be nice to have an easy and quick way to manually cause it to refresh.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Start an interpreter

### How do you reproduce the issue?
Open Workspace Explorer. Create variable.

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: unknown
  Platform: Win32
  Date: unknown
  Git commit: unknown
  Preferences:{
    "kbdLocale":"en_US",
    "lbarOrder":"← +-×÷*⍟⌹○!? |⌈⌊⊥⊤⊣⊢ =≠≤<>≥≡≢ ∨∧⍲⍱ ↑↓⊂⊃⊆⌷⍋⍒ ⍳⍸∊⍷∪∩~ /\\⌿⍀ ,⍪⍴⌽⊖⍉ ¨⍨⍣.∘⍤@ ⍞⎕⍠⌸⌺⌶⍎⍕ ⋄⍝→⍵⍺∇& ¯⍬",
    "otherExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 17.0 Unicode\\dyalog.exe",
    "selectedExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 17.0 Unicode\\dyalog.exe",
    "squiggleTips":"1",
    "title":"{WSID} {VER}",
    "zoom":"10",
    "dbg":"1",
    "wse":"1"
  }

Interpreter:
  Version: 17.0.31153
  Platform: Windows-64
  Edition: Unicode/64
  Date: Oct 16 2017 at 10:27:50

**Comment by fourier** [comment]
The runtime update of Workspace Explorer was requested in #18 .

**Comment by e9gille** [comment]
Refreshing the WSE was done using F5, but with 3907989381e1a1c434cc2e61b8b9925a64c64867 it is auto-refreshed every 5 seconds.
