### ISSUE TITLE
Workspace explorer is missing icons for name class 8

### ISSUE THREAD

**Issue by abrudz** [Dyalog/ride#254]
### Describe the issue you are having
Names of class 8 are listed in the Workspace Explorer without icon (and thus misaligned.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Start an interpreter on Windows

### How do you reproduce the issue?
`)load dfns`
`⎕NC'ActivateApp'`
Open Workspace Explorer
![image](https://user-images.githubusercontent.com/10961427/31660796-7d80a74c-b330-11e7-9e79-5ef77dab964f.png)

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: unknown
  Platform: Win32
  Date: unknown
  Git commit: unknown
  Preferences:{
    "dbg":"1",
    "kbdLocale":"en_US",
    "lbarOrder":"← +-×÷*⍟⌹○!? |⌈⌊⊥⊤⊣⊢ =≠≤<>≥≡≢ ∨∧⍲⍱ ↑↓⊂⊃⊆⌷⍋⍒ ⍳⍸∊⍷∪∩~ /\\⌿⍀ ,⍪⍴⌽⊖⍉ ¨⍨⍣.∘⍤@ ⍞⎕⍠⌸⌺⌶⍎⍕ ⋄⍝→⍵⍺∇& ¯⍬",
    "otherExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 17.0 Unicode\\dyalog.exe",
    "selectedExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 17.0 Unicode\\dyalog.exe",
    "squiggleTips":"1",
    "title":"{WSID} {VER}",
    "zoom":"4",
    "wse":"1"
  }

Interpreter:
  Version: 17.0.31153
  Platform: Windows-64
  Edition: Unicode/64
  Date: Oct 16 2017 at 10:27:50

**Comment by jayfoad** [comment]
The Windows GUI IDE workspace explorer does not display names with class 8 at all. Perhaps we should do the same.
