### ISSUE TITLE
Suggestion: Keyboard icon which better matches new UI style

### ISSUE THREAD

**Issue by abrudz** [Dyalog/ride#255]
### Describe the issue you are having
The upper-right corner of the language bar has a keyboard icon which was taken from the IDE. With the current sleek styling, it look out of place, and it doesn't scale with the font size. By using `⌨` Unicode Character 'KEYBOARD' (U+2328) instead it can be styled and scaled to fit.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Start an interpreter

### How do you reproduce the issue?
Increase font size.
![image](https://user-images.githubusercontent.com/10961427/31662694-64875572-b337-11e7-8e63-ca9e410383a4.png)

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: unknown
  Platform: Win32
  Date: unknown
  Git commit: unknown
  Preferences:{
    "dbg":"1",
    "kbdLocale":"en_US",
    "lbarOrder":"← +-×÷*⍟⌹○!? |⌈⌊⊥⊤⊣⊢ =≠≤<>≥≡≢ ∨∧⍲⍱ ↑↓⊂⊃⊆⌷⍋⍒ ⍳⍸∊⍷∪∩~ /\\⌿⍀ ,⍪⍴⌽⊖⍉ ¨⍨⍣.∘⍤@ ⍞⎕⍠⌸⌺⌶⍎⍕ ⋄⍝→⍵⍺∇& ¯⍬",
    "otherExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 17.0 Unicode\\dyalog.exe",
    "selectedExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 17.0 Unicode\\dyalog.exe",
    "squiggleTips":"1",
    "title":"{WSID} {VER}",
    "wse":"1",
    "zoom":"12"
  }

Interpreter:
  Version: 17.0.31153
  Platform: Windows-64
  Edition: Unicode/64
  Date: Oct 16 2017 at 10:27:50

**Comment by jayfoad** [comment]
In addition @bpbecker reckons the keyboard icon needs better visual separation from the othey glyphs in the language bar -- "a border or something".

**Comment by abrudz** [comment]
Here is a suggestion:
```
#lb_prf {
    background: rgb(250, 199, 57);
    text-decoration: none;
    font-size: 95%;
    color: rgb(85, 81, 83);
    text-align: center;
}
```
![image](https://user-images.githubusercontent.com/10961427/31813279-aa24174e-b57d-11e7-97d1-a0d78f3ac911.png)

**Comment by DyalogRichard** [comment]
Nice!

I guess the keyboard icon is http://www.fileformat.info/info/unicode/char/2328/index.htm

That icon seems incorrect given the keyboard settings are just one part of what comes up (and even though it's what the ODE uses). Would one of these be better? 

![image](https://user-images.githubusercontent.com/10868907/31814110-7e53023a-b580-11e7-90ce-5c955abd3bf1.png)
(http://www.fileformat.info/info/unicode/char/2699/index.htm)

![image](https://user-images.githubusercontent.com/10868907/31814070-6b8d4138-b580-11e7-9401-c865fb5f568e.png)
(http://www.fileformat.info/info/unicode/char/2630/index.htm)

![image](https://user-images.githubusercontent.com/10868907/31814044-54da9a80-b580-11e7-9dda-4e69d4eb92e0.png)
(http://www.fileformat.info/info/unicode/char/22ee/index.htm)

**Comment by abrudz** [comment]
No need for guessing; it is in the original post :-)

Yeah, that button (?) is decidedly non-standard in the IDE. It has two (almost) unrelated functionalities:

1. Hover to see keyboard shortcuts (unavailable to touch users)
2. Click to edit the keyboard shortcuts

However, in RIDE, clicking it opens the PREFERENCES box to the tab that was last open, so it would seem that an icon symbolising "settings" would be more appropriate.

That being said, how often does one really need to change preferences? Most applications do not have a 1-click toolbar item for preferences. Maybe, in order to serve touch users and exhibit more usual behaviour, the button should only open up the shortcuts' reminder panel, and preferences should only be available through the menu?

**Comment by jayfoad** [comment]
> That icon seems incorrect given the keyboard settings are just one part of what comes up (and even though it's what the ODE uses). Would one of these be better?

Indeed. This is #341, now fixed.

**Comment by mkromberg** [comment]
Problem now is it looks like "just another APL symbol". Needs to be bigger or somehow "different", IMHO.

**Comment by jayfoad** [comment]
@e9gille can you (or Mike) style it a bit?

**Comment by e9gille** [comment]
preferences button moved to status bar cd23796bded61819dd08e0d8d5efa6552c72acb8
