### ISSUE TITLE
Linux: tick marks on View menu don't update

### ISSUE THREAD

**Issue by jayfoad** [Dyalog/ride#257]
On Linux, if I toggle options on the View menu like
- Show Workspace Explorer
- Floating Edit Windows
- Editors on Top

... then the change takes effect, but the little tick mark in the menu doesn't seem to get updated; it stays in whatever state it was (ticked or unticked) when RIDE was started.

**Comment by jayfoad** [comment]
From the [Electron docs](https://github.com/electron/electron/blob/master/docs/api/tray.md):
> On Linux in order for changes made to individual `MenuItem`s to take effect, you have to call `setContextMenu` again.

**Comment by abrudz** [comment]
Changing the actual menu items in Preferences also does not update the menu until restarting RIDE.

**Comment by jayfoad** [comment]
This was a problem for me on Ubuntu 17.04 with the Unity desktop. Now I've upgraded to 17.10 with the GNOME desktop, the problem has gone away: checkmarks are appearing and disappearing correctly.

**Comment by jayfoad** [comment]
Closing cos it no longer affects me :-)
