### ISSUE TITLE
Drag and drop doesn't work

### ISSUE THREAD

**Issue by abrudz** [Dyalog/ride#259]
### Describe the issue you are having
After selecting text in session or editor with the mouse, I would expect it possible to click and drag the text to a new location.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Start an interpreter

### How do you reproduce the issue?
Select some text. Try to click and drag it. A new selection begins instead.

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: unknown
  Platform: Win32
  Date: unknown
  Git commit: unknown
  Preferences:{
    "floating":"1",
    "kbdLocale":"en_US",
    "lbarOrder":"← +-×÷*⍟⌹○!? |⌈⌊⊥⊤⊣⊢ =≠≤<>≥≡≢ ∨∧⍲⍱ ↑↓⊂⊃⊆⌷⍋⍒ ⍳⍸∊⍷∪∩~ /\\⌿⍀ ,⍪⍴⌽⊖⍉ ¨⍨⍣.∘⍤@ ⍞⎕⍠⌸⌺⌶⍎⍕ ⋄⍝→⍵⍺∇& ¯⍬",
    "otherExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 17.0 Unicode\\dyalog.exe",
    "selectedExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 17.0 Unicode\\dyalog.exe",
    "squiggleTips":"1",
    "title":"{WSID} {VER}",
    "zoom":"1",
    "floatOnTop":"1"
  }

Interpreter:
  Version: 17.0.31153
  Platform: Windows-64
  Edition: Unicode/64
  Date: Oct 16 2017 at 10:27:50

**Comment by jayfoad** [comment]
Works for me (on Linux) now we're using Monaco.
