### ISSUE TITLE
Auto-complete should kick in after 0 chars

### ISSUE THREAD

**Issue by abrudz** [Dyalog/ride#26]
The IDE has a setting for how many characters one needs to write before auto-complete kicks in. Since this setting is not alterable from within RIDE, it should default to 0. It is currently 1.

Example:
In the IDE, set Options>Configure>Auto Complete>Make suggestions after **0** characters.
In the session, type `⎕SE.` and wait to see the suggestions.
In RIDE, type `⎕SE.`

**Comment by johndaintree** [comment]
The interpreter uses a AUTOCOMPLETE_PREFIXSIZE setting. e.g.

 

RIDE_INIT=SERVE::4502 AUTOCOMPLETE_PREFIXSIZE=0 apl.

 

Is it sufficient  for RIDE to set that and/or our apl scripts to set it?

 

/JD

**Comment by e9gille** [comment]
@johndaintree any news on this? Will it make it into the protocol?
