### ISSUE TITLE
Colour customiser: Clicking in the righthand margin selects what is on the left

### ISSUE THREAD

**Issue by abrudz** [Dyalog/ride#260]
### Describe the issue you are having
In order to change the "normal" token type, I need to click outside any tokens, but clicking in the righthand margin selects what is on the left. Only clicking at the bottom of the code example selects "normal", but this area may not be visible at large font sizes, and certainly isn't intuitive.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Start an interpreter

### How do you reproduce the issue?
Preferences>Colours>Clone
Click in the whitespace to the right of any line.

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: unknown
  Platform: Win32
  Date: unknown
  Git commit: unknown
  Preferences:{
    "floating":"1",
    "kbdLocale":"en_US",
    "lbarOrder":"← +-×÷*⍟⌹○!? |⌈⌊⊥⊤⊣⊢ =≠≤<>≥≡≢ ∨∧⍲⍱ ↑↓⊂⊃⊆⌷⍋⍒ ⍳⍸∊⍷∪∩~ /\\⌿⍀ ,⍪⍴⌽⊖⍉ ¨⍨⍣.∘⍤@ ⍞⎕⍠⌸⌺⌶⍎⍕ ⋄⍝→⍵⍺∇& ¯⍬",
    "otherExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 17.0 Unicode\\dyalog.exe",
    "selectedExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 17.0 Unicode\\dyalog.exe",
    "squiggleTips":"1",
    "title":"{WSID} {VER}",
    "zoom":"-6",
    "wrap":"1"
  }

Interpreter:
  Version: 17.0.31153
  Platform: Windows-64
  Edition: Unicode/64
  Date: Oct 16 2017 at 10:27:50

**Comment by e9gille** [comment]
The tokenizer doesn't explicitly change the token type on the end of a line, so if the last item is a number, that is what is selected.

I've now allowed clicking beyond end of line which inserts white space up until the cursor position. In this case the tokenizer identifies white space as the last token of the line.
