### ISSUE TITLE
Keyboard layout: Colours are inappropriate

### ISSUE THREAD

**Issue by abrudz** [Dyalog/ride#262]
### Describe the issue you are having
The top row is all red and the bottom row is black and green. Firstly, the static shifted symbols should be differentiated from the editable shifted APL symbols. Secondly, The special keys (Tab, Caps, etc.) are green as if they were editable. Lastly, red and green should not be used to distinguish properties as a lot of people are red-green colourblind. Choose four colours from this chart:
![image](https://user-images.githubusercontent.com/10961427/31664180-5b773ef2-b33c-11e7-9d37-09993dab6373.png)

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Start an interpreter

### How do you reproduce the issue?
Preferences>Layout
![image](https://user-images.githubusercontent.com/10961427/31664275-b9293d02-b33c-11e7-987b-7b1ba5ef988d.png)

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: unknown
  Platform: Win32
  Date: unknown
  Git commit: unknown
  Preferences:{
    "floating":"1",
    "kbdLocale":"en_US",
    "lbarOrder":"← +-×÷*⍟⌹○!? |⌈⌊⊥⊤⊣⊢ =≠≤<>≥≡≢ ∨∧⍲⍱ ↑↓⊂⊃⊆⌷⍋⍒ ⍳⍸∊⍷∪∩~ /\\⌿⍀ ,⍪⍴⌽⊖⍉ ¨⍨⍣.∘⍤@ ⍞⎕⍠⌸⌺⌶⍎⍕ ⋄⍝→⍵⍺∇& ¯⍬",
    "otherExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 17.0 Unicode\\dyalog.exe",
    "selectedExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 17.0 Unicode\\dyalog.exe",
    "squiggleTips":"1",
    "title":"{WSID} {VER}",
    "wrap":"1"
  }

Interpreter:
  Version: 17.0.31153
  Platform: Windows-64
  Edition: Unicode/64
  Date: Oct 16 2017 at 10:27:50

**Comment by jayfoad** [comment]
> Choose four colours from this chart

@abrudz can you suggest some? I'm not even sure how to read the charts.

**Comment by abrudz** [comment]
Shift+Key:3    ` Shift+Key:8
    Key:0          ` Key:13

**Comment by abrudz** [comment]
Yes, it is fine for highlighting to distinguish categories. Nobody will spend a significant amount of time staring at that chart.

**Comment by e9gille** [comment]
The colors you suggested had a poor contrast ratio, so I picked 0 2 6 11 instead.

**Comment by abrudz** [comment]
Looks fine, but I'd swap 2 and 11 since 2 is very dark, and the more bright colours indicate that these can be changed.
