### ISSUE TITLE
Workspace explorer: clicking on an unscripted namespace opens a useless edit window

### ISSUE THREAD

**Issue by jayfoad** [Dyalog/ride#266]
In the workspace explorer, if you click on an unscripted namespace like ⎕SE.Dyalog, it pops up a read-only edit window containing the text "⎕SE.Dyalog". This is useless.

IDE:
  Version: 4.1.2929
  Platform: Linux x86_64
  Date: 2017-10-17 14:45:33 +0200
  Git commit: 9dac822b9ac196597660b35ab30cd61b3dbf599c
  Preferences:{
    "floatOnTop":"1",
    "floating":"1",
    "zoom":"1",
    "wse":"1"
  }

Interpreter:
  Version: 17.0.31188
  Platform: Linux-64
  Edition: Unicode/64
  Date: Oct 18 2017 at 09:15:46

**Comment by e9gille** [comment]
Is this not the same in ODE?
I agree it is useless, apart from indicating that the namespace is not scripted.

**Comment by jayfoad** [comment]
I don't usually use the ODE Explorer, but I've just tried and I couldn't get it to open an edit window containing the text "⎕SE.Dyalog".

**Comment by e9gille** [comment]
my bad, I don't use it often myself. I was thinking of what happens when you edit/dbl click a namespace in the session/editor. That is when you get a read only window with the name of the space. I'll get this changed to match ODE (toggle the node).

**Comment by e9gille** [comment]
fixed in branch [iss266](https://github.com/Dyalog/ride/tree/iss266)
It now toggles nodes on double click. This affects scripted spaces as well, so you get the editor only when double clicking a child of a space (leaf node).

**Comment by jayfoad** [comment]
This is unfixed by 3f20f2b8b94797103dcbb5951072ebb876c6eb27. We might need some help from the interpreter to decide whether an edit is going to be "useless".
