### ISSUE TITLE
RIDE 4.1 will not die

### ISSUE THREAD

**Issue by DyalogRichard** [Dyalog/ride#268]
### Describe the issue you are having
Cannot close RIDE connected to a running interpreter

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Connect to already running

### How do you reproduce the issue?
Start an an interpreter. Start RIDE and connect to the interpreter.
Attempt to close RIDE from either the X in the title bar or File->Quit
RIDE prompts "Disconnect from interpreter. Are you sure?". Respond Yes
Nothing happens; RIDE remains open and attached to the interpreter

Typing )OFF in the session kills both the interpreter and RIDE, but I cannot just disconnect from the running interpreter.

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.1.2932
  Platform: Linux x86_64
  Date: 2017-10-16 16:21:47 +0200
  Git commit: 89b3f1393ce9bd2bd0981d68d882621c7359a60a
  Preferences:{
    "dbg":"1",
    "floating":"1",
    "kbdLocale":"en_GB",
    "wse":"1"
  }

Interpreter:
  Version: 17.0.31185
  Platform: Linux-64
  Edition: Unicode/64
  Date: Oct 17 2017 at 16:11:55

**Comment by jayfoad** [comment]
@DyalogRichard is running on the floating branch. I hope this is already fixed on master...

**Comment by DyalogRichard** [comment]
It does appear that it is.

I had no such problem when I reinstalled:

IDE:
  Version: 4.1.2931
  Platform: Linux x86_64
  Date: 2017-10-19 07:03:44 +0200
  Git commit: e84f86990bc2d885af4b2dbf19db0d6cc765a28f
  Preferences:{
    "dbg":"1",
    "floating":"1",
    "kbdLocale":"en_GB",
    "wse":"1"
  }

Interpreter:
  Version: 17.0.31185
  Platform: Linux-64
  Edition: Unicode/64
  Date: Oct 17 2017 at 16:11:55
