### ISSUE TITLE
About box missing DYALOG logo when in-browser

### ISSUE THREAD

**Issue by abrudz** [Dyalog/ride#270]
### Describe the issue you are having
About box DYALOG logo and editor toolbar icons are missing when run in-browser

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Connect to already running

### How do you reproduce the issue?
)ed foo
![image](https://user-images.githubusercontent.com/10961427/31813493-7c9b2b7c-b57e-11e7-86b3-8ded66e0387b.png)
Shift-F1
![image](https://user-images.githubusercontent.com/10961427/31812553-4345ed74-b57b-11e7-9ef1-ff2f7d240224.png)

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: unknown
  Platform: Win32
  Date: unknown
  Git commit: unknown
  Preferences:{
    "colourScheme":"Kazimir Malevich",
    "kbdLocale":"en_GB"
  }

Interpreter:
  Version: 16.0.30942
  Platform: Windows-64
  Edition: Unicode/64
  Date: Sep 25 2017 at 13:40:32

**Comment by jayfoad** [comment]
Works for me. Do you see any errors in your browser's Javascript console?

**Comment by abrudz** [comment]
Now it works. Must have been a network glitch.
