### ISSUE TITLE
"Editors on Top"  doesn't work with Floating Edit Windows

### ISSUE THREAD

**Issue by JohnScholes** [Dyalog/ride#273]
### Describe the issue you are having
"Editors on Top" doesn't work with Floating Edit Windows.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Started an interpreter from RIDE.

### How do you reproduce the issue?
      )ed foo
focus session window
foo disappears behind the session

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.1.2937
  Platform: MacIntel
  Date: 2017-10-19 13:13:28 +0100
  Git commit: 63839b2386a1d9b8cae3a5f60f3508c87ea44eb0
  Preferences:{
    "autocompletion":"0",
    "blinkCursor":"0",
    "colourScheme":"Albrecht Dürer",
    "floatOnTop":"1",
    "floating":"1",
    "fold":"0",
    "ilf":"0",
    "indentOnOpen":"0",
    "kbdLocale":"en_US_Mac",
    "lbar":"0",
    "lineNums":"0",
    "pfkeys":"[\"\",\"\",\"\",\"\",\"\",\"wsdiff''<ER>\",\"\",\"\",\"\",\"\",\")reset<ER>)save<ER>\",\"\",\"\"]",
    "sqp":"0",
    "valueTips":"0",
    "zoom":"5"
  }

Interpreter:
  Version: 17.0.31214
  Platform: Mac-64
  Edition: Unicode/64
  Date: Oct 20 2017 at 04:10:13

**Comment by e9gille** [comment]
Added this in the branch iss273 930f8364306a058ca425a84f1c85b5d3a825c059

Note that on Mac the editor windows open on top of each other, so it gets a bit hard to manage on  a small screen. I can see where your request for a single floating editor comes from...

**Comment by JohnScholes** [comment]
> On 29 Oct 2017, at 13:25, Gilgamesh Athoraya <notifications@github.com> wrote:
> Closed #273 <https://github.com/Dyalog/ride/issues/273> via 89c9117 <https://github.com/Dyalog/ride/commit/89c91175db5be54a365dedd3de32f23ec07ae766>.
> 
This doesn't seem to be fixed in my latest download. If I open an edit window and tab to the session, the edit window still disappears behind the session.

John.


IDE:
  Version: 4.1.2947
  Platform: MacIntel
  Date: 2017-10-29 22:19:16 +0100
  Git commit: 85898387ec1d5472bac7e99a93752e1b478f694f
  Preferences:{
    "autocompletion":"0",
    "blinkCursor":"0",
    "colourScheme":"JohnS",
    "colourSchemes":"[{\"name\":\"JohnS\",\"styles\":\"diam=B err=fg:#ff0000,bg:#ffffff,bgo:0.5 idm=bg:#ffffff,bgo:0.5,fg:0 kw=B lnum=bg:f,bgo:1 mod=bg:e,bgo:1 mtch=bg:c,bgo:0.5 norm=bg:f,bgo:1 ns=fg:8 num=fg:8 quad=fg:8 srch=bg:c,bgo:0.5 str=fg:#000000 tc=bg:#ffffff,bgo:1,fg:0 zld=fg:8 vtt=bc:aaa\"}]",
    "floating":"1",
    "fold":"0",
    "ilf":"0",
    "indentOnOpen":"0",
    "kbdLocale":"en_US_Mac",
    "lbar":"0",
    "lineNums":"0",
    "pfkeys":"[\"\",\"\",\"\",\"\",\"\",\"wsdiff''<ER>\",\"\",\"\",\"\",\"\",\")reset<ER>)save<ER>\",\"\",\"\"]",
    "sqp":"0",
    "valueTips":"0",
    "zoom":"5",
    "floatOnTop":"1"
  }

Interpreter:
  Version: 17.0.31313
  Platform: Mac-64
  Edition: Unicode/64
  Date: Oct 30 2017 at 04:10:16

**Comment by e9gille** [comment]
Sorry, I overlooked the fact that the setting only affects new windows. Can you check if it works on a restart of Ride?

**Comment by JohnScholes** [comment]
Ah, it appears to be a bit more subtle:

  set View->Editors on top
  restart MacDyalog

  )ed foo
Ctrl+Tab to session
  Edit window stays on top   :-)

  Esc to close edit window

  )ed foo
Ctrl+Tab to session
  Edit window disappears    :-(

**Comment by e9gille** [comment]
I'm sorry John but I can't replicate that. On my mac the editors remain on top, even when re-opened.

You have identified a shortcoming in that there is no support for dynamically changing the "on top" setting. This option can only be set when creating the window (as the Windows OS doesn't support changing it dynamically). The editor windows are recycled (for performance reasons), so once it is created it sticks around. This means I would have to destroy existing editor windows and re-open them to honor the on top setting (under Windows). 

If I add support for dynamically changing the setting I feel it should cover all platforms, but it will be tricky to do that for Windows. What do you say @jayfoad ?

**Comment by JohnScholes** [comment]
I don't need to change the on-top property dynamically. Here's what happens with the versions below.

Start Dyalog/Mac
Uncheck View->Editors on top
)off

Start Dyalog/Mac
Check View->Editors on top
)off

Start Dyalog/Mac
)ed foo
edit window appears
Tab to session - edit window stays on top  :-)
Esc Esc to close edit window
)ed foo
edit window appears
Tab to session - edit window disappears behind session :-(



IDE:
  Version: 4.1.2947
  Platform: MacIntel
  Date: 2017-10-29 22:19:16 +0100
  Git commit: 85898387ec1d5472bac7e99a93752e1b478f694f
  Preferences:{
    "autocompletion":"0",
    "blinkCursor":"0",
    "colourScheme":"JohnS",
    "colourSchemes":"[{\"name\":\"JohnS\",\"styles\":\"diam=B err=fg:#ff0000,bg:#ffffff,bgo:0.5 idm=bg:#ffffff,bgo:0.5,fg:0 kw=B lnum=bg:f,bgo:1 mod=bg:e,bgo:1 mtch=bg:c,bgo:0.5 norm=bg:f,bgo:1 ns=fg:8 num=fg:8 quad=fg:8 srch=bg:c,bgo:0.5 str=fg:#000000 tc=bg:#ffffff,bgo:1,fg:0 zld=fg:8 vtt=bc:aaa\"}]",
    "floatOnTop":"1",
    "floating":"1",
    "fold":"0",
    "ilf":"0",
    "indentOnOpen":"0",
    "kbdLocale":"en_US_Mac",
    "lbar":"0",
    "lineNums":"0",
    "pfkeys":"[\"\",\"\",\"\",\"\",\"\",\"wsdiff''<ER>\",\"\",\"\",\"\",\"\",\")reset<ER>)save<ER>\",\"\",\"\"]",
    "sqp":"0",
    "valueTips":"0",
    "zoom":"5"
  }

Interpreter:
  Version: 17.0.31313
  Platform: Mac-64
  Edition: Unicode/64
  Date: Oct 30 2017 at 04:10:16

**Comment by JohnScholes** [comment]
FWIW: I'm running OS/X 10.11.0 El Capitan. 

I can't upgrade because, as I understand it, Remote Desktop, on which I rely, would no longer work.

**Comment by e9gille** [comment]
@JohnScholes I have just found the issue. For some reason I had a newer version of electron installed on my machine. I have now specified the correct version (1.8.1) in 836b191c44bf85a73c73e4b039ff47065fcfb63f so it should fix your issue.
Make sure to clear you run npm install after checking out the code to get the correct version installed.

Let me know how you get on.

**Comment by JohnScholes** [comment]
> Let me know how you get on.
The latest build works a treat. Thank you, this makes a huge difference.
