### ISSUE TITLE
In browser: tick marks only appear next to menu items when you hover

### ISSUE THREAD

**Issue by jayfoad** [Dyalog/ride#275]
I'm running in the browser with the language bar and workspace explorer visible. If I open the View menu, the tick marks next to the "Show Language Bar" and "Show Workspace Explorer" items are only visible when I hover over those items. They should be visible irrespective of hovering.

IDE:
  Version: 4.1.2932
  Platform: Linux x86_64
  Date: 2017-10-19 11:49:58 +0100
  Git commit: c27ba14420fc61ef67cff55d47d21efcfc9d2b35
  Preferences:{
    "kbdLocale":"en_GB"
  }

Interpreter:
  Version: 17.0.31090
  Platform: Linux-64
  Edition: Unicode/64
  Date: Oct 11 2017 at 04:36:33

**Comment by e9gille** [comment]
fixed in e1d37ffa3627305f16a2f69ef088bad7d0fdfa2f
