### ISSUE TITLE
WIBNI Floating Edit Windows remembered my position/size preference

### ISSUE THREAD

**Issue by JohnScholes** [Dyalog/ride#277]
### Describe the issue you are having

Floating windows appear "centre stage" by default. This is fine but:

1. After I move or resize an edit/trace window WIBNI _additional_ windows appeared at my preferred position and size.

2. WIBNI these position and size preferences could be remembered between Dyalog sessions, in the same way that Font size is remembered.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
N/A

### How do you reproduce the issue?
)ed foo    --- appears in centre. OK.
Move the edit window top-right and resize to around 20x80 chars
)ed goo    --- additional window appears in centre - my preference is top-right, 20x80
close both windows
)off 
Restart Dyalog. WIBNI Dyalog remembered my edit and trace window posn/size preferences from the previous session?

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.1.2937
  Platform: MacIntel
  Date: 2017-10-19 13:13:28 +0100
  Git commit: 63839b2386a1d9b8cae3a5f60f3508c87ea44eb0
  Preferences:{
    "autocompletion":"0",
    "blinkCursor":"0",
    "colourScheme":"JohnS",
    "colourSchemes":"[{\"name\":\"JohnS\",\"styles\":\"diam=B err=fg:#ff0000,bg:#ffffff,bgo:0.5 idm=bg:#ffffff,bgo:0.5,fg:0 kw=B lnum=bg:f,bgo:1 mod=bg:e,bgo:1 mtch=bg:c,bgo:0.5 norm=bg:f,bgo:1 ns=fg:8 num=fg:8 quad=fg:8 srch=bg:c,bgo:0.5 str=fg:#000000 tc=bg:e,bgo:1 zld=fg:8 vtt=bc:aaa\"}]",
    "floatOnTop":"1",
    "floating":"1",
    "fold":"0",
    "ilf":"0",
    "indentOnOpen":"0",
    "kbdLocale":"en_US_Mac",
    "lbar":"0",
    "lineNums":"0",
    "pfkeys":"[\"\",\"\",\"\",\"\",\"\",\"wsdiff''<ER>\",\"\",\"\",\"\",\"\",\")reset<ER>)save<ER>\",\"\",\"\"]",
    "sqp":"0",
    "valueTips":"0",
    "zoom":"5"
  }

Interpreter:
  Version: 17.0.31214
  Platform: Mac-64
  Edition: Unicode/64
  Date: Oct 20 2017 at 04:10:13

**Comment by DyalogRichard** [comment]
My preference (as an addition to John's request) would be that instead of being in exactly the same position, windows were created offset from each other so that part of every window was visible.

**Comment by JohnScholes** [comment]
For the avoidance of doubt, I think Richard's **"created offset from each other"** should be an _additional_ (and very reasonable) configuration setting. My personal preference is that they don't offset (AKA offset=0 0).
