### ISSUE TITLE
Floating window "close" dialogue box opens behind the window being closed

### ISSUE THREAD

**Issue by DyalogRichard** [Dyalog/ride#279]
### Describe the issue you are having
Open a floating window and make it "always on top". Now close the window. The "Save? Yes/No/Cancel" dialogue opens behind the floating window. 

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Connect to already running

### How do you reproduce the issue?
Open a floating window and make it "always on top". Close the floating window.

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.1.2931
  Platform: Linux x86_64
  Date: 2017-10-19 07:03:44 +0200
  Git commit: e84f86990bc2d885af4b2dbf19db0d6cc765a28f
  Preferences:{
    "dbg":"1",
    "floating":"1",
    "kbdLocale":"en_GB",
    "wse":"1"
  }

Interpreter:
  Version: 17.0.31268
  Platform: Linux-64
  Edition: Unicode/64
  Date: Oct 23 2017 at 17:10:43

**Comment by jayfoad** [comment]
This might be another non-bug due to your use of the OS to force windows to be on top, like #278 and #280.

**Comment by JohnScholes** [comment]
Irrespective of the "View->Editors on top" option on the Mac version. the modal (if that's the word) "Can't Fix" dialog box appears behind the edit window, giving the appearance of a system hang.

**Comment by e9gille** [comment]
The floating windows are not created as children of the main window and the modal message appears on top of the main window. I have changed this to place it on top of the focused window and it now works as expected. (test in the monaco branch)

**Comment by e9gille** [comment]
fixed in master
