### ISSUE TITLE
Multitude of tabs in a narrow panel overlap to the point of being unusable

### ISSUE THREAD

**Issue by abrudz** [Dyalog/ride#28]
If many tabs are open, they should scroll or go multi-line instead of overlapping the tabs. C.f. Notepad++ (good) vs Chrome (bad).

RIDE:
![image](https://cloud.githubusercontent.com/assets/10961427/21863616/1cb64c26-d836-11e6-9ab9-17b685099e8c.png)

Notepad++ (multi-line setting):
![image](https://cloud.githubusercontent.com/assets/10961427/21863712/6c058396-d836-11e6-9fea-99efe26ac97c.png)

Notepad++ (scroll setting):
![image](https://cloud.githubusercontent.com/assets/10961427/21863749/954848ce-d836-11e6-8cc2-199b6391fa9c.png)

Chrome:
![image](https://cloud.githubusercontent.com/assets/10961427/21863948/5d1b0c24-d837-11e6-8250-3c165440c20c.png)

**Comment by jayfoad** [comment]
@ngn said:
> in ride3 extra tabs look bad but they are still accessible through <BT> (ctrl-tab)
> in ride4 they are squeezed tightly but clickable
