### ISSUE TITLE
WIBNI floating windows could be configured to open "always on top" by default

### ISSUE THREAD

**Issue by DyalogRichard** [Dyalog/ride#280]
### Describe the issue you are having
WIBNI floating windows could be configured to open "always on top" by default

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Connect to already running

### How do you reproduce the issue?
Open a floating window. To have it "always on top" you have to explicitly set it so.

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.1.2931
  Platform: Linux x86_64
  Date: 2017-10-19 07:03:44 +0200
  Git commit: e84f86990bc2d885af4b2dbf19db0d6cc765a28f
  Preferences:{
    "dbg":"1",
    "floating":"1",
    "kbdLocale":"en_GB",
    "wse":"1"
  }

Interpreter:
  Version: 17.0.31268
  Platform: Linux-64
  Edition: Unicode/64
  Date: Oct 23 2017 at 17:10:43

**Comment by jayfoad** [comment]
> WIBNI floating windows could be configured to open "always on top" by default

That's what "View -> Editors on Top" is for. The fact that it doesn't work properly is #273.

**Comment by DyalogRichard** [comment]
Jay points out that there is a (currently broken) option for this, on View->Floating Edit Windows.

This, I assert, is a non-obvious place. I looked for it in Preferences and the Window tab - surely more obvious locations?

**Comment by e9gille** [comment]
I'll need to investigate this a bit, but when I tested the "on top" behavior on a Mac, the editors were stacked on top of each other.:
`)ED a b c` => `a` covers `b` covers `c` covers session

On windows, you could still change the stack order for the editors and they were all on top of session. This is my expected behavior.
