### ISSUE TITLE
Floating windows don't die

### ISSUE THREAD

**Issue by DyalogRichard** [Dyalog/ride#281]
### Describe the issue you are having
When you close the main RIDE window (File->Quit or X on the title bar) any floating windows remain open and then can't be closed.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Connect to already running

### How do you reproduce the issue?
Start RIDE. Open a floating edit window. Close the main RIDE window. Try to close the floating edit window (the only way I could do it was with kill).

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.1.2931
  Platform: Linux x86_64
  Date: 2017-10-19 07:03:44 +0200
  Git commit: e84f86990bc2d885af4b2dbf19db0d6cc765a28f
  Preferences:{
    "dbg":"1",
    "floating":"1",
    "kbdLocale":"en_GB",
    "lineNums":"0",
    "wse":"1"
  }

Interpreter:
  Version: unknown
  Platform: unknown
  Edition: unknown
  Date: unknown

**Comment by e9gille** [comment]
fixed in 2e48661293d699371e0b854ab5a0d2fb4df33502 (branch iss281)

**Comment by jayfoad** [comment]
Works for me, thanks!
