### ISSUE TITLE
RIDE language bar and help are built with a fixed version of Dyalog APL 

### ISSUE THREAD

**Issue by bpbecker** [Dyalog/ride#285]
The language bar glyphs, tool tips, and the F1 help links are built, presumably, based on the latest released version of Dyalog APL (happens to be v16.0 currently).  If I start or connect to a  v15.0 interpreter, these items will be incorrect.

It would be nice to point to the proper resources for the interpreter I'm running, or at least issue some notification that the RIDE and interpreter versions are not the same.

**Comment by jayfoad** [comment]
I've raised Mantis 15286 for some interpreter support for this.
