### ISSUE TITLE
Right-click on language bar glyph gives inappropriate context menu

### ISSUE THREAD

**Issue by abrudz** [Dyalog/ride#29]
Currently, a right-click on a language bar item gives a context menu with editing commands (copy/cut/paste…) which is completely inappropriate.

**Comment by mkromberg** [comment]
I removed the enhancement tag, the project to make language bar texts more sophisticated is separate.

**Comment by e9gille** [comment]
The context menu is currently added to the root window object. I'll change that and set it explicitly on the areas where it makes sense.
