### ISSUE TITLE
` and `` autocompletes have empty entries

### ISSUE THREAD

**Issue by abrudz** [Dyalog/ride#301]
### Describe the issue you are having
<code>`</code> and <code>``</code> autocompletes have empty entries

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Start an interpreter

### How do you reproduce the issue?
<code>`</code>
scroll down to <code>`A</code>
![image](https://user-images.githubusercontent.com/10961427/32273357-11ee6016-befa-11e7-8f2c-cc3e9e014074.png)

press <code>`</code> again
scroll down the very bottom
![image](https://user-images.githubusercontent.com/10961427/32273471-88986a5e-befa-11e7-998a-de6c113b8d78.png)

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: unknown
  Platform: Win32
  Date: unknown
  Git commit: unknown
  Preferences:{
    "colourScheme":"Francisco Goya",
    "floatOnTop":"1",
    "floating":"1",
    "kbdLocale":"en_US",
    "keys":"{\"RP\":[\"Ctrl-R\"]}",
    "lbarOrder":"← +-×÷*⍟⌹○!? |⌈⌊⊥⊤⊣⊢ =≠≤<>≥≡≢ ∨∧⍲⍱ ↑↓⊂⊃⊆⌷⍋⍒ ⍳⍸∊⍷∪∩~ /\\⌿⍀ ,⍪⍴⌽⊖⍉ ¨⍨⍣.∘⍤@ ⍞⎕⍠⌸⌺⌶⍎⍕ ⋄⍝→⍵⍺∇& ¯⍬",
    "menu":"# see below for syntax\n\nDyalog                          {mac}\n  About Dyalog             =ABT\n  -\n  Preferences              =PRF\n  -                            \n  &Quit                    =QIT\n&File                           {!browser}\n  New &Session             =NEW\n  &Connect...              =CNC\n  -                             {!mac}\n  &Quit                    =QIT {!mac}\n&Edit\n  Undo                     =UND {!browser}\n  Redo                     =RDO {!browser}\n  -                             {!browser}\n  Cut                      =CT  {!browser}\n  Copy                     =CP  {!browser}\n  Paste                    =PT  {!browser}\n  Select All               =SA  {mac}\n  -                             {!mac&&!browser}\n  Preferences              =PRF {!mac}\n&View\n  Show Language Bar        =LBR\n  Show Workspace Explorer  =WSE\n  Show Debug               =DBG\n  Floating Edit Windows    =FLT\n  Editors on Top           =TOP {!browser}\n  Line Wrapping in Session =WRP\n  -                             {!browser}\n  Increase Font Size       =ZMI {!browser}\n  Decrease Font Size       =ZMO {!browser}\n  Reset Font Size          =ZMR {!browser}\n  -                             {!browser}\n  Toggle Full Screen            {!browser}\n&Window\n  Close All Windows        =CAW\n&Action\n  Edit                     =ED\n  Trace                    =TC\n  Weak Interrupt           =WI\n  Strong Interrupt         =SI\n&Help\n  Dyalog Help              =http://help.dyalog.com/\n  Documentation Centre     =http://dyalog.com/documentation.htm\n  &Idioms                  =http://miserver.dyalog.com/Examples/Applications/Idiom_Search.mipage?nowrapper=1\n  -\n  Dyalog Website           =http://dyalog.com/\n  MyDyalog                 =https://my.dyalog.com/\n  -\n  Dyalog Forum             =http://www.dyalog.com/forum\n  -                             {!mac}\n  About                    =ABT {!mac}\n\n# Syntax:\n#   &x   access key, alt+x\n#   =CMD command code; some are special:\n#          LBR FLT WRP TOP WSE render as checkboxes\n#   =http://example.com/  open a URL\n#   {}   conditional display, a boolean expression\n#          operators: && || ! ( )\n#          variables: browser mac win\n#   -    separator (when alone)\n#   #    comment\n\n# The =PRF (\"Preferences\") menu item must be present.",
    "otherExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 17.0 Unicode\\dyalog.exe",
    "selectedExe":"C:\\Program Files (x86)\\Dyalog\\Dyalog APL 16.0 Unicode\\dyalog.exe",
    "squiggleTips":"1",
    "title":"RIDE {RIDE_VER} - {WSID} {VER}",
    "wse":"1"
  }

Interpreter:
  Version: 17.0.31153
  Platform: Windows-64
  Edition: Unicode/64
  Date: Oct 16 2017 at 10:27:50

**Comment by jayfoad** [comment]
The \`\` entries: I don't think they're empty, they just weren't displaying properly. They should be:
```
Ⓜ ``_m
Ⓝ ``_n
...
```
(The letters in the first column are circled or underscored depending on your font.)

**Comment by jayfoad** [comment]
The single-\` entries are slightly worse in RIDE 4.1, because where the left column is empty the right column no longer lines up:
![screenshot from 2018-04-20 13-38-39](https://user-images.githubusercontent.com/108316/39051408-7d128e5e-44a0-11e8-9bf4-996b723e7536.png)
So yes I think we should remove these entries.
