### ISSUE TITLE
Stack full leads to a hang

### ISSUE THREAD

**Issue by JohnScholes** [Dyalog/ride#302]
### Describe the issue you are having
Run-away recursion can cause WS FULL. Then an attempt to → or )reset leads to the process being busy and uninterruptible for a l-o-n-g time.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
N/A

### How do you reproduce the issue?
```
      ⍎⎕fx'ff'
WS FULL
f[1] f
     )reset
```
This is a bummer if you have to kill the process and so lose your work.

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.1.2961
  Platform: MacIntel
  Date: 2017-11-01 10:10:59 +0100
  Git commit: 836b191c44bf85a73c73e4b039ff47065fcfb63f
  Preferences:{
    "autocompletion":"0",
    "blinkCursor":"0",
    "breakPts":"0",
    "colourScheme":"JohnS",
    "colourSchemes":"[{\"name\":\"JohnS\",\"styles\":\"diam=B err=fg:#ff0000,bg:#ffffff,bgo:0.5 idm=bg:#ffffff,bgo:0.5,fg:0 kw=B lnum=bg:f,bgo:1 mod=bg:#e7e1e7,bgo:1,fg:#000000 mtch=bg:c,bgo:0.5 norm=bg:f,bgo:1 ns=fg:8 num=fg:8 quad=fg:8 srch=bg:#0000ff,bgo:0.5 str=fg:#000000 tc=bg:#ffffff,bgo:1,fg:0 zld=fg:8 vtt=bc:aaa\"}]",
    "editWins":"{\"width\":1082,\"height\":625,\"x\":357,\"y\":23,\"ox\":0,\"oy\":0}",
    "editWinsRememberPos":"1",
    "floatOnTop":"1",
    "floating":"1",
    "fold":"0",
    "ilf":"0",
    "indentOnOpen":"0",
    "kbdLocale":"en_US_Mac",
    "lbar":"0",
    "lineNums":"0",
    "pfkeys":"[\"\",\"\",\"\",\"\",\"\",\"wsdiff''<ER>\",\"\",\"\",\"\",\"\",\")reset<ER>)save<ER>\",\"\",\"\"]",
    "sqp":"0",
    "valueTips":"0",
    "zoom":"5"
  }

Interpreter:
  Version: 17.0.31348
  Platform: Mac-64
  Edition: Unicode/64
  Date: Nov  1 2017 at 09:18:24

**Comment by jayfoad** [comment]
I can't reproduce this on Linux or Mac with up-to-date builds. Please re-open if you can and we'll dig deeper.
