### ISSUE TITLE
Shift+Enter in an empty session line should focus the trace window *and* open it for editing

### ISSUE THREAD

**Issue by JohnScholes** [Dyalog/ride#304]
### Describe the issue you are having
Currently: two lines in the session are greyed (eh?); the trace window is focussed (good); but not turned into an edit window.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
N/A

### How do you reproduce the issue?
```
      ⍎⎕fx'f∘'
SYNTAX ERROR
f[1] ∘
    ∧
```
Focus the session window (but see issue 303) and hit Shift+Enter.
Two session lines are greyed.
The trace window gets the focus but it hasn't been turned into an edit window.

### Paste the contents of Help → About (Shift+F1)

IDE:
  Version: 4.1.2961
  Platform: MacIntel
  Date: 2017-11-01 10:10:59 +0100
  Git commit: 836b191c44bf85a73c73e4b039ff47065fcfb63f
  Preferences:{
    "autocompletion":"0",
    "blinkCursor":"0",
    "breakPts":"0",
    "colourScheme":"JohnS",
    "colourSchemes":"[{\"name\":\"JohnS\",\"styles\":\"diam=B err=fg:#ff0000,bg:#ffffff,bgo:0.5 idm=bg:#ffffff,bgo:0.5,fg:0 kw=B lnum=bg:f,bgo:1 mod=bg:#e7e1e7,bgo:1,fg:#000000 mtch=bg:c,bgo:0.5 norm=bg:f,bgo:1 ns=fg:8 num=fg:8 quad=fg:8 srch=bg:#0000ff,bgo:0.5 str=fg:#000000 tc=bg:#ffffff,bgo:1,fg:0 zld=fg:8 vtt=bc:aaa\"}]",
    "editWins":"{\"width\":1082,\"height\":625,\"x\":357,\"y\":23,\"ox\":0,\"oy\":0}",
    "editWinsRememberPos":"1",
    "floatOnTop":"1",
    "floating":"1",
    "fold":"0",
    "ilf":"0",
    "indentOnOpen":"0",
    "kbdLocale":"en_US_Mac",
    "lbar":"0",
    "lineNums":"0",
    "pfkeys":"[\"\",\"\",\"\",\"\",\"\",\"wsdiff''<ER>\",\"\",\"\",\"\",\"\",\")reset<ER>)save<ER>\",\"\",\"\"]",
    "sqp":"0",
    "valueTips":"0",
    "zoom":"5"
  }

Interpreter:
  Version: 17.0.31348
  Platform: Mac-64
  Edition: Unicode/64
  Date: Nov  1 2017 at 09:18:24

**Comment by e9gille** [comment]
In the latest commit 19e7fcb8c389badc842eb9312bcd38a5ed6c696f it now updates the tracer to an edit window if you Shift+Enter in the session. This only works if the tracer window is opened already. 

When there is no window open and you hit Ctrl-Enter, it opens the tracer window (we send an Execute command to the interpreter with the tracer flag set which responds by opening the tracer window). If I instead try to issue an Edit command nothing happens. I'm not sure what the correct request is to get the editor for the currently suspended function. @johndaintree any ideas?

**Comment by e9gille** [comment]
fixed in master
