### ISSUE TITLE
Glyph top bar doesn't support as many spaces as I want.

### ISSUE THREAD

**Issue by GolfingSuccess** [Dyalog/ride#307]
### Describe the issue you are having

In RIDE 4.0, you can see that the glyphs at the top bar can be moved around. This is handy if you want a different grouping than the default. Unfortunately, there is a finite number of spaces in the top bar you can move around, so not all groupings are possible, and I feel like this could be limiting for some.

### Did you connect to an already running interpreter or start the interpreter from RIDE?

Started from RIDE.
### How do you reproduce the issue?

It's not something you reproduce, it's an issue with the interface.
### Paste the contents of Help → About (Shift+F1)

IDE:
  Version: 4.0.2860
  Platform: Linux x86_64
  Date: 2017-08-03 09:42:41 +0100
  Git commit: ea7171c622602555be0e6dfb106ed73f6261f7d7
  Preferences:{
    "kbdLocale":"en_US",
    "lbarOrder":"← +-×÷*⍟⌹○!? |⌈⌊⊥⊤⊣⊢ =≠≤<>≥≡≢ ∨∧⍲⍱ ↑↓⊂⊃⊆⌷⍋⍒ ⍳⍸∊⍷∪∩~ /\\⌿⍀ ,⍪⍴⌽⊖⍉ ¨⍨⍣.∘⍤@ ⍞⎕⍠⌸⌺⌶⍎⍕ ⋄⍝→⍵⍺∇& ¯⍬",
    "selectedExe":"/opt/mdyalog/16.0/64/unicode/mapl"
  }

Interpreter:
  Version: 16.0.30863
  Platform: Linux-64
  Edition: Unicode/64
  Date: Aug 31 2017 at 02:58:43

**Comment by abrudz** [comment]
Right, in the IDE, you can right click and select "Insert Space Before". Maybe a solution would be to always ensure a single trailing space. Then if the user moves that somewhere, we add another space at the end. And if the user moves a space to the end, we remove one, so only one trailing space remains.

**Comment by ngn** [comment]
that was the case before, likely changed with 67c3a3cb5fbe464737a73d28de2b17b68fb95493

**Comment by GolfingSuccess** [comment]
@abrudz except that's not the case here.

**Comment by abrudz** [comment]
@GolfingSuccess The IDE is the default Windows desktop interface.

**Comment by GolfingSuccess** [comment]
@abrudz But I'm not using Windows.

**Comment by e9gille** [comment]
@ngn spot on what I was going to say. I had not noticed that the feature had been lost. I'm sure it wasn't intentional.

I suspect the attempt was to add attributes to enable more detailed styling of separators. I'll add it back in for now while we review the suggestions from @abrudz (#264 #267)

**Comment by GolfingSuccess** [comment]
@e9gille RIDE doesn't seem to have been packaged with the temporary fix yet, just re-installed RIDE and found out no trailing space or "Insert space" option.

**Comment by e9gille** [comment]
Sorry, I fixed it in the master branch only. I'll see if we can get a release out for v4.0 anytime soon.

**Comment by GolfingSuccess** [comment]
Oh, that's alright. Hope it's packaged soon! Thanks in advance.
