### ISSUE TITLE
Floating windows

### ISSUE THREAD

**Issue by abrudz** [Dyalog/ride#31]
Coming from terminal to RIDE 4 without floating editor/tracer windows is a huge step forward.

Coming from RIDE 3 or the IDE to RIDE 4, thus losing the floating windows is a huge loss. Among other things, it makes it difficult to use multiple monitors, and to have an "L" shaped session with a top corner being an editor.

**Comment by JasonRivers** [comment]
@ngn looked in to this with Electron, It's not impossible, but it's not quite as easy as it was with node-webkit. It's something I'd also like to see, but might not be completely feasible within the time-frame that we currently have for RIDE 4. @flouc001 might have more information.

**Comment by JohnScholes** [comment]
An L-shaped session is important for me. Using the term "Floating Windows" might pre-suppose the technology used to implement it and over-generalise the requirement. All I need is for the edit/trace window to occupy the top right part of my (13" MacBook) full-screen session.

**Comment by jayfoad** [comment]
L-shaped session is now #81

**Comment by jayfoad** [comment]
We'd like to at least research this for 4.1.
