### ISSUE TITLE
Can't reformat followed by blank editor

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/ride#312]
### Describe the issue you are having
See the subject line and repro.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Connect to already running

### How do you reproduce the issue?
)load isolate
)ed #.isolate.ynys.start
Get "Dyalog APL Error - Can't reformat"
At the point the function is visible, but after I hit "OK" the editor is cleared.

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: unknown
  Platform: Win32
  Date: unknown
  Git commit: unknown
  Preferences:{
    "kbdLocale":"da_DK",
    "prefixKey":"<",
    "zoom":"7"
  }

Interpreter:
  Version: 16.0.31748
  Platform: Linux-64
  Edition: Unicode/64
  Date: Dec 10 2017 at 03:19:17

**Comment by e9gille** [comment]
can't replicate. Please reopen if this is still an issue.
