### ISSUE TITLE
MAC users require extra settings

### ISSUE THREAD

**Issue by JasonRivers** [Dyalog/ride#314]
### Describe the issue you are having
On macOS users don't start RIDE and connect to an interpreter, they have a "Dyalog-16.0" icon which runs RIDE and spawns an interpreter, This means macOS users are unable to change any environment variables or runtime arguments for launching Dyalog.

An extra settings/options to allow one to set arguments used when spawning an interpreter would allow these users to adjust these settings.

**Comment by mkromberg** [comment]
+1 for this, you need to be able to set MAXWS and such. ideally of course, you'd be able to have separate icons for starting APL with different settings, as you can under Windows.

**Comment by JasonRivers** [comment]
The last bit is a much more difficult issue because of the way in which the mac has the installer, the thing you click on to load is actually a directory with a special contents to say it contains an application, which means to have a separate one, you'd have to have a separate full application. but maybe quickly switching between configs would be a good way to deal with this file -> dyalog profile -> bigmaxws for example.

**Comment by e9gille** [comment]
I can't even launch Dyalog on my mac with that icon, it just throws an error. Are you saying there is no way to start RIDE independently with the default Mac installation?

**Comment by JasonRivers** [comment]
If you install ride standalone, then it works as expected with the connect window, the issue is that a dyalog apl install on the Mac includes ride, the TTY interpreter is hidden in the background. You never see the connect window,  it launches ride which spawns the interpreter. This means the Mac users of an installed dyalog have no way to adjust these settings.

**Comment by e9gille** [comment]
> file -> dyalog profile -> bigmaxws for example.

@JasonRivers Is your suggestion that you'd select a profile from the file menu which affects subsequent launches of "Dyalog"?

I need some guidelines here for how to move forward with this one. Do we want a GUI solution or can this be driven entirely from config files?

**Comment by abrudz** [comment]
Installing stand-alone RIDE on a mac enables options.
