### ISSUE TITLE
Hang after FILE ACCESS ERROR attempting to write back UCMD file

### ISSUE THREAD

**Issue by JohnScholes** [Dyalog/ride#315]
### Describe the issue you are having
Following a FILE ACCESS ERROR trying to write back a change to a user-command file, the system hangs.
### Did you connect to an already running interpreter or start the interpreter from RIDE?
Started an interpreter
### How do you reproduce the issue?
      ]udebug on
Was OFF
      ]map -
make a change to the Run function and Esc to save.
FILE ACCESS ERROR
1. There appears to be no way out of the hang apart from using the OS "Force Quit ..." on the application, thus loosing all current work.
2. Having used "Force Quit ...", the application seems to disappear but a "ps -ef" shows a dyalog process still running.

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.1.2987
  Platform: MacIntel
  Date: 2017-12-12 12:42:45 +0100
  Git commit: 68b9290adafb564c6236ef35eb0583ae538ea308
  Preferences:{
    "autocompletion":"0",
    "blinkCursor":"0",
    "breakPts":"0",
    "colourScheme":"JohnS",
    "colourSchemes":"[{\"name\":\"JohnS\",\"styles\":\"diam=B err=fg:#ff0000,bg:#ffffff,bgo:0.5 idm=bg:#ffffff,bgo:0.5,fg:0 kw=B lnum=bg:f,bgo:1 mod=bg:#e7e1e7,bgo:1,fg:#000000 mtch=bg:c,bgo:0.5 norm=bg:f,bgo:1 ns=fg:8 num=fg:8 quad=fg:8 srch=bg:#0000ff,bgo:0.5 str=fg:#000000 tc=bg:#ffffff,bgo:1,fg:0 zld=fg:8 vtt=bc:aaa\"}]",
    "editWins":"{\"width\":1082,\"height\":593,\"x\":353,\"y\":23,\"ox\":0,\"oy\":0}",
    "editWinsRememberPos":"1",
    "floatOnTop":"1",
    "floating":"1",
    "fold":"0",
    "ilf":"0",
    "indentOnOpen":"0",
    "kbdLocale":"en_US_Mac",
    "lbar":"0",
    "lineNums":"0",
    "pfkeys":"[\"\",\"\",\"\",\"\",\"\",\"wsdiff''<ER>\",\"\",\"\",\"\",\"\",\")reset<ER>)save<ER>\",\"\",\"\"]",
    "sqp":"0",
    "valueTips":"0",
    "zoom":"5"
  }

Interpreter:
  Version: 17.0.31774
  Platform: Mac-64
  Edition: Unicode/64
  Date: Dec 14 2017 at 04:09:58

**Comment by abrudz** [comment]
Can't repro in 4.4
