### ISSUE TITLE
Floating Edit Windows: PageDown page-height calculation comes up one short.

### ISSUE THREAD

**Issue by JohnScholes** [Dyalog/ride#318]
### Describe the issue you are having
With floating edit windows, if there's a horizontal scroll bar, PageDown can move the line just below the window to just above it. This means that the string I'm looking for can whoosh past without my spotting it.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
N/A

### How do you reproduce the issue?
Make sure "Floating Edit Windows" is checked.

      zz←⍕⍪(⍳100)(⍪⍳100)
      )ed zz

Repeatedly PageDown to check that all lines make an appearance in the window.

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.1.2988
  Platform: MacIntel
  Date: 2017-12-14 21:00:41 +0100
  Git commit: b50942479e4d884ad23be5659c1ef7fece907db5
  Preferences:{
    "autocompletion":"0",
    "blinkCursor":"0",
    "breakPts":"0",
    "colourScheme":"JohnS",
    "colourSchemes":"[{\"name\":\"JohnS\",\"styles\":\"diam=B err=fg:#ff0000,bg:#ffffff,bgo:0.5 idm=bg:#ffffff,bgo:0.5,fg:0 kw=B lnum=bg:f,bgo:1 mod=bg:#e7e1e7,bgo:1,fg:#000000 mtch=bg:c,bgo:0.5 norm=bg:f,bgo:1 ns=fg:8 num=fg:8 quad=fg:8 srch=bg:#0000ff,bgo:0.5 str=fg:#000000 tc=bg:#ffffff,bgo:1,fg:0 zld=fg:8 vtt=bc:aaa\"}]",
    "editWins":"{\"width\":995,\"height\":593,\"x\":440,\"y\":23,\"ox\":0,\"oy\":0}",
    "editWinsRememberPos":"1",
    "floatOnTop":"1",
    "floating":"1",
    "fold":"0",
    "ilf":"0",
    "indentOnOpen":"0",
    "kbdLocale":"en_US_Mac",
    "lbar":"0",
    "lineNums":"0",
    "pfkeys":"[\"\",\"\",\"\",\"\",\"\",\"wsdiff''<ER>\",\"\",\"\",\"\",\"\",\")reset<ER>)save<ER>\",\"\",\"\"]",
    "sqp":"0",
    "valueTips":"0",
    "zoom":"6"
  }

Interpreter:
  Version: 17.0.31839
  Platform: Mac-64
  Edition: Unicode/64
  Date: Dec 28 2017 at 04:05:11

**Comment by e9gille** [comment]
I can replicate this but can see that it is not an issue in the new monaco editor I am working on. Can we park this while I work on the replacement?

**Comment by e9gille** [comment]
fixed in master
