### ISSUE TITLE
Source code is lost if RIDE is unable to get the interpreter to reformat the code

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/ride#319]
### Describe the issue you are having
Source code is lost if RIDE is unable to get the interpreter to reformat the code.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Connect to already running

### How do you reproduce the issue?
Enable "handle formatting through the interpreter", then edit a function. Error message "Dyalog APL Error / Can't reformat" is visible, with code behind it. But on clicking OK, the code all disappears.

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: unknown
  Platform: Win32
  Date: unknown
  Git commit: unknown
  Preferences:{
    "kbdLocale":"da_DK",
    "prefixKey":"<",
    "zoom":"7"
  }

Interpreter:
  Version: 16.0.31812
  Platform: Linux-64
  Edition: Unicode/64
  Date: Dec 20 2017 at 03:17:48

**Comment by e9gille** [comment]
how do you replicate this?

**Comment by mkromberg** [comment]
I am unable to reproduce this today, with the latest RIDE that I have checked out. I think I just connected RIDE to a v15.0 interpreter (one which does not support the reformat message), but that doesn't seem to trigger the problem today.

**Comment by e9gille** [comment]
can't replicate
