### ISSUE TITLE
Copy from RIDE doesn't give usable text in the clipboard

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/ride#320]
### Describe the issue you are having
I tried to copy

     :If 0≠≢t←2 ⎕NQ'.' 'GetEnvironment' 'port'
         commandLineArgs,←⊂'port=',(⍕t),' '
     :EndIf
     :If 0≠≢t←2 ⎕NQ'.' 'GetEnvironment' 'codelocation'
         commandLineArgs,←⊂'codelocation=',(⍕t),' '
     :EndIf

I am able to paste it into this window, but notepad and the Dyalog ODE editor only get the first :If block and seem to think there are nasty control chars in the text.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Connect to already running

### How do you reproduce the issue?
See above.

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: unknown
  Platform: Win32
  Date: unknown
  Git commit: unknown
  Preferences:{
    "kbdLocale":"da_DK",
    "prefixKey":"<",
    "zoom":"7",
    "ilf":"0"
  }

Interpreter:
  Version: 16.0.31812
  Platform: Linux-64
  Edition: Unicode/64
  Date: Dec 20 2017 at 03:17:48

**Comment by e9gille** [comment]
I can't replicate this. If you can, can you confirm that you definitely don't have any nasty control characters in the text :)

**Comment by mkromberg** [comment]
I am unable to reproduce the problem, will reopen if it happens again.
