### ISSUE TITLE
Unhelpful error message if you set working directory to ~

### ISSUE THREAD

**Issue by jayfoad** [Dyalog/ride#321]
### Describe the issue you are having
I tried to start an interpreter, not over ssh, selected "v16.0, 64-bit, Unicode" from the dropdown, set the "Working directory" field to "\~" and then clicked GO. I got an error pop-up saying "Cannot find the interpreter's executable". This is unhelpful, because it turns out that the problem is nothing to do with finding the executable. The problem is it can't find the directory "\~", because it doesn't do tilde expansion.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Tried to start an interpreter on the local machine.

### How do you reproduce the issue?
As above.

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.1.2985
  Platform: Linux x86_64
  Date: 2017-11-23 09:40:58 +0100
  Git commit: 2dddc0ebbb7fa89cc9fd7e83e03e1f5398b3baec
  Preferences:{

  }

Interpreter:
  Version: unknown
  Platform: unknown
  Edition: unknown
  Date: unknown

**Comment by jayfoad** [comment]
Thanks, but that doesn't really fix the unhelpful error. What if I set the working directory to "/fdhjsk/fhdsklfds" ? What I'd really like is for the error message to tell me that the working directory I specified does not exist.

**Comment by e9gille** [comment]
Sure, my "fix" also broke it by not allowing an empty cwd. :(

I meant to only reference the issue, not close it. Will get back to this sometime

**Comment by dyavc** [comment]
This issue also happens if you set the Working directory to an invalid directory.  reproduced in:
IDE:
  Version: 4.3.3463
  Platform: Win32
  Date: 2020-07-07 10:44:21 +0100
  Git commit: 0cd6e9faf39a5d6a5f5caa94d1ff51743d5cdd75
  Preferences:{
    "connectFav":"1",
    "kbdLocale":"en_GB",
    "keys":"{\"TL\":[\"Ctrl-Shift-Right\",\"Ctrl-Up\"]}",
    "selectedExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 18.0 Unicode\\dyalog.exe"
  }

Interpreter:
  Version: 18.0.40044
  Platform: Windows-64
  Edition: Unicode/64
  Date: Feb 14 2021 at 20:01:06
