### ISSUE TITLE
Explorer single click 

### ISSUE THREAD

**Issue by dyavc** [Dyalog/ride#322]
### Describe the issue you are having
user would like a single click to open edit window from WS Explrorer

### Did you connect to an already running interpreter or start the interpreter from RIDE?
on Mac

### How do you reproduce the issue?

Customer said this (about the WS Explorer):  "Also, I’d like to be able to single click items in the list, rather than double click (why should I have to tell my Mac everything twice?)"

### Paste the contents of Help → About (Shift+F1)
Dyalog for Mac of Dec 2017, 16.0.31693,  Ride 4.0.

**Comment by fourier** [comment]
I would suggest to make it "switcheable" according to preferences.
