### ISSUE TITLE
New trace window doesn't always get focus.

### ISSUE THREAD

**Issue by JohnScholes** [Dyalog/ride#324]
### Describe the issue you are having
If a new trace window is a little slow to open, focus is given back to the session window.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Started an interpreter

### How do you reproduce the issue?
First thing in the morning when all Ride's caches have faded away overnight ...
Start the interpreter ...
      )xload dfns
... saved ...
      display 99 <TC>   ⍝ trace this line
If the trace window took a little time to appear, the chances are it won't have the focus.

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.1.2988
  Platform: MacIntel
  Date: 2017-12-14 21:00:41 +0100
  Git commit: b50942479e4d884ad23be5659c1ef7fece907db5
  Preferences:{
    "autocompletion":"0",
    "blinkCursor":"0",
    "colourScheme":"JohnS",
    "colourSchemes":"[{\"name\":\"JohnS\",\"styles\":\"diam=B err=fg:#ff0000,bg:#ffffff,bgo:0.5 idm=bg:#ffffff,bgo:0.5,fg:0 kw=B lnum=bg:f,bgo:1 mod=bg:#e7e1e7,bgo:1,fg:#000000 mtch=bg:c,bgo:0.5 norm=bg:f,bgo:1 ns=fg:8 num=fg:8 quad=fg:8 srch=bg:#0000ff,bgo:0.5 str=fg:#000000 tc=bg:#ffffff,bgo:1,fg:0 zld=fg:8 vtt=bc:aaa\"}]",
    "editWins":"{\"width\":1104,\"height\":633,\"x\":336,\"y\":23,\"ox\":0,\"oy\":0}",
    "editWinsRememberPos":"1",
    "floatOnTop":"1",
    "floating":"1",
    "fold":"0",
    "ilf":"0",
    "indentOnOpen":"0",
    "kbdLocale":"en_US_Mac",
    "lbar":"0",
    "lineNums":"0",
    "pfkeys":"[\"\",\"\",\"\",\"\",\"\",\"wsdiff''<ER>\",\"\",\"\",\"\",\"\",\")reset<ER>)save<ER>\",\"\",\"\"]",
    "sqp":"0",
    "valueTips":"0",
    "zoom":"5"
  }

Interpreter:
  Version: 17.0.32236
  Platform: Mac-64
  Edition: Unicode/64
  Date: Feb 17 2018 at 04:24:06

**Comment by e9gille** [comment]
works as expected on monaco branch, even if monaco editor is exceptionally slow on load the first time.

**Comment by jayfoad** [comment]
@e9gille so can this be closed?

**Comment by e9gille** [comment]
closing this, @JohnScholes can re-open it if still an issue
