### ISSUE TITLE
"List of interpreters" (for Start-Option) should be cached

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/ride#325]
### Describe the issue you are having
When launching Ride with the "Start"-Option, it is always required to retrieve the list of interpreters before it is possible to start one. Would be nice if Ride kept (per IP) a list of the last interpreter that was run there and use that as a default in this input. (So ideally one could just select a config and click "Start" - w/o having to go through "unneccessary dialogs" (in just wanting to restart the interpreter tht was used last time).

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Intending to start one.

### How do you reproduce the issue?
Start Ride.

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.1.2988
  Platform: Win32
  Date: 2017-12-14 21:00:41 +0100
  Git commit: b50942479e4d884ad23be5659c1ef7fece907db5
  Preferences:{

  }

Interpreter:
  Version: 16.0.32270
  Platform: Linux-64
  Edition: Unicode/64
  Date: Feb 21 2018 at 04:09:51

**Comment by e9gille** [comment]
fixed and in master
