### ISSUE TITLE
Disconnecting Ride leaves a Zombie-Interpreter that only consumes CPU

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/ride#326]
### Describe the issue you are having
After starting a session via SSH and disconnecting from it, the interpreter keeps running, but it is not possible to connect to it again and the job seems to have intense CPU-usage.

### How do you reproduce the issue?
- start an interpreter using SSH
- File|Quit
- try to connect to the interpreter again - it will not be possible
-  ps -ef |grep dyalog for CPU-usage

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.1.2988
  Platform: Win32
  Date: 2017-12-14 21:00:41 +0100
  Git commit: b50942479e4d884ad23be5659c1ef7fece907db5
  Preferences:{
    "floating":"1",
    "otherExe":"/opt/mdyalog/16.0/64/unicode/mapl",
    "wse":"1",
    "kbdLocale":"en_US",
    "prefixKey":"<"
  }

Interpreter:
  Version: 16.0.32270
  Platform: Linux-64
  Edition: Unicode/64
  Date: Feb 21 2018 at 04:09:51

**Comment by jayfoad** [comment]
Might be related to #136.

**Comment by e9gille** [comment]
I can't replicate this. If I start an interpreter it is shut down when exiting RIDE.

I did notice the menu File|Quit is no longer working though.

**Comment by e9gille** [comment]
@mbaas2 can you replicate this issue still?

**Comment by mbaas2** [comment]
@e9gille Can't replicate with 4.1.3211 - seems to be fixed!
