### ISSUE TITLE
Mac: swiping between desktops loses edit-window focus

### ISSUE THREAD

**Issue by JohnScholes** [Dyalog/ride#327]
### Describe the issue you are having
With a MacBook it's convenient to use multiple desktops (virtual screens) and to 3-finger-swipe between them. Swiping away and back during an edit returns focus to the session window. This is slightly irritating when I just want to check something in another desktop.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Started an intperpreter

### How do you reproduce the issue?
    )ed foo
edit window focused 
swipe left / swipe right
session window focused

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.1.2988
  Platform: MacIntel
  Date: 2017-12-14 21:00:41 +0100
  Git commit: b50942479e4d884ad23be5659c1ef7fece907db5
  Preferences:{
    "autocompletion":"0",
    "blinkCursor":"0",
    "colourScheme":"JohnS",
    "colourSchemes":"[{\"name\":\"JohnS\",\"styles\":\"diam=B err=fg:#ff0000,bg:#ffffff,bgo:0.5 idm=bg:#ffffff,bgo:0.5,fg:0 kw=B lnum=bg:f,bgo:1 mod=bg:#e7e1e7,bgo:1,fg:#000000 mtch=bg:c,bgo:0.5 norm=bg:f,bgo:1 ns=fg:8 num=fg:8 quad=fg:8 srch=bg:#0000ff,bgo:0.5 str=fg:#000000 tc=bg:#ffffff,bgo:1,fg:0 zld=fg:8 vtt=bc:aaa\"}]",
    "editWins":"{\"width\":1104,\"height\":633,\"x\":336,\"y\":23,\"ox\":0,\"oy\":0}",
    "editWinsRememberPos":"1",
    "floatOnTop":"1",
    "floating":"1",
    "fold":"0",
    "ilf":"0",
    "indentOnOpen":"0",
    "kbdLocale":"en_US_Mac",
    "lbar":"0",
    "lineNums":"0",
    "pfkeys":"[\"\",\"\",\"\",\"\",\"\",\"wsdiff''<ER>\",\"\",\"\",\"\",\"\",\")reset<ER>)save<ER>\",\"\",\"\"]",
    "sqp":"0",
    "valueTips":"0",
    "zoom":"5"
  }

Interpreter:
  Version: 17.0.32332
  Platform: Mac-64
  Edition: Unicode/64
  Date: Feb 27 2018 at 14:14:32

**Comment by e9gille** [comment]
works on monaco branch

**Comment by e9gille** [comment]
closing as fixed in master
