### ISSUE TITLE
Don't close Ride client on disconnect ->Allow reconnect.

### ISSUE THREAD

**Issue by norberturkiewicz** [Dyalog/ride#330]
### Describe the issue you are having
I connect to a remote Linux interpreter from Ride on Windows.  When I kill off the remote interpreter, Ride closes on the client.  It would be nice to have an option for reconnect or at-least select another connection.  

Currently I have to restart the whole Ride app and establish a new session.

**Comment by e9gille** [comment]
added option "Code>Connect on close" in master
