### ISSUE TITLE
The session's "There is no next/previous line" popup is an unnecessary distraction.

### ISSUE THREAD

**Issue by JohnScholes** [Dyalog/ride#331]
### Describe the issue you are having
"Back" or "Forward" keys at either end of the session history pop up a message box, which I have to clear. I prefer the approach taken by the editor with Undo/Redo: at either end of the Undo history the relevant key just becomes "dead" when, IMHO, it is immediately and intuitively clear what's going on.

The session's behaviour is particularly puzzling if the modal "no next line" popup comes up _behind_ an edit window (see issue #279) and so the system appears to hang.

**Comment by e9gille** [comment]
modal messages replaced by toasts in master
