### ISSUE TITLE
Add idiom highlighting

### ISSUE THREAD

**Issue by H0tSauce** [Dyalog/ride#332]
### Describe the issue you are having
In today's [webinar](https://video.dyalog.com/Webinar/?v=8cbPLRAcC7M), I saw  #Adám Brudzewsky enter the expression `{(⊂⍋⍵)⌷⍵}` into the windows IDE. The IDE then automatically highlighted the idiom in yellow. The Windows IDE will highlight any idiom that is recognised by the interpreter.

This seems like a particularly cool feature that I would like to see in RIDE.

**Comment by JohnScholes** [comment]
I think you can already do this in RIDE. Open Preferences->Colours. Select the idiom "{⍵[⍋⍵]}" on line[9], then choose a colour for it.

**Comment by abrudz** [comment]
What threw me off is that you must click Clone before you can set colours.

**Comment by H0tSauce** [comment]
I have the line `{⍵[⍋⍵]} ⋄ global←local←0`. Do I change the number? What are my options?
Note that I am on Linux (Fedora)

**Comment by abrudz** [comment]
Click Clone, then in the "Token type:" selection box, select "idiom", then check "Background" and select yellow. Click OK. You can of course select any combo of foreground, background, transparency, Bold, Italic, and Underline.

**Comment by H0tSauce** [comment]
Thanks, I've got it now
