### ISSUE TITLE
WIBNI user-command help autocompleted?

### ISSUE THREAD

**Issue by JohnScholes** [Dyalog/ride#333]
### Describe the issue you are having
Input starting ]... enjoys autocompletion from the list of user commands but input starting ]?... doesn't.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
N/A

### How do you reproduce the issue?
Ensure Preferences->Code->Autocompletion is checked then
      ]cale[TAB]   ⍝ autocompletes to ]calendar but
      ]?cale[TAB] ⍝ doesn't

**Comment by abrudz** [comment]
This isn't a RIDE issue, rather this is the behaviour in the IDE as well. As a kind of work-around, `]?` allows partial command names, though I agree that the inconsistency is undesirable. Maybe I can look into autocompleting even with questionmarks.

**Comment by johndaintree** [comment]
FWIW I'm really not a fan of that syntax. Any other special cases / oddnesses that you'd like the IDE to know about?

**Comment by mbaas2** [comment]
> Any other special cases / oddnesses that you'd like the IDE to know
about?

Well, now that you mention it...(sorry for jumping in)

)load xxx autocompleted, ]load doesn't. My personal WIBNI would be a hotkey
to trigger autocompletion for filenames :-)

2018-04-03 13:46 GMT+02:00 johndaintree <notifications@github.com>:

**Comment by e9gille** [comment]
hard to change now perhaps, but a standard:
`]group.cmd -h`
would make more sense

**Comment by abrudz** [comment]
How about `]cmd -?` That may be possible as I think modifiers with non-alphanumeric names are forbidden. How would we deal with multi-page help then? `]cmd -??` and `]cmd -???` etc?

**Comment by JohnScholes** [comment]
]foo -?    ⍝ 1st help level
    ]foo -??   ⍝ 2nd help level
...
works for me.

**Comment by jayfoad** [comment]
I've raised Mantis 15730 for the interpreter part of this.

**Comment by abrudz** [comment]
r32861 now allows `]cmd -??`

**Comment by JohnScholes** [comment]
With the new ]cmd -? syntax, this now works for me. 
```
      ]m<Tab> -??     ⍝ displays help for ]map ucmd
```
I'm happy for this issue to be closed.
