### ISSUE TITLE
Programmable Function keys do not work in edit/trace window

### ISSUE THREAD

**Issue by abrudz** [Dyalog/ride#336]
### Describe the issue you are having
Programmable Function keys do not work in edit/trace window, even if they work fine in the session.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Start an interpreter

### How do you reproduce the issue?
Set PF2 to `Foo`
Press <kbd>F2</kbd>
This inserts `Foo` as expected
Press <kbd>Shift</kbd>+<kbd>Enter</kbd> to edit `Foo`
Press <kbd>F2</kbd> to insert `Foo`
Nothing happens

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.1.2988
  Platform: Win32
  Date: 2017-12-14 21:00:41 +0100
  Git commit: b50942479e4d884ad23be5659c1ef7fece907db5
  Preferences:{
    "colourScheme":"Default (1)",
    "colourSchemes":"[{\"name\":\"Default (1)\",\"styles\":\"asgn=fg:00f com=fg:088 dfn=fg:00f diam=fg:00f err=fg:f00 fn=fg:008 idm=fg:008,bg:#ffff00 kw=fg:800 lnum=fg:008,bg:f,bgo:0 mod=bg:e,bgo:1 mtch=bg:ff8,bgo:0.5 norm=bg:f,bgo:1 ns=fg:8 num=fg:8 op1=fg:00f op2=fg:00f par=fg:00f quad=fg:808 sel=bg:48e,bgo:0.5 semi=fg:00f sqbr=fg:00f srch=bg:f80,bgo:0.5 str=fg:088 tc=bg:d,bgo:1 tcpe=bg:c8c8c8,bgo:1 trad=fg:8 var=fg:8 zld=fg:008 scmd=fg:00f ucmd=fg:00f vtt=bg:ff0\"}]",
    "floatOnTop":"1",
    "floating":"1",
    "ime":"0",
    "indentComments":"1",
    "kbdLocale":"en_US",
    "keys":"{\"AC\":[\"Ctrl-,\"],\"AO\":[\"Ctrl-'\"],\"BP\":[\"Ctrl-.\"],\"DO\":[\"Ctrl-;\"],\"FX\":[\"Ctrl-S\"],\"MA\":[\"Ctrl-G\"],\"NEW\":[],\"NX\":[\"Ctrl-N\"],\"PV\":[\"Ctrl-P\"],\"RP\":[\"Ctrl-R\"]}",
    "lbarOrder":"← +-×÷*⍟⌹○!? |⌈⌊⊥⊤⊣⊢ =≠≤<>≥≡≢ ∨∧⍲⍱ ↑↓⊂⊃⊆⌷⍋⍒ ⍳⍸∊⍷∪∩~ /\\⌿⍀ ,⍪⍴⌽⊖⍉ ¨⍨⍣.∘⍤@ ⍞⎕⍠⌸⌺⌶⍎⍕ ⋄⍝→⍵⍺∇⍬& ¯",
    "menu":"# see below for syntax\n\nDyalog                          {mac}\n  About Dyalog             =ABT\n  -\n  Preferences              =PRF\n  -                            \n  &Quit                    =QIT\n&File                           {!browser}\n  New &Session             =NEW\n  &Connect...              =CNC\n  -                             {!mac}\n  &Quit                    =QIT {!mac}\n&Edit\n  Undo                     =UND {!browser}\n  Redo                     =RDO {!browser}\n  -                             {!browser}\n  Cut                      =CT  {!browser}\n  Copy                     =CP  {!browser}\n  Paste                    =PT  {!browser}\n  Select All               =SA  {mac}\n  -                             {!mac&&!browser}\n  Preferences              =PRF {!mac}\n&View\n  Show Language Bar        =LBR\n  Show Workspace Explorer  =WSE\n  Show Debug               =DBG\n  Floating Edit Windows    =FLT\n  Editors on Top           =TOP {!browser}\n  Line Wrapping in Session =WRP\n  -                             {!browser}\n  Increase Font Size       =ZMI {!browser}\n  Decrease Font Size       =ZMO {!browser}\n  Reset Font Size          =ZMR {!browser}\n  -                             {!browser}\n  Toggle Full Screen            {!browser}\n&Window\n  Close All Windows        =CAW\n&Action\n  Edit                     =ED\n  Trace                    =TC\n  Weak Interrupt           =WI\n  Strong Interrupt         =SI\n&Help\n  Dyalog Help              =http://help.dyalog.com/\n  Documentation Centre     =http://dyalog.com/documentation.htm\n  &Idioms                  =http://miserver.dyalog.com/Examples/Applications/Idiom_Search.mipage?nowrapper=1\n  -\n  Dyalog Website           =http://dyalog.com/\n  MyDyalog                 =https://my.dyalog.com/\n  -\n  Dyalog Forum             =http://www.dyalog.com/forum\n  -                             {!mac}\n  About                    =ABT {!mac}\n\n# Syntax:\n#   &x   access key, alt+x\n#   =CMD command code; some are special:\n#          LBR FLT WRP TOP WSE render as checkboxes\n#   =http://example.com/  open a URL\n#   {}   conditional display, a boolean expression\n#          operators: && || ! ( )\n#          variables: browser mac win\n#   -    separator (when alone)\n#   #    comment\n\n# The =PRF (\"Preferences\") menu item must be present.",
    "otherExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 17.0 Unicode\\dyalog.exe",
    "pfkeys":"[\"\",\"\",\"Foo\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\"]",
    "selectedExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 16.0 Unicode\\dyalog.exe",
    "squiggleTips":"1",
    "title":"RIDE {RIDE_VER} - {WSID} {VER}",
    "zoom":"4"
  }

Interpreter:
  Version: unknown
  Platform: unknown
  Edition: unknown
  Date: unknown

**Comment by jayfoad** [comment]
Seems to work for me (on a Windows 7 VM).

**Comment by abrudz** [comment]
Fixed in Monaco branch.
