### ISSUE TITLE
Syntax highlighting feature: wavy underline

### ISSUE THREAD

**Issue by jayfoad** [Dyalog/ride#337]
This is a feature request. The syntax highlighting configuration system allows you to use bold, italic and underline. Could we also have "wavy underline" as an option? I think it would be nice to be able to use it to indicate errors. Lots of word processors and web browsers seem to do this.

I think you can implement it in CSS with text-decoration-style=wavy: https://www.w3.org/TR/css-text-decor-3/#text-decoration-style

**Comment by abrudz** [comment]
Should work in Chromium, but accessing RIDE through a Edge or IE would not render correctly: https://caniuse.com/#search=text-decoration-style

**Comment by e9gille** [comment]
Unfortunately the monaco editor is very limited in this aspect. It can't be done easily.

**Comment by jayfoad** [comment]
OK. I humbly withdraw the request.
