### ISSUE TITLE
Font size in value tips should match font size in session

### ISSUE THREAD

**Issue by jayfoad** [Dyalog/ride#34]

**Comment by FionaDyalog** [comment]
and the language bar tool tips...
email to RIDE 06-07-17: "Is it possible to decrease the size of the text in the language bar tooltips? I can decrease the font size in the Session but can’t work out how to do it in the tooltips – I would like to know for the documentation."
response from Callum 07-07-17: "Currently the font size for value tips is not modifiable."

**Comment by flouc001** [comment]
@jayfoad @FionaDyalog fix in place in branch iss34, please test and confirm it behaves as expected.

**Comment by jayfoad** [comment]
Value tips look good to me! Are you planning to tackle #146 at the same time?

**Comment by flouc001** [comment]
Looking into #146 separately but it is next on the list.
