### ISSUE TITLE
Abandon customisable menus?

### ISSUE THREAD

**Issue by jayfoad** [Dyalog/ride#340]
I think we should consider abandoning the system that lets you customise RIDE's menus. Advantages:
* It'll simplify the source code.
* At the moment, in order to put something like "Show Language Bar" on the menu, you are obliged to create a command code (like LBR) for it. This is (a) extra work and (b) means it pops up in Preferences->Shortcuts where the user can assign a keystroke to it, even if it doesn't make much sense to _have_ a keyboard shortcut for it. This means that developers tend to put things in Preferences->Code instead of on a menu item, _just_ because it's less work.
* I'd like to have menus on the Connect page, being a subset of the full set of menus (e.g. maybe just File->Quit and Help->About). To do this properly with the current customisable system we'd have to come up with and implement some syntax to say which menu items appear when you're on the Connect page.

**Comment by abrudz** [comment]
I think it is nice to have commands for everything. There are people who like using keyboard shortcuts for most tasks.

Allowing customisation of the menus makes it easy to use alternative languages (like BUILDSE allows).

I find it really valuable to be able to to have "links" in the menu, e.g. to open the idiom library (#65) or other APL-related webpages.

**Comment by mbaas2** [comment]
+1 ;-)


Adám Brudzewsky <notifications@github.com> schrieb am Mi. 18. Apr. 2018 um
11:25:
