### ISSUE TITLE
Replace keyboard icon with a preferences icon?

### ISSUE THREAD

**Issue by jayfoad** [Dyalog/ride#341]
The current keyboard icon (at the right of the language bar) seems to serve two purposes:
1. Hovering over it gives you a cheat sheet of a few keyboard shortcuts
2. Clicking on it takes you to the Preferences dialog -- but not necessarily to the Layout pane!

I suggest abandoning (1) because showing just a few shortcuts doesn't seem very useful to me.

As for (2) I suggest replacing the keyboard icon with a "gear wheel" or other "settings" icon, so that it makes more sense for it to take you to (any pane on) the Preferences dialog.

**Comment by e9gille** [comment]
done as suggested, now in master branch.
