### ISSUE TITLE
Behavior under PF-key control is inconsistent with manual control

### ISSUE THREAD

**Issue by abrudz** [Dyalog/ride#342]
### Describe the issue you are having
I'm trying to get the behaviour corresponding to `<BP><RM><TC><BP>` so that I can be tracing in a function, click on a line further down, and run until there. It works by setting a breakpoint (stop) there, resume execution, then clear the break point. Doing this manually using those exact four commands works fine. But if put on an F-key, it looks as if `<TC>` is pressed twice and the final `<BP>` isn't being pressed.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Start an interpreter

### How do you reproduce the issue?
Preferences > Shortcuts:
PF5: `<BP>`
PF6: `<RM>`
PF7: `<TC>`
PF8 `<BP>`
PF10: `<BP><RM><TC><BP>`

    ⎕FX'f',⎕D

Now type `f` and trace into that. Click on the line with a `7` on it and press <kbd>F5</kbd><kbd>F6</kbd><kbd>F7</kbd><kbd>F8</kbd>. This works as expected.

Now press <kbd>Esc</kbd> and type `f` and trace into it again. This time click the line with a `7` and press <kbd>F10</kbd>. The tracer has gone one line too far, and the stop bit was not cleared.

### Paste the contents of Help → About (Shift+F1)
```
IDE:
  Version: 4.1.3130
  Platform: Win32
  Date: 2018-04-18 10:24:09 +0200
  Git commit: 38a8a2347ec732fd79e0b486627408a5f793dd80
  Preferences:{
    "colourScheme":"Francisco Goya",
    "kbdLocale":"en_US",
    "lbarOrder":"←+ -  × ÷*⍟⌹○!?|⌈⌊⊥⊤⊣⊢=≠≤<>≥≡≢∨∧⍲⍱↑↓⊂⊃⊆⌷⍋⍒ ⍳⍸∊⍷∪∩~ /\\⌿⍀ ,⍪⍴⌽⊖⍉ ¨⍨⍣.∘⍤@ ⍞⎕⍠⌸⌺⌶⍎⍕ ⋄⍝→⍵⍺∇& ¯ ⍬",
    "otherExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 17.0 Unicode\\dyalog.exe",
    "pfkeys":"[\"\",\"\",\"\",\"\",\"\",\"<BP>\",\"<RM>\",\"<TC>\",\"<BP>\",\"\",\"<BP><RM><TC><BP>\",\"\",\"\"]",
    "wse":"1",
    "zoom":"1",
    "lineNums":"0"
  }

Interpreter:
  Version: 17.0.32776
  Platform: Windows-64
  Edition: Unicode/64
  Date: Apr  9 2018 at 16:10:15
```

**Comment by e9gille** [comment]
I haven't tested this in ODE, but in your PF10 all commands are sent to the interpreter more or less at the same time. In RIDE the TC command is different depending on which window it is issued in.

When you execute PF10 it fires all the commands in the context of the editor window, so the TC is issuing a step into request which is moving the cursor down from 7 to 8. 

When run sequentially with PF5-PF8, the TC is fired in the session as that is where the focus is moved to on error. TC in session on a blank line moves focus to the tracer window, after which the stop is removed.

In actual fact, the PF10 does remove the stop, but the interpreter manages to receive it just after it sends an OpenWindow command to RIDE listing the stop that existed when it hit the stop in the first place. this leaves the RIDE editor with a stop marker. (you can confirm this by closing and re-opening f at which point the stop marker disappears)

**Comment by abrudz** [comment]
I'm not sure I fully understand, but it sounds to me like the issue could be fixed by artificially introducing a slight delay in between the issuing of each command.

**Comment by e9gille** [comment]
in your example function the lines take no time to execute, so a delay may fix the problem. In the general case it may take several seconds before you reach the stop marker. The TC command would have to be issued after the stop has been reached to work as you expect it.

**Comment by abrudz** [comment]
After issuing a command, RIDE shouldn't issue the next one until the interpreter has relinquished control and is awaiting user input.

**Comment by e9gille** [comment]
You make it sound easy 😊. Yes, we could check the prompt type after a short delay to see if it has been changed and hold until it looks safe to carry on. That would solve this particular chain of commands.

**Comment by e9gille** [comment]
Next you'll ask me why issuing an interrupt from a function key doesn't work 😉.
Need to sleep on it, good night.
