### ISSUE TITLE
APL symbols dont get popups with description in editor

### ISSUE THREAD

**Issue by fourier** [Dyalog/ride#348]
### Describe the issue you are having
Ride Issue, ride commit id 98cdb12

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Start an interpreter

### How do you reproduce the issue?
1. Set Preferences->Code->Contextual help->Show tips for glyphs to on
2. Open any function in editor
3. Navigate the mouse over any APL glyph -> nothing happens

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.1.3151
  Platform: Linux x86_64
  Date: 2018-04-20 17:00:22 +0200
  Git commit: 98cdb1278456012d2cc257831a253b58901a1a1a
  Preferences:{
    "blinkCursor":"0",
    "blockCursor":"1",
    "colourScheme":"Francisco Goya",
    "cursorBlinking":"solid",
    "kbdLocale":"en_US",
    "keys":"{\"BK\":[\"Ctrl-Up\"],\"FD\":[\"Ctrl-Down\"],\"LBR\":[\"F10\"],\"PF10\":[],\"TL\":[]}",
    "otherExe":"/opt/mdyalog/16.0/64/unicode/mapl",
    "selectionHighlight":"1",
    "snippetSuggestions":"1",
    "squiggleTips":"1",
    "zoom":"5"
  }

Interpreter:
  Version: 16.0.32456
  Platform: Linux-64
  Edition: Unicode/64
  Date: Mar 13 2018 at 03:31:46

**Comment by jayfoad** [comment]
@e9gille On Linux if I hover over a glyph it seems to give me a popup for the glyph to the left. (Perhaps my cursor is _just_ left of centre on the ⍴?)

![screenshot from 2018-04-24 10-30-36](https://user-images.githubusercontent.com/108316/39178901-cfd6580c-47aa-11e8-9987-c8583aca1f2a.png)

**Comment by e9gille** [comment]
OK, so you noticed as well :)

The hover provider seems to get the closest edge rather than the character position. I'll see if I can find a workaround.

**Comment by fourier** [comment]
Thanks, works now.
