### ISSUE TITLE
Cmd+C with an empty selection

### ISSUE THREAD

**Issue by jayfoad** [Dyalog/ride#349]
### Describe the issue you are having
John Scholes reported that on the Mac, with the cursor on a line in the session containing some text, but no text selected...
> if I Cmd+c it seems to copy the whole of the line, plus its newline, to the clipboard. I believe that the Mac convention is that, if I hit Cmd+c with no text explicitly selected, there should be an error sound and the clipboard should remain unchanged.

### Paste the contents of Help → About (Shift+F1)
```
IDE:
  Version: 4.1.1
  Platform: MacIntel
  Date: 2018-04-21 19:32:14 +0200
  Git commit: c7743a6f265de9500a682e8faca21321c744af87
  Preferences:{
    "kbdLocale":"en_US_Mac",
    "title":"{WSID} ",
    "colourSchemes":"[{\"name\":\"Default (1)\",\"theme\":\"light\",\"styles\":\"asgn=fg:00f com=fg:088 dfn=fg:00f diam=fg:00f err=fg:f00 fn=fg:008 idm=fg:008 kw=fg:800 lnum=fg:008,bg:f,bgo:0 mod=bg:7,bgo:0.25 mtch=bg:ff8,bgo:0.5 norm=bg:f,bgo:1 ns=fg:8 num=fg:8 op1=fg:00f op2=fg:00f par=fg:00f quad=fg:808 sel=bg:48e,bgo:0.5 semi=fg:00f sqbr=fg:00f srch=bg:f80,bgo:0.5 str=fg:088 tc=bg:d,bgo:1 tcpe=bg:c8c8c8,bgo:1 trad=fg:8 var=fg:8 zld=fg:008 scmd=fg:00f ucmd=fg:00f vtt=bg:ff0\"}]",
    "colourScheme":"Default (1)"
  }

Interpreter:
  Version: 17.0.32914
  Platform: Mac-64
  Edition: Unicode/64
  Date: Apr 23 2018 at 01:51:48
```

**Comment by e9gille** [comment]
@JohnScholes no error sound is issued, but I have turned off the feature that copies the current line on empty selection. Feel free to re-open if you need the noise as well.
