### ISSUE TITLE
Help for Environment variables is misleading

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/ride#350]
### Describe the issue you are having
The help text seems to suggest that you can have comma-separated names and values, but in fact you need to put one pair of names and values on each line. If you use commas, you get no error message, but also don't get the vars set to what you want.

### Paste the contents of Help → About (Shift+F1)
```
(Paste here)
```

**Comment by mkromberg** [comment]
Sorry, should have been more specific, I meant the "example", which reads:
For example: MAXWS=1G, WSPATH=., HISTORY_SIZE=1000, ...

**Comment by jayfoad** [comment]
I don't have strong opinions, but how about putting each example on a separate line:

![screenshot from 2018-04-24 15-05-07](https://user-images.githubusercontent.com/108316/39192423-0c33787c-47d1-11e8-9dae-8d8146c6131f.png)

**Comment by e9gille** [comment]
implemented @jayfoad 's suggestion
