### ISSUE TITLE
WSE: double clicking on ⎕SE.SALT should edit it

### ISSUE THREAD

**Issue by jayfoad** [Dyalog/ride#354]
### Describe the issue you are having

Open the workspace explorer and expand ⎕SE, so you can see SALT. SALT should be both expandable (because it's a namespace with members) and editable (because it's scripted).

Clicking on the plus expands it (good). Double clicking on it also expands it, and apparently there is no way to edit it.

I would suggest that double clicking should edit it instead of expanding it.

### Paste the contents of Help → About (Shift+F1)
```
IDE:
  Version: 4.1.3171
  Platform: Linux x86_64
  Date: 2018-04-25 09:42:12 +0200
  Git commit: 6e614349fc3936835adfe25c5e59fccd5373424b
  Preferences:{
    "wse":"1"
  }

Interpreter:
  Version: 17.0.32920
  Platform: Linux-64
  Edition: Unicode/64
  Date: Apr 24 2018 at 14:54:58
```

**Comment by e9gille** [comment]
With SALT I think it should be no problem as it is a class (nc 9.4) but what about SALTUtils (nc 9.1). RIDE has no way of knowing it is editable.

**Comment by jayfoad** [comment]
Ah, I see now that this changed for #266 (clicking on an unscripted namespace opens a useless edit window). I don't think RIDE can tell whether editing a thing will give you a "useless" edit window or not. You can't tell just from the nameclass.

**Comment by e9gille** [comment]
So what should we do?

**Comment by jayfoad** [comment]
Await further instructions :-) I'll think about it. _Perhaps_ the ReplyTreeList message should include information about whether each item is "scripted" or not.

**Comment by jayfoad** [comment]
How about: single click to expand, double click to edit? (See also #322.)

Failing that I'm tempted to revert the fix for #300, since I think the cure (which caused this bug) was worse than the disease (getting useless but harmless edit windows).

**Comment by e9gille** [comment]
> How about: single click to expand, double click to edit? (See also #322.)

So, the opposite of what the user requested?
ODE is single click = edit, double click = toggle. Unless good reason not to I suggest we change to match that.

**Comment by jayfoad** [comment]
> ODE is single click = edit, double click = toggle. Unless good reason not to I suggest we change to match that.

Sure, good idea.
