### ISSUE TITLE
"Editors on top" doesn't work

### ISSUE THREAD

**Issue by DyalogRichard** [Dyalog/ride#355]
### Describe the issue you are having

The Editors on Top option (assuming it means "keep edit windows on top of the main IDE window") doesn't seem to work.

Aside: could the option be greyed out when Floating Edit Windows is not set?

### Did you connect to an already running interpreter or start the interpreter from RIDE?

Connect

### How do you reproduce the issue?

Set:
View->Floating Edit Windows
View->Editors on Top
Bring up an edit or trace window
Type in the session - edit/trace window goes behind IDE window

### Paste the contents of Help → About (Shift+F1)
```
IDE:
  Version: 4.1.3170
  Platform: Linux x86_64
  Date: 2018-04-25 00:24:55 +0200
  Git commit: 9cd0c566b20f8eaa1abfb061d37a2fdf6d3911ef
  Preferences:{
    "dbg":"1",
    "floatOnTop":"1",
    "floating":"1",
    "kbdLocale":"en_GB",
    "lbarOrder":"← +-×÷*⍟⌹○!? |⌈⌊⊥⊤⊣⊢ =≠≤<>≥≡≢ ∨∧⍲⍱ ↑↓⊂⊃⊆⌷⍋⍒ ⍳⍸∊⍷∩~∪ /\\⌿⍀ ,⍪⍴⌽⊖⍉ ¨⍨⍣.∘⍤@ ⍞⎕⍠⌸⌺⌶⍎⍕ ⋄⍝→⍵⍺∇& ¯⍬ ",
    "lineNums":"0",
    "wse":"1"
  }

Interpreter:
  Version: unknown
  Platform: unknown
  Edition: unknown
  Date: unknown

```

**Comment by e9gille** [comment]
Yes, this seems to be a problem on the Linux version. I'll log an error on the electron project.

**Comment by e9gille** [comment]
found a workaround, so this should now work on Linux as well

**Comment by e9gille** [comment]
> Aside: could the option be greyed out when Floating Edit Windows is not set?

Sorry, I missed that comment. I can look into it, but I wonder if we should keep those options in the menu at all. Should we remove both "Editors on top" and "Floating Edit Windows" and add the "Editors on Top" option to the Preferences>Windows?
