### ISSUE TITLE
Cannot scroll back when connecting to running interpreter

### ISSUE THREAD

**Issue by DyalogRichard** [Dyalog/ride#356]
### Describe the issue you are having

When I connect to a running interpreter the RIDE IDE session window comes up blank. It would be nice if I could see what was in the session window, scroll back in its history etc. There is effectively no session history when connecting to a running interpreter.

(Note: any open edit/trace windows do come up and are populated.)

### Did you connect to an already running interpreter or start the interpreter from RIDE?

Connect

### How do you reproduce the issue?

Connect to a running interpreter.

### Paste the contents of Help → About (Shift+F1)
```
IDE:
  Version: 4.1.3170
  Platform: Linux x86_64
  Date: 2018-04-25 00:24:55 +0200
  Git commit: 9cd0c566b20f8eaa1abfb061d37a2fdf6d3911ef
  Preferences:{
    "dbg":"1",
    "floatOnTop":"1",
    "floating":"1",
    "kbdLocale":"en_GB",
    "lbarOrder":"← +-×÷*⍟⌹○!? |⌈⌊⊥⊤⊣⊢ =≠≤<>≥≡≢ ∨∧⍲⍱ ↑↓⊂⊃⊆⌷⍋⍒ ⍳⍸∊⍷∩~∪ /\\⌿⍀ ,⍪⍴⌽⊖⍉ ¨⍨⍣.∘⍤@ ⍞⎕⍠⌸⌺⌶⍎⍕ ⋄⍝→⍵⍺∇& ¯⍬ ",
    "lineNums":"0",
    "wse":"1"
  }

Interpreter:
  Version: unknown
  Platform: unknown
  Edition: unknown
  Date: unknown

```

**Comment by e9gille** [comment]
I've tested connecting to both v16 and v17 running interpreters and do get the session log. Can you check the log (Ctrl+F12) once you've connected to see if the protocol messages are there (ReplyGetLog)?

**Comment by DyalogRichard** [comment]
Immediately after connection this is the entire log:

1815 send SupportedProtocols=2
1815 send UsingProtocol=2
1815 send ["Identify",{"identity":1}]
1815 send ["Connect",{"remoteId":2}]
1815 send ["GetWindowLayout",{}]
2138 recv SupportedProtocols=2
2138 recv UsingProtocol=2
2138 recv ["Identify",{"Port":0,"IPAddress":"","Vendor":"Dyalog Limited","Language":"APL","version":"17.0.32919","Machine":"richard-VirtualBox","arch":"Unicode/64","Project":"CLEAR WS","Process":"","User":"richard","pid":23533,"token":"","date":"Created: Apr 24 2018 at 15:24:55","platform":"Linux-64"}]
2139 send ["SetPW",{"pw":42}]
2140 recv ["UpdateDisplayName",{"displayName":"CLEAR WS"}]
2140 recv ["SetPromptType",{"type":1}]
2226 send ["SetPW",{"pw":189}]
2609 send ["TreeList",{"nodeId":0}]
2674 recv ["ReplyTreeList",{"classes":[-1,-1],"err":"","names":["#","⎕SE"],"nodeId":0,"nodeIds":[2,1]}]
2729 send ["SetPW",{"pw":136}]
2739 send ["GetSIStack",{}]
2740 send ["GetThreads",{}]
2768 recv ["ReplyGetSIStack",{"stack":[],"tid":0}]
2769 recv ["ReplyGetThreads",{"threads":[{"description":"Tid:0","state":"Session","tid":0,"flags":"Normal","Treq":"","Location":"(no stack)"}]}]

**Comment by e9gille** [comment]
@DyalogRichard could you test connecting to an older version of the interpreter? I have 17.0.32866 and get the ReplyGetLog message. If it is OK when you connect to an older interpreter then it is possibly a regression in the interpreter (ask @johndaintree )

**Comment by DyalogRichard** [comment]
Got to the bottom of it, with Jay's help. Executive summary - it's an interpreter issue.

Construction of the ReplyGetLog message failed, because there was an invalid Unicode character in the (very long) session history. This really was in the session history, from when something I was working on spit out a DMX message containing junk.

We need to think about how to address it, but it's not a RIDE issue.

**Comment by DyalogRichard** [comment]
Interpreter issue is Mantis 15771 (http://mantis.dyalog.com/view.php?id=15771).

The interpreter will now translate invalid characters which cannot be UTF-8 encoded to 0xFFFD (REPLACEMENT CHARACTER - https://www.fileformat.info/info/unicode/char/fffd/index.htm). RIDE already displays invalid (but encodable) Unicode characters it receives this way.
