### ISSUE TITLE
First character entered into session appears in a different place to the cursor

### ISSUE THREAD

**Issue by DyalogRichard** [Dyalog/ride#357]
### Describe the issue you are having

When you connect to a running interpreter the session window cursor is flashing in column 7 of the first line (regardless of where it in the session connected to). However, any text entered appears in column 1.

Note; may be dependent on issue #356.

### Did you connect to an already running interpreter or start the interpreter from RIDE?

Connect

### How do you reproduce the issue?

Connect; observe cursor position; type something.

### Paste the contents of Help → About (Shift+F1)
```
IDE:
  Version: 4.1.3170
  Platform: Linux x86_64
  Date: 2018-04-25 00:24:55 +0200
  Git commit: 9cd0c566b20f8eaa1abfb061d37a2fdf6d3911ef
  Preferences:{
    "dbg":"1",
    "floatOnTop":"1",
    "floating":"1",
    "kbdLocale":"en_GB",
    "lbarOrder":"← +-×÷*⍟⌹○!? |⌈⌊⊥⊤⊣⊢ =≠≤<>≥≡≢ ∨∧⍲⍱ ↑↓⊂⊃⊆⌷⍋⍒ ⍳⍸∊⍷∩~∪ /\\⌿⍀ ,⍪⍴⌽⊖⍉ ¨⍨⍣.∘⍤@ ⍞⎕⍠⌸⌺⌶⍎⍕ ⋄⍝→⍵⍺∇& ¯⍬ ",
    "lineNums":"0",
    "wse":"1"
  }

Interpreter:
  Version: unknown
  Platform: unknown
  Edition: unknown
  Date: unknown

```

**Comment by DyalogRichard** [comment]
As suspected, with a fix for the interpreter which was behind the problem reported in in issue 356, this is no longer really noticeable. You can still experience it this way (on Linux, at least):

Press CTRL-I (not Tab). The left hand part of the line up to the cursor turns blue leaving the cursor wherever it was. Then press a regular character key and the character appears at the beginning of the line, not where the cursor was.

**Comment by jayfoad** [comment]
Ctrl-I is a Monaco keystroke for "select current line", so I think that's working correctly -- a regular key stroke replaces the current selection.
