### ISSUE TITLE
Text appears within scroll bars

### ISSUE THREAD

**Issue by DyalogRichard** [Dyalog/ride#359]
### Describe the issue you are having

The session window scroll bar can show session text in it/

### Did you connect to an already running interpreter or start the interpreter from RIDE?

Connect.

### How do you reproduce the issue?

Enter an expression such as ⍳100 . The output contains line breaks exactly calculated so that each line is the full width of the session window pane, which is nice. Then narrow the session window pane such that some of the text would be obscured - that which the scroll bar is now over remains visible within the scroll bar.

### Paste the contents of Help → About (Shift+F1)
```
IDE:
  Version: 4.1.3170
  Platform: Linux x86_64
  Date: 2018-04-25 00:24:55 +0200
  Git commit: 9cd0c566b20f8eaa1abfb061d37a2fdf6d3911ef
  Preferences:{
    "dbg":"1",
    "floatOnTop":"1",
    "floating":"1",
    "kbdLocale":"en_GB",
    "lbarOrder":"← +-×÷*⍟⌹○!? |⌈⌊⊥⊤⊣⊢ =≠≤<>≥≡≢ ∨∧⍲⍱ ↑↓⊂⊃⊆⌷⍋⍒ ⍳⍸∊⍷∩~∪ /\\⌿⍀ ,⍪⍴⌽⊖⍉ ¨⍨⍣.∘⍤@ ⍞⎕⍠⌸⌺⌶⍎⍕ ⋄⍝→⍵⍺∇& ¯⍬ ",
    "lineNums":"0",
    "wse":"1"
  }

Interpreter:
  Version: unknown
  Platform: unknown
  Edition: unknown
  Date: unknown

```

**Comment by jayfoad** [comment]
I think that's intentional. The scroll bar is a transparent overlay over the text:

![screenshot from 2018-04-25 15-50-27](https://user-images.githubusercontent.com/108316/39253776-8efef4f0-48a0-11e8-88b2-a6cf429aa1c5.png)

**Comment by DyalogRichard** [comment]
Ok, if it's by design it's not a bug.

It seems a peculiar design to me, though - it was certainly unexpected.

**Comment by jayfoad** [comment]
You can also see it in action here in a bog standard Monaco editor (see the second demo, Diff Editor): https://microsoft.github.io/monaco-editor/
