### ISSUE TITLE
File->New Session  produces phantom edit window

### ISSUE THREAD

**Issue by JohnScholes** [Dyalog/ride#365]
### Describe the issue you are having
After using the editor, selecting menu option File->New Session produces an error dialog and then leaves open an empty edit window, which can't be removed.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Started from Ride

### How do you reproduce the issue?
    )ed phantom
    <Escape> to close edit window
    File->New Session
    <Enter> to dismiss "The current session is remote ..." error message
    edit window can't be closed.
### Paste the contents of Help → About (Shift+F1)
```
IDE:
  Version: 4.1.3187
  Platform: MacIntel
  Date: 2018-04-26 16:06:28 +0200
  Git commit: 42ceb995e920b300bb2257a6a1d7023a07c009ec
  Preferences:{
    "autocompletion":"shell",
    "breakPts":"0",
    "colourScheme":"Zen",
    "colourSchemes":"[{\"name\":\"Zen\",\"theme\":\"light\",\"styles\":\"norm=bg:fdfefe,bgo:1 lnum=fg:0 err=fg:#ff0000 sqbr=fg:0 mtch=fg:#000000,bg:#c0c0c0\"}]",
    "editWins":"{\"width\":1100,\"height\":600,\"x\":338,\"y\":23,\"ox\":0,\"oy\":0}",
    "editWinsRememberPos":"1",
    "floatOnTop":"1",
    "floating":"1",
    "fold":"0",
    "indentOnOpen":"0",
    "kbdLocale":"en_US_Mac",
    "lbar":"0",
    "lineNums":"0",
    "minimapRenderCharacters":"0",
    "pfkeys":"[\"\",\"\",\"\",\"\",\"\",\"wsdiff''<ER>\",\"\",\"\",\"\",\"\",\")reset<ER>)save<ER>\",\"\",\"\"]",
    "showEditorToolbar":"0",
    "sqp":"0",
    "valueTips":"0",
    "zoom":"5"
  }

Interpreter:
  Version: unknown
  Platform: unknown
  Edition: unknown
  Date: unknown
```

**Comment by e9gille** [comment]
Thanks John!
This helped me identify the cause of another symptom reported by @jayfoad.
The floating windows re-installed the menu, so when you run the "New Session" from the menu it triggered in the hidden floating window instead of the main app.
