### ISSUE TITLE
Language bar pop-up text is truncated

### ISSUE THREAD

**Issue by DyalogRichard** [Dyalog/ride#371]
### Describe the issue you are having

The language bar pop-up boxes appear to be constrained to the size of the main IDE window, and don't have scroll bars. If the text does not fit into the box it is truncated without indication this has happened, resulting in e.g. examples that make no sense.

### Did you connect to an already running interpreter or start the interpreter from RIDE?

Connect

### How do you reproduce the issue?

Hover over transpose in the language bar.

### Paste the contents of Help → About (Shift+F1)
```
IDE:
  Version: 4.1.3200
  Platform: Linux x86_64
  Date: 2018-04-28 00:31:45 +0200
  Git commit: c6f3b252f91fabb7cb936fc486b4275af7e22fc0
  Preferences:{
    "dbg":"1",
    "floatOnTop":"1",
    "floating":"1",
    "kbdLocale":"en_GB",
    "lbarOrder":"← +-×÷*⍟⌹○!? |⌈⌊⊥⊤⊣⊢ =≠≤<>≥≡≢ ∨∧⍲⍱ ↑↓⊂⊃⊆⌷⍋⍒ ⍳⍸∊⍷∩~∪ /\\⌿⍀ ,⍪⍴⌽⊖⍉ ¨⍨⍣.∘⍤@ ⍞⎕⍠⌸⌺⌶⍎⍕ ⋄⍝→⍵⍺∇& ¯⍬ ",
    "lineNums":"0",
    "wse":"1"
  }

Interpreter:
  Version: 17.0.32941
  Platform: Linux-64
  Edition: Unicode/64
  Date: Apr 26 2018 at 14:38:44

```

**Comment by abrudz** [comment]
![image](https://user-images.githubusercontent.com/10961427/39420222-7d35d50e-4c5b-11e8-8577-ff4d643faf9b.png)
