### ISSUE TITLE
⎕PW ⍴ ⎕A spills over slightly

### ISSUE THREAD

**Issue by JohnScholes** [Dyalog/ride#372]
### Describe the issue you are having
Using exactly the whole of the print-width cause a horizontal scroll-bar to appear at the bottom of the session. This is unwelcome if you're using ]rows on -style=cut.

### How do you reproduce the issue?
      ⎕PW ⍴ ⎕A
ABCDE...

The output of the final char on the right causes a horizontal scroll bar to appear.

**Comment by e9gille** [comment]
I'll take a look at changing the monaco internal padding, but a quick fix is to enable `View>Line Wrapping in Session`. With wrapping enabled, monaco doesn't add extra padding to the right. As the PW is set to reflect the exact character width available, it should therefore not wrap anything in the session anyway. The net effect is that the horizontal scrollbar disappears.

**Comment by JohnScholes** [comment]
The View->Line Wrapping trick works a treat. Thank you.
