### ISSUE TITLE
Nitpick: telephone number format

### ISSUE THREAD

**Issue by DyalogRichard** [Dyalog/ride#374]
### Describe the issue you are having

The Help->About box has +44 (0)1256 830030 as the telephone number. This is not the correct format.

Note: the ODE does the same.

The correct format is:

National: (01256) 830030
International: +44 1256 830030

Official standard: https://www.itu.int/rec/T-REC-E.123/en - see especially 7.2 "The ( ) should not be used in an international number".
Wikipedia: https://en.wikipedia.org/wiki/UK_telephone_code_misconceptions#International_notation_of_UK_numbers
Blog post: https://www.revk.uk/2009/09/it-is-not-44-0207-123-4567.html

### How do you reproduce the issue?
Open Help -> About

### Paste the contents of Help → About (Shift+F1)
```
IDE:
  Version: 4.1.3200
  Platform: Linux x86_64
  Date: 2018-04-28 00:31:45 +0200
  Git commit: c6f3b252f91fabb7cb936fc486b4275af7e22fc0
  Preferences:{
    "kbdLocale":"en_GB",
    "colourSchemes":"[{\"name\":\"Factory default\",\"theme\":\"light\",\"styles\":\"asgn=fg:00f com=fg:088 dfn=fg:00f diam=fg:00f err=fg:f00 fn=fg:008 idm=fg:008 kw=fg:800 lnum=fg:008,bg:f,bgo:0 mod=bg:7,bgo:0.25 mtch=bg:ff8,bgo:0.5 norm=bg:f,bgo:1 ns=fg:8 num=fg:8 op1=fg:00f op2=fg:00f par=fg:00f quad=fg:808 sel=bg:48e,bgo:0.5 semi=fg:00f sqbr=fg:00f srch=bg:f80,bgo:0.5 str=fg:088 tc=bg:d,bgo:1 tcpe=bg:c8c8c8,bgo:1 trad=fg:8 var=fg:8 zld=fg:008 scmd=fg:00f ucmd=fg:00f vtt=bg:ff0 ca=bg:828282,bgo:1,fg:0f0 cm=bg:0,bgo:1,fg:0f0 cv=bg:f,bgo:1,fg:0 cvv=bg:0,bgo:1,fg:0ff ma=bg:828282,bgo:1,fg:0ff na=bg:828282,bgo:1,fg:f qor=bg:f00,bgo:1,fg:f\"}]",
    "editWinsRememberPos":"1",
    "wse":"1",
    "dbg":"1",
    "floating":"1",
    "editWins":"{\"width\":800,\"height\":600,\"x\":65,\"y\":279,\"ox\":0,\"oy\":0}"
  }

Interpreter:
  Version: 17.0.32941
  Platform: Linux-64
  Edition: Unicode/64
  Date: Apr 26 2018 at 14:38:44

```

**Comment by jayfoad** [comment]
Fixed. I don't think it's worth including the "national" format as well.
