### ISSUE TITLE
Feature request: dislay cursor location when editing

### ISSUE THREAD

**Issue by romilly** [Dyalog/ride#375]
### Describe the issue you are having
I'd like to see the row and column of my cursor position within the edit window displayed on a status bar when editing. I know I can toggle line numbers, but that's not quite what I want.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Started from RIDE

### How do you reproduce the issue?
edit something :)

### Paste the contents of Help → About (Shift+F1)
```
(Paste here)
```

**Comment by e9gille** [comment]
status bar added in cd23796bded61819dd08e0d8d5efa6552c72acb8
