### ISSUE TITLE
Cursor placed in wrong line of traced called function

### ISSUE THREAD

**Issue by JohnScholes** [Dyalog/ride#379]
### Describe the issue you are having
Tracing from line[n] of the calling function leaves the input cursor on line[n] of the called function.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Started an interpreter

### How do you reproduce the issue?
Configure "Single floating window"
```
      ⎕fx 1 3 1/'foo' '⍝' 'goo'
      ⎕fx 1 5  /'goo' '⍝'
      foo <TC><TC><TC><TC><TC>
```
Note that the input cursor is on goo[4]. You might have to hit Esc-Trace a couple of times to exit and trace back into goo in order to see the effect.

### Paste the contents of Help → About (Shift+F1)
```
IDE:
  Version: 4.1.3200
  Platform: MacIntel
  Date: 2018-04-28 00:31:45 +0200
  Git commit: c6f3b252f91fabb7cb936fc486b4275af7e22fc0
  Preferences:{
    "autocompletion":"shell",
    "colourScheme":"Zen",
    "colourSchemes":"[{\"name\":\"Zen\",\"theme\":\"light\",\"styles\":\"norm=bg:fdfefe,bgo:1 lnum=fg:0 err=fg:#ff0000 sqbr=fg:0 mtch=fg:#000000,bg:#c0c0c0\"}]",
    "editWins":"{\"width\":1100,\"height\":600,\"x\":335,\"y\":23,\"ox\":0,\"oy\":0}",
    "editWinsRememberPos":"1",
    "floatOnTop":"1",
    "floating":"1",
    "fold":"0",
    "indentOnOpen":"0",
    "kbdLocale":"en_US_Mac",
    "lbar":"0",
    "lineNums":"0",
    "minimapRenderCharacters":"0",
    "pfkeys":"[\"\",\"\",\"\",\"\",\"\",\"wsdiff''<ER>\",\"\",\"\",\"\",\"\",\")reset<ER>)save<ER>\",\"\",\"\"]",
    "showEditorToolbar":"0",
    "sqp":"0",
    "valueTips":"0",
    "zoom":"5"
  }

Interpreter:
  Version: 17.0.32924
  Platform: Mac-64
  Edition: Unicode/64
  Date: Apr 25 2018 at 01:50:14

```

**Comment by e9gille** [comment]
I tested this on my mac with your configuration many times but failed to replicate. If you manage to replicate again, could you please open the protocol log (Ctrl-F12) and take a snapshot of the last few lines.

**Comment by JohnScholes** [comment]
I can make it happen every time. I did it; it happened; protocol log is empty:

**Comment by e9gille** [comment]
@JohnScholes sorry, I didn't read carefully. The cursor is indeed on the wrong line, but the highlight line is correct.
@johndaintree checking the protocol log just after stepping into `goo` I see RIDE incorrectly receiving the messages:
```
16861 send ["StepInto",{"win":1}]
16861 recv ["SetPromptType",{"type":0}]
16862 recv ["UpdateWindow",{"currentRow":4,"debugger":1,"entityType":1,"name":"goo","offset":0,"readOnly":0,"size":0,"stop":[],"text":["goo","⍝","⍝","⍝","⍝","⍝"],"tid":0,"tname":"Tid:0","token":1}]
16864 recv ["SetHighlightLine",{"win":1,"line":1}]
```
currentRow indicates 4, then followed by highlight line 1.

Protocol log is empty when launched from a floating window, I'll fix that.

**Comment by e9gille** [comment]
Protocol log should now be launched correctly (25e606cefb5c99d242b1fe3da13275c402e0ded3)
