### ISSUE TITLE
Allow clicking to the right of a line to move cursor there even though no spaces have been typed

### ISSUE THREAD

**Issue by abrudz** [Dyalog/ride#381]
### Describe the issue you are having
In the IDE, a quick way to start typing to the far right (e.g. a comment) is clicking where you want to start, and then just start typing. Any necessary spaces are automatically inserted. This doesn't work on RIDE.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Start an interpreter

### How do you reproduce the issue?
Try typing the following line into the session (don't just cut and paste):
`2+2                                                                                ⍝ four?`
You'll find it very tedious to have to type so many spaces instead of just clicking to the right and typing.

### Paste the contents of Help → About (Shift+F1)
```
IDE:
Version: 4.1.3130
Platform: Win32
Date: 2018-04-18 10:24:09 +0200
Git commit: 38a8a23
Preferences:{
"cursorBlinking":"solid",
"floatOnTop":"1",
"floating":"1",
"kbdLocale":"en_US",
"lineNums":"0",
"sqp":"0",
"zoom":"4"
}

Interpreter:
Version: 17.0.32977.0 64 Unicode
Platform: Windows
Edition: 10 Pro
Date: May 1 2018 at 12:54:39
```

**Comment by jayfoad** [comment]
Same as #238.
