### ISSUE TITLE
WIBNI typed-ahead characters were not lost

### ISSUE THREAD

**Issue by JohnScholes** [Dyalog/ride#383]
### Describe the issue you are having
Any characters typed in the session, before the next read is issued, are lost.

### How do you reproduce the issue?
```
      ⎕dl 5
      type some more stuff during the delay
```

**Comment by e9gille** [comment]
I'm not sure what you mean. If you prepare a couple of lines they get executed sequentially until they are all processed or an error is triggered. Is your request that one should be allowed to type while the editor is in pending mode?

**Comment by abrudz** [comment]
In the IDE you can type ahead (until the buffer is full) and even press Enter, all while a program is running. When the interpreter *would* return to a 6-space prompt, it then processes whatever is in the buffer. Try e.g. to type `⎕dl 5` and press Enter. Then, while the system is still busy, type `2+2` and press Enter. Nothing happens for a few seconds, and then both `2+2` and the answer `4` appear:
![buffer](https://user-images.githubusercontent.com/10961427/39671405-aee2b578-510f-11e8-8f8b-f052dfb0b034.gif)

**Comment by e9gille** [comment]
I see, thanks for the clarification.
