### ISSUE TITLE
The "Save changes and return" button is unnecessary

### ISSUE THREAD

**Issue by abrudz** [Dyalog/ride#384]
### Describe the issue you are having
The IDE needs a separate button to close an item and the editor, since the editor can stay open with no items being edited. However, this concept does not exist in RIDE; each edited object has its own window or tab with an OS GUI close button (if floating) or a Golden Layout `x` (if docked).

### Paste the contents of Help → About (Shift+F1)
```
IDE:
  Version: 4.1.3130
  Platform: Win32
  Date: 2018-04-18 10:24:09 +0200
  Git commit: 38a8a2347ec732fd79e0b486627408a5f793dd80
  Preferences:{
    "cursorBlinking":"solid",
    "floatOnTop":"1",
    "kbdLocale":"en_US",
    "lineNums":"0",
    "pfkeys":"[\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"<BP><RM><BP><TC>\",\"\",\"\"]",
    "sqp":"0",
    "zoom":"12",
    "cursorBeyondEOL":"1",
    "wse":"1",
    "floating":"1"
  }

```

**Comment by jayfoad** [comment]
I think you are correct that it is the only thing you can click on to turn an edit window back into a trace window, so it does serve some purpose, so I would suggest leaving it there. But I don't feel strongly about it.

**Comment by e9gille** [comment]
leaving it in for now
