### ISSUE TITLE
A connection needs a little nudge

### ISSUE THREAD

**Issue by lstefano71** [Dyalog/ride#387]
### Describe the issue you are having
If I try and connect to a running interpreter, the "Connecting" box with the spinning icon remains on until I do anything else in the Ride window, like clicking on "About Dyalog" in the menu.

### How do you reproduce the issue?
Start a Dyalog 15.0 interpreter. Use the i-beam 3502 to setup the ride server.
Start Ride-4.1,exe. Type the hostname and port number for the interpreter already running.
Click on "Connect". You get "Connecting" and the spinning icon, until you click on a menu item in the "Dyalog" menu.

### Paste the contents of Help → About (Shift+F1)
```
IDE:
  Version: 4.1.1
  Platform: Win32
  Date: 2018-05-08 15:52:41 +0200
  Git commit: 5a29e6450a2559f5d2921239125ecca517cfba06
  Preferences:{
    "dbg":"1",
    "kbdLocale":"it_IT",
    "wse":"1"
  }

Interpreter:
  Version: 15.0.29488
  Platform: Windows
  Edition: Classic/32
  Date: Mar 14 2017 at 18:52:50

```

**Comment by e9gille** [comment]
Sorry, I misunderstood the issue reported here. It's not just the connect modal that remains, but you don't even connect successfully until you nudge it.

I've replicated this and can only add that resizing the window also helps it along. It is most peculiar and I haven't managed to identify the source yet.

**Comment by e9gille** [comment]
tested with node v10.1.0 and it resolves the issue. Will consider uppgrading
