### ISSUE TITLE
RIDE help does not appear to cover RIDE

### ISSUE THREAD

**Issue by romilly** [Dyalog/ride#388]
### Describe the issue you are having
When I open help from RIDE's menu I can see help for every aspect of Dyalog APL - apart from RIDE itself!

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Either

### How do you reproduce the issue?
Open RIDE, clisk on Help

### Paste the contents of Help → About (Shift+F1)
n/a

**Comment by abrudz** [comment]
RIDE UG will be part of the new integrated online help.
