### ISSUE TITLE
RIDE help should offer quick reference for keyboard shortcuts

### ISSUE THREAD

**Issue by romilly** [Dyalog/ride#389]
### Describe the issue you are having
If I want to explore/find RIDE's keyboard shortcuts I have to
1. Open RIDE help,
2. go the documentation centre,
3. open the RIDE doc,
4. navigate to Appendix A
5. work though until I find the shortcut I'm interested in.

Life's too short for this, (especially at my age).

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Either

### How do you reproduce the issue?
See above

### Paste the contents of Help → About (Shift+F1)
```
(Paste here)
```

**Comment by jayfoad** [comment]
How about going to Preferences->Shortcuts. Isn't that a more useful reference? It's always up-to-date!

**Comment by jayfoad** [comment]
Perhaps you'd like a new menu item Help->Keyboard Shortcuts to take you straight to that pane of the preferences window?

**Comment by e9gille** [comment]
I guess the preference window doesn't actually describe the commands, only lists their names. if we add another column with descriptions perhaps? It would make descriptions searchable, but the table busier.

**Comment by jayfoad** [comment]
There is already a column of descriptions!
ABT About
AC Align comments
AO Comment out lines
etc.

**Comment by JohnScholes** [comment]
> There is already a column of descriptions!
Agreed. A couple of them could be improved:
ABT About **Dyalog**
EMD Edit current trace window (?)
TC Trace **line**

**Comment by jayfoad** [comment]
> A couple of them could be improved

Done.
NB the ODE still calls TC "Trace".
I'm not sure we need EMD any more. It was put in to appease some ODE users (@dyaandys ?) who found that in RIDE, they couldn't easily put their cursor onto some whitespace in order to hit \<TC> to edit the current function. But I think these problems may have been fixed.

**Comment by JohnScholes** [comment]
> NB the ODE still calls TC "Trace".
> 
cf ER Execute line

I'm all for removing EMD.

**Comment by romilly** [comment]
My mistake (though others may make it) - I'd never visited preferences until now, so I had no idea that's where the shortcuts were listed.

Some sort of link from help to the shortcuts (in preferences) would be fine.

**Comment by FionaDyalog** [comment]
In RIDE 4.0 there was a little keyboard icon to the right of the language bar:
•	Positioning the cursor over the icon displayed a tooltip showing selected keyboard shortcuts for command codes.
•	Clicking on the icon displayed the Preferences dialog box (the same as selecting the Edit > Preferences menu option)

In RIDE 4.1 this is no longer there. Maybe reinstating this (or something similar to the first bulet point above at least) would provide a convenient way of checking what you have configured your shortcuts to be?

**Comment by jayfoad** [comment]
@FionaDyalog see #341: the change was deliberate. The tooltip only showed an arbitrary subset of shortcuts, which didn't seem very useful, and the icon changed to a gear wheel and then migrated to the left of the status bar.

**Comment by FionaDyalog** [comment]
@jayfoad It might have been deliberate, and I agree the arbitrary nature of its population was not helpful, but could there not be a dynamic replacement that you mouse over to see all your configured shortcuts without having to go into the correct tab of the dialog box? I might be biased here though as I found it useful!

**Comment by e9gille** [comment]
I have re-instated the keyboard icon in the language bar. Hovering over it shows all defined shortcuts. Clicking it opens the preferences on the Shortcuts tab.
Once there you can filter to show only defined shortcuts.
Top right you will find a print button to print the (optionally filtered) list.

Hope that helps.
