### ISSUE TITLE
Keystrokes involving dead keys do not work

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/ride#390]
### Describe the issue you are having
Keystrokes which require the prefix key to be followed by a dead key like ^ to produce ⍬ or ¨ to produce → do not work. The desired key briefly appears, but at the next keystroke it disappears and is replaced by the symbol on the dead key.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Launch Dyalog v17.0 "Beta 1" on a Danish Mac.

### How do you reproduce the issue?
On a Danish Mac, type <^, see the ⍬, and then see it revert to ^ at the next keystroke.

### Paste the contents of Help → About (Shift+F1)
```
IDE 4.1.3253, Interpreter 17.0.33034
```

**Comment by abrudz** [comment]
Does this happen even if the next keystroke is a space?

**Comment by mkromberg** [comment]
Yes - if the next keystroke is something that actually combines with the dead key then you get î or ü (etc).

**Comment by e9gille** [comment]
Just tested this on a UK WinOS with Danish keyboard layout in RIDE and Swedish keyboard input language in OS (so I'm not sure how much use this is) but prefix+dead key+space seems to work...

I know dead keys are handled differently on Mac. I'll see what I can do.

**Comment by mkromberg** [comment]
Yup, I can also confirm it works for me under Danish Windows.

**Comment by e9gille** [comment]
done some work on this. Dead keys are problematic, but with the latest changes you should be able to use them.
To complete the sequence you can hit space, eg
`prefix`+`dead key`+`space`
or
`prefix`+`Shift+dead key`+`space`

If you follow the dead key with something it can complete you end up with prefix followed by the completed character:
`prefix`+`diaresis`+`a` => `prefix`+`ä`

This has been tested on mac and win, will need to check linux.

**Comment by mkromberg** [comment]
Will test it when I get a new Mac build. The behaviour that you describe seems to be "correct".

**Comment by e9gille** [comment]
@mkromberg can we close this one?

**Comment by mkromberg** [comment]
Works fine with Dyalog 17.0.33055 / IDE 4.1.3271 on Mortens Danish MacBook Air.
