### ISSUE TITLE
Unhelpful error message when trying to open multiple connections between the same RIDE and interpreter

### ISSUE THREAD

**Issue by FionaDyalog** [Dyalog/ride#392]
### Describe the issue you are having
Unhelpful error message when trying to open multiple connections between the same RIDE and interpreter

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Connect to already running

### How do you reproduce the issue?
Open local interpreter
Open RIDE and connect to local interpreter
In File menu select Connect... to get the RIDE-Connect dialog box
Try to reconnect to the same interpreter.

This fails (correctly). However, the error I get is "write ECONNABORTED", which is no help to me at all! I would like a more helpful error message explaining that I can't establish multiple connections between the same RIDE and interpreter instance.

(related issue: having the Connect dialog box open at exactly the same size as and directly on top of the Session compounds this issue as it obscures the fact that there is still a Session running).

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.1.3258
  Platform: Win32
  Date: 2018-05-09 21:37:18 +0200
  Git commit: a2dd832e5712e4dcf8d7f69d4f7e3a561d5123f4
  Preferences:{
    "kbdLocale":"en_GB"
  }

Interpreter:
  Version: 17.0.33034
  Platform: Windows-64
  Edition: Unicode/64
  Date: May  9 2018 at 09:31:12

**Comment by FionaDyalog** [comment]
Addendum: if I click OK on the error message to close it (twice!) then I do get a new Session window, with the caption "{WSID}". This raises two issues. Do I now have two connections between the same interpreter and RIDE (which I thought was not possible) and, as per Gil's comment on #397 , "You should never see a session window with a caption of {WSID}. This was caused by the net module incorrectly firing a "connection" event." so surely I shouldn't have a new session with this caption.

IDE:
  Version: 4.1.3278
  Platform: Win32
  Date: 2018-05-15 18:39:32 +0200
  Git commit: 828e800529dd8c602b71a46741a1edba009be16d

Interpreter:
  Version: 17.0.33034
  Platform: Windows-64
  Edition: Unicode/64
  Date: May  9 2018 at 09:31:12

**Comment by e9gille** [comment]
Traced this through and the issue is that a second attempt to connect succeeds but is then terminated, at which point the process of establishing the session is already started. I'll debounce the setup to give the aborted connection a chance to interrupt the setup.
