### ISSUE TITLE
Prereqs for RIDE 4.1.3261 on Linux need altering

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/ride#396]
### Describe the issue you are having
Default 16.04 Ubuntu has libnss3 at 3.23; RIDE 4.1 will install, but attempting to start RIDE via the shortcut leads to an unhelpful window manager error pop-up, and from the command line error text which mentions "NSS 3.26"

The .deb and .rpm images should check that libnss3 is at a suitable high level.
On Ubuntu I believe that the fileset in question is libnss3
On openSUSE it _may_ be mozilla-nss

**Comment by jayfoad** [comment]
> openSUSE Leap 42.3: liXScrnSaver is needed by ride-4.1-0:4.1.3261-1.x86_64
> Not entirely sure whether that name is correct .. think it should be libXScrnSaver

Looks like I messed up the fix for #233.

**Comment by dyaandys** [comment]
Actually, I think it possible that for rpms, rather than referring to the package name which contains the library, we may be better off referring to the actual library that's needed.  
References:
https://github.com/atom/atom/pull/13386/files
https://stackoverflow.com/questions/41013006/how-to-install-libxscrnsaver-on-opensuse-leap-42-2
https://ask.fedoraproject.org/en/question/62604/why-are-rpm-dependencies-given-as-sonames-instead-of-package-names/

**Comment by jayfoad** [comment]
I've done my best to sort out the deb and rpm dependencies. Tested by installing on docker images of Debian 8, Ubuntu 14.04, Centos 7, Fedora 25 and openSUSE 13.2.
