### ISSUE TITLE
Checkmarks in View menu not updated when Show Debug/Show Windows Explorer are selected

### ISSUE THREAD

**Issue by FionaDyalog** [Dyalog/ride#398]
### Describe the issue you are having
Checkmarks in View menu not updated when Show Debug/Show Windows Explorer are selected

### Did you connect to an already running interpreter or start the interpreter from RIDE?
irrelevant

### How do you reproduce the issue?
View > Show Debug is not selected and the Debug pane is not displayed.
Select View > Show Debug
The Debug pane is now displayed
View > Show Debug is still not checked and it should be.

Same issue with Workspace Explorer

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.1.3261
  Platform: Linux x86_64
  Date: 2018-05-11 00:20:40 +0200
  Git commit: a11154957eb6f90207d42a66e2b3d80b5b852094
  Preferences:{
    "kbdLocale":"en_GB",
    "dbg":"1"
  }

Interpreter:
  Version: 16.0.31812
  Platform: Linux-64
  Edition: Unicode/64
  Date: Dec 20 2017 at 03:17:48

**Comment by jayfoad** [comment]
A reappearance of #257 ?

**Comment by e9gille** [comment]
I don't think we ever "fixed" this issue. It works on Ubuntu 17.10 and 18.04, so @jayfoad decided to close #257.

I believe there are other issues on 16.04 (such as #395). Do we want to support older versions of Ubuntu?

**Comment by jayfoad** [comment]
Yes we'd like to support all versions of Ubuntu that Canonical still support, if possible (currently 14.04 16.04 17.10 18.04).
