### ISSUE TITLE
Use all lines from demo (DM) scripts

### ISSUE THREAD

**Issue by JohnScholes** [Dyalog/ride#399]
### Describe the issue you are having
The demo (DM) system skips blank lines and lines starting with multiple ⍝⍝... symbols. It would be better if _all_ lines were honoured. 

### How do you reproduce the issue?
MyScript:
```
2+3   ⍝ ok
⍝⍝⍝⍝  this line and following blank line are ignored

4+5   ⍝ ok
```
### Paste the contents of Help → About (Shift+F1)
```
IDE:
  Version: 4.1.3261
  Platform: MacIntel
  Date: 2018-05-11 00:20:40 +0200
  Git commit: a11154957eb6f90207d42a66e2b3d80b5b852094
  Preferences:{
    "autocompletion":"shell",
    "autocompletionDelay":"2147483647",
    "blinkCursor":"0",
    "breakPts":"0",
    "colourScheme":"JohnS",
    "colourSchemes":"[{\"name\":\"JohnS\",\"theme\":\"light\",\"styles\":\"diam=B err=fg:#ff0000,bg:#ffffff,bgo:0.5 idm=bg:#ffffff,bgo:0.5,fg:0 kw=B lnum=bg:f,bgo:1 mod=bg:#e7e1e7,bgo:1,fg:#000000 mtch=bg:c,bgo:0.5 norm=bg:f,bgo:1 ns=fg:8 num=fg:8 quad=fg:8 srch=bg:#0000ff,bgo:0.5 str=fg:#000000 tc=bg:#ffffff,bgo:1,fg:0 zld=fg:8 vtt=bc:aaa\"}]",
    "cursorBeyondEOL":"1",
    "editWins":"{\"width\":1103,\"height\":621,\"x\":337,\"y\":0,\"ox\":0,\"oy\":0}",
    "editWinsRememberPos":"1",
    "floatOnTop":"1",
    "floating":"1",
    "fold":"0",
    "ilf":"0",
    "indentOnOpen":"0",
    "kbdLocale":"en_GB_Mac",
    "keys":"{\"BP\":[\"Ctrl-Backspace\"],\"DMN\":[\"Ctrl-Right\"],\"DMP\":[\"Ctrl-Left\"],\"DMR\":[\"Ctrl-1\"],\"SC\":[],\"WI\":[\"Ctrl-C\"]}",
    "lbar":"0",
    "lineNums":"0",
    "minimapRenderCharacters":"0",
    "persistentHistorySize":"10",
    "pfkeys":"[\"\",\"\",\"\",\"\",\"\",\"wsdiff''<ER>\",\"\",\"\",\"\",\"\",\")reset<ER>)save<ER>\",\"\",\"\"]",
    "sbar":"0",
    "showEditorToolbar":"0",
    "sqp":"0",
    "valueTips":"0",
    "zoom":"10"
  }

Interpreter:
  Version: 17.0.33046
  Platform: Mac-64
  Edition: Unicode/64
  Date: May 11 2018 at 01:58:54
```

**Comment by DyalogRichard** [comment]
Alternative view: I find it very useful to put comments in a script file which I do not want to appear in the session when I run it.

**Comment by mkromberg** [comment]
I think it would be nice to have a special syntax that did allow "notes". Perhaps lines beginning with ⍝⍝ or ⍝: or ⍝! or some convention that one is unlikely to want to ever appear in the demo itself. But not just because a line begins with a comment, because that *is* something you might well want to appear in the demo itself.

**Comment by JohnScholes** [comment]
> Alternative view: I find it very useful to put comments in a script file which I do not want to appear in the session when I run it.

I think this can be addressed when we extend the protocol with an escape system to make some lines have special effects, see #228. With the current system, it's not possible to have a script that includes lines such as:
```
⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝
⍝   Summary  ⍝
⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝⍝
```

**Comment by JohnScholes** [comment]
> Perhaps lines beginning with ⍝⍝ or ⍝: or ⍝! or some convention that one is unlikely to want to ever appear in the demo itself.

Perhaps a line starting with invalid APL, so there is never a conflict.
```
...⍝ script comment
...⍎ 'gcd'⎕cy'dfns'   ⍝ execute but don't show
...⎕ Display this line in the session but don't execute it.
etc
```
I'm writing a discussion document. Will share when ready.

**Comment by DyalogRichard** [comment]
For consistency and portability, oughtn't we to do the same as the existing demo system? #228 currently prevents that being done in its entirety, but that seems to me like the direction we should be going.

**Comment by e9gille** [comment]
Syntax for comments in ODE is `&⍝`

Also, from what I can tell, empty lines are skipped going forward, but honored going backwards. Don't see the point in that, but leave it to Demo users to decide how to deal with them.

**Comment by JohnScholes** [comment]
Closed: to be replaced with simpler alternative.
