### ISSUE TITLE
Prompt appears when hovering over a name

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/ride#400]
### Describe the issue you are having
If you hover over a name in RIDE and ODE, you see the definition - which is very nice. However, if the file has been edited outside APL and you hover over the name, you get a popup warning you that the file has changed and asking you what you want to do. By the time you have answered the question, the cursor is outside the name and you don't see the definition. And even if you answer that you would like to use the new file, you continue to get the popup each time you try to move the mouse over the name again.

It might be better to show the ⎕VR of the function, with a warning in the header that it has changed outside APL?

### Did you connect to an already running interpreter or start the interpreter from RIDE?
N/A

### How do you reproduce the issue?
2 ⎕FIX 'file://temp/foo.dyalog'. Edit foo.dyalog using notepad. Type )fns and then hover over "foo".

### Paste the contents of Help → About (Shift+F1)
```
V17.0 beta 1 with latest RIDE.
```

**Comment by e9gille** [comment]
I can't replicate this. foo is updating the source automatically without prompting. Is this something I have done? (I'm on a Mac)

**Comment by e9gille** [comment]
Just tested on Windows and I see what you mean.
@johndaintree on Mac and Linux I don't get the prompt at all (no TaskDialog message received on hover) only Windows. Same thing if I edit after an external change. On nixes I see the modified source without prompt. Is this a bug in the interpreter?

**Comment by e9gille** [comment]
Just to clarify, this is not a RIDE issue, please log in Mantis.

**Comment by jayfoad** [comment]
It's Mantis 15866.
