### ISSUE TITLE
WIBNI: DM demo system: ability to use blank lines and ⍝⍝⍝... lines as part of a demo.

### ISSUE THREAD

**Issue by JohnScholes** [Dyalog/ride#406]
### Describe the issue you are having
It would be nice to be able to have blank and ⍝⍝⍝... lines in a DM script transferred to the session, rather than ignored.

**Comment by JohnScholes** [comment]
A counter-argument is that people like to embed comment lines the script itself and not have them transferred to the session. If we implement an escape convention, as per #404, we could have & on it's own to mean this.
```
& script commentary
```

**Comment by lstefano71** [comment]
Not with the intention of throwing a wrench in the spinning wheels for the
sake of it, but once upon a time there was the concept of a "public
comment" in certain APLs. A public comment would be accessible even inside
locked functions. If I remember correctly the syntax for a public comment
was: ⍝∇
Just my 2c.
