### ISSUE TITLE
Search bar exhibiting strange behaviour

### ISSUE THREAD

**Issue by FionaDyalog** [Dyalog/ride#407]
### Describe the issue you are having
Two issues when populating the Edit window> Search bar > Find field:
1. Entering text in the Find field using the Language bar does not find the text in the Edit window.
2. Entering a regular expression does not work.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Connect to already running (irrelevant)

### How do you reproduce the issue?
1. Open the Edit window and put some text in it.
2. Click the Search icon to display the Search bar.
3. Put a glyph in the Find field using the Language bar - nothing is highlighted in the Edit window and the count remains at "no results".

1. Open the Edit window and put some text in it.
2. Click the Search icon to display the Search bar.
3. Put "f*" in the Find field and select Use Regular Expression. The count increases to the number of lines in the Edit window and highlights the first (blank) character in each line. Using the Next Match button to go through them changes the count to "? of 10" (assuming 10 lines) and does not move the cursor. It works better if using the Previous Match button in that it does count them down and move the cursor.

![image](https://user-images.githubusercontent.com/13313372/40111888-268e56d8-58fc-11e8-836f-245ea4cbb6d1.png)

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.1.3278
  Platform: Win32
  Date: 2018-05-15 18:39:32 +0200
  Git commit: 828e800529dd8c602b71a46741a1edba009be16d

Interpreter:
  Version: 17.0.33034
  Platform: Windows-64
  Edition: Unicode/64
  Date: May  9 2018 at 09:31:12

**Comment by jayfoad** [comment]
> Two issues

In future please raise one issue per issue!

**Comment by e9gille** [comment]
input using language bar is something I can look at fixing.
The regular expression issue is something internal to monaco. It looks like it has been fixed in latest version (0.13.1) but not something I plan on upgrading to for RIDE 4.1.

Also, I think I would expect every f or lack thereof to be matched by the expression `f*`. I don't see when you would use that in a real scenario.
