### ISSUE TITLE
Cannot enable Windows IME

### ISSUE THREAD

**Issue by FionaDyalog** [Dyalog/ride#408]
### Describe the issue you are having
Cannot use the Windows IME to enter glyphs.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Connect to already running (irrelevent)

### How do you reproduce the issue?
Preferences > Keyboard has the checkbox selected for enabling the IME but the IME is not enabled (I have restarted numerous times).

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.1.3278
  Platform: Win32
  Date: 2018-05-15 18:39:32 +0200
  Git commit: 828e800529dd8c602b71a46741a1edba009be16d

Interpreter:
  Version: 17.0.33034
  Platform: Windows-64
  Edition: Unicode/64
  Date: May  9 2018 at 09:31:12

**Comment by e9gille** [comment]
I fear the exe that does this is outdated, probably never run under Windows 10. Will see what I can do.
