### ISSUE TITLE
WIBNI the Keyboard in the Configuration dialog box was printable

### ISSUE THREAD

**Issue by FionaDyalog** [Dyalog/ride#412]
### Describe the issue you are having
No idea how feasible it is, but being able to print the keyboard as defined in the Configuration dialog box (Keyboard tab) would be very useful, especially as it's configurable.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
irrelevant

### How do you reproduce the issue?
irrelevant

### Paste the contents of Help → About (Shift+F1)
irrelevant but IDE:
  Version: 4.1.3278
  Platform: Win32
  Date: 2018-05-15 18:39:32 +0200
  Git commit: 828e800529dd8c602b71a46741a1edba009be16d

**Comment by fourier** [comment]
I agree it could be of a great help to create a pdf out of the layout.
