### ISSUE TITLE
RIDE protocol log does not scroll down, unlike RIDE 4.0

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/ride#414]
When watching the traffic between RIDE and an interpreter, once the initial screen has been filled, further updates appear off screen. Updates in RIDE 4.0 caused the contents of the window to scroll, which was more useful.

IDE:
  Version: 4.1.3300
  Platform: Win32
  Date: 2018-05-21 10:36:27 +0200
  Git commit: 9b26459792f1019b247efa62d90fb828d4cda964
  Preferences:{
    "kbdLocale":"en_US"
  }

**Comment by e9gille** [comment]
this is odd, the code is still there to scroll, but it seems something has changed (maybe in the browser) so scrolling now needs to be done to the document rather than the body.
