### ISSUE TITLE
Editor:  copy of multiple lines put all the lines into a single line on the clipboard

### ISSUE THREAD

**Issue by dyavc** [Dyalog/ride#416]
### Describe the issue you are having
RIDE on MS Windows 

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Connect to already running

### How do you reproduce the issue?
)ed foo
⍝⍝ Insert into foo 2 or 3 lines of any text

select all the text and copy

paste into Dyalog or notepad

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.1.3262
  Platform: Win32
  Date: 2018-05-11 12:16:38 +0100
  Git commit: 750aac529a6d872aa6d7cad4259f1bbda7ce1175
  Preferences:{
    "floatOnTop":"1",
    "floating":"1",
    "indent":"2",
    "indentComments":"1",
    "indentMethods":"2",
    "kbdLocale":"en_US",
    "matchBrackets":"0",
    "pfkeys":"[\"\",\"\",\"\",\":access Public <ER>\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\"]",
    "title":"{WSID}  {VER} PID: {PID}",
    "wse":"1"
  }

Interpreter:
  Version: 16.0.33112
  Platform: Windows
  Edition: Unicode/32
  Date: May 17 2018 at 20:07:48

**Comment by dyavc** [comment]
The RIDE session window does add multiple lines to the clipboard when you copy from it.

**Comment by e9gille** [comment]
Should now be fixed by ec9f39414801e6c527bd725ec824a28f7bdf39da
