### ISSUE TITLE
Add a key bindings for the beginning/end of line

### ISSUE THREAD

**Issue by fourier** [Dyalog/ride#418]
### Describe the issue you are having
Currently only Home/End could be used to jump to the beginnig/end of line.
However in OSX and Linux terminals the Emacs key bindings Ctrl-A/E could also be used for this purposes. Please add an option to bind beginning/end of line to Ctrl-A/E

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Start interpreter
### How do you reproduce the issue?
Move cursor to the middle of the line, press Ctrl-A or Ctrl-E

### Paste the contents of Help → About (Shift+F1)
```
IDE:
  Version: 4.1.3151
  Platform: Linux x86_64
  Date: 2018-04-20 17:00:22 +0200
  Git commit: 98cdb1278456012d2cc257831a253b58901a1a1a
  Preferences:{
    "blinkCursor":"0",
    "blockCursor":"1",
    "colourScheme":"Francisco Goya",
    "cursorBlinking":"solid",
    "kbdLocale":"en_US",
    "keys":"{\"BK\":[\"Ctrl-Up\"],\"FD\":[\"Ctrl-Down\"],\"LBR\":[\"F10\"],\"PF10\":[],\"TL\":[]}",
    "otherExe":"/opt/mdyalog/16.0/64/unicode/mapl",
    "selectionHighlight":"1",
    "squiggleTips":"1",
    "zoom":"5"
  }

Interpreter:
  Version: 16.0.32456
  Platform: Linux-64
  Edition: Unicode/64
  Date: Mar 13 2018 at 03:31:46
```

**Comment by e9gille** [comment]
I believe monaco adds Cmd+A and Cmd+E by default for MacOS, but I'll make them configurable.
