### ISSUE TITLE
Empty Status Output Window

### ISSUE THREAD

**Issue by bpbecker** [Dyalog/ride#42]
### Description:
When starting MiServer 3.0 (download from a current GitHub commit), an empty Status Output window pops up (over my Windows APL session, not my RIDE session).  However, starting MiServer 3.0 without RIDE produces no discernible status output.    
### Repro:
1. Download/Clone [MiServer 3.0](https://github.com/Dyalog/MiServer/archive/master.zip)
1. Start RIDE (I started a 150u64 interpreter)
1. )load the miserver workspace
1. Cursor up to the line that says "Start './SampleMiSites/MS3' ,,,"
1. Press Enter
### About Information:
IDE:
  Version: 4.0.2591
  Platform: Win32
  Date: 2017-01-05 12:21:28 +0000
  Git commit: aeaeb457fcf46871b0abc647cfb32b42d8f2a5d6
  Preferences:{
    "kbdLocale":"en_US",
    "selectedExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 15.0 Unicode\\dyalog.exe",
    "title":"{PROFILE}-{WSID}"
  }

Interpreter:
  Version: 15.0.28845
  Platform: Windows-64
  Edition: Unicode/64
  Date: Dec 18 2016 at 17:55:13

**Comment by mbaas2** [comment]
Alternative repo:  
```
)load util
FIND'FIND'
```
also produces "Status Output"-window with no content. Doing the same in the interpreter produces output in the status-window.

**Comment by jayfoad** [comment]
I can't reproduce this. I'm on Windows running RIDE 4.0.2638, spawning either Dyalog 15.0.27982 or 16.0.28955. In both cases, when the interpreter generates some status output, the text goes into BOTH a window that pops up over the interpreter AND a window that pops up over RIDE.

**Comment by mbaas2** [comment]
I observed this with R2634 and Dyalog 16.0.29146 Unicode and can still reproduce with R2638 and D29184u.
![2017-02-15_14-31-49](https://cloud.githubusercontent.com/assets/5645494/22976604/c90bd2dc-f38b-11e6-80e7-7c99bb58d6fd.png)

**Comment by jayfoad** [comment]
Ah! It's RIDE's "Status Output" window which is empty. The "Status" window with File and Options menus is the interpreter's one.

**Comment by jayfoad** [comment]
Fixed
