### ISSUE TITLE
Windows: AppData\Roaming\RIDE\logs is created when starting RIDE, but is never updated

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/ride#421]
Windows: AppData\Roaming\RIDE\logs is created when starting RIDE, but is never updated

In WIndows Explorer navigate to AppData\Roaming; delete RIDE directory if present.
Start RIDE 4.1
Note that the directory has reappeared, with a subdirectory, logs, in it.  I've never seen anything in this directory.  Even if needed, should it not be in Ride-4.1 rather than RIDE ?

IDE:
  Version: 4.1.3300
  Platform: Win32
  Date: 2018-05-21 10:36:27 +0200
  Git commit: 9b26459792f1019b247efa62d90fb828d4cda964
  Preferences:{
    "kbdLocale":"en_US"
  }

**Comment by jayfoad** [comment]
Almost certainly caused by electron/electron#11858.

**Comment by abrudz** [comment]
Can't repro in 4.4
