### ISSUE TITLE
Something odd about the "..." fields on the connect page

### ISSUE THREAD

**Issue by jayfoad** [Dyalog/ride#423]
A very minor issue: on Linux, if I TAB to or click on the "..." fields on the connect page, the dotted outline doesn't seem to match the size of the actual "...":

![screenshot from 2018-06-04 11-19-40](https://user-images.githubusercontent.com/108316/40912498-a3ed2da6-67e9-11e8-948f-b42e0c5ec464.png)

**Comment by jayfoad** [comment]
Same goes for the refresh icon, if you select Start over SSH.

**Comment by abrudz** [comment]
Included in #890
