### ISSUE TITLE
When the connection type is Start, fields are displayed which can't be enabled/changed

### ISSUE THREAD

**Issue by FionaDyalog** [Dyalog/ride#424]
### Describe the issue you are having
When the connection type is Start, fields are displaying which can't be enabled/changed. I find this confusing (and difficult to explain in the documentation as they are pointless!). Specifically:
- with Local: host and port cannot be changed and don't mean anything. Including them doesn't help a user...suggest removing them.
- with SSH: Working directory cannot be enabled - it should either not be displayed or it should be enabled when a local interpreter is selected.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Start an interpreter

### How do you reproduce the issue?
Start RIDE. In the RIDE - Connect dialog box, set the Type to Start. 

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.1.3321
  Platform: Win32
  Date: 2018-05-27 22:39:34 +0200
  Git commit: 260f7337e44a6302d558cc052403ae657702d76b

Interpreter:
  Version: unknown
  Platform: unknown
  Edition: unknown
  Date: unknown

**Comment by e9gille** [comment]
removed in fd94d5676e955ec67cf10c19902a10b15eeaa7f8
