### ISSUE TITLE
Action > Clear all trace/stop/monitor does not clear break points from an unfixed function

### ISSUE THREAD

**Issue by FionaDyalog** [Dyalog/ride#425]
### Describe the issue you are having
If I have an Edit window open and add break-points, selecting Action > Clear all trace/stop/monitor does not clear them. Jay has explained to me the rationale behind this and why I need to fix the function before it will work, but to me as a user that’s not logical and I would like them to be cleared if I select that option from the Action menu.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
irrelevant

### How do you reproduce the issue?
Create a function in the Edit window, add break points, select Action > Clear all trace/stop/monitor from the menu bar.

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.1.3321
  Platform: Win32
  Date: 2018-05-27 22:39:34 +0200
  Git commit: 260f7337e44a6302d558cc052403ae657702d76b

Interpreter:
  Version: 17.0.33252
  Platform: Windows-64
  Edition: Unicode/64
  Date: May 31 2018 at 09:07:02

**Comment by FionaDyalog** [comment]
comment from Gil:

Just looked into this and can see 2 commands that clear stops
CAM – clear all stops (the one you trigger from the menu)
CBP – clear all stops in current object (from the tracer toolbar)

Neither of them can be given a shortcut at the moment, maybe we should add them as commands to allow that.

I don’t think it would be too much to ask for. CPB would clear the stops in the editor if you could only trigger it. CAM could call CBP on open editors in addition to what it does now.

**Comment by e9gille** [comment]
I have changed CAM to also trigger CBP in each editor. Note that the counts of stops cleared are not included in the total reported by the CAM command.

Also added CAM and CBP to the list of commands that can be given shortcuts.
