### ISSUE TITLE
Connect to running interpreter has become very slow (~15 seconds)

### ISSUE THREAD

**Issue by DyalogRichard** [Dyalog/ride#426]
### Describe the issue you are having
It is taking a long time to connect to a running interpreter on the local machine.

### Did you connect to an already running interpreter or start the interpreter from RIDE?

Connect

### How do you reproduce the issue?

APL is running and listening for connections. RIDE is connected on the local machine.

This used to be near-instantaneous but now takes around 15 seconds. 

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.1.3330
  Platform: Linux x86_64
  Date: 2018-06-04 16:50:49 +0100
  Git commit: 5407e4cc5de2c0e20a103e1acbbe965223f7b2b1
  Preferences:{
    "autoCloseBrackets":"0",
    "dbg":"1",
    "floatOnTop":"1",
    "floating":"1",
    "kbdLocale":"en_GB",
    "wrap":"1",
    "wse":"1"
  }

Interpreter:
  Version: 18.0.33317
  Platform: Linux-64
  Edition: Unicode/64
  Date: Jun  5 2018 at 10:59:17

**Comment by DyalogRichard** [comment]
I’ve had a bit of a look at what is going on.

1.	The delay is happening in Conga/RIDE before the interpreter gets a look-in.
2.	I can see, but not completely understand, the Conga bit, and can’t see the RIDE bit at all.

There’s a loop in Conga work.cpp:WorkThread() which calls select() (via socket.cpp:SfWait()) to wait for something to arrive from RIDE and dispatch it to work.cpp:ExecSub(), and ExecSub() can recurse a bit handling types like TRoot, TServer and TConnect.

What I see is this:

When you hit RIDE’s Connect button, work.cpp:WorkThread() gets called for the first time and begins looping.

On the first iteration, select() returns immediately. work.cpp:ExecSub() then processes TRoot and TServer.
On the second iteration, select() returns immediately. work.cpp:ExecSub() then processes TRoot and TServer and TConnect.
On the third iteration, select waits(). When it eventually returns (and before Conga does anything else), RIDE stops displaying its connect screen with its “waiting” animation and brings up its session / workspace explorer / debug windows. Back in Conga, work.cpp:ExecSub() then processes TRoot and TServer and TConnect.

So I’m not exactly sure what this all means, but given that RIDE sends something to Conga twice, then waits, then sends something else to Conga, and then brings up its IDE session before Conga processes that something else, I think the key to this is in understanding why RIDE is waiting.

**Comment by e9gille** [comment]
I can replicate the issue but not sure what's behind it yet. I did update a bunch of packages recently, I'll check if it is related to that.

**Comment by DyalogRichard** [comment]
Jay has commented on some of my analysis, specifically:

> There’s a loop in Conga work.cpp:WorkThread() which calls select() (via socket.cpp:SfWait()) to wait for something to arrive from RIDE and dispatch it to work.cpp:ExecSub()

Correction: It's not necessarily waiting for something to arrive, it could be waiting for other things (like a connection).

> When you hit RIDE’s Connect button, work.cpp:WorkThread() gets called for the first time and begins looping.

Correction: it looks like it is already in that loop before you hit RIDE's Connect button.

**Comment by e9gille** [comment]
I believe this is related to #387 
I still don't know what the root cause is, but if I connect to a running interpreter, it takes about 15 seconds before it opens the session window on its own. If I connect to a running interpreter and then immediately open the Preferences from the Dyalog menu, the connection is established and the session window appears shortly after.

For some reason the internal message queue of the core net module is not processed until I send some messages on the IPC channel (which I do when opening the Preferences window).

**Comment by e9gille** [comment]
This is now somewhat better, takes 2-3 seconds on my VM. Still clueless as to why this is a problem on linux.
