### ISSUE TITLE
End of session disappears on Trace

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/ride#43]
If the input line is below the middle of the screen and you enter trace mode using ctrl+enter, the tracer grabs the bottom half of the screen, and the last half screen worth of the session is hidden. The session should be scrolled so that the bottom of the session with the input line remains visible.

**Comment by jayfoad** [comment]
Brian said:
> when I open an editor/tracer window, the session display is no longer at the bottom of the session, so I have to scroll down to the bottom when I switch to the session window
> 
> when I close an editor/tracer window, the session is not at the bottom, so, again, I need to scroll

**Comment by e9gille** [comment]
This was fixed in 69a4fcccdb2d3e8f35f5e2671ad0032c84ccc291
