### ISSUE TITLE
Edit windows have no menu bar

### ISSUE THREAD

**Issue by DyalogRichard** [Dyalog/ride#434]
### Describe the issue you are having

Edit windows have no menu bar.

At the very least there could be:

File
...Fix
...Exit (and Fix)
...Exit (and discard changes)

Edit
... Undo
... Redo
... Cut
... Copy
... Paste

### Did you connect to an already running interpreter or start the interpreter from RIDE?

Connect

### How do you reproduce the issue?

Open an edit window

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.1.3330
  Platform: Linux x86_64
  Date: 2018-06-04 16:50:49 +0100
  Git commit: 5407e4cc5de2c0e20a103e1acbbe965223f7b2b1
  Preferences:{
    "autoCloseBrackets":"0",
    "dbg":"1",
    "floatOnTop":"1",
    "floating":"1",
    "kbdLocale":"en_GB",
    "lbarOrder":"← +-×÷*⍟⌹○!? |⌈⌊⊥⊤⊣⊢ =≠≤<>≥≡≢ ∨∧⍲⍱ ↑↓⊂⊃⊆⌷⍋⍒ ⍳⍸∊⍷∪∩~ /\\⌿⍀ ,⍪⍴⌽⊖⍉ ¨⍨⍣.∘⍤@ ⍞⎕⍠⌸⌺⌶⍎⍕ ⋄⍝→⍵⍺∇& ¯⍬ ",
    "wrap":"1",
    "wse":"1"
  }

Interpreter:
  Version: 18.0.33338
  Platform: Linux-64
  Edition: Unicode/64
  Date: Jun  6 2018 at 16:21:25

**Comment by abrudz** [comment]
This is only critical for those that cannot use a mouse. They have two alternative courses of action:
1. Use context-menu key to access the edit commands, and assign keystrokes to the File commands
2. Use docked edit windows
