### ISSUE TITLE
Preferences > Windows behaves oddly

### ISSUE THREAD

**Issue by FionaDyalog** [Dyalog/ride#435]
### Describe the issue you are having
All related, hence submitting as a single issue.
1. The floating windows option is a duplicate of that in the Edit menu. Gil has suggested removing it from the menu and just leaving it here. It would be nicer for a user if a note made it clear that the settings on this tab only apply when floating windows have been selected or, alternatively, if all the fields were disabled unless floating windows were selected. Gil also commented that as you can’t use floating windows in web version, this page should be removed/disabled in that version.
2. Similarly, the offset field is only valid if "Single floating window" has not been selected – either a note to this effect or disabling this field when "Single floating window" is selected would improve the UX.
3. If "Remember previous window position" is not selected, then I would expect the posn and offset fields to have an effect but they don’t. Gil comments "You are right, I have overlooked to take this setting into account when re-opening existing windows. It ought to re-position the window according to the specified position and offset. At the moment this is only done for newly created windows."
4. Gil has stated that "The position is only used when creating new windows, not on re-opening existing windows. As RIDE never destroys windows (it merely hides them when asked to close) it means that changing this setting after having already opened 3 windows won’t affect the position of those. This is an undocumented feature, it essentially means you can position floating windows on your screen and close them, the next time you open the windows, they will appear where you had them." I find this very unintuitive. If I haven't selected "Remember previous window position" but have defined a size, position and offset, then having the first Edit window I open after setting these values ignore them is unexpected and, to my mind, incorrect (if I wanted it to follow a previous configuration I would have selected "Remember previous window position". The fact that subsequent Edit windows behave as I would expect makes the non-conformity of the first one worse.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Connect to already running

### How do you reproduce the issue?
Open the Preferences dialog box and move to the Windows tab. Play with the settings and see their effects!

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.1.3330
  Platform: Win32
  Date: 2018-06-04 16:50:49 +0100
  Git commit: 5407e4cc5de2c0e20a103e1acbbe965223f7b2b1

Interpreter:
  Version: 17.0.33293
  Platform: Windows-64
  Edition: Unicode/64
  Date: Jun  3 2018 at 20:03:03

**Comment by FionaDyalog** [comment]
Tested 1 and 2 and happy with them (not sure what's happening with the zero-footprint option though and how this tab will be displayed there).

Something a bit odd when testing 3 though. I turned off "remember previous window position and set the posn x and y to 0 with an offset. Although the offset seems to work correctly, the top left of the window is off my screen (tot he left, fine vertically) and I can't move it (see screenshot).
![image](https://user-images.githubusercontent.com/13313372/41419888-12e8731a-6feb-11e8-8f7e-586acb7973ce.png)

**Comment by e9gille** [comment]
>  Although the offset seems to work correctly, the top left of the window is off my screen (off to the left, fine vertically) and I can't move it (see screenshot).

I think I know what may cause that. I'll double check the code and will get back to you.
