### ISSUE TITLE
Preferences > General has Code folding option in incorrect category

### ISSUE THREAD

**Issue by FionaDyalog** [Dyalog/ride#436]
### Describe the issue you are having
The option to turn on/off code folding (outlining) is categorised under "Minimap" but it's nothing to do with minimaps. It doesn't really fit into any of the existing categories, so might have to go under "Other". (Aside – one of the entries under Other is "Show editor toolbar" but this applies to the Trace window as well as Edit windows. As well as changing the name of this it might be worth introducing a new category for Edit/Trace windows and having this and the code folding option under it. Just a thought though!).

### Did you connect to an already running interpreter or start the interpreter from RIDE?
irrelevant

### How do you reproduce the issue?
Open Preference > General. Scroll down to Minimap section

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.1.3330
  Platform: Win32
  Date: 2018-06-04 16:50:49 +0100
  Git commit: 5407e4cc5de2c0e20a103e1acbbe965223f7b2b1

Interpreter:
  Version: 17.0.33293
  Platform: Windows-64
  Edition: Unicode/64
  Date: Jun  3 2018 at 20:03:03

**Comment by e9gille** [comment]
Yes, I agree. Your suggestions sound good to me.

**Comment by e9gille** [comment]
Actually, I changed my mind. Looking at the settings under the `Code` tab, most of them relate to the edit/trace window, so it doesn't make sense to create a special subheading for this.

I will remove the folding option from the prefs window and leave it in the menu (as agreed in email thread).
