### ISSUE TITLE
Outdenting a line in the editor makes it and the remainder of the fn collapsible

### ISSUE THREAD

**Issue by DyalogRichard** [Dyalog/ride#437]
### Describe the issue you are having
Outdenting a line in the editor make it an the remainder of the function collapsible

### Did you connect to an already running interpreter or start the interpreter from RIDE?

Connect

### How do you reproduce the issue?

)ed x
Edit the program so that it contains
 x
 1
 2

Now move the cursor to the 1 and press backspace. It outdents 1 character and a boxed - character appears to its left. Click on it and it, and the line with the 2 on it, collapse.

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.1.3330
  Platform: Linux x86_64
  Date: 2018-06-04 16:50:49 +0100
  Git commit: 5407e4cc5de2c0e20a103e1acbbe965223f7b2b1
  Preferences:{
    "autoCloseBrackets":"0",
    "dbg":"1",
    "floatOnTop":"1",
    "floating":"1",
    "kbdLocale":"en_GB",
    "lbarOrder":"← +-×÷*⍟⌹○!? |⌈⌊⊥⊤⊣⊢ =≠≤<>≥≡≢ ∨∧⍲⍱ ↑↓⊂⊃⊆⌷⍋⍒ ⍳⍸∊⍷∪∩~ /\\⌿⍀ ,⍪⍴⌽⊖⍉ ¨⍨⍣.∘⍤@ ⍞⎕⍠⌸⌺⌶⍎⍕ ⋄⍝→⍵⍺∇& ¯⍬ ",
    "showEditorToolbar":"0",
    "wrap":"1",
    "wse":"1"
  }

Interpreter:
  Version: 18.0.33338
  Platform: Linux-64
  Edition: Unicode/64
  Date: Jun  6 2018 at 16:21:25

**Comment by e9gille** [comment]
Folding of code can't be controlled in the version of the monaco editor we use at the moment. Unfortunately there is a showstopper preventing the use of the latest version (0.13.1). I'll get back to this when this has been fixed and we can upgrade.

**Comment by e9gille** [comment]
I should add that the folding at them moment is purely based on whitespace/indentation.

**Comment by DyalogRichard** [comment]
Ok, thanks! The effect of this was made more obvious by #433 so will be less pronounced now that is fixed.

Feel free to close this; presumably "implementing code folding" is a fairly major bit of work and having this issue open may not be terribly useful.
