### ISSUE TITLE
Preferences > Windows – offset behaves oddly

### ISSUE THREAD

**Issue by FionaDyalog** [Dyalog/ride#438]
### Describe the issue you are having
I have set an offset and created multiple windows. A few features struck me as counter-intuitive:
1. If I move a the last window created, the next one I created is offset from the previous window's creation position, not its current position.
2. If I close a window, the next one I create takes its place rather than being offset from the last window created (this might be related the issue in #435 whereby windows that are closed are really only hidden).

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Connect to already running

### How do you reproduce the issue?
Open the Preferences dialog box and move to the Windows tab. Set an offset then create multipple windows and play with them!

### Paste the contents of Help → About (Shift+F1)
IDE:
Version: 4.1.3330
Platform: Win32
Date: 2018-06-04 16:50:49 +0100
Git commit: 5407e4c

Interpreter:
Version: 17.0.33293
Platform: Windows-64
Edition: Unicode/64
Date: Jun 3 2018 at 20:03:03

**Comment by abrudz** [comment]
Can't repro
