### ISSUE TITLE
Renaming a function while tracing it confuses Ride

### ISSUE THREAD

**Issue by aplteam** [Dyalog/ride#439]
Watch the attached video:
[RenamingProblem.zip](https://github.com/Dyalog/ride/files/2085624/RenamingProblem.zip)
 It demonstrates the problem.

In order to be able to upload the video I had to zip it.

I am using the built from 2018-06-08

**Comment by e9gille** [comment]
This will require a fix on the interpreter side. RIDE doesn't receive any message to update the content of the trace window, even if the effect of fixing the changes actually creates a new function and should leave the original unaltered.

**Comment by mkromberg** [comment]
This is an interpreter issue, Mantis 0018844: Renaming a function while tracing it confuses Ride (Ride issue 439)

**Comment by johndaintree** [comment]
I've committed an interpreter side fix. I don't think anything is required in RIDE.
