### ISSUE TITLE
<tab> versus <cursor-right> in autocomplete

### ISSUE THREAD

**Issue by aplteam** [Dyalog/ride#441]
`<tab>` is used as the "OK" key in the autocomplete list, but at the same time `<cursor-right>` (the default in the ODE) is doing the same thing.

Why are two keys used for this? I suggest to use just `<cursor-right>` and make the `<tab>` key behave "normal".

**Comment by e9gille** [comment]
Why? Because some users come from environments where tab is the commit character. We could make it configurable.

Do you find that you often would like to insert a tab while autocomplete suggestions are listed?

**Comment by aplteam** [comment]
I just realized that actually it could stay the way it works right now. What I want is that when the cursor is positioned at the end of this:

```
a←3
```
and I press the `<tab>` key it should jump but it does not because it is the autocomplete "OK" key. But it does when I first add a space after the `3`. But there is no autocomplete list in either case!

**Comment by e9gille** [comment]
Right, and that is what you reported in #431 
I'll close this then.

**Comment by aplteam** [comment]
Why closing it? It's not doing what it could and should do!

**Comment by e9gille** [comment]
Sorry? You just said it could stay the way it is?!
What did I miss?

**Comment by aplteam** [comment]
That both `<tab>` and `<cursor-right>` select a row in the autocomplete list can stay the way it is ;)

**Comment by e9gille** [comment]
Right, if both can stay then this issue is a duplicate of 431 and can therefore be closed. Agree?

**Comment by JohnScholes** [comment]
FWIW: on my laptop, [tab] is much easier to type than [cursor-right].

**Comment by aplteam** [comment]
@e9gille: agreed
