### ISSUE TITLE
Selecting rectangle area with the mouse via right-click

### ISSUE THREAD

**Issue by aplteam** [Dyalog/ride#442]
One really useful feature of the ODE editor is its ability to select a rectangle area anywhere on the screen by starting with a right-click.

I wonder whether it's technically possible at all to implement this in Ride...

**Comment by abrudz** [comment]
Try Ctrl+Alt+Shift+ArrowKeys.

**Comment by aplteam** [comment]
Excellent. Even better than the mouse; I had always trouble to click at the
right spot.

**Comment by abrudz** [comment]
Feature exists.

**Comment by e9gille** [comment]
It is no secret that RIDE is using the Monaco editor now, which is also the editor used in VS Code. A good place to find information about available features is on VS Code's homepage:
https://code.visualstudio.com/docs/getstarted/tips-and-tricks#_keyboard-reference-sheets

Note that some features need language specific implementation and will therefore be missing (go to definition and similar).

To make a box selection with the mouse, first place the cursor at start position, then press Shift+Alt (in Windows) and drag mouse to make a box selection.
