### ISSUE TITLE
Want to specify the default port number of the command line

### ISSUE THREAD

**Issue by aplteam** [Dyalog/ride#443]
It would be helpful to be able to do this when firing up a new instance og both Dyalog APL and Ride.

(Spawn is a good if not better alternative but as long as I cannot specify command line parameters for the APL instance I cannot use it)

**Comment by jayfoad** [comment]
@aplteam can you please explain more clearly what you want?

**Comment by aplteam** [comment]
Typo: "of" ==> "on"; now corrected

I want to start Ride and be able to specify the value of the field "Port" of the "Default" so that it is in line with the APL I fire up via code in parallel. 

Something like `-port=4256`

**Comment by e9gille** [comment]
You have 2 options (examples for Windows):

1. RIDE_SPAWN
```
>set RIDE_SPAWN=dyalog.exe&&ride.exe -- arg1 arg2
```
1. RIDE_CONNECT
```
>set RIDE_INIT=SERVE::4256&&dyalog.exe arg1 arg2
>set RIDE_CONNECT=localhost:4256&&ride.exe
```
