### ISSUE TITLE
<AO> and <DO> have no effect in the editor if issued via a PFKEY shortcut

### ISSUE THREAD

**Issue by aplteam** [Dyalog/ride#445]
They should put a `⍝` in front of the line (or lines) or remove it if there is one.

In the session they work fine.

**Comment by e9gille** [comment]
can't replicate

**Comment by e9gille** [comment]
I have talked to Kai about this issue and the error report is missing a critical detail: The commands are issued via PFKEY shortcuts.

Defining shortcuts for AO and DO directly works fine.
