### ISSUE TITLE
Ctrl+Tab tabs from edit window to session but not back again

### ISSUE THREAD

**Issue by jayfoad** [Dyalog/ride#45]
If I fire up a fresh RIDE 4 and spawn a local interpreter:
1. )ed foo opens a new editor window and focuses on it
2. Ctrl+Tab switches focus to the session, leaving the editor window open
3. Ctrl+Tab again does nothing. It should switch focus back to the editor.

Sometimes (possibly after using the tracer) RIDE gets into a state where this bug goes away, and I can switch focus in both directions.

IDE:
  Version: unknown
  Platform: Linux x86_64
  Date: unknown
  Git commit: unknown
  Preferences:{
    "favs":"[{\"type\":\"start\",\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"exe\":\"apl\"}]",
    "kbdLocale":"en_GB",
    "keys":"{\"NX\":[\"Shift-Ctrl-Right\"]}",
    "otherExe":"apl"
  }

Interpreter:
  Version: 16.0.29028
  Platform: Linux-64
  Edition: Unicode/64
  Date: Jan 19 2017 at 14:17:27

**Comment by e9gille** [comment]
I can replicate this. For some reason it works fine as soon as you blur and then focus ride again.

**Comment by jayfoad** [comment]
The problem seems to be that it has got into a state where I have two windows, D.ide.wins={0:D.Se,1:D.Ed}, and neither of them hasFocus() because they both fail the window.focused test.

**Comment by jayfoad** [comment]
This fixes it for me, but I don't know if it'll have bad side effects. In src/se.js and src/ed.js:
```
-  hasFocus:function(){return window.focused&&this.cm.hasFocus()},
+  hasFocus:function(){return this.cm.hasFocus()},
```
(And then we could probably remove the code from src/init.js that tracks focus and blur events to maintain the window.focused flag.)

**Comment by e9gille** [comment]
I don't know. You'd think @ngn had a reason for putting it in  in the first place. Do you remember the reason Nick?

**Comment by ngn** [comment]
It has to do with floating windows in older versions of RIDE.
Every floating window is a browser of its own, with its own focus management, so it used to be possible that two CM instances from different floating windows return true for `cm.hasFocus()`. The one actually focused is the one in the focused floating window.
