### ISSUE TITLE
RIDE should ask "are you sure" before exiting on a key stroke

### ISSUE THREAD

**Issue by jayfoad** [Dyalog/ride#46]
RIDE 4 on Linux exits immediately (killing my spawned interpreter) if I do any of:
* press Ctrl+Q
* press Alt+F4
* click on the x in the window decoration

All of these ought to prompt me with an "are you sure?" dialog. (But there's no need to prompt if I type )off/)continue/⎕off in the session.)

**Comment by jayfoad** [comment]
Same goes for Cmd+W on a Mac. JS said "It's very easy to lose your work by typing Cmd+w instead of Alt+w (for ⍵)."

**Comment by e9gille** [comment]
The fix I put in will prompt even on close from File menu. This is different from ODE, but does it matter?

**Comment by jayfoad** [comment]
Personally I think it's OK to prompt even on File/Quit. We can always refine the fix later.
