### ISSUE TITLE
Autocomplete for filenames does not work on files/folders starting with a digit

### ISSUE THREAD

**Issue by aplteam** [Dyalog/ride#460]

**Comment by e9gille** [comment]
Please provide a repro. It works fine when I try it.

**Comment by aplteam** [comment]
See attached Video. (Just remove ".zip" from the name - it's not  a zipped file)
[1526.mp4.zip](https://github.com/Dyalog/ride/files/2115063/1526.mp4.zip)

**Comment by e9gille** [comment]
Sorry, my bad. It works fine if you prompt for suggestions (shell style or classic with tab), it doesn't auto trigger on digits.
