### ISSUE TITLE
macOS: changes to shortcuts not reflected in menu items

### ISSUE THREAD

**Issue by FionaDyalog** [Dyalog/ride#464]
### Describe the issue you are having
Using Preferences > Shortcuts to add/delete/change a shortcut does not update the shortcuts shown in the menu items.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
default macOS Dialog icon

### How do you reproduce the issue?
Change settings in Preferences > Shortcuts and look at menu items

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.1.3363
  Platform: MacIntel
  Date: 2018-06-20 16:03:15 +0200
  Git commit: a3de78419b8cd9d07833e209b406e76b57d545ad
  Preferences:{
    "kbdLocale":"en_GB_Mac",
    "title":"{WSID}{HOST}",
    "keys":"{\"ED\":[]}"
  }

Interpreter:
  Version: 17.0.33439
  Platform: Mac-64
  Edition: Unicode/64
  Date: Jun 21 2018 at 01:18:14

**Comment by JohnScholes** [comment]
You might have to quit and restart Ride to see the changes. It would be better if they took effect on OKing/Applying the preferences dialog.

**Comment by FionaDyalog** [comment]
I was expecting dynamic changes (similar to the way in which the little keyboard icon’s shortcuts update) – having to restart to see the changes is not ideal.
