### ISSUE TITLE
RIDE with spawned interpreter should show banner at top of session window

### ISSUE THREAD

**Issue by jayfoad** [Dyalog/ride#47]
When starting a session (for a demo), WIBNI the banner appeared at the top, rather than the bottom, which reveals the prior session log.

**Comment by JasonRivers** [comment]
I think this is actually a bug, IIRC @flouc001 had solved this at one point, but it appears to have come back at some point.

**Comment by jayfoad** [comment]
Needs interpreter/protocol changes. Currently RIDE can't distinguish the banner from all the rest of the session log history it is sent.

**Comment by johndaintree** [comment]
It's trivial for me to change 16.0 to use a "SessionLog" message instead of "AppendSessionOutput" (same parameters), if that's all that is required at the interpreter end.

**Comment by johndaintree** [comment]
Separating the "banner" part from the history might be difficult though.

**Comment by e9gille** [comment]
@johndaintree Adding SessionLog would actually be a good enough solution. We could then prepend that to the log rather than appending. If you then wanted to transfer it in chunks (if log is large) we would expect most recent to arrive first. Essentially it would be a "PrependSessionOutput" command.

**Comment by e9gille** [comment]
I have added the ReplyGetLog to the RIDE side and changed the way the banner is scrolled to in 1b536c1b54cbb9592c411a2f5ae72a5731b4c7f9 . This should fix this issue for now.
