### ISSUE TITLE
Ride 4.1 installes now several times

### ISSUE THREAD

**Issue by aplteam** [Dyalog/ride#477]
### Describe the issue you are having

Since the Ride folder stopped carrying the version number incl the build number  it installs under the exact same name again when a new build is provided. Shouldn't it either replace the old version or add the build number to the name of the program?

![ride](https://user-images.githubusercontent.com/16479389/42308511-ae8564b6-802d-11e8-891b-d36e60aed222.png)

**Comment by jayfoad** [comment]
Yes, as described here: https://github.com/Dyalog/ride/issues/420#issuecomment-395399614
