### ISSUE TITLE
Debugger does not have Go Back One Line and Skip Current Line icons...

### ISSUE THREAD

**Issue by bpbecker** [Dyalog/ride#479]
The Windows debugger has icons to Go Back One Line and to Skip Current Line.
As far as I can tell there are no similar icons in the RIDE debugger.
IDE:
  Version: 4.1.3363
  Platform: Win32
  Date: 2018-06-20 16:03:15 +0200
  Git commit: a3de78419b8cd9d07833e209b406e76b57d545ad
Interpreter:
  Version: 17.0.33663
  Platform: Windows-64
  Edition: Unicode/64
  Date: Jul 10 2018 at 20:06:50

**Comment by jayfoad** [comment]
True, but they were removed deliberately in #230 in favour of having a "skip to this line" context menu item, which I thought was a better UI. The BK and FD keystrokes are still available.

**Comment by e9gille** [comment]
Can we close this issue?

**Comment by e9gille** [comment]
Shout if you want this put back in.
