### ISSUE TITLE
Ctrl+Enter on a blank line makes cursor disappear

### ISSUE THREAD

**Issue by jayfoad** [Dyalog/ride#48]
On Linux RIDE with a local spawned interpreter, if I hit Ctrl+Enter on a blank line in the session then the cursor disappears! I can still type into the session, but the cursor doesn't reappear until the next time I hit Enter.

IDE:
  Version: unknown
  Platform: Linux x86_64
  Date: unknown
  Git commit: unknown
  Preferences:{
    "favs":"[{\"type\":\"start\",\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"exe\":\"apl\"}]",
    "kbdLocale":"en_GB",
    "keys":"{\"NX\":[\"Shift-Ctrl-Right\"]}",
    "otherExe":"apl"
  }

Interpreter:
  Version: 16.0.29028
  Platform: Linux-64
  Edition: Unicode/64
  Date: Jan 19 2017 at 14:17:27

**Comment by jayfoad** [comment]
N.B. In the ODE Ctrl+Enter on a blank line in the session will switch to an open tracer window if there is one, else do nothing. Dunno if RIDE needs to duplicate that behaviour.

**Comment by JasonRivers** [comment]
I feel duplicating what the ODE does is a good idea, It's what people are most likely going to be used to, and this is one of those small things that people that don't use won't care and people that do use will want the behaviour to be the same.

**Comment by flouc001** [comment]
@jayfoad the cursor will no longer dissapear... working on switching to tracer.

**Comment by jayfoad** [comment]
> working on switching to tracer

Thanks. There are actually two cases:

1. If there is already a trace window open, switch to it, just like Ctrl+TAB would.
2. If you are suspended but the tracer is not open yet, open it. This one has to work, because there is no other way to open the tracer in this situation.

A test case for (2): run the interpreter **without** TRACE_ON_ERROR=1, load dfns.dws, do "1 ⎕STOP'queens'" then "queens 4". At this point you'll be suspended in the "queens" function but the tracer won't be open yet.

**Comment by e9gille** [comment]
The 95badff00a0afd220ca2b9345b5ac11eca86960b commit fixes scenario (1) above. Not sure how to do (2)...
