### ISSUE TITLE
Each time RIDE starts it creates, but does not delete, a file in /tmp 

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/ride#481]
This may be a non-Windows only issue; it has been seen on both Linux and macOS.

ls /tmp | grep -c ride

start RIDE or RIDE&APL and terminate

ls /tmp | grep -c ride
one more file in there now

RIDE 4.1.3366
Interpreter 17.0.33756 (17.0 first release)

**Comment by e9gille** [comment]
These are indeed socket files. I don't know much about how they work, but I would expect them to be removed by the process upon termination. At first glance in node documentation it suggests there are instances when these files are not removed and it will need to be done manually.

**Comment by e9gille** [comment]
in master branch
