### ISSUE TITLE
Segmentation fault when running RIDE 4.1

### ISSUE THREAD

**Issue by dlozeve** [Dyalog/ride#484]
### Describe the issue you are having
When I try to install RIDE and run it, I run into a segmentation fault.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
(cannot start RIDE)

### How do you reproduce the issue?
From the precompiled `deb` file: install, and then run `/opt/ride-4.1/Ride-4.1`: segmentation fault.

When cloning the git repo, I run `npm i` then `npm start`, nothing happen:

```
$ npm start --verbose
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node', '/usr/bin/npm', 'start', '--verbose' ]
npm info using npm@6.3.0
npm info using node@v10.8.0
npm verb run-script [ 'prestart', 'start', 'poststart' ]
npm info lifecycle ride42@4.2.0~prestart: ride42@4.2.0
npm info lifecycle ride42@4.2.0~start: ride42@4.2.0

> ride42@4.2.0 start /home/dimitri/builds/ride
> electron .

npm verb lifecycle ride42@4.2.0~start: unsafe-perm in lifecycle true
npm verb lifecycle ride42@4.2.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/dimitri/builds/ride/node_modules/.bin:/home/dimitri/.local/bin:/home/dimitri/.gem/ruby/2.4.0/bin:/home/dimitri/.cargo/bin/:/home/dimitri/bin:/home/dimitri/.local/bin:/home/dimitri/.gem/ruby/2.4.0/bin:/home/dimitri/.cargo/bin/:/home/dimitri/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/cuda/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/dimitri/dev/embedded/esp/xtensa-esp32-elf/bin:/home/dimitri/anaconda3/bin:/home/dimitri/dev/embedded/esp/xtensa-esp32-elf/bin:/home/dimitri/anaconda3/bin
npm verb lifecycle ride42@4.2.0~start: CWD: /home/dimitri/builds/ride
npm info lifecycle ride42@4.2.0~poststart: ride42@4.2.0
npm verb exit [ 0, true ]
npm timing npm Completed in 1222ms
npm info ok 
```
When I build with `node mk dist` and run the resulting binary, I get a segmentation fault.

System info: up-to-date Arch Linux, Node 10.8.0, Electron 2.0.7 (not sure if this is relevant).

RIDE 4.0, installed from the precompiled `.deb`, worked correctly.

### Paste the contents of Help → About (Shift+F1)
(not applicable)

**Comment by jayfoad** [comment]
@dlozeve I assume this is x86-64 Linux, yes? What sort of hardware are you running on? What CPU?

**Comment by dlozeve** [comment]
Yes, I run x86_64 Linux, on an Intel i7-7500U CPU.

**Comment by jayfoad** [comment]
This is an electron bug: electron/electron#13972

**Comment by dlozeve** [comment]
This is solved on up-to-date Arch Linux.

**Comment by jayfoad** [comment]
This affects Ubuntu 18.10. RIDE 4.1 is using Electron 2.0.2. @e9gille could we update it to Electron 2.0.8, which has a [fix](https://electronjs.org/releases#2.0.8)?

**Comment by e9gille** [comment]
Certainly, I'll upgrade to latest version (2.0.16).

**Comment by jayfoad** [comment]
Thanks, that works for me!
