### ISSUE TITLE
macOS: clicking on close button closes session without prompting

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/ride#485]
In all previous versions on macOS, and in the IDE clicking on the close button of the session results in a popup/drop down appearing asking whether you want to Quit APL.  In 17.0/RIDE 4.1 you just get taken straight out.

IDE:
  Version: 4.1.3366
  Platform: MacIntel
  Date: 2018-07-17 15:26:35 +0100
  Git commit: 0088ce492350a8d582b019adfc5d5a87efbdc00b
  Preferences:{
    "floatSingle":"0",
    "floating":"1",
    "kbdLocale":"en_GB_Mac"
  }

Interpreter:
  Version: 17.0.33948
  Platform: Mac-64
  Edition: Unicode/64
  Date: Aug 14 2018 at 01:21:42

**Comment by e9gille** [comment]
fixed in f2ff94dfa77359e79de154bcf3d028fdc68da8c0
