### ISSUE TITLE
Session popup menu hides behind trace window (if it's open).

### ISSUE THREAD

**Issue by johndaintree** [Dyalog/ride#487]
### Describe the issue you are having
I have the tracer open (in the bottom of the session), select some text, and use the menu to copy.
Then, I click at the bottom of the session and right click to get the menu for Paste. However most of the menu is hidden behind the trace window. I need to scroll the session and right click a second time to be able to see the paste menu item.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Neither of these things. RIDE started an interpreter for me.

### How do you reproduce the issue?
see above,

<img width="1680" alt="screen shot 2018-09-25 at 10 39 52" src="https://user-images.githubusercontent.com/10829577/46006633-e181f380-c0af-11e8-81e6-5c4b8064978c.png">

### Paste the contents of Help → About (Shift+F1)
 (No Help->About on MACOS)

IDE:
  Version: 4.1.3366
  Platform: MacIntel
  Date: 2018-07-17 15:26:35 +0100
  Git commit: 0088ce492350a8d582b019adfc5d5a87efbdc00b
  Preferences:{

  }

Interpreter:
  Version: 17.0.34414
  Platform: Mac-64
  Edition: Unicode/64
  Date: Sep 25 2018 at 01:38:29

**Comment by e9gille** [comment]
Value tip on hover also gets clipped as reported in #501

**Comment by abrudz** [comment]
Fixed by RIDE 4.4
