### ISSUE TITLE
Copy and paste from Safari to RIDE loses the line endings

### ISSUE THREAD

**Issue by jayfoad** [Dyalog/ride#491]
@johndaintree reported that copying APL code from Safari(?) displaying http://docs.dyalog.com/14.1/Dyalog%20APL%20R%20Interface%20Guide.pdf into RIDE loses the line endings, so the code ends up all on the same line.

<img width="1680" alt="screen shot 2018-09-25 at 10 12 44" src="https://user-images.githubusercontent.com/108316/46540673-ee71c480-c8b1-11e8-9f7f-33925c0021e4.png">

It looks like the high minus hasn't pasted properly either.

**Comment by e9gille** [comment]
As far as I can tell this wont fix as it depends on the PDF reader used. I have tested Chrome's built in PDF reader, Safari's and Preview (I think Safari uses Preview), all on MacOS, and only Chrome includes the correct number of line breaks. The other 2 don't provide enough breakpoints in the clipboard, so there is little I can do about that.

**Comment by jayfoad** [comment]
> The other 2 don't provide enough line breaks in the clipboard

Can you actually inspect the content of the clipboard to confirm that?

**Comment by e9gille** [comment]
That is what I did. I don't know if there's a way you can generate the PDF's ina  Preview compatible way, but there is nothing I can do from RIDE.
