### ISSUE TITLE
Language bar double height

### ISSUE THREAD

**Issue by rikedyp** [Dyalog/ride#493]
### Describe the issue you are having

Language bar is double height

![image](https://user-images.githubusercontent.com/9338369/47012083-55596e00-d13b-11e8-94a0-ef1f2fbf777f.png)

### Did you connect to an already running interpreter or start the interpreter from RIDE?
env RIDE_SPAWN=/usr/bin/dyalog /usr/bin/ride-4.1 

### How do you reproduce the issue?
See above. NB am running virtual machine

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.1.3366
  Platform: Linux x86_64
  Date: 2018-07-17 15:26:35 +0100
  Git commit: 0088ce492350a8d582b019adfc5d5a87efbdc00b
  Preferences:{
    "kbdLocale":"en_GB"
  }

Interpreter:
  Version: 17.0.34137
  Platform: Linux-64
  Edition: Unicode/64
  Date: Aug 31 2018 at 10:58:46

**Comment by e9gille** [comment]
The language bar ends with a blank space that you can use to drag and drop to split an existing group. That space doesn't fit on the top row and causes the language bar to take up 2 rows. Try zooming one step and it will fit.
