### ISSUE TITLE
Enter on Connect window should connect to the APL session

### ISSUE THREAD

**Issue by JasonRivers** [Dyalog/ride#50]
Pressing 'enter'/'return' on the keyboard when in the Connect window with focus on the "host" should connect to that host. Currently one has to use the mouse to click "Go".

**Comment by flouc001** [comment]
@JasonDyalog I have added keyboard handling to the host fields. Are there any other fields you think I should add the handling to?

**Comment by JasonRivers** [comment]
@flouc001 Probably the "port" field, too on a connect, and on "start an interpreter" probably on the interpreter field "cn_exe", on Listen probably an idea on the Port field, too.
