### ISSUE TITLE
RIDE 4.[12]: attempting to get list of installed interpreters on AIX server frequently does nothing

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/ride#500]
Start RIDE 4.1 or 4.2

"Start" over "SSH"
hostname: p8-72qa
set username and password
hit the Refresh/find button

Button is greyed out
Nothing else happens for a considerable time .. a timeout msgbox appears after ?10-15 minutes?.

This is not consistent - sometimes I can get the list first time.

Typing the path to the interpreter I want to use does work.

Same with 4.1.3379.

IDE:
  Version: 4.2.3379
  Platform: Win32
  Date: 2018-10-30 08:27:53 +0000
  Git commit: 7b046167ca6cab996fcd7753e41102da5fa1ea43
  Preferences:{
    "kbdLocale":"en_US",
    "otherExe":"/opt/mdyalog/18.0/64/unicode/p8/mapl"
  }

Interpreter:
  Version: 18.0.34813
  Platform: AIX-64
  Edition: Unicode/64
  Date: Nov 20 2018 at 00:35:15

**Comment by dyaandys** [comment]
Jay has just seen this when using RIDE 4.2 from his Linux box.

**Comment by e9gille** [comment]
@jayfoad do you have anything to add on this one? Is it only happening when you try starting over SSH?
