### ISSUE TITLE
Docked windows: ⎕pw is reset when you open or close the editor

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/ride#502]
⎕pw←3000
foo [ED]
      ⎕pw
86
close the editor
      ⎕pw
177

Think that that is changing rather too often.

IDE:
  Version: 4.2.3379
  Platform: Win32
  Date: 2018-10-30 08:27:53 +0000
  Git commit: 7b046167ca6cab996fcd7753e41102da5fa1ea43
  Preferences:{
    "kbdLocale":"en_US",
    "otherExe":"/opt/mdyalog/18.0/64/unicode/p8/mapl"
  }

Interpreter:
  Version: 18.0.34813
  Platform: AIX-64
  Edition: Unicode/64
  Date: Nov 20 2018 at 00:35:15

**Comment by e9gille** [comment]
⎕PW is set on every resize of the session window. Would it be better if we only set it once (on create) and then added a command to set it to available width?

**Comment by dyavc** [comment]
Hi Gil,

I think some people might also like ⎕PW to be set in dyalog.config (on the Mac) or session file (windows) and it not to change.  I have had a customer report to that effect.

Regards,

Vince

**Comment by e9gille** [comment]
Fixed in ab3584569bcf49313faa812ed5af3d417cd36242
