### ISSUE TITLE
The tracer, when opened on a function which will not fit in the tracer window, shows the bottom 1/2 of line 1, and nothing of line 0

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/ride#505]
The tracer, when opened on a function which will not fit in the tracer window, shows the bottom 1/2 of line 1, and nothing of line 0.  If you Up Cursor immediately after having opened the tracer, you'll scroll to line 0.

If the function has fewer lines than the size of the trace window all is ok

      ⎕fx(⊂'foo'),⍕¨⍳50
      foo [TC]

IDE:
  Version: 4.2.3389
  Platform: Win32
  Date: 2018-11-24 00:46:44 +0100
  Git commit: dbb5f3c4296c1e3e19b95903cf40e124d06ac4eb
  Preferences:{
    "connectFav":"1",
    "kbdLocale":"en_US",
    "sbar":"0",
    "selectedExe":"/opt/mdyalog/17.0/64/unicode/mapl"
  }

Interpreter:
  Version: 18.0.34751
  Platform: Windows-64
  Edition: Unicode/64
  Date: Nov  8 2018 at 21:15:37

**Comment by e9gille** [comment]
This is also a problem when opening the editor on a line in a larger script, even with a big window. Fixed in master.
