### ISSUE TITLE
)ed existing file has difficulties...

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/ride#509]
### Describe the issue you are having
Trying to edit an existing file:
`)ed /Users/mbaas/Desktop/Git/{repo}/foo.dyalog`
to which RIDE (MacOS) responds with a confirmation-dialog "The specified file does not exist. Do you want to create it?"
(I verified existence of file from within Dyalog with NEXISTS...)
Confirming creation of the file then leads to an error:

> There was an error ("FILE NAME ERROR") with the specified file

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Started new interpreter.

### How do you reproduce the issue?
)ed "some file"

### Paste the contents of Help → About (Shift+F1)
```
IDE:
  Version: 4.1.3367
  Platform: MacIntel
  Date: 2018-10-08 09:18:20 +0100
  Git commit: 583ec5b75b640d1f95d06d8e62e1a4f2ec80b693
  Preferences:{
    "kbdLocale":"de_DE",
    "prefixKey":"<"
  }

Interpreter:
  Version: 17.0.34979
  Platform: Mac-64
  Edition: Unicode/64
  Date: Dec 13 2018 at 01:17:20
```

**Comment by e9gille** [comment]
I don't know either. I would have thought it shouldn't be required unless there are spaces in the path. Either way, this is an interpreter side issue. I'll report to Dyalog.

**Comment by dyavc** [comment]
I can reproduce it in Dyalog for Windows 17.0.35664 Unicode 64-bit with no RIDE involvement.

I have logged this as 16987.  Gil, can you close this RIDE 509 issue please?
