### ISSUE TITLE
Add an SI Stack window

### ISSUE THREAD

**Issue by jayfoad** [Dyalog/ride#52]
Add an SI stack window, like in the ODE. There is a GetSIStack message in the protocol for this.

**Comment by jayfoad** [comment]
There is a GetSIStack message in the protocol.

**Comment by e9gille** [comment]
@jayfoad should we not also add the stack drop-down list in the tracer?

@johndaintree does the protocol allow for RIDE to request switching to another item in the stack?

**Comment by johndaintree** [comment]
>>> @johndaintree <https://github.com/johndaintree>  does the protocol allow for RIDE to request switching to another item in the stack?

Nope.

/JD

**Comment by e9gille** [comment]
@johndaintree I thought as much, but presumably it is something you'd like to add, right?

**Comment by johndaintree** [comment]
Sure, we can add it.

 

/JD

**Comment by jayfoad** [comment]
> @jayfoad should we not also add the stack drop-down list in the tracer?

No, I don't want this. It seems like duplicating functionality that you can get by opening the stack window. And I don't think we should add it **just** because the ODE has it.
