### ISSUE TITLE
Tracer; the contents of the hint shown when hovering over a name are wrong and hint is wrong shape

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/ride#531]
⎕fix ':Namespace ns'  '∇foo'  '1'  '∇'  ''  '∇goo'  '2'  '    ∇'  ''  ':EndNamespace'
      ns.foo TC
move mouse over foo
hint shows :Endnamespace
move mouse over goo
hint shows
    ∇

    ∇ goo
      2
    ∇

:EndNamespace

In both cases I think there's more text further up the hint.

IDE:
  Version: 4.2.3425
  Platform: Win32
  Date: 2019-04-04 08:49:30 +0200
  Git commit: ab3584569bcf49313faa812ed5af3d417cd36242
  Preferences:{
    "connectFav":"5",
    "kbdLocale":"en_US",
    "otherExe":"/dyalog/Dyalog-17.1.app/Contents/Resources/Dyalog/mapl",
    "sbar":"0",
    "selectedExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 17.1 Unicode\\dyalog.exe"
  }

Interpreter:
  Version: 17.1.36202
  Platform: Windows-64
  Edition: Unicode/64
  Date: Apr 14 2019 at 20:01:34

it's the same with an AIX interpreter 36215

**Comment by e9gille** [comment]
I can replicate that. We had the same issue with the context menu when it was HTML based. The hover is placed based on the entire application window, but gets clipped by its container (which when tracing is typically not very high). I don't know of any trivial solution to this.
