### ISSUE TITLE
Cannot Close Edit Windows

### ISSUE THREAD

**Issue by ndrogers** [Dyalog/ride#533]
When in a remote ride session:
`[Violation] 'setTimeout' handler took 1801ms`

Cannot close edit windows. 

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Start new interpreter remotely

### How do you reproduce the issue?
Start a new interpreter remotely, open an edit window, make changes, attempt to close the window.  Esc does nothing, and clicking close and yes to save changes gives me the following in the console `[Violation] 'setTimeout' handler took 1801ms`

### Paste the contents of Help → About (Shift+F1)
```
IDE:
  Version: 4.1.3366
  Platform: Win32
  Date: 2018-07-17 15:26:35 +0100
  Git commit: 0088ce492350a8d582b019adfc5d5a87efbdc00b
  Preferences:{
    "blockCursor":"1",
    "kbdLocale":"en_US",
    "keys":"{\"AC\":[\"Alt-Shift-A\"],\"BK\":[\"Alt-Up\"],\"DMN\":[\"Alt-N\"],\"DMP\":[\"Alt-B\"],\"DMR\":[\"Alt-D\"],\"FD\":[\"Alt-Down\"]}",
    "title":"{WSID} {PROFILE} ",
    "zoom":"4"
  }

Interpreter:
  Version: 17.1.36090
  Platform: Linux-64
  Edition: Unicode/64
  Date: Apr  2 2019 at 01:27:19

```

**Comment by abrudz** [comment]
Can't repro. If you can, please reopen.
