### ISSUE TITLE
Browser mode

### ISSUE THREAD

**Issue by jibanes** [Dyalog/ride#535]
Could you document how to run ride in a browser window, I think you refer this as the "zero footprint" mode. Thank you.

**Comment by jayfoad** [comment]
The official documentation is at http://docs.dyalog.com/17.0/RIDE%20User%20Guide.pdf -- see sections 3.2.1, 4.1.4 and Appendix B. Unfortunately it is a little out of date and makes the process sound more complicated than it really is. So here's an updated quickstart guide:

1. Install Dyalog and the corresponding version of RIDE (e.g. RIDE 4.1 for Dyalog 17.0) in its default location.
2. Start Dyalog with something like RIDE_INIT=http:*:4502. * means listen on all interfaces and 4502 is an arbitrary port number. The process for setting RIDE_INIT is different between different platforms: on Linux it's an environment variable, on Windows you can set it on the command line, and on the Mac you'd typically add it to ~/.dyalog/dyalog.config.
3. Point your browser at localhost:4502.

We'll get the official docs updated too.

**Comment by jibanes** [comment]
Thank you!

**Comment by lstefano71** [comment]
When you say "default location", what do you mean exactly? :-)
I mean: if we don't install the interpreter nor Ride, but simply copy files around, which files should be put where for this to work? And it would be useful for the "where" to be qualified relatively to the location of the dyalog(rt).exe being executed. Thank you in advance...

**Comment by jayfoad** [comment]
@lstefano71 a default installation of RIDE 4.1 on Windows puts index.html in [FOLDERID_UserProgramFiles](https://docs.microsoft.com/en-us/windows/desktop/shell/knownfolderid)\Dyalog\Ride-4.1\resources\app\index.html (see #420). You would either have to put it in the same place, or start APL with RIDE_INIT set to load a config.ini file with HttpDir set to the appropriate directory (see Appendix B of the RIDE User Guide). In both cases, the location of dyalog.exe is irrelevant.

**Comment by FionaDyalog** [comment]
The RIDE User Guide (version 4.2, associated with Dyalog version 17.1) has been updated to be more explicit about configuring and running the Zero Footprint RIDE.

**Comment by lstefano71** [comment]
I see. The RIDE_INIT=config and the HttpDir were the missing bits for me. To be honest, they are mentioned in the docs so they should have been enough. Shame on me. 
One of these days I'll have to test if they can be specified also via the 3502 i-beam (we have too many and too unpredictable sessions to be able to pre-assign all the ports, or, even worse, to create dozens of different config files). If the i-beam is a no go, I'll make sure to raise an RFC. Thank you again.
