### ISSUE TITLE
Rename a field in the RIDE-Session dialog box

### ISSUE THREAD

**Issue by FionaDyalog** [Dyalog/ride#536]
### Describe the issue you are having
A field in the RIDE-Session dialog box ought to be renamed (occurs in two places)

### Did you connect to an already running interpreter or start the interpreter from RIDE?
n/a

### How do you reproduce the issue?
Open the RIDE-Session dialog box and select Start from the Type drop-down list. Irrespective of the security protocol setting, there is a fild called "Environment variables". After extensive discussions we decided that these would always be named "Configuration parameters" in the documentation (not fully implemented yet but a work in progress!) – for consistency it would be nice if this ttweak could be made in the UI too. (Sounds petty, but there are numerous possible names and ways of setting these on different operating systems and configuration parameters was the most accurate cover-all that we could come up with! Definitely not environment variables...don't want anything that encourages Windows users to play with those!)

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.2.3422
  Platform: Win32
  Date: 2019-04-01 12:22:09 +0200
  Git commit: 0ca733456fca430c3112d2eb19308480fda99eee
  Preferences:{
    "kbdLocale":"en_GB"
  }

**Comment by jayfoad** [comment]
Yeah but, "environment variables" accurately describes what RIDE is gonna do with the values you put in that box. It's gonna set them in the environment of the spawned process, even on Windows. So at the moment you kinda have to know that on Windows you should put things like "MAXWS=999M" in the Arguments box, and on Linux you should put things like that in the Environment variables box.

Perhaps you'd like the connection page to work at a slightly higher level of abstraction: it could have a single box called Configuration parameters, and it could magically know whether to pass them to the APL process as command line arguments or as environment variables. But that's quite a bold change, and I'm sure some users would still want the ability to explicitly specify some things as either command line arguments or as environment variables.
