### ISSUE TITLE
ZF RIDE Cannot close and fix with the editor  

### ISSUE THREAD

**Issue by bpbecker** [Dyalog/ride#537]
While testing a MiServer website running in a Docker container:

- I use Zero-Footprint RIDE to access the session.
- I type )ed foo
- I get a docked editor window in which I make a change
- The Circle-X icon (save and return) does nothing
- The "x" to close the tab brings up a dialog to save the changes to foo
-- Clicking yes closes the dialog but neither fixes the function in the workspace, nor closes the editor window
-- Clicking no closes the dialog and the editor window (as expected)
-- Clicking cancel closes the dialog and keeps the editor window open (as expected)

IDE: 4.2.3427
Interpreter: 17.1.36338 Linux Unicode 64bit

**Comment by e9gille** [comment]
I suspect this is related to the threading issues reported (#626 #627) as it works as expected without threads running.

**Comment by mkromberg** [comment]
No longer reproduces in RIDE 4.4 and Dyalog APL 18.1.39916 (pre-releases).
