### ISSUE TITLE
double clicking function name does not behave properly after reopening editor window

### ISSUE THREAD

**Issue by ndrogers** [Dyalog/ride#538]
![image](https://user-images.githubusercontent.com/49650395/58294151-caea8400-7d85-11e9-8953-91a157f621cf.png)

When using the editor window, I am able to double click a function name to open that function in a new editor window. When exiting the window, and reopening the editor window, functions which take character vectors as an argument are formatted from this

`nest '_rels'`

To this

`nest'_rels'`

When double clicking nest now, nest is not opened in a new editor window, instead `nest'_rels'` are now highlighted as in the above image.

**Comment by e9gille** [comment]
Just tested in master and can't replicate. Might have been fixed by update of monaco editor.
