### ISSUE TITLE
Mouse-pointer should change to "Vertical Resize" when hovering over splitter between edit window and session

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/ride#54]
![2017-01-25_19-01-18](https://cloud.githubusercontent.com/assets/5645494/22303522/eed164ae-e333-11e6-9e36-dc3d2e8448c5.png)

see screenshot...

IDE:
  Version: 4.0.2611
  Platform: Win32
  Date: 2017-01-17 09:27:04 +0000
  Git commit: ce39e769dbef50395b3b38b4be1dc78287434ad5
  Preferences:{
    "favs":"[{\"type\":\"start\",\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"host\":\"localhost\",\"exe\":\"C:\\\\Program Files\\\\Dyalog\\\\Dyalog APL-64 16.0 Unicode\\\\dyalog.exe\",\"args\":\"inifile=\\\"SOFTWARE\\\\Dyalog\\\\Dyalog APL/W-64 16.0 Unicode\\\"\\nC:\\\\Program Files\\\\Dyalog\\\\Dyalog APL-64 16.0 Unicode\\\\Samples\\\\ole\\\\ado.dws\"}]",
    "kbdLocale":"en_US",
    "selectedExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 16.0 Unicode\\dyalog.exe",
    "wse":"1"
  }

Interpreter:
  Version: 16.0.29046
  Platform: Windows-64
  Edition: Unicode/64
  Date: Jan 23 2017 at 18:32:43

**Comment by jayfoad** [comment]
I can reproduce this on Linux. I get "horizontal resize" pointers, but not "vertical resize".

On the [GoldenLayout demo page](https://www.golden-layout.com/) I get both kinds of pointers.

**Comment by jayfoad** [comment]
Caused by e73f883727e1017aec68d1b80ed9578e87664753 deliberately overriding the width of a drag handle to be 8px instead of 100% of the width of the splitter. @ngn do you remember why?

**Comment by ngn** [comment]
It must have seemed too narrow. Then I probably forgot then that vertical splits exist...

**Comment by jayfoad** [comment]
Works for me, thanks!
