### ISSUE TITLE
Classic interpreter: ⎕u2286 and similar appear in error colour

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/ride#541]
⎕FX,⊂'f←{' '⎕u2286 ⍵}'
      )ed f

⎕u2286 is in red.  But
      a←201⌶⍬
      200⌶⎕nr'f'
 22 19 146  13 13 13 13 13 13 3 10 149
      a[13;]
 Global token                   12  MINI⌷QUADCON   141

IDE:
  Version: 4.2.3432
  Platform: Win32
  Date: 2019-05-24 12:10:06 +0100
  Git commit: 3be9ea797d360ddb13d87752f36752316f1e19fa
  Preferences:{
    "selectedExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 16.0 Classic\\dyalog.exe"
  }

Interpreter:
  Version: 17.1.36365
  Platform: Windows-64
  Edition: Classic/64
  Date: Jun  2 2019 at 19:44:41

**Comment by e9gille** [comment]
#702  duplicates this
