### ISSUE TITLE
Can get a Gtk-Message about transient parent being discouraged

### ISSUE THREAD

**Issue by dyavc** [Dyalog/ride#543]
### Describe the issue you are having
If you start Ride from within a command shell, Gtk-Message about transient parent e.g.:  "Gtk-Message: 16:52:42.458: GtkDialog mapped without a transient parent. This is discouraged."

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Start an interpreter 

### How do you reproduce the issue?
start ride from within a command shell like xterm or Terminal
Start dyalog
For a user, in dyalog, )ed foo, changing it and closing it causes this issue

Alternatively, click on the X close button and say No to the dialog which asks if you want to close Dyalog.
### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.2.3432
  Platform: Linux x86_64
  Date: 2019-05-24 12:10:06 +0100
  Git commit: 3be9ea797d360ddb13d87752f36752316f1e19fa
  Preferences:{
    "kbdLocale":"en_GB"
  }

Interpreter:
  Version: 17.1.36353
  Platform: Linux-64
  Edition: Unicode/64
  Date: May 30 2019 at 01:11:22

**Comment by jayfoad** [comment]
Might be electron/electron#12423.

**Comment by dyavc** [comment]
Ah, thanks Jay!

**Comment by ckerr** [comment]
Closing duplicate issue.

**Comment by michael-ryan** [comment]
@ckerr I think you forgot to close it :)
