### ISSUE TITLE
Multiple threads: syserror 162 code 0

### ISSUE THREAD

**Issue by lstefano71** [Dyalog/ride#544]
### Issue
Interacting with the Threads pane causes the interpreter to crash with a syserror 162 code 0.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Irrelevant.

### How do you reproduce the issue?
The following syserror was reproduced in Dyalog 32 bits classic 17.0.34605 under Windows with both Ride 4.0 and the latest 4.1.
 
Just start a new interpreter session via Ride (or connect to an existing one via Ride).
Make sure Ride has the “Show Debug” pane active.
 
Execute the following in the session:
 
```apl
     ⎕tget&¨⍳10
```
 
And refresh the Threads pane if the freshly created threads are not visible.
 
Now click on one of the threads (like Tid: 1).
The interpreter crashes immediately with a syserror 162 code 0.

**Comment by lstefano71** [comment]
Problem still present. Repro-ed in Version: 17.1.36847.0 64 Unicode with Ride 4.2 (though the Ride version should be irrelevant giving that it's the interpreter that goes belly up).

**Comment by e9gille** [comment]
Can't replicate. Tested on:
Dyalog APL/W-64 Version 17.1.38770
Dyalog APL/W-64 Version 18.0.39845
Dyalog APL/W-64 Version 18.1.39916
