### ISSUE TITLE
F1 should point to the relevent version on help.dyalog.com

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/ride#546]
Currently when you hit F1 in RIDE4.2 the help page that is opened is for version 17.0.

Better would be to open the help pages for the version which the current RIDE session is pointing to.  That could mean that if one RIDE instance has sessions open on different versions of Dyalog then F1 will take you to different pages (or rather different versions of the same page) but that seems reasonable.

Only slight downside of doing this is that we may need to publish the help pages for the trunk (next) version of Dyalog earlier than before, but that is acceptable.
 

IDE:
  Version: 4.2.3432
  Platform: Win32
  Date: 2019-05-24 12:10:06 +0100
  Git commit: 3be9ea797d360ddb13d87752f36752316f1e19fa
  Preferences:{
    "otherExe":"/dyalog/Dyalog-18.0.app/Contents/Resources/Dyalog/mapl",
    "selectedExe":"/opt/mdyalog/17.1/64/classic/mapl"
  }

**Comment by e9gille** [comment]
fixed in 67dc2955569504b8cc75ae19da81e26a410b09dd
