### ISSUE TITLE
WIBNI the Help and DocCentre MenuItems on the Help Menu pointed to the relevent version's pages

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/ride#549]
If you now hit F1 on any primitive you are taken to the help page for that primitive for the version that you are currently running (resolved #546).

WIBNI the Help-> Dyalog Help and Help -> Documentation Centre links did the same.

https://help.dyalog.com/17.1
https://www.dyalog.com/documentation_171.htm   (no "." in the version !)

IDE:
  Version: 4.2.3437
  Platform: Win32
  Date: 2019-08-13 14:55:17 +0200
  Git commit: 691f47856e05a36f70847313b23e061a0cf95392
  Preferences:{
    "connectFav":"6",
    "kbdLocale":"en_US",
    "otherExe":"/opt/mdyalog/17.1/64/classic/p9/mapl",
    "selectedExe":"/opt/mdyalog/17.1/64/classic/mapl"
  }

Interpreter:
  Version: 17.1.36845
  Platform: Linux-64
  Edition: Unicode/64
  Date: Aug 15 2019 at 00:13:45

**Comment by e9gille** [comment]
I believe this has already been corrected and works as requested.
