### ISSUE TITLE
Language-Bar should show glyphs in same order as in ODE

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/ride#55]
For most glyphs it is ok, but there are some differences:
![2017-01-25_19-32-24](https://cloud.githubusercontent.com/assets/5645494/22303823/42e26074-e335-11e6-88d5-6075a1b11444.png)

Also, in my fresh 16-install, zilde is missing on the lb of the ODE, I'll take that to Andy, just mentioning here because it is the final difference...

**About:**
IDE:
  Version: 4.0.2611
  Platform: Win32
  Date: 2017-01-17 09:27:04 +0000
  Git commit: ce39e769dbef50395b3b38b4be1dc78287434ad5
  Preferences:{
    "favs":"[{\"type\":\"start\",\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"host\":\"localhost\",\"exe\":\"C:\\\\Program Files\\\\Dyalog\\\\Dyalog APL-64 16.0 Unicode\\\\dyalog.exe\",\"args\":\"inifile=\\\"SOFTWARE\\\\Dyalog\\\\Dyalog APL/W-64 16.0 Unicode\\\"\\nC:\\\\Program Files\\\\Dyalog\\\\Dyalog APL-64 16.0 Unicode\\\\Samples\\\\ole\\\\ado.dws\"}]",
    "kbdLocale":"en_US",
    "selectedExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 16.0 Unicode\\dyalog.exe",
    "wse":"1"
  }

Interpreter:
  Version: 16.0.29046
  Platform: Windows-64
  Edition: Unicode/64
  Date: Jan 23 2017 at 18:32:43

**Comment by mbaas2** [comment]
Sorry, how embarassing :((   Had sized the window, so it too narrow for ⍬! ;-)

**Comment by jayfoad** [comment]
I've just regenerated the RIDE language bar from the 16.0 interpreter sources, so they should be identical now.
