### ISSUE TITLE
RIDE4.2: Once in ⎕ED it's impossible to get out, and undo/redo go awry.

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/ride#551]
∇foo
⎕ed'goo'
∇
foo

now try to get out of the editor .. cannot do so without killing the process.  Also, undo and redo go awry .. try putting some more text in the edit window and repeatedly select Undo and Redo.

IDE:
  Version: 4.2.3437
  Platform: Win32
  Date: 2019-08-13 14:55:17 +0200
  Git commit: 691f47856e05a36f70847313b23e061a0cf95392
  Preferences:{
    "connectFav":"6",
    "kbdLocale":"en_US",
    "otherExe":"/opt/mdyalog/17.1/64/classic/p9/mapl",
    "selectedExe":"/opt/mdyalog/18.0/64/unicode/mapl"
  }

Interpreter:
  Version: 17.1.36901
  Platform: AIX-64
  Edition: Classic/64
  Date: Sep  2 2019 at 01:08:15

**Comment by e9gille** [comment]
Fixed in 0307bcc9b5c681a77fce623a09f360a5f213cc54
