### ISSUE TITLE
RIDE does not open workspaces with an older .DWS extension as workspaces

### ISSUE THREAD

**Issue by dyavc** [Dyalog/ride#558]
### Describe the issue you are having
RIDE does not open workspaces with an older .DWS extension as workspaces

### Did you connect to an already running interpreter or start the interpreter from RIDE?
started an interpreter from RIDE

### How do you reproduce the issue?
File->Open 
D:\cust\masteringDyaCompanionFiles\DyalogTutor_EN.DWS

It does not load it, 
and silently fails (but on mac will give an error message)
https://stackoverflow.com/questions/58706045/error-while-loading-dyalogtutor-en-workspace-in-dyalog-apl-how-to-proceed

### Paste the contents of Help → About (Shift+F1)
```
IDE:
  Version: 4.2.3437
  Platform: Win32
  Date: 2019-08-13 14:55:17 +0200
  Git commit: 691f47856e05a36f70847313b23e061a0cf95392
  Preferences:{
    "floatOnTop":"1",
    "floating":"1",
    "indent":"2",
    "indentComments":"1",
    "indentMethods":"2",
    "kbdLocale":"en_GB",
    "keys":"{\"MA\":[\"Ctrl-Alt-R\"]}",
    "matchBrackets":"0",
    "pfkeys":"[\"\",\"\",\"\",\":access Public <ER>\",\":access Public <ER>\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\"]",
    "prefixMaps":"{\"en_GB\":\"S[D]\"}",
    "selectedExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 17.1 Unicode\\dyalog.exe",
    "title":"{WSID}  {VER} PID: {PID} under RIDE {RIDE_VER}",
    "wse":"1"
  }

Interpreter:
  Version: 17.1.37133
  Platform: Windows-64
  Edition: Unicode/64
  Date: Oct 21 2019 at 19:37:25

```

**Comment by e9gille** [comment]
fixed in master and ride4.2 (bdf759f)
