### ISSUE TITLE
If you mistakenly )ed a workspace from RIDE under Windows, it silently fails

### ISSUE THREAD

**Issue by dyavc** [Dyalog/ride#559]
### Describe the issue you are having
If you mistakenly )ed a workspace from RIDE under Windows, it silently fails.  On macOS, RIDE will issue an error which is "There was an error ("TRANSLATION ERROR") with the specified file".

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Start an interpreter

### How do you reproduce the issue?
I have copied an old workspace here:  D:\cust\masteringDyaCompanionFiles\
)ED file://D:\cust\masteringDyaCompanionFiles\DyalogTutor_EN.DWS

silent failure.

In Dyalog for Windows using the original IDE, it will issue an error message.  It will also issue an error message on a mac.

### Paste the contents of Help → About (Shift+F1)
```
IDE:
  Version: 4.2.3437
  Platform: Win32
  Date: 2019-08-13 14:55:17 +0200
  Git commit: 691f47856e05a36f70847313b23e061a0cf95392
  Preferences:{
    "floatOnTop":"1",
    "floating":"1",
    "indent":"2",
    "indentComments":"1",
    "indentMethods":"2",
    "kbdLocale":"en_GB",
    "keys":"{\"MA\":[\"Ctrl-Alt-R\"]}",
    "matchBrackets":"0",
    "pfkeys":"[\"\",\"\",\"\",\":access Public <ER>\",\":access Public <ER>\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\"]",
    "prefixMaps":"{\"en_GB\":\"S[D]\"}",
    "selectedExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 17.1 Unicode\\dyalog.exe",
    "title":"{WSID}  {VER} PID: {PID} under RIDE {RIDE_VER}",
    "wse":"1"
  }

Interpreter:
  Version: 17.1.37133
  Platform: Windows-64
  Edition: Unicode/64
  Date: Oct 21 2019 at 19:37:25

```

**Comment by e9gille** [comment]
I can replicate, but it seems to be a problem on the interpreter side. RIDE doesn't receive any error message from the interpreter. Can you log this in Mantis please?

**Comment by dyavc** [comment]
Thanks Gil.  I have logged this as Dyalog issue 17617 and will close this RIDE issue.
