### ISSUE TITLE
Window handling when opening editor from maximized WS-Explorer

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/ride#56]
When clicking a fn or class in maxmized WS-Explorer to open the editor, it shows the editor - but also the session (which was not there in maximized explorer-view) comes back. That is unexpected and probably not too helpful, but probably unavoidable with the current window-handling.
If [floating windows](https://github.com/Dyalog/ride/issues/31) will be implemented, perhaps this can be revisited...

![2017-01-26_07-42-15](https://cloud.githubusercontent.com/assets/5645494/22322459/82e7aba4-e39c-11e6-8992-03086ef1e2b7.png)

**Comment by jayfoad** [comment]
@flouc001 @e9gille Is this "unavoidable with the current window-handling"? Is it possible to have the explorer and the editor visible, but not the session?

**Comment by e9gille** [comment]
With the latest build I get neither editor nor session when wse is maximized. I must have broken something.

What I understand, the maximized state is a view on top of the normal layout. If you then try to edit a function, it should restore the view to normal and therefore show session, debug window and other editors you may have had open.

**Comment by jayfoad** [comment]
> What I understand, the maximized state is a view on top of the normal layout. If you then try to edit a function, it should restore the view to normal and therefore show session, debug window and other editors you may have had open.

In that case, I think we should probably close this as "won't fix".

**Comment by jayfoad** [comment]
Looks like this now works properly if you have floating edit windows: the workspace explorer stays maximised in its window.

Without floating edit windows, I don't think we can fix this, as noted before.
