### ISSUE TITLE
Feature request: "Format code" button within the editor

### ISSUE THREAD

**Issue by Bubbler-4** [Dyalog/ride#563]
### Describe the issue you are having

Within the editor pane, I want to format the entire definition without closing and re-opening the editor. A button on the toolbar would be preferable, since the web browser version doesn't support context menu (mouse right click).

This feature is especially needed for scripted namespaces, where the code is not formatted at all when fixing if "formatting by interpreter" is disabled.

(I just found that RD shortcut does what I wanted to do, but it's only available as shortcut, and it's hard to see that the functionality exists. I strongly believe this particular feature should gain better visibility.)

### Did you connect to an already running interpreter or start the interpreter from RIDE?

I mainly use RIDE in two ways: start local interpreter from RIDE on my local PC, or connect to a running interpreter on the cloud through a web browser. I'd appreciate if both versions have this feature added.

### How do you reproduce the issue?

N/A

### Paste the contents of Help → About (Shift+F1)

Local:

```
IDE:
  Version: 4.2.3437
  Platform: Win32
  Date: 2019-08-13 14:55:17 +0200
  Git commit: 691f47856e05a36f70847313b23e061a0cf95392
  Preferences:{
    "kbdLocale":"en_US",
    "wse":"1",
    "indentComments":"1",
    "ilf":"0"
  }

Interpreter:
  Version: 17.1.36847
  Platform: Windows-64
  Edition: Unicode/64
  Date: Aug 15 2019 at 09:04:32
```

Cloud:

```
IDE:
  Version: 4.2.3437
  Platform: Win32
  Date: 2019-08-13 14:55:17 +0200
  Git commit: 691f47856e05a36f70847313b23e061a0cf95392
  Preferences:{
    "ilf":"0",
    "wse":"1",
    "kbdLocale":"en_US",
    "lbar":"0",
    "indentComments":"1"
  }

Interpreter:
  Version: 17.1.36845
  Platform: Linux-64
  Edition: Unicode/64
  Date: Aug 15 2019 at 00:13:45
```

**Comment by abrudz** [comment]
Also, make every functionality available via menu.

**Comment by abrudz** [comment]
For 4.5, let's only do the menu item.
