### ISSUE TITLE
Feature Request:  File->Save to save a workspace

### ISSUE THREAD

**Issue by dyavc** [Dyalog/ride#564]
### Describe the issue you are having
User would like a File->Save to save a workspace similar to the File->Open (#212) which opens a workspace/.dyalog file.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Requested on Mac

### Paste the contents of Help → About (Shift+F1)
```
Dyalog 17.1, RIDE 4.2 ?
```
This is also mentioned in #157, but I thought I would log a specific request for Save.

**Comment by abrudz** [comment]
Superceded by #823
