### ISSUE TITLE
WIBNI there was a way to save the current connection configuration once you have connected to APL

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/ride#565]
I have just got RIDE to start an APL on a remote machine.  But I cannot get back to the configuration window and save the current configuration .. I have to add the details back in, then save the configuration and then click on Start.  It would be nice if I could save that configuration while I was connected ..

**Comment by abrudz** [comment]
Maybe even an automatically added "last configuration" which is overwritten every time you start?

**Comment by mkromberg** [comment]
It would also be nice to edit and save the configuration when using the mac version, where RIDE is not visible to the user at all.
