### ISSUE TITLE
RIDE becomes unresponsive if the Status Bar is switched off

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/ride#567]
### Describe the issue you are having
If a thread is running, RIDE stops responding to all input in a timely fashion. Some output is delayed until the running thread ends.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
The problem appears in both scenarios.

### How do you reproduce the issue?
Close all windows except the main session window. The important thing seems to be that nothing is open that would regularly poll for thread and stack information.
Enter the following expressions in quick succession:
      {⎕←⎕DL ⍵}&30
      2+2
      2+2

The first and the second expressions typically execute immediately, The third statement is not executed until the first thread completes. The resulting output will be as follows - the result of the delay appears before the output echo of the 2nd 2+2:

{⎕←⎕DL ⍵}&30
      2+2
4
30.065382
      2+2
4

### Paste the contents of Help → About (Shift+F1)
```
IDE:
  Version: 4.2.3438
  Platform: Win32
  Date: 2019-09-02 17:16:29 +0200
  Git commit: 0307bcc9b5c681a77fce623a09f360a5f213cc54
  Preferences:{
    "connectFav":"7",
    "floatSingle":"0",
    "floating":"1",
    "ilf":"0",
    "indentOnOpen":"0",
    "kbdLocale":"da_DK",
    "lbarOrder":"← +-×÷*⍟⌹○!? |⌈⌊⊥⊤⊣⊢ =≠≤<>≥≡≢ ∨∧⍲⍱ ↑↓⊂⊃⊆⌷⍋⍒ ⍳⍸⍷∪∊∩~ /\\⌿⍀ ,⍪⍴⌽⊖⍉ ¨⍨⍣.∘⍤@ ⍞⎕⍠⌸⌺⌶⍎⍕ ⋄⍝→⍵⍺∇& ¯⍬ ",
    "prefixKey":"<",
    "selectedExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 18.0 Unicode\\dyalog.exe",
    "title":"{PROFILE}",
    "zoom":"3"
  }

Interpreter:
  Version: 18.0.38223
  Platform: Linux-64
  Edition: Unicode/64
  Date: Apr  3 2020 at 00:18:15

```

**Comment by johndaintree** [comment]
Interpreter side fix Mantis #17991
