### ISSUE TITLE
RIDE unresponsive

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/ride#57]
RIDE got into a state today where it did not react to resizing of the window, selections from the menu and even closing the main-window to exit the app did not work. Had to end it via Taskmanager.

I know this is not worth much w/o a repro which I do not have (yet). Wanted to mention it anyway - maybe a repro will show up...  ;-)

**Comment by mkromberg** [comment]
I just experience the same thing... I was tracing and the function I was in used ⎕SIGNAL to throw an error. The RIDE Trace window correctly cut back the stack but was subsequently completely unresponsive. This on the Raspeberry Pi.

**Comment by lstefano71** [comment]
Today's the first day I tried Ride from the master branch and I managed to put Ride in exactly the same state described by Michael half a dozen times. Once it simply happened after I waited long enough in the state described by issue #167. No repro yet.

**Comment by flouc001** [comment]
fixed in commit 6e66c16
