### ISSUE TITLE
Improve icon for "Toggle line numbers" in Tracer

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/ride#571]
Version: 4.2.3375

The current icon feels a wee bit odd compared with the general look & feel: 

![image](https://user-images.githubusercontent.com/5645494/79587709-3989ac00-80d3-11ea-81ae-12970818f1b1.png)

I'd like to suggest upgrading to FontAwesome 5.13 and using one of these - I'm undecided which I prefer, but probably `brackets` is more suited to the purpose:

`fal fa-list-ol`:
![image](https://user-images.githubusercontent.com/5645494/79588072-b2890380-80d3-11ea-9c88-7c40d12213e6.png)

`fal fa-brackets`:
![image](https://user-images.githubusercontent.com/5645494/79588127-c2a0e300-80d3-11ea-8f6f-4d087f5f1622.png)

**Comment by e9gille** [comment]
Good suggestions, thanks. I've replaced it with the 1st option, for now, but only because it matches the ODE. Let me know if you have any stronger feeling about swapping it for brackets.
