### ISSUE TITLE
)load does not refresh WS-Explorer (if opened)

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/ride#58]
When the WS-Explorer has been opened and a )load is performed, the explorer's tree does not update.  Must close and re-enable it via View|"Show WS-Explorer" to update the control. 

![2017-01-26_10-13-02](https://cloud.githubusercontent.com/assets/5645494/22326007/5620f19c-e3b1-11e6-953a-54b668f08666.png)

Also )clear does not clear the treeview:

![2017-01-26_10-21-27](https://cloud.githubusercontent.com/assets/5645494/22326048/739729da-e3b1-11e6-896e-12e9c716c612.png)

**Comment by mkromberg** [comment]
The RIDE WS explorer is intentionally not as responsive to changes in workspace structure as the Windows ODE explorer, due to performance and stability constraints. However, I agree that we might want to respond to major events like )CLEAR and )LOAD.

**Comment by jayfoad** [comment]
Seems like a special case of #18.

**Comment by e9gille** [comment]
We should add something to the protocol to pick up on major events like that. For now we can trigger on the UpdateDisplayName, which isn't ideal.
