### ISSUE TITLE
Zero-footprint RIDE tries to serve files from wrong path

### ISSUE THREAD

**Issue by Bubbler-4** [Dyalog/ride#580]
### Describe the issue you are having

On Linux, if I run `RIDE_INIT=HTTP:*:4502 dyalog`, Dyalog interpreter serves the files so that one can access RIDE through a web browser. Now with RIDE 4.3 and Dyalog 18.0, opening the page on the browser gives 404 instead:

> 404 File not found
> File: /opt/ride-4.2/resources/app/index.html
> Using configfile: /home/gitpod/.dyalog/ride.ini

### Did you connect to an already running interpreter or start the interpreter from RIDE?

Start both using the command `RIDE_INIT=HTTP:*:4502 dyalog`

### How do you reproduce the issue?

1. Install Dyalog 18.0 and RIDE 4.3 on Linux
2. Run `RIDE_INIT=HTTP:*:4502 dyalog`, open browser, and go to `127.0.0.1:4502`
3. See the 404 message

### Paste the contents of Help → About (Shift+F1)

N/A, because I can't open RIDE in the cloud at all.

**Comment by Bubbler-4** [comment]
Known workaround: `cd /opt && ln -s ride-4.3 ride-4.2`

**Comment by abrudz** [comment]
Try setting `httpdir` in the `[Ride]` section of your configfile.

**Comment by dyaandys** [comment]
The default Ride version for zfpr is set in the interpreter; I have altered 18.0 to point to 4.3 (and 19.0 to point to Ride 4.4).  

At some point we will include zfpr in the non-Windows releases, but for now setting httpdir is the way to go.

**Comment by Bubbler-4** [comment]
Thanks @abrudz @dyaandys.

For future reference, it worked after I put the following into `~/.dyalog/ride.ini`:

```
[Ride]
httpdir=/opt/ride-4.3/resources/app
```

One liner for Dockerfile (works only after you run `dyalog` once or create directory `~/.dyalog` manually):

```
RUN printf "[Ride]\nhttpdir=/opt/ride-4.3/resources/app\n" > ~/.dyalog/ride.ini
```

**Comment by dyaandys** [comment]
Have added zero footprint RIDE to 17.0 onwards .. the default now is $DYALOG/RIDEapp.  This is included in the latest generally available downloads.
