### ISSUE TITLE
DMK	Toggle key display mode doesn't work inside editors

### ISSUE THREAD

**Issue by abrudz** [Dyalog/ride#591]
### Describe the issue you are having

With DMK turned on, in the session, type "abc" and hit Shift+Enter. The DMK system shows Shift+Enter and the label is stuck rather than fading out. No other keystrokes are displayed until focus returns to the session.

### Paste the contents of Help → About (Shift+F1)
```
IDE:
  Version: 4.4.3687
  Platform: Win32
  Date: 2019-09-03 14:09:43 +0200
  Git commit: cc9cc6b4c5000c8033146a1731bc376d09f30ee1
Interpreter:
  Version: 19.0.38702
  Platform: Windows-64
  Edition: Unicode/64
  Date: Jul  7 2020 at 13:53:12

```

**Comment by e9gille** [comment]
The committed fix only ensures the last keystroke fades out, it still doesn't show keys on editors.

**Comment by abrudz** [comment]
Closing this in light of #1009
