### ISSUE TITLE
Add some helpful text to Preferences->Title tab 

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/ride#593]
WIBNI there were a few words on the title tab which explained how to build up a useful title, and that the expressions in {} are (a) replaced by their value when connected to an interpreter, and (b) that that list is complete.

http://help.dyalog.com/18.0/#UserGuide/Installation and Configuration/Window Captions.htm has the equivalent for the IDE.

IDE:
  Version: 4.3.3437
  Platform: Win32
  Date: 2019-07-09 13:38:28 +0100
  Git commit: 88a9eb9a96fd5e90dcb8dfdffc6aa7a9cb035441
  Preferences:{
    "connectFav":"2",
    "indent":"-1",
    "kbdLocale":"en_US",
    "otherExe":"/Dyalog/Dyalog-18.0.app/Contents/Resources/Dyalog/mapl",
    "zoom":"1"
  }

Interpreter:
  Version: unknown
  Platform: unknown
  Edition: unknown
  Date: unknown

**Comment by abrudz** [comment]
Documentation issue: Mantis 19890
