### ISSUE TITLE
RIDE with a RIDE_EDITOR does not fix the function if the RIDE_EDITOR external editor is not closed

### ISSUE THREAD

**Issue by dyavc** [Dyalog/ride#600]
### Describe the issue you are having
RIDE does not see changes to a function made with an external editor set with RIDE_EDITOR if the changes are just written, and the editor is not closed.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Start dyalog from RIDE

### How do you reproduce the issue?
setup RIDE_EDITOR by doing this:
1)  create a file called myedit in your home directory
 
2)  chmod +x myedit
 
3)  and put in it the following text:
xterm -e /usr/bin/vim "$*"
 
On my Fedora 32, I had to install xterm.
 
4)  export RIDE_EDITOR=~/myedit
 
ride

start dyalog from ride

)ed foo

in external vim editor 
add
⍳9

and use : and w to write a file

Dyalog does not see the change.

Dyalog only sees the change if you : and wq

### Paste the contents of Help → About (Shift+F1)
```
IDE:
  Version: 4.3.3463
  Platform: Linux x86_64
  Date: 2020-07-07 10:44:21 +0100
  Git commit: 0cd6e9faf39a5d6a5f5caa94d1ff51743d5cdd75
  Preferences:{
    "kbdLocale":"en_GB"
  }

Interpreter:
  Version: 18.0.38756
  Platform: Linux-64
  Edition: Unicode/64
  Date: Jul 16 2020 at 00:18:12

```

**Comment by abrudz** [comment]
This is normal. Use Link and edit the source file directly using the preferred editor to be able to save without closing, and have APL pick up the changes.
