### ISSUE TITLE
Input prompt off screen at startup if scroll bar is present

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/ride#61]
The attached image shows how my session comes up on the Raspberry Pi. The input prompt is not visible when RIDE starts up - possibly because of the presence of the scroll bar. Ideally, as previously mentioned, the session should be scrolled to that only input from the new session is visible (typically starting with "Dyalog APL version....").
![img_20170127_125008](https://cloud.githubusercontent.com/assets/2799045/22370069/bac45be6-e48f-11e6-85eb-c7ada0d929c8.jpg)

**Comment by jayfoad** [comment]
See also: #16 #43

**Comment by e9gille** [comment]
I believe this has been fixed in 64110d34d020282e248c3a7061ca1d7863a82eb7
