### ISSUE TITLE
Tool bar covers the language bar in 'zero footprint' mode

### ISSUE THREAD

**Issue by YsHaNgM** [Dyalog/ride#614]
### Describe the issue you are having
When RIDE opens inside Chrome based browser with workspace explorer shows, there will be multiple tool bars take over all space on the top, including language bar.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Connected to a Docker container where interpreter runs and RIDE initialise with 'zero footprint'.

### How do you reproduce the issue?
Connect to RIDE within browser, in View, choose Show Workspace Explorer.

### Paste the contents of Help → About (Shift+F1)
```
IDE:
  Version: 4.3.3463
  Platform: MacIntel
  Date: 2020-07-07 10:44:21 +0100
  Git commit: 0cd6e9faf39a5d6a5f5caa94d1ff51743d5cdd75
  Preferences:{
    "kbdLocale":"en_GB_Mac"
  }

Interpreter:
  Version: 18.0.38756
  Platform: Linux-64
  Edition: Unicode/64
  Date: Jul 16 2020 at 00:18:12

```

**Comment by dyaandys** [comment]
I think this is the same as #806
