### ISSUE TITLE
Over operator haven't been recognized in syntax highlighting

### ISSUE THREAD

**Issue by LdBeth** [Dyalog/ride#616]
### Describe the issue you are having
Since Dyalog 18.0 a new operator Over `⍥` (APL FUNCTIONAL SYMBOL CIRCLE DIAERESIS) has been added, but it seems RIDE still identifies this operator as syntax error.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
I start the interpreter from RIDE, but seems connect to existed running instance is also affected.

### How do you reproduce the issue?
type any valid expression uses Over operator such as `+⍥- 12`, and the over operator is rendered red in default color schema, indicates it has been recognized as syntax error.

### Paste the contents of Help → About (Shift+F1)
```
IDE:
  Version: 4.3.3463
  Platform: MacIntel
  Date: 2020-07-07 10:44:21 +0100
  Git commit: 0cd6e9faf39a5d6a5f5caa94d1ff51743d5cdd75
  Preferences:{
    "kbdLocale":"en_US_Mac"
  }

Interpreter:
  Version: 18.0.38756
  Platform: Mac-64
  Edition: Unicode/64
  Date: Jul 16 2020 at 01:08:20
```

**Comment by e9gille** [comment]
Fixed in #630
