### ISSUE TITLE
ZF 3500⌶

### ISSUE THREAD

**Issue by cybearinsight** [Dyalog/ride#618]
### Describe the issue you are having

It seems that the I-beam 3500 is not working with ZeroFoot print ride.

### Did you connect to an already running interpreter or start the interpreter from RIDE?

Zero Foot print running of a Docker Container

### How do you reproduce the issue?

```apl
3500⌶'<!DOCTYPEhtml><html><body><h1>MyFirstHeading</h1><p>Myfirstparagraph.</p></body></html>'
```
### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.3.3463
  Platform: Win32
  Date: 2020-07-07 10:44:21 +0100
  Git commit: 0cd6e9faf39a5d6a5f5caa94d1ff51743d5cdd75
  Preferences:{

  }

Interpreter:
  Version: 18.0.38756
  Platform: Linux-64
  Edition: Unicode/64
  Date: Jul 16 2020 at 00:18:12

```

**Comment by abrudz** [comment]
Normally, `3500⌶` pops up a separate chrome-less window. This cannot easily be done in a browser, though we could possibly open a separate browser tab.

**Comment by abrudz** [comment]
ZF RIDE can just open another tab for `3500⌶`:
https://stackoverflow.com/a/10573430/5306507

**Comment by abrudz** [comment]
At least, `3500⌶` should error under ZF.

**Comment by e9gille** [comment]
I can't replicate, may have been fixed in the meantime. Please re-open if you can replicate.
