### ISSUE TITLE
Editor-Window should save window-layout before closing and restore on next open

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/ride#62]
i.e. currently when double-clicking a fn in wsx, the new editor opens to the right of the session.
Take that window and place it above the session. Close editor. Edit a fn. Editor will open right again. 
I think it should restore the last window-layout.

**Comment by jayfoad** [comment]
With floating edit windows, you can use Preferences->Windows->"Remember previous window position". Is that good enough for you @mbaas2 ?

**Comment by e9gille** [comment]
closing this as no response. Please shout if you disagree.
