### ISSUE TITLE
Status window stays on top and can't be minimised

### ISSUE THREAD

**Issue by nicolas-dyalog** [Dyalog/ride#621]
### Describe the issue you are having
Status window stays on top and can't be minimised
A - It always remains on top of the main RIDE window
B - Minimising it minimises the main RIDE window too
C - It can't be docked

I believe A and B to be bugs and C to be an RFE

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Either way

### How do you reproduce the issue?
      +2 ⎕FIX,⊂':blah'
DOMAIN ERROR: unrecognised keyword encountered
      +2 ⎕FIX,⊂':blah'
         ∧

⍝ which pops up a status message saying

line(0,1) : error AC0037: unrecognised keyword encountered ":blah"
                                                             ^
Complete: 1 error.

### Paste the contents of Help → About (Shift+F1)
```
IDE:
  Version: 4.1.3366
  Platform: Linux x86_64
  Date: 2018-07-17 15:26:35 +0100
  Git commit: 0088ce492350a8d582b019adfc5d5a87efbdc00b
```

**Comment by e9gille** [comment]
A and B fixed in #679 
@nicolas-dyalog  feel free to log C separately as a RFE if you like.
