### ISSUE TITLE
Ride steals focus when tracer pops up

### ISSUE THREAD

**Issue by nicolas-dyalog** [Dyalog/ride#622]
### Describe the issue you are having
Ride steals focus when tracer pops up

### Did you connect to an already running interpreter or start the interpreter from RIDE?
either way

### How do you reproduce the issue?
 
       +2 ⎕FIX 'foo' '⎕DL 3' '∘∘∘'
  foo 
       foo  ⍝ right after executing foo, switch focus to another window
 SYNTAX ERROR
 foo[2] ∘∘∘
          ∧
      ⍝ when the tracer pops up, RIDE steals the focus.

### Paste the contents of Help → About (Shift+F1)
```
IDE:
  Version: 4.1.3366
  Platform: Linux x86_64
  Date: 2018-07-17 15:26:35 +0100
  Git commit: 0088ce492350a8d582b019adfc5d5a87efbdc00b

Desktop : Lubuntu 18.04 (Xfce)

**Comment by abrudz** [comment]
Won't fix.
