### ISSUE TITLE
6-space prompt is not issued after starting a threaded function

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/ride#624]
### Describe the issue you are having
No 6-space prompt after starting a threaded function.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Does not matter

### How do you reproduce the issue?
```
)load ridetests.dws ⍝ requires v19.0
Init ⍝ Requires ability to 'DRC' ⎕CY 'conga.dws'
Server&4321 ⍝ 4321 must be a free port
```

Notice the cursor remains at the left. You can type 2+2, get 4, and get the prompt.
The Windows ODE immediately issues a 6-space prompt.

It *may* matter what the function does: This one enters a loop waiting on an asynchronous ⎕NA call to Conga's wait (this is a VERY common pattern for Dyalog APL running on Linux). Attempts to reproduce with more trivial functions failed.

### Paste the contents of Help → About (Shift+F1)
```
IDE:
  Version: 4.4.3469
  Platform: Win32
  Date: 2020-07-07 16:02:26 +0100
  Git commit: b97d35464cceaf671e05e82e8db59e50f69a0481
  Preferences:{
    "connectFav":"1",
    "floatSingle":"0",
    "floating":"1",
    "kbdLocale":"da_DK",
    "prefixKey":"<"
  }

Interpreter:
  Version: 19.0.39694
  Platform: Linux-64
  Edition: Unicode/64
  Date: Dec  8 2020 at 03:38:37

```
[ridetests.zip](https://github.com/Dyalog/ride/files/5671814/ridetests.zip)

**Comment by e9gille** [comment]
There was an issue when a thread appended text to the session. Fixed in master.
