### ISSUE TITLE
Self-referring namespaces cause error

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/ride#63]
(Sorry, I'm just trying to be a bad boy ;-))

```
x←⎕ns''
x.y←#.x

```
Double-click "x" in ws-explorer and this error comes up:

![2017-01-28_16-04-16](https://cloud.githubusercontent.com/assets/5645494/22397543/b31c1836-e573-11e6-9134-739c70c8b321.png)

ODE's WSX copes with that...

About:
IDE:
  Version: 4.0.2611
  Platform: Win32
  Date: 2017-01-17 09:27:04 +0000
  Git commit: ce39e769dbef50395b3b38b4be1dc78287434ad5
  Preferences:{
    "favs":"[{\"type\":\"start\",\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"host\":\"localhost\",\"exe\":\"C:\\\\Program Files\\\\Dyalog\\\\Dyalog APL-64 16.0 Unicode\\\\dyalog.exe\",\"args\":\"inifile=\\\"SOFTWARE\\\\Dyalog\\\\Dyalog APL/W-64 16.0 Unicode\\\"\\nC:\\\\Program Files\\\\Dyalog\\\\Dyalog APL-64 16.0 Unicode\\\\Samples\\\\ole\\\\loan.dws\",\"name\":\"V16 locally\"},{\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"Connect4502\"}]",
    "kbdLocale":"en_US",
    "keys":"{\"SC\":[\"Shift-F9\"]}",
    "selectedExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 16.0 Unicode\\dyalog.exe",
    "wse":"1"
  }

Interpreter:
  Version: 16.0.29074
  Platform: Windows-64
  Edition: Unicode/64
  Date: Jan 25 2017 at 18:32:22

**Comment by jayfoad** [comment]
This is a problem in the interpreter. I've raised it internally as Mantis 14182.

**Comment by jayfoad** [comment]
Fixed in interpreters 15.0.29101 and 16.0.29104.
