### ISSUE TITLE
Checkbox "in methods" in Preferences/General cannot be toggled

### ISSUE THREAD

**Issue by aplteam** [Dyalog/ride#636]
### Describe the issue you are having

When I open the Preferences dialog and then click the "in methods" checkbox it does not toggle its state.

Once I press Alt+m in order to toggle it via the keyboard I can toggle it with the mouse as well.

### Did you connect to an already running interpreter or start the interpreter from RIDE?

n/a

### How do you reproduce the issue?

See above

### Paste the contents of Help → About (Shift+F1)
```
IDE:
  Version: 4.3.3463
  Platform: Linux x86_64
  Date: 2020-07-07 10:44:21 +0100
  Git commit: 0cd6e9faf39a5d6a5f5caa94d1ff51743d5cdd75
  Preferences:{
    "kbdLocale":"en_US"
  }

Interpreter:
  Version: unknown
  Platform: unknown
  Edition: unknown
  Date: unknown
```

**Comment by aplteam** [comment]
The "Autoindent" and the "Indent lines..." checkboxes suffer from the same problem.

**Comment by e9gille** [comment]
Well, disabled checkboxes shouldn't allow you to toggle them, so the fact that the keyboard shortcut allowed you is a bug.

I'll leave this issue open as it highlights a UX issue, but will need to ponder the solution.
