### ISSUE TITLE
Rationalise & Enhance Status Information

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/ride#645]
We should replace the current GetSIStack and GetThreads calls that are made every 5 seconds with a new mechanism which also includes the information requested in #447 and #632.

**Comment by abrudz** [comment]
Is there a reason RIDE polls the interpreter rather than the interpreter pushing change notifications to RIDE?

The polling has the effect of flooding the protocol log, making debugging RIDE harder.

**Comment by dyaandys** [comment]
Perhaps add a filter mechanism to the logging mechanism ?
