### ISSUE TITLE
Strange message about line endings

### ISSUE THREAD

**Issue by abrudz** [Dyalog/ride#646]
### Describe the issue you are having
Strange message when session has odd characters

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Start an interpreter

### How do you reproduce the issue?
Start RIDE, select to start interpreter.
Enter `⎕ucs 8232`
This message pops up:
![image](https://user-images.githubusercontent.com/10961427/106720573-88211c00-65fb-11eb-91d2-4b4dbf00bdc8.png)

### Paste the contents of Help → About (Shift+F1)
```
IDE:
  Version: 4.4.3474
  Platform: Win32
  Date: 2021-01-29 17:14:19 +0100
  Git commit: 9105fc792fb7f507a9b66f0265cd436d2b63565f
  Preferences:{
    "selectedExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 18.0 Unicode\\dyalog.exe",
    "kbdLocale":"en_GB"
  }

Interpreter:
  Version: 18.0.39556
  Platform: Windows-64
  Edition: Unicode/64
  Date: Nov 16 2020 at 20:00:44
```

**Comment by e9gille** [comment]
This is caused by a new feature in the monaco editor. We need to disable the check by configuring the session and editor windows, see:
https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.ieditorconstructionoptions.html#unusuallineterminators
