### ISSUE TITLE
Wrong icon on OS X

### ISSUE THREAD

**Issue by JasonRivers** [Dyalog/ride#66]
IDE:
  Version: 4.0.2628
  Platform: MacIntel
  Date: 2017-01-30 11:56:55 +0200
  Git commit: 47d310f2d53c46f3ff1a2c2479b53850dadeef3d
  Preferences:{

  }

Interpreter:
  Version: 16.0.29127
  Platform: Mac-64
  Edition: Unicode/64
  Date: Feb  1 2017 at 11:47:30

Icon on OS X is the Electron icon and not the Dyalog icon.

**Comment by jayfoad** [comment]
Fixed.
