### ISSUE TITLE
When dbl-clicking a fn in session to edit, it should not be selected

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/ride#668]
### Describe the issue you are having

When double-clicking the name of a function, that fn can be edited. But as a side-effect, its name also gets highlighted. This leads to confusing behavior when (after fixing changes) one presses enter (assuming this would execute the line) it just executes the name of that fn (without the arguments or the namespace-prefix that are shown on the original line)

In most examples that I tried, I could NOT repro the behavior I just described and RIDE executed the entire line as I expected. But this report was triggered by the repro given below - which still repros. I just can't isolate the problem well enough to give a general repro.

### Did you connect to an already running interpreter or start the interpreter from RIDE?

Does not matter.

### How do you reproduce the issue?

`)load sqapl`
Type `SQA.Init''` and dbl-click `Init` to edit it. After looking at it, exit the editor and press Enter to execute the line. This only executes the highlighted `Init`-statement.

### Paste the contents of Help → About (Shift+F1)
```
IDE:
  Version: 4.4.3489
  Platform: MacIntel
  Date: 2021-02-24 14:31:49 +0000
  Git commit: 12fbfea4e2d7176e53420001de6fde3ff04d7a7d
  Preferences:{
    "autoPW":"1",
    "colourScheme":"Francisco Goya",
    "kbdLocale":"de_DE_Mac",
    "prefixKey":"<"
  }

Interpreter:
  Version: 18.1.40095
  Platform: Mac-64
  Edition: Unicode/64
  Date: Feb 25 2021 at 03:38:13

```

**Comment by abrudz** [comment]
In the Windows IDE you can choose whether double-click should select or edit:
![image](https://user-images.githubusercontent.com/10961427/116653090-6925f200-a97e-11eb-85a5-fa681e12e120.png)
Maybe this should be an option in RIDE too?

**Comment by e9gille** [comment]
Ah, I hadn't noticed this was an option. Sounds sensible to me, @JonnersW can you take a look at doing this?
