### ISSUE TITLE
RIDE should use the -nokbd switch when launching the mapl script to start Linux APL

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/ride#674]
Some versions (pre March 2021) of the Linux mapl script call the aplkeys script and "hijack" the Windows key as the APL mode switch key, rendering many Linux desktops unusable. Although new versions of the mapl script will no longer do this, RIDE should add the -nokbd switch to disable this keyboard switching as a side-effect of launching older APL sessions from RIDE.

**Comment by e9gille** [comment]
Fixed in #676
