### ISSUE TITLE
Listen mode should allow multiple interpreters to connect to the same port

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/ride#675]
When RIDE is instructed to listen, it should create a new session for each APL interpreter that connects to the listening socket. This would be allow a single RIDE session to act as a debugging station for a cluster of APL processes that can create a debugging session if they need one.

I believe this worked in an earlier version of RIDE, but cannot prove it.

**Comment by lstefano71** [comment]
Yes! But... how would you find out which session is which? If you have 20 connections coming from the same IP address all spewing similar garbage in the session, how do you tell them apart at a glance? The various APL sessions might know who they are, what they do inside the cluster, what is their specific role, but how would they tell the lonely RIDE client? 
Tangentially, how would you deal with the fact that when you start the cluster you may not know the IP Address of the RIDE session that you are going to use to debug it? But I understand this is a very different scenario so it would probably be better to create a separate issue for it.

**Comment by e9gille** [comment]
Added this in #677 but haven't tested with isolates. It might not be fast enough in case a large number of interpreters try to connect at the same time.

**Comment by e9gille** [comment]
Fixed in #677
