### ISSUE TITLE
Need option to use interpreter formatting of APL code

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/ride#68]
It needs to be possible to enable an option whereby APL code formatting is done by the interpreter. This is to make it possible for developers to edit the same code using ODE+RIDE.

**Comment by johndaintree** [comment]
The most recent decision was to have a message which RIDE would send to the interpreter (including the text). The interpreter would then return a formatted version.

**Comment by flouc001** [comment]
Fixed in commit 03da47c
