### ISSUE TITLE
Context-Menu of Configurations: Copy & Paste not doing anything

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/ride#680]
### Describe the issue you are having

RIDE on macOS: context-menu of configuration-items offers Copy & Paste, but "Copy" doesn't seem to change the clipboard, so "Paste" does not find anything to paste.

### Did you connect to an already running interpreter or start the interpreter from RIDE?

Not relevant.

### How do you reproduce the issue?

Open context-menu of a configuration in RIDE's initial window. Select"Copy", then "Paste".

### Paste the contents of Help → About (Shift+F1)
```
IDE:
  Version: 4.4.3495
  Platform: MacIntel
  Date: 2021-03-01 11:06:54 +0000
  Git commit: 60c97877d29383d3afca3751ad18319faab610c2
  Preferences:{
    "kbdLocale":"de_DE_Mac",
    "prefixKey":"<"
  }

Interpreter:
  Version: unknown
  Platform: unknown
  Edition: unknown
  Date: unknown

```

**Comment by e9gille** [comment]
Tried replicating with no luck. Can you still replicate?
![issue680](https://user-images.githubusercontent.com/8232484/118308021-be6c1280-b4eb-11eb-9886-a92065fb6c3c.gif)

**Comment by abrudz** [comment]
Can't repro in 4.4 on Ventura
