### ISSUE TITLE
How do you install Ride on Windows 10. Tried from downloaded, extracted zip. Not clear how.

### ISSUE THREAD

**Issue by lgroner** [Dyalog/ride#681]
### Paste the contents of Help → About (Shift+F1)
```
(Paste here)
```

**Comment by abrudz** [comment]
1. Go [here](https://github.com/Dyalog/ride/releases/latest)
2. Download ride-X.Y.ZZZZ_windows.zip and extract that.
4. Inside the extracted zip, you will find a directory named "ride" ― open that
3. Inside, you will find setup_ride.exe ― run that (you may get a warning from Windows about it being potentially unsafe, but just click "more info" and then <kbd>Run anyway</kbd>)

**Comment by lgroner** [comment]
Thanks,
I did not see the "run anyway" under "more info".
Leo (Lou) Groner

408 887 9938 (M)
***@***.***
