### ISSUE TITLE
PgDn in the editor causes the rightmost part of the lines to be shown when you reach the last page. PgUp shows the first part of the lines on the first page.

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/ride#699]
s←166⍴⊂⍕⍳50
      s<ED>
note that the lines all start 1 2 3 ..
repeatedly page down in the editor.  When you get to the bottom of the array, you'll see the last characters on each row.  I think that even on the last page down the columns displayed should not change.  Similar is true of paging up.

IDE:
  Version: 4.4.3518
  Platform: Win32
  Date: 2021-05-05 17:39:35 +0100
  Git commit: 7cff681139ca4a4696640a13c5b3c3ee92cbb0fc
  Preferences:{
    "ime":"1",
    "kbdLocale":"en_US",
    "keys":"{\"MA\":[\"F2\"],\"PF2\":[]}",
    "otherExe":"/opt/mdyalog/18.1/64/unicode/p9/mapl",
    "selectedExe":"/opt/mdyalog/18.1/64/classic/p9/mapl"
  }

Interpreter:
  Version: 18.1.40520
  Platform: Linux-64
  Edition: Unicode/64
  Date: May  5 2021 at 02:38:27

**Comment by abrudz** [comment]
This is how the underlying editor works. Same behaviour in e.g. VSCode etc.
