### ISSUE TITLE
WS Explorer contextmenu: Cut/Copy & Paste not working

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/ride#70]
I right-clicked a function, selected either "Cut" or "Copy" and in the contextmenu of another ns (or "#") tried "Paste" - function was not found in that ns afterwards. (Verified using )fns - did not rely on WSX alone)

**Comment by jayfoad** [comment]
The workspace explorer is (currently) not supposed to allow you to change things. So for now I think we should not have cut/copy/paste in the context menu, since they are not supposed to work.

**Comment by e9gille** [comment]
Closing this issue as context menu no longer appears in WSE. Please log a separate enhancement request if you think we should add this as a feature.
