### ISSUE TITLE
The ⎕xxxx representations of the glyphs that cannot be shown in classic appear in the error colour

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/ride#702]
This is not a RIDE 4.4 specific error.

Classic interpreters represent Nest, Key, Stencil, Variant, Rank, Over and Where as `⎕U2286`, `⎕U2338`, `⎕U233A`, `⎕U2360`, `⎕U2364`, `⎕U2365` and `⎕U2378` respectively.   The editor displays them (default colour scheme) in scarlet .. the error colour.  Other ⎕things appear in purple as expected.

Over time this list may extend ..

IDE:
  Version: 4.4.3518
  Platform: Win32
  Date: 2021-05-05 17:39:35 +0100
  Git commit: 7cff681139ca4a4696640a13c5b3c3ee92cbb0fc
  Preferences:{
    "ime":"1",
    "kbdLocale":"en_US",
    "keys":"{\"MA\":[\"F2\"],\"PF2\":[]}",
    "otherExe":"/opt/mdyalog/18.1/64/unicode/p9/mapl",
    "selectedExe":"/opt/mdyalog/18.1/64/classic/p9/mapl"
  }

Interpreter:
  Version: 18.1.40535
  Platform: AIX-64
  Edition: Classic/64
  Date: May  7 2021 at 08:34:53

**Comment by DyalogRichard** [comment]
If RIDE cannot distinguish between Unicode and Classic subordinates, fixing Classic would break Unicode. In such circumstances I would say: leave Classic broken.

If RIDE can distinguish between Unicode and Classic subordinates, it should stay the way it is now for Unicode.
