### ISSUE TITLE
RIDE should automatically do horizontal scrolling to leftmost position when executing statements in the session

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/ride#713]
### Describe the issue you are having
When entering a looong statement that causes horizont scrolling and executing it, the display should scroll back to the left margin when displaying the result.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Start from RIDE

### How do you reproduce the issue?
⎕PW←1024
Enter `402⍴'1+'` (or a different value instead of 402, depending on screen size)
Press Enter.
Search result of that command.

Screenshot to illustrate the effect:
<img width="1434" alt="grafik" src="https://user-images.githubusercontent.com/5645494/118158547-3834cb00-b41c-11eb-9304-2585b13144cc.png">

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.4.3524
  Platform: MacIntel
  Date: 2021-05-13 15:23:54 +0200
  Git commit: 1fe00f6eab7e24c8f602c8e8badb13e20574280d
  Preferences:{
    "autoPW":"1",
    "confirmations":"{\"SaveFileOptionsExtension:.aplf\":100}",
    "kbdLocale":"de_DE_Mac",
    "prefixKey":"<",
    "selectedExe":"/Applications/Dyalog-18.0.app/Contents/Resources/Dyalog/mapl"
  }

Interpreter:
  Version: 18.1.40475
  Platform: Mac-64
  Edition: Unicode/64
  Date: Apr 24 2021 at 03:40:12

**Comment by e9gille** [comment]
I tried replicating this but failed. Where am I going wrong?
![Uploading issue713.gif…]()

**Comment by mbaas2** [comment]
Aah - sorry - I left out one step: go back into that line of output, move cursor to end of line and press Enter!
