### ISSUE TITLE
Highlighting text in dracula theme is difficult to see

### ISSUE THREAD

**Issue by 0xACE** [Dyalog/ride#735]
![cap](https://user-images.githubusercontent.com/1482942/120890933-5ba2fe00-c5f5-11eb-9960-d669a8a9bda4.png)

Image showcases me selecting the same text in the left (dracula) and right (default) theme. The dracula theme doesn't display the highlighted active line, this is what it looks like when i hit `CTRL+a` to select everything:

![cap](https://user-images.githubusercontent.com/1482942/120890967-89884280-c5f5-11eb-9dd0-9fb1fb7bf5b3.png)

```
IDE:
  Version: 4.4.3534
  Platform: Linux x86_64
  Date: 2021-06-01 14:19:53 +0100
  Git commit: e659c69043fea737dfac2fde13c519f7a32050ba
  Preferences:{
    "kbdLocale":"en_US",
    "minimapEnabled":"1",
    "minimapShowSlider":"always",
    "otherExe":"/usr/bin/dyalog",
    "zoom":"7",
    "colourScheme":"Dracula"
  }

Interpreter:
  Version: 18.0.39712
  Platform: Linux-64
  Edition: Unicode/64
  Date: Dec 11 2020 at 01:07:55
```

**Comment by 0xACE** [comment]
Incase anyone is curios i solved this by reducing transparency of the "modified line" style:

![cap](https://user-images.githubusercontent.com/1482942/120932208-67212280-c6e4-11eb-9483-600c09e3cf3f.png)

**Comment by abrudz** [comment]
@0xACE  You did right; the intention was for the selection to be transparent.
