### ISSUE TITLE
Key bindings for search in the session?

### ISSUE THREAD

**Issue by jayfoad** [Dyalog/ride#75]
You can search in an editor window either by pressing the search button or by binding a keystroke to the SC action.

Searching also works in the session, but since there is no button the only way you can do it is by binding a keystroke to the SC action. I feel this makes the functionality too obscure. Maybe we should provide a default binding for SC, so that you don't have to do any manual configuration in order to be able to search the session?

**Comment by mbaas2** [comment]
...and ideally also have a menuitem to trigger this command!

**Comment by JohnScholes** [comment]
The standard OSX search keystroke cmd+s works out-of-the-box in an edit window and should also work in the session (and everywhere else).

**Comment by flouc001** [comment]
CTRL+F works on Windows and Ubuntu, please could you retry @jayfoad

**Comment by JohnScholes** [comment]
FYI: Cmd+F now works nicely on my Mac, in session, edit and trace windows.

**Comment by jayfoad** [comment]
I can confirm that Ctrl+F lets me search the session on Windows, thanks. I was confused (and still am) by the fact that Preferences/Shortcuts doesn't show any key binding for SC.

**Comment by flouc001** [comment]
@jayfoad it may be the search plugin we use silently setting the key bindings, I will look at showing a default. @JohnScholes thank you for confirmation on mac :)
