### ISSUE TITLE
Question: how to configure interpreter?

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/ride#76]
Not a "complaint", just an issue for discussion: *if* RIDE should/will become an alternate frontend for the interpreter, then how do we configure that interpreter? (Equivalent for "Options > Preferences" in ODE)

**Comment by e9gille** [comment]
There area certainly many things that are missing in RIDE's preferences window, but could you please clarify which ones you think ought to be added?

**Comment by e9gille** [comment]
closing due to no response.
