### ISSUE TITLE
Please allow RIDE IDE to work with aarch64 architecture. 

### ISSUE THREAD

**Issue by JTurco32** [Dyalog/ride#762]
Hello,

I am using a 64-bit distro of Raspberry pi OS (aarch 64/ARM-64) and the IDE will not start due to not supporting the architecture. 
Is this somthing the RIDE IDE Team might be interested in supporting, since, eventually, raspberry pi will be moving to 64-bit stable (i am using a beta version)?

**Comment by e9gille** [comment]
RIDE is built using electron and is therefore limited by what platforms it is supported on:
https://www.electronjs.org/docs/tutorial/support#supported-platforms

**Comment by abrudz** [comment]
It should be possible to use [Zero Footprint RIDE](https://docs.dyalog.com/18.0/RIDE%20User%20Guide.pdf#page=11).

**Comment by dyaandys** [comment]
Zero footprint RIDE is included with all non-Windows installations of Dyalog APL.   But where is the APL interpreter running ?  We don't currently have a 64-bit version of Dyalog APL for Raspberry Pi, and when I last tried a couple of months ago the 32-bit version won't run on 64-bit Raspberry Pi OS - I could not find some required 32-bit support libraries in the Raspberry Pi OS repositories.
