### ISSUE TITLE
About>Help lists version info as "unknown".

### ISSUE THREAD

**Issue by abrudz** [Dyalog/ride#79]
I think this only happens when run as repo, not as a proper install.

**Comment by JasonRivers** [comment]
It doesn't know the version number until it's built. running npm start won't give you this information, run:

`./mk dist`

and then run the binary for your platform from the _ directory.

**Comment by ngn** [comment]
or:
```
node mk build
npm start
```

**Comment by jayfoad** [comment]
Properly built RIDEs know their version, so I don't think there's anything to fix.
