### ISSUE TITLE
RIDE fails to start with the GNU APL 1.8-1_amd64 interpreter

### ISSUE THREAD

**Issue by mlliarm** [Dyalog/ride#797]
### Describe the issue you are having
Hello !

RIDE fails to start when I try to make it use the GNU APL interpreter.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Hm, no. I had connected earlier RIDE to the Dyalog APL interpreter, but I closed RIDE and reopened it from fresh.

### How do you reproduce the issue?

I select "Start".

I enter the path to the GNU-APL interpreter binary that is: `/usr/bin/apl`

 as you can see:

```
$ mlocate bin/apl
/usr/bin/apl
/usr/bin/aplay
/usr/bin/aplaymidi
```

I press Start.

The attached pop up, pops up:

![RIDE_GNU-APL_issue](https://user-images.githubusercontent.com/5833270/142750983-18bc0a85-d9c5-4b06-b9c1-771a239986d1.png)

### Paste the contents of Help → About (Shift+F1)
(I opened RIDE with the Dyalog interpreter in order to get the info you've requested:

```
More info:

IDE:
  Version: 4.3.3463
  Platform: Linux x86_64
  Date: 2020-07-07 10:44:21 +0100
  Git commit: 0cd6e9faf39a5d6a5f5caa94d1ff51743d5cdd75
  Preferences:{
    "colourScheme":"Francisco Goya",
    "kbdLocale":"en_US",
    "otherExe":"/usr/bin/apl"
  }

Interpreter:
  Version: 18.0.44786
  Platform: Linux-64
  Edition: Unicode/64
  Date: Nov 18 2021 at 00:08:54
```

### Other possibly useful info
```
GNU APL:
$ apl -v
BUILDTAG:
---------
    Project:        GNU APL
    Version / SVN:  1.8 / Unversioned directory
    Build Date:     2014-01-04 12:14:00 UTC
    Build OS:      
    config.status:  '--build=x86_64-linux-gnu' '--prefix=/usr' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-silent-rules' '--libexecdir=${prefix}/lib/apl' '--disable-maintainer-mode' '--disable-dependency-tracking' 'build_alias=x86_64-linux-gnu'
    Archive SVN:

DEB file installed:
1.8-1_amd64.deb (I didn't compile from source).

OS:
$ sudo lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 18.04.6 LTS
Release: 18.04
Codename: bionic

RIDE:
ride-4.3.3463-1_amd64.deb

Dyalog APL:
RIDE works nicely with this interpreter. Sharing it for comparison or whatever.
linux_64_18.0.44786_unicode.x86_64.deb
```

**Comment by abrudz** [comment]
In order to work with RIDE, an APL interpreter needs to communicate and be controlled via [the RIDE protocol](/Dyalog/ride/blob/master/docs/protocol.md). GNU APL does not support this. Consider logging an issue against GNU APL asking for this feature.
