### ISSUE TITLE
F1 links to V15-Help

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/ride#80]
While I was using V16 here...
I assume RIDE knows which version of the interpreter it is connected to - so it should bring up the corresponding online-help.

**Comment by jayfoad** [comment]
In the short term RIDE 4.0 should probably just assume that it's talking to Dyalog 16.0, for the purposes of help URLs and language bar contents and stuff like that.

Longer term we might want to make it change its behaviour based on what interpreter version it is actually talking to. That would probably require some additional information in the protocol.

**Comment by JasonRivers** [comment]
I think RIDE links to the latest docs IIRC this is currently hard-coded @ngn or @flouc001 will know for sure, RIDE does know the version number of the interpreter, so it's probably not too difficult to work out which docs to link to and have a default of the latest, We could perhaps have a "latest" link in online help that always points to the latest (released) help if that would help to do this without hard-coding to a specific version.

**Comment by abrudz** [comment]
Why not use `911⌶`?

**Comment by mkromberg** [comment]
What is 911⌶ and how can RIDE call it?

Seriously: Until we sort out dynamic help, RIDE 4 should provide help for 16.0, as Jay suggests.

**Comment by ngn** [comment]
To get the interpreter version: `D.remoteIdentification.version`

Help URLs for v15.0 are in https://github.com/Dyalog/ride/blob/master/src/hlp.js
URLs differ between versions and it's not just the substition of a digit.
There was once talk of making them more straightforward, e.g. the help file for `⍴` would be `u2374.html`, named after the hex code point.

Don't forget to test for 404-s: https://github.com/Dyalog/ride/blob/master/tools/chk-hlp-urls.js

**Comment by JasonRivers** [comment]
The problem with currently linking to v16 help, is that it's currently password protected until the release (or at least official beta), Which is why it still points to v15 help.

If we link to v16 only, then help wont work for anyone using RIDE that can't login to the v16 help files.

**Comment by dyaandys** [comment]
Now takes you to 16.0 documentation. Can be closed.
