### ISSUE TITLE
Initial configuration type should be start, not connect

### ISSUE THREAD

**Issue by ghost** [Dyalog/ride#817]
### Describe the issue you are having
The initial configuration type is "connect", I (and others) believe it'd make more sense for this to be changed to "start" - as it'd be more friendly to beginners.  (It's also, probably, the most common type)

### Paste the contents of Help → About (Shift+F1)
```
IDE:
  Version: 4.4.1
  Platform: Linux x86_64
  Date: 2021-12-29 12:22:26 +0000
  Git commit: 6499cb1a4187cd4b6ae1ffcc394b786ccdd78895
  Preferences:{
    "kbdLocale":"en_GB",
    "otherExe":"/opt/apl/dyalog/mapl"
  }

Interpreter:
  Version: 18.0.40684
  Platform: Linux-64
  Edition: Unicode/64
  Date: Jun 19 2021 at 00:08:29
```

**Comment by abrudz** [comment]
Seems fixed in 4.5.3748
