### ISSUE TITLE
Some standard macOS shortcuts don’t work

### ISSUE THREAD

**Issue by AleBeda** [Dyalog/ride#822]
### Suggestion for enhancement: standard macOS shortcuts
Some standard macOS shortcuts don’t work. For instance:

- `⌘ ,` (Command-Comma) should open the preferences
- `⌘ w` (Command-W) should close the current window (e.g. editor pop-up window)
- `⌘ h` (Command-H) should hide the current window
- etc.

### RIDE version
```
IDE:
  Version: 4.3.3463
  Platform: MacIntel
  Date: 2020-07-07 10:44:21 +0100
  Git commit: 0cd6e9faf39a5d6a5f5caa94d1ff51743d5cdd75
  Preferences:{
    "floating":"1",
    "kbdLocale":"en_US_Mac",
    "wse":"1",
    "dbg":"1",
    "wrap":"1",
    "squiggleTips":"1"
  }

Interpreter:
  Version: 18.0.40684
  Platform: Mac-64
  Edition: Unicode/64
  Date: Jun 19 2021 at 00:08:08
```

**Comment by abrudz** [comment]
<kbd>⌘</kbd>+<kbd>,</kbd> (Command-Comma) should open the preferences is fine, but <kbd>⌘</kbd>+<kbd>w</kbd> is contentious. Should it be save+exit or discard changes+quit? What do other tabbed editors do on macOS?

**Comment by abrudz** [comment]
OK, then <kbd>⌘</kbd>+<kbd>w</kbd> should be \<EP\> (i.e. save+exit)
