### ISSUE TITLE
Common menu items are missing

### ISSUE THREAD

**Issue by AleBeda** [Dyalog/ride#823]
### Suggestion for enhancement: common menu items
Some common menu items are missing. For instance:
- `File→Open Recent` to open recent sessions
- `File→Close` to close the current session
- `File→Print` to print the session
- `File→Export` to export the session to a file
- `File→Share` and selection share (via contextual menu) to share the session or the selected text via email, social media, etc.
- `Edit→Comment` and `Edit→Uncomment` to comment/uncomment blocks of selected text
- `Edit→Save` etc.
### RIDE version
```
IDE:
  Version: 4.3.3463
  Platform: MacIntel
  Date: 2020-07-07 10:44:21 +0100
  Git commit: 0cd6e9faf39a5d6a5f5caa94d1ff51743d5cdd75
  Preferences:{
    "floating":"1",
    "kbdLocale":"en_US_Mac",
    "wse":"1",
    "dbg":"1",
    "wrap":"1",
    "squiggleTips":"1"
  }

Interpreter:
  Version: 18.0.40684
  Platform: Mac-64
  Edition: Unicode/64
  Date: Jun 19 2021 at 00:08:08
```

**Comment by dyavc** [comment]
A customer asked today how to print from RIDE.  See also RIDE issue #231

**Comment by abrudz** [comment]
All parts of this (except Print, see #1027) are in #1019.
