### ISSUE TITLE
Difficult to see the value of a variable when hovering in the trace/debug window

### ISSUE THREAD

**Issue by AleBeda** [Dyalog/ride#832]
### Describe the issue you are having
It is very difficult to see the value of a variable (especially single-character names like ⍵ and ⍺) when hovering with the mouse over the variable name. In the trace/debug window the mouse cursor is an I-beam, whose active point is not obvious as it would be for an arrow. The sensitive area on the variable name is only a few pixels wide.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
All-in-one interpreter+RIDE on MacOS.

### How do you reproduce the issue?
During a debug session, in the trace window, hover with the mouse over ⍵.

### RIDE version
```
IDE:
  Version: 4.3.3463
  Platform: MacIntel
  Date: 2020-07-07 10:44:21 +0100
  Git commit: 0cd6e9faf39a5d6a5f5caa94d1ff51743d5cdd75
  Preferences:{
    "floating":"1",
    "kbdLocale":"en_US_Mac",
    "wse":"1",
    "dbg":"1",
    "wrap":"1",
    "squiggleTips":"1"
  }

Interpreter:
  Version: 18.0.40684
  Platform: Mac-64
  Edition: Unicode/64
  Date: Jun 19 2021 at 00:08:08
```

**Comment by e9gille** [comment]
Should be fixed by #870 and improved by 061c1f1a5048e2974ee04845e0d0629011de3b57
