### ISSUE TITLE
Incorrect linked file name in editor title bar

### ISSUE THREAD

**Issue by bpbecker** [Dyalog/ride#838]
<img width="418" alt="Untitled" src="https://user-images.githubusercontent.com/4154043/151679590-89dc366f-57c3-4cd8-bfe1-41e1c70a50fb.png">
When editing a linked function, the source file name is displayed in the editor title bar.
Then double-click on a function name (of an also-linked function) within the function being edited.
The editor brings up the new function's code, but does not update the source file name in the editor title bar.

IDE:
  Version: 4.4.3686
  Platform: Win32
  Date: 2022-01-28 09:34:33 +0100
  Git commit: e6c092ec7633d757a17a4d5aebb683a1963fe60d
  Preferences:{
    "connectOnQuit":"1",
    "kbdLocale":"en_US",
    "otherExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 18.2 Unicode\\dyalog.exe",
    "selectedExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 18.2 Unicode\\dyalog.exe"
  }

Interpreter:
  Version: 18.2.45154
  Platform: Windows-64
  Edition: Unicode/64
  Date: Jan 27 2022 at 21:15:29

**Comment by e9gille** [comment]
I just managed to replicate this, but it wasn't trivial to replicate. This seems to happen only when the available space for tab buttons is in a certain range (too small and it renders horribly, spanning 2 rows of text in the tab button, large enough and it shows the correct button).
I'll see if I can figure out where it goes wrong, but it's likely in the GoldenLayout tool, so might be a bit hairy.

**Comment by e9gille** [comment]
Found a solution, will post a fix asap.
