### ISSUE TITLE
Update Releases (to Include the New Color Themes)

### ISSUE THREAD

**Issue by codereport** [Dyalog/ride#839]
### Describe the issue you are having
The [latest releases](https://github.com/Dyalog/ride/releases/tag/v4.3.3468) don't include the Dracula theme (add in https://github.com/Dyalog/ride/pull/684) which many people want and I get a lot of questions about. If we update theme, that will resolve the issue so ppl dont have to build from source.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Yes.

### How do you reproduce the issue?
Just a request, not really an issue.

**Comment by abrudz** [comment]
Pre-releases have it, and we're very close to releasing 4.4. Probably not worth backporting the themes to 4.3.

**Comment by codereport** [comment]
I see (I didn't know how releases work). For those that stumble across this, you can find 4.4 assets here: https://github.com/Dyalog/ride/releases/tag/v4.4.3682
