### ISSUE TITLE
RIDE on Windows fails to detect UK locale so defaults to US keyboard layout

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/ride#84]
When RIDE is installed/first run, could it attempt to identify the most appropriate keyboard layout and use that  ?

Most especially, can RIDE identify that it's running on macOS and use such as en_GB_mac, rather than en_GB.

IDE:
  Version: 4.0.2644
  Platform: Win32
  Date: 2017-02-16 10:37:54 +0000
  Git commit: 167f1aa6f75189bf7f9e19c1ff888f3d1dc02782
  Preferences:{
    "favs":"[{\"type\":\"connect\",\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"debian7dev\",\"host\":\"debian7dev.dyalog.bramley\",\"port\":\"4502\"},{\"type\":\"connect\",\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"dfsaix\",\"host\":\"10.0.61.100\",\"port\":\"9003\"},{\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"type\":\"start\",\"exe\":\"C:\\\\Program Files\\\\Dyalog\\\\Dyalog APL-64 16.0 Unicode\\\\dyalog.exe\"},{\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"mac0\",\"host\":\"mac0\"},{\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"local\",\"host\":\"127.0.0.1\",\"port\":\"9999\",\"type\":\"start\",\"exe\":\"C:\\\\Program Files\\\\Dyalog\\\\Dyalog APL-64 16.0 Unicode\\\\dyalog.exe\"},{\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"p7-61qa\",\"host\":\"p7-61qa\",\"port\":\"4503\"}]",
    "kbdLocale":"en_US",
    "selectedExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 16.0 Unicode\\dyalog.exe",
    "wse":"1",
    "lineNums":"0"
  }

Interpreter:
  Version: 16.0.29184
  Platform: Windows-64
  Edition: Unicode/64
  Date: Feb 14 2017 at 18:10:45

**Comment by jayfoad** [comment]
I think RIDE correctly determines the keyboard layout based on navigator.language. But Andy has just shown me that on his UK Windows machine, electron seems to think his language is en-US not en-GB.

**Comment by jayfoad** [comment]
I have the same problem: my Windows VM is set to UK language and locale, but Electron sets navigator.language to en-US not en-GB.

This seems to be a problem with Electron not RIDE. I have confirmed by reproducing the problem in a freshly downloaded electron.exe running the [hello world app](https://github.com/electron/electron-quick-start).

**Comment by e9gille** [comment]
Detecting locale has been a longstanding issue in electron and still not fixed. I've resorted to use another package for now.
