### ISSUE TITLE
macOS Monterey (and others where zsh is the default shell): RIDE should not populate the list of available Dyalog versions with "vNAN, NaN-bit, *"

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/ride#844]
Applies to all versions of RIDE

When generating the list of available APLs, RIDE displays
```
Interpreter: vNAN, NaN-bit, *
zsh:1: no matches found: /opt/mdyalog/*/*/*/mapl
```

Is because RIDE calls
`/bin/ls -1 /opt/mdyalog/*/*/*/mapl /opt/mdyalog/*/*/*/*/mapl /Applications/Dyalog-*/Contents/Resources/Dyalog/mapl`

which is fine unless you're using zsh by default: then you get
`ls: /opt/mdyalog/*/*/*/mapl: No such file or directory`

makes no odds which order you search in.

IDE:
  Version: 4.4.3687
  Platform: Win32
  Date: 2022-02-23 13:44:34 +0100
  Git commit: a3d8123cfb690ead493e261ccced59407db04c64
  Preferences:{
    "ime":"1",
    "kbdLocale":"en_US",
    "keys":"{\"MA\":[\"F2\"],\"PF2\":[]}",
    "otherExe":"/opt/mdyalog/17.1/64/classic/p9/mapl",
    "selectedExe":"/opt/mdyalog/18.2/64/unicode/p9/mapl",
    "wse":"1"
  }

Interpreter:
  Version: unknown
  Platform: unknown
  Edition: unknown
  Date: unknown

IDE:
  Version: 4.3.3437
  Platform: Win32
  Date: 2019-07-09 13:38:28 +0100
  Git commit: 88a9eb9a96fd5e90dcb8dfdffc6aa7a9cb035441
  Preferences:{
    "connectFav":"3",
    "indent":"-1",
    "kbdLocale":"en_GB",
    "otherExe":"/opt/mdyalog/17.1/64/classic/p9/mapl",
    "pfkeys":"[\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"<ED>\",\"\",\"<ED>\",\"<ED>\",\"<ED>\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\"]",
    "zoom":"1"
  }

Interpreter:
  Version: unknown
  Platform: unknown
  Edition: unknown
  Date: unknown

**Comment by abrudz** [comment]
does this still repro with RIDE 4.5?

**Comment by xpqz** [comment]
Unable to repro on Ventura, which uses zsh. Works as advertised both with RIDE 4.4 and 4.5.

**Comment by abrudz** [comment]
Closing as can't repro, @dyaandys please comment if you still see it.
