### ISSUE TITLE
Language bar button stops working after clicking on tip

### ISSUE THREAD

**Issue by abrudz** [Dyalog/ride#846]
### Describe the issue you are having
When hovering over a language bar glyph, a tip will pop up. Clicking on this sub-window (e.g. to select an example) makes the language bar button stop working.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Start an interpreter

### How do you reproduce the issue?
1. Hover over a language bar glyph
2. Click the pop-up
3. Click the glyph
4. Nothing is inserted into the session.

### Paste the contents of Help → About (Shift+F1)
```
IDE:
  Version: 4.4.3687
  Platform: Win32
  Date: 2022-02-23 13:44:34 +0100
  Git commit: a3d8123cfb690ead493e261ccced59407db04c64
Interpreter:
  Version: 19.0.45434
  Platform: Windows-64
  Edition: Unicode/64
  Date: Mar 25 2022 at 19:24:05
```

**Comment by e9gille** [comment]
Fixed in a73ebd66f89312786be7ca61c0dfbf24f32d02cd
