### ISSUE TITLE
WINBI when opening editor or tracer windows, the text was drawn only once, rather than twice which leads to visual flack

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/ride#85]
Open the editor or tracer (the tracer is perhaps more noticeable) on an existing function.  The text is displayed, and then redrawn .. can't quite see what is happening, but it appears that all the text moves right a bit.  This is offputting.   Can the text be displayed once its final formatting has been applied ?

IDE:
  Version: 4.0.2644
  Platform: Win32
  Date: 2017-02-16 10:37:54 +0000
  Git commit: 167f1aa6f75189bf7f9e19c1ff888f3d1dc02782
  Preferences:{
    "favs":"[{\"type\":\"connect\",\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"debian7dev\",\"host\":\"debian7dev.dyalog.bramley\",\"port\":\"4502\"},{\"type\":\"connect\",\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"dfsaix\",\"host\":\"10.0.61.100\",\"port\":\"9003\"},{\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"type\":\"start\",\"exe\":\"C:\\\\Program Files\\\\Dyalog\\\\Dyalog APL-64 16.0 Unicode\\\\dyalog.exe\"},{\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"mac0\",\"host\":\"mac0\"},{\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"local\",\"host\":\"127.0.0.1\",\"port\":\"9999\",\"type\":\"start\",\"exe\":\"C:\\\\Program Files\\\\Dyalog\\\\Dyalog APL-64 16.0 Unicode\\\\dyalog.exe\"},{\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"p7-61qa\",\"host\":\"p7-61qa\",\"port\":\"4503\"}]",
    "kbdLocale":"en_US",
    "selectedExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 16.0 Unicode\\dyalog.exe",
    "wse":"1",
    "lineNums":"0"
  }

Interpreter:
  Version: 16.0.29184
  Platform: Windows-64
  Edition: Unicode/64
  Date: Feb 14 2017 at 18:10:45

**Comment by dyaandys** [comment]
JD asks .. is the redraw done to add the outline marking .. and if so, could the an empty outline area be added before the 1st draw to avoid the movement which catches the eye ?

**Comment by jayfoad** [comment]
@dyaandys is this still a problem with the current master?

**Comment by dyaandys** [comment]
Looks good to me now.
