### ISSUE TITLE
Can't use RIDE to connect to a RIDE that is listening

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Dyalog/ride#851]
### Describe the issue you are having

After connecting RIDE to another RIDE instance that was started on "Listen", the two instances seem to have been paired up correctly but I can't write expressions in either window.

### How do you reproduce the issue?

 1. Open RIDE
 2. Change connection type to LISTEN
 3. Press LISTEN
 4. Open another RIDE
 5. Change connection type to CONNECT
 6. Press CONNECT
 7. Try to write an expression in either window, neither work (you can _write_ code but you can't evaluate it by pressing <kbd>Enter</kbd>)

### Paste the contents of Help → About (Shift+F1)

```
IDE:
  Version: 4.3.3463
  Platform: Win32
  Date: 2020-07-07 10:44:21 +0100
  Git commit: 0cd6e9faf39a5d6a5f5caa94d1ff51743d5cdd75
  Preferences:{
    "autoCloseBrackets":"0",
    "autoPW":"1",
    "connectFav":"1",
    "editWins":"{\"width\":800,\"height\":600,\"x\":200,\"y\":200,\"ox\":50,\"oy\":50}",
    "floatSingle":"0",
    "kbdLocale":"en_US",
    "keys":"{\"FX\":[\"Ctrl-S\"]}",
    "persistentHistory":"0",
    "selectedExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 18.2 Unicode\\dyalog.exe",
    "squiggleTips":"1",
    "title":"RIDE {RIDE_VER_A}.{RIDE_VER_B} - {WSID}",
    "zoom":"7"
  }

Interpreter:
  Version: 18.2.45505
  Platform: Windows-64
  Edition: Unicode/64
  Date: Apr  6 2022 at 19:22:59
```

**Comment by aplteam** [comment]
A Ride listens to an interpreter, not another Ride - that makes no sense.

**Comment by rodrigogiraoserrao** [comment]
After reading the [RIDE User Guide](https://www.dyalog.com/documentation_182.htm#TOOLS) more carefully I see my issue arose from a misunderstanding of what the "Listen" and "Connect" options meant.
