### ISSUE TITLE
Closing the editor results in the WS explorer pane getting wider each time

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/ride#86]
In a CLEAR WS
repeatedly doing
     foo ED EP
results in an inexorable march rightwards of the splitter between the WS explorer and the session

IDE:
  Version: 4.0.2644
  Platform: Win32
  Date: 2017-02-16 10:37:54 +0000
  Git commit: 167f1aa6f75189bf7f9e19c1ff888f3d1dc02782
  Preferences:{
    "favs":"[{\"type\":\"connect\",\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"debian7dev\",\"host\":\"debian7dev.dyalog.bramley\",\"port\":\"4502\"},{\"type\":\"connect\",\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"dfsaix\",\"host\":\"10.0.61.100\",\"port\":\"9003\"},{\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"type\":\"start\",\"exe\":\"C:\\\\Program Files\\\\Dyalog\\\\Dyalog APL-64 16.0 Unicode\\\\dyalog.exe\"},{\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"mac0\",\"host\":\"mac0\"},{\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"local\",\"host\":\"127.0.0.1\",\"port\":\"9999\",\"type\":\"start\",\"exe\":\"C:\\\\Program Files\\\\Dyalog\\\\Dyalog APL-64 16.0 Unicode\\\\dyalog.exe\"},{\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"p7-61qa\",\"host\":\"p7-61qa\",\"port\":\"4503\"}]",
    "kbdLocale":"en_GB",
    "selectedExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 16.0 Unicode\\dyalog.exe",
    "wse":"1",
    "lineNums":"0"
  }

Interpreter:
  Version: 16.0.29184
  Platform: Windows-64
  Edition: Unicode/64
  Date: Feb 14 2017 at 18:10:45

**Comment by mkromberg** [comment]
This is one symptom of a broader problem: Ideally, I think that the user should be able to control the amount of space allocated to each of a number of regions:
1) The session
2) Editors
3) The WS explorer
4) The tracer
Regions 2 & 3 should ideally only take horizontal space from the session when they are opened- they should not cause anything other than the session to be resized. The ratio between regions 1-3 should be preserved and the user should be allowed to manage it with the splitter.
Region 4 (tracer) takes vertical space (I think) and again, the user should be able to manage that: If the tracer disappears and comes back it should take the same amount of space that it did the last time it was visible.
I think this kind of stability is critical to user comfort during long RIDE sessions.

**Comment by dyaandys** [comment]
Checked AWS on Windows and Mac in 16.0.29464/4.0.2729
