### ISSUE TITLE
When tracing a call to ⎕ and you hit Enter in the session, you get a VALUE ERROR which results in the current line in tracer being displayed 

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/ride#862]
⎕fx'foo' 'andy←⎕'
foo<TC><TC>
Get ⎕: prompt
hit Enter .. 
VALUE ERROR
foo[1] andy←⎕
            ∧

Second issue:
Try it again, but this time backspace over the 6 spaces and hit Enter .. get a second
⎕:
note that the cursor is on the left edge of the session.  Hit Enter and you get a VALUE ERROR.

IDE:
  Version: 4.4.3687
  Platform: Win32
  Date: 2022-02-23 13:44:34 +0100
  Git commit: a3d8123cfb690ead493e261ccced59407db04c64
  Preferences:{
    "ime":"1",
    "kbdLocale":"en_US",
    "keys":"{\"MA\":[\"F2\"],\"PF2\":[]}",
    "otherExe":"/opt/mdyalog/17.1/64/classic/p9/mapl",
    "selectedExe":"/opt/mdyalog/19.0/64/unicode/mapl",
    "wse":"1"
  }

Interpreter:
  Version: 18.2.45645
  Platform: Windows-64
  Edition: Unicode/64
  Date: May 26 2022 at 19:23:35

**Comment by abrudz** [comment]
Logged as Mantis 19934: ⎕ input gets value error if user enters spaces
