### ISSUE TITLE
The word "Locale" in the layout tab of the preferences box is not right

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/ride#87]
Locale suggests more than a keyboard layout/mapping, and your locale doesn't necessarily reflect the keyboard layout that you're using.  Locale also has implications of the language that text and error messages is in.

Suggestions to replace "Locale" with include "Keyboard", "Keyboard layout", or "Select layout"  ..

IDE:
  Version: 4.0.2644
  Platform: Win32
  Date: 2017-02-16 10:37:54 +0000
  Git commit: 167f1aa6f75189bf7f9e19c1ff888f3d1dc02782
  Preferences:{
    "favs":"[{\"type\":\"connect\",\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"debian7dev\",\"host\":\"debian7dev.dyalog.bramley\",\"port\":\"4502\"},{\"type\":\"connect\",\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"dfsaix\",\"host\":\"10.0.61.100\",\"port\":\"9003\"},{\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"type\":\"start\",\"exe\":\"C:\\\\Program Files\\\\Dyalog\\\\Dyalog APL-64 16.0 Unicode\\\\dyalog.exe\"},{\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"mac0\",\"host\":\"mac0\"},{\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"local\",\"host\":\"127.0.0.1\",\"port\":\"9999\",\"type\":\"start\",\"exe\":\"C:\\\\Program Files\\\\Dyalog\\\\Dyalog APL-64 16.0 Unicode\\\\dyalog.exe\"},{\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"p7-61qa\",\"host\":\"p7-61qa\",\"port\":\"4503\"}]",
    "kbdLocale":"en_GB",
    "selectedExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 16.0 Unicode\\dyalog.exe",
    "wse":"1",
    "lineNums":"0"
  }

Interpreter:
  Version: 16.0.29184
  Platform: Windows-64
  Edition: Unicode/64
  Date: Feb 14 2017 at 18:10:45

**Comment by jayfoad** [comment]
I think I'll change it to "Choose layout".
