### ISSUE TITLE
Password field contents persist when changing SSH configurations

### ISSUE THREAD

**Issue by bpbecker** [Dyalog/ride#880]
### Describe the issue you are having
I have several SSH configurations to connect to different machines.  When I type in a password in one SSH configuration and then switch to a different SSH configuration, the password field stays populated.

### Did you connect to an already running interpreter or start the interpreter from RIDE?
N/A

### How do you reproduce the issue?
See description above

### Paste the contents of Help → About (Shift+F1)
```
IDE:
  Version: 4.4.3700
  Electron: 13.6.9
  Chrome: 91.0.4472.164
  Node: 14.16.0
  Platform: Win32
  Date: 2022-06-21 09:48:27 +0200
  Git commit: b3db6781df6dc63f7bbc4fa4e0a634ef5b44765c
  Preferences:{
    "connectOnQuit":"1",
    "dbg":"1",
    "kbdLocale":"en_US",
    "selectedExe":"/Applications/Dyalog-18.2.app/Contents/Resources/Dyalog/mapl",
    "title":"{HOST} {WSID}",
    "wse":"1",
    "otherExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 18.2 Unicode\\dyalog.exe"
  }

Interpreter:
  Version: unknown
  Platform: unknown
  Edition: unknown
  Date: unknown

```

**Comment by e9gille** [comment]
FIxed in 19d557e01d61680e0750ec5486dc7433f2fdbc6e
