### ISSUE TITLE
Fail gracefully with a sensible error message when trying to SSH start a Windows interpreter

### ISSUE THREAD

**Issue by bpbecker** [Dyalog/ride#881]
### Describe the issue you are having
When I use RIDE 4.4.3700, enter my credentials, and click the icon to retrieve the list of interpreters I get a popup stating 'Cannot read property "replace" of undefined'.  I'm able to successfully start interpreters using SSH to my Pi, my local Ubuntu box, my MacBook, and a remote AIX system - it's only the Windows systems that fail. I've verified that the ssh host is working on both Windows laptops because I can ssh via the command line from any of my platforms to either of my Windows laptops (one runs Windows 10, the other Windows 11).  

I'm able to reproduce this behavior from my MacBook, Windows 10, and Windows 11 (I didn't try using RIDE from any other platforms).

### Did you connect to an already running interpreter or start the interpreter from RIDE?
N/A

### How do you reproduce the issue?
1. Get a Windows box and make sure 
  1.1 it's got SSH installed and working.
  1.2 it has a RIDEable APL installed
2. From another box
  2.1 verify that you can SSH to the Windows box
  2.2 Open RIDE, enter the credentials, and click the icon to discover what interpreters are on the Windows box
3. (hopefully) Observe the popup with the message 'Cannot read property "replace" of undefined'

**Comment by e9gille** [comment]
I can understand why it doesn't work as the discovery via SSH only supports unix. 
On a related note, I've also noticed a significant slowdown of discovery on a local machine for Windows.

**Comment by abrudz** [comment]
If this cannot be made to work on Windows, then at least RIDE should fail gracefully with a sensible error message.
