### ISSUE TITLE
In the editor's "Find" field, POS1 ("Home") and END affect the cursor position in the editor instead of in the find field

### ISSUE THREAD

**Issue by aplteam** [Dyalog/ride#883]
IDE:
  Version: 4.4.3700
  Electron: 13.6.9
  Chrome: 91.0.4472.164
  Node: 14.16.0
  Platform: Win32
  Date: 2022-06-21 09:48:27 +0200
  Git commit: b3db6781df6dc63f7bbc4fa4e0a634ef5b44765c
  Preferences:{
    "autoPW":"1",
    "autocompletionDelay":"150",
    "blockCursor":"1",
    "colourScheme":"Kai",
    "colourSchemes":"[{\"name\":\"Kai\",\"theme\":\"dark\",\"styles\":\"asgn=fg:#00ff00 com=fg:b cur=bc:f00 dfn2=fg:eb4 dfn3=fg:c79 dfn4=fg:cd0 dfn5=fg:a0d dfn=fg:a7b diam=fg:ff0 err=fg:#ff00ff,bg:822,bgo:0.5,B fn=fg:0f0 idm=fg:0f0 glb=B kw=fg:aa2 lbl=bg:642,bgo:0.5 lnum=fg:b94,bg:010,bgo:0 mod=bg:7,bgo:0.5 mtch=fg:0,bg:0,bgo:0 norm=fg:9c7,bg:0,bgo:1 num=fg:a8b op1=fg:d95 op2=fg:#00ff00 sel=bg:048,bgo:0.5 semi=fg:8 sqbr=fg:8 srch=bg:b96,bgo:0.75,fg:0 str=fg:dae tc=bg:1,bgo:1 tcpe=bg:2,bgo:1 zld=fg:d9f,B scmd=fg:0ff ucmd=fg:f80,B vtip=bg:733,fg:ff0,bgo:1,bc:900 vtt=bc:f80 ca=bg:828282,bgo:1,fg:0f0 cm=bg:0,bgo:1,fg:0f0 cv=bg:f,bgo:1,fg:0 cvv=bg:0,bgo:1,fg:0ff ma=bg:828282,bgo:1,fg:0ff na=bg:828282,bgo:1,fg:f qor=bg:f00,bgo:1,fg:f dc=bg:900,bgo:1\"}]",
    "editWins":"{\"width\":1365,\"height\":988,\"x\":1817,\"y\":144,\"ox\":0,\"oy\":0}",
    "editWinsRememberPos":"1",
    "floating":"1",
    "kbdLocale":"en_GB",
    "keys":"{\"ABT\":[],\"DK\":[\"Ctrl-Delete\"],\"LN\":[\"NumPad_Subtract\"],\"MA\":[\"F6\"],\"RP\":[\"Ctrl-R\"],\"SI\":[\"Ctrl-Shift-PauseBreak\"],\"ZMI\":[\"Ctrl-NumPad_Add\"],\"ZMO\":[\"Ctrl-NumPad_Subtract\"],\"ZMR\":[\"Ctrl-NumPad0\"],\"PF6\":[]}",
    "minimapEnabled":"1",
    "otherExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 18.1 Unicode\\dyalog.exe",
    "pfkeys":"[\"\",\"\",\"⎕TRAP←0 'S'\",\"\",\"⎕se.aplteam.Display \",\"→⎕LC+1\",\"<MA>\",\"⍎⎕SE.aplteam.GotoQLC_AndSetStopVector ER \",\"⍎⎕SE.aplteam.GotoQLC_AndDropStopVector ER \",\"<LL>⍝<ER>\",\"⎕THIS\",\"\",\"\",\"\",\"\",\"]ListObjects \",\"]Latest\",\"∘∘∘\",\"\",\"\",\"\",\"\",\"\",\"⎕DMX.(⍪{⍵(⍎⍵)}¨⎕NL-2) \",\"⎕SE.aplteam.Clear\",\"\",\"\",\"\",\"⊣⎕SE.Link.Expunge '\",\"\",\"\",\"\",\"\",\"]UDEBUG \",\"⍝TODO⍝ \",\"{{}(#.⎕NS'').(⎕ED⍠('ReadOnly' 1)&{'ed'}ed←⍵)}\",\"\",\"]Cider.\",\"]Cider.OpenProject \",\"]Cider.ListProjects\",\"]Cider.CloseProject \",\"\",\"]Git.\",\"]Git.Status\",\"]Git.OpenGitShell\",\"]Git.Commit -m='\",\"]Tatin.\",\"]Tatin.ListPackages\",\"]Tatin.Registries\"]",
    "renderLineHighlight":"line",
    "selectedExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 18.2 Unicode\\dyalog.exe",
    "selectionHighlight":"1",
    "title":"{WSID}  ⋄  {HOST}:{PORT}",
    "pauseOnError":"1"
  }

Interpreter:
  Version: 18.2.45749
  Platform: Windows-64
  Edition: Unicode/64
  Date: Jun 28 2022 at 19:23:15

**Comment by e9gille** [comment]
Fixed in e586dc7bfea07d0d40a4211f298ccf13cd874387
