### ISSUE TITLE
Strong interrupt during ⍞  input leads to odd behaviour

### ISSUE THREAD

**Issue by abrudz** [Dyalog/ride#888]
### Describe the issue you are having
Strong interrupt during ⍞  input leads to odd behaviour

### Did you connect to an already running interpreter or start the interpreter from RIDE?
start

### How do you reproduce the issue?
```apl
⎕FX'foo' 'z←⍞' '⎕←⍴z'
foo
```
Action>Strong interrupt [nothing appears to happen]
answer the prompt, e.g. "abc"
interpreter error: invalid syntax
"interesting" indentation and spaces…
answer the prompt, e.g. "abcdefg"
function returns 7 (length of "abcdefg")

### Paste the contents of Help → About (Shift+F1)
```
Version: 4.4.3687 (Windows)
```

**Comment by abrudz** [comment]
Once fixed, have a look at #514

**Comment by e9gille** [comment]
Tested on Mac:
17.1.45750
18.0.45750
18.2.45750

This is an interpreter issue that seems to be fixed in 18.2, although it sometimes takes a few seconds before the interrupt is actioned (but that's not unusual).

**Comment by e9gille** [comment]
I don't see how this is different from #514. The InvalidSyntax message from the interpreter is unexpected and leaves RIDE in quote-quad input mode (and that seems to be correct and match the interpreter state).
Feel free to re-open if you don't agree.
