### ISSUE TITLE
The RM Keystroke does not work from the session and produces a messagebox with a bad caption

### ISSUE THREAD

**Issue by johndaintree** [Dyalog/ride#889]
1) Set up a keystroke for <RM>
2) Press that keystroke in the session

... this dodgy caption doesn't appear to be coming from the interpreter

![image](https://user-images.githubusercontent.com/10829577/179461904-5c6d411f-f378-41cc-aed1-bb953a5c5a3b.png)

**Comment by abrudz** [comment]
Duplicate of #802
