### ISSUE TITLE
Support keyboard in common (Yes/No)-Prompts

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/ride#90]
If would be useful if the keys "yn" could also be used to handle prompts like this one:
![2017-02-17_08-56-20](https://cloud.githubusercontent.com/assets/5645494/23057257/89a6b714-f4ef-11e6-8a8f-20a36b6a2cbe.png)

**Comment by jayfoad** [comment]
For testing purposes, you can pop up a dialog like this with: `3503⌶'Title' 'Message' 'Query'('Yes' 'No')`

**Comment by e9gille** [comment]
This has been fixed

**Comment by e9gille** [comment]
I should add that it has been fixed with regards to allowing Escape and Enter keys for cancelling/accepting default buttons.
