### ISSUE TITLE
A way to "mark for execution"

### ISSUE THREAD

**Issue by abrudz** [Dyalog/ride#908]
### Describe the issue you are having
In the Windows IDE, one can use `x<DB>` to mark an interactive session line for execution (so it'll be run next time I press <ER>), because this makes a change (inserts letter `x` then backspaces over it). Unfortunately, RIDE does not implement `<DB>` (backspace), nor `<DI>` (delete – which could be used as `x<LC><DI>` to move left and delete). I cannot think of another way to mark my line for execution, without moving the cursor to a different column (`<RL> ` moves the cursor to the end of the line and adds a space).

RIDE Version: 4.4.3687

**Comment by e9gille** [comment]
Fixed in 6c723cbd2b2f29276d5c2d6728e99ab47145ac33
Use <VAL> to mark a line in the session.
