### ISSUE TITLE
RIDE does not support <TB> keystroke

### ISSUE THREAD

**Issue by geoffstreeter** [Dyalog/ride#91]
foo \<ED>
opens edit window and caret is in window
\<TB> does nothing - should put caret in session

**Comment by jayfoad** [comment]
See also #45

**Comment by jayfoad** [comment]
@geoffstreeter Were you hitting something like Win+Tab to get your X keyboard map to send \<TB>? Does it work if you hit Ctrl+Tab instead (i.e. using RIDE's keyboard handling instead of X's)?

**Comment by geoffstreeter** [comment]
Yes I was. If I reenable the Ctrl+Tab shortcut to <TB> then it works but why would I want to do that when I already have <TB> on the keyboard. I have turned off the shortcuts for keystrokes that I already (or should already) have.

On my windows VM I have set the registry so that the Win key behaves like Ctrl which means the Windows  keyboard is slightly less broken.

For RIDE this issue is another example of a generic issue where certain keys are treated as if they cannot produce Unicode. It is best illustrated with the line drawing glyphs on the numeric keypad. Some work, some don't. This illustration avoids the aspect of using private use Unicode pages. It just demonstrates the underlying error.

Note that using normal input in different browsers illustrates the same problem. Chrome and Opera get it wrong, Firefox and Qupzilla get it right.

**Comment by jayfoad** [comment]
\<TB> (Win+Tab) works for me now on Linux. Can we close this?

**Comment by geoffstreeter** [comment]
If I run RIDE I get Version: 4.0.2864. I use /devt/builds/ride/ride4/latest/linux-x64/Ride-4.0

On that version I do
	)ED foo
<TB>
does not go to the session in RIDE but has gone to the session in the tty window.

So providing "latest" means what is says on the tin I don't think this can be closed.
