### ISSUE TITLE
<EP> does not close edit window for last tab

### ISSUE THREAD

**Issue by geoffstreeter** [Dyalog/ride#92]
foo \<ED>
\<EP>
nothing happens. The editor should close and caret return to the session.

IDE:
  Version: 4.0.2655
  Platform: Linux x86_64
  Date: 2017-02-17 17:33:17 +0100
  Git commit: c63fb58303258497915514fb2eb648d3949d29a4
  Preferences:{
    "favs":"[{\"type\":\"connect\",\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"user\":\"root\",\"host\":\"10.0.61.73\",\"port\":\"9003\"}]"
  }

Interpreter:
  Version: 15.0.29225
  Platform: Linux-64
  Edition: Unicode/64
  Date: Feb 17 2017 at 16:01:06

**Comment by jayfoad** [comment]
I can't reproduce this.
