### ISSUE TITLE
Prefilled IP and port does not update, should be a list

### ISSUE THREAD

**Issue by geoffstreeter** [Dyalog/ride#94]
I connected to 10.0.61.73:9003
now every time I try to connect it pre fills those values. Despite several successful connects to  127.0.0.1:5402

It should remember the most recent. Better still it should remember several recent.

**Comment by geoffstreeter** [comment]
Probably not a bug. Yes it should remember the last connection. Yes I should set up connections using the left pain.

**Comment by e9gille** [comment]
If you save the configuration, it now remembers the last selected configuration and preselects it on re-start.
