### ISSUE TITLE
RIDE wishlist

### ISSUE THREAD

**Issue by xpqz** [Dyalog/ride#940]
This is my wishlist for RIDE papercuts to address:

* Visual indicator that an `)ed` window contains unsaved data
* A button in the debug windows that executes `)sic`
* Sane default keyboard bindings appropriate for the host platform (e.g. cmd-s for save, ctrl-c for strong interrupt for Mac)
* Make strong interrupt also interrupt anything in flight, especially if something massive is being rendered for display with boxing on.
* Support for shell-style ctrl-l, with option to wipe the session log

A `ride` shell command, analoguos to VS Code's `code` or TextMate's `mate`. It should upon `ride <path>` open RIDE, setting the session's `]cd` to `<path>`. With a `--link` given, also `]link.create` the current directory. Somewhat orthogonally, as there is no meaningful way currently to feed environment variables to Dyalog on a Mac, a RIDE shell command gives an entrypoint from where this could be implemented:

    stefans-macbook> MAXWS=4G ride --link .

**Comment by abrudz** [comment]
Closing as too broad.
