### ISSUE TITLE
Initial output of session is incompletely shown in RIDE

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/ride#98]
See screenshot of #96 : the first lines of session-output at startup (the interpreter's beta-Warning as well as UCMD-Output) are not shown in RIDE!

![image](https://cloud.githubusercontent.com/assets/5645494/23210755/4db0a882-f8ff-11e6-8d15-2e53cd3b2dc8.png)

**Comment by jayfoad** [comment]
Probably the same as #47

**Comment by jayfoad** [comment]
@mbaas2 can you please check that this is fixed now?

**Comment by e9gille** [comment]
This is likely already fixed. Please re-open if still an issue.
