### ISSUE TITLE
Linebreaks in RIDE

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/ride#99]
It looks like ⎕PW of the session is not considered, Preferences also have no setting to control length of lines - and there certainly is more screen estate available...
![2017-02-22_17-04-59](https://cloud.githubusercontent.com/assets/5645494/23220331/ee5f509a-f921-11e6-9388-939724699728.png)

**Comment by JasonRivers** [comment]
Please could you include information from shift+F1 (Help > About). Could you also include if you are connecting to an already running interpreter or if you are starting the interpreter from RIDE.

If you're starting the interpreter from RIDE, Please could you try adding the Environment Variable: AUTO_PW=1 in the RIDE connect window.

**Comment by mbaas2** [comment]
I've added AUTO_PW and started the interpreter through RIDE as follows:
![image](https://cloud.githubusercontent.com/assets/5645494/23253999/c3dfd778-f9b6-11e6-90fc-776d058cebfc.png)

Still getting the same result:
![image](https://cloud.githubusercontent.com/assets/5645494/23254050/f92ef88c-f9b6-11e6-9fd8-47928ae230a0.png)

The config that About displays does not include AUTO_PW (yes, I had saveded it):
```
IDE:
  Version: 4.0.2667
  Platform: Win32
  Date: 2017-02-23 09:35:21 +0000
  Git commit: c1aa51a6224bb69d73387f3914888c3f25e8efe3
  Preferences:{
    "favs":"[{\"type\":\"start\",\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"host\":\"localhost\",\"exe\":\"C:\\\\Program Files\\\\Dyalog\\\\Dyalog APL-64 16.0 Unicode\\\\dyalog.exe\",\"name\":\"V16 locally\",\"env\":\"inifile=SOFTWARE\\\\Dyalog\\\\Dyalog APL/W-64 16.0 Unicode\\n\"},{\"ssh_auth_type\":\"pass\",\"ssh_tnl_auth_type\":\"pass\",\"name\":\"Connect4502\"}]",
    "kbdLocale":"en_US",
    "keys":"{\"SC\":[\"Shift-F9\"]}",
    "selectedExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 16.0 Unicode\\dyalog.exe"
  }

Interpreter:
  Version: 16.0.29236
  Platform: Windows-64
  Edition: Unicode/64
  Date: Feb 20 2017 at 18:09:34
```

**Comment by ngn** [comment]
Note that some system commands don't respect `⎕PW`. It's a known issue in the interpreter.

**Comment by mbaas2** [comment]
After upgrading to R4.0.2669 and D16.0.29298 I can no longer reproduce the problem...
